--- tests/hardware/run_sqlite_manual_marker_chars.lua
--- Native production software event-protocol scalar audit; no physical input claim.
local uv = require("luv")
require("compat.utf8").install()
local root = assert(uv.fs_mkdtemp("/tmp/ergopti-core-scalar-XXXXXX"))
for _, name in ipairs({ "CONFIG", "DATA", "CACHE", "STATE" }) do
	assert(uv.os_setenv("XDG_" .. name .. "_HOME", root .. "/" .. name:lower()))
end
assert(uv.fs_mkdir(root .. "/config", 448))
assert(uv.fs_mkdir(root .. "/config/ergopti", 448))
local config = assert(io.open(root .. "/config/ergopti/config.toml", "w"))
assert(config:write("[metrics]\nenabled = true\n") and config:close())
local K = require("modules.keylogger.keylogger")
local W = require("modules.keylogger.sqlite_writer")
local R = require("modules.keylogger.sqlite_reader")
local Clock = require("infra.monotonic")
local J = require("json")
local path, today = root .. "/metrics.sqlite", os.date("%Y-%m-%d")
K.init({ sqlite_path = path, log_dir = root .. "/logs" })
assert(K.is_enabled() and W.is_available())
local checks, failures = 0, 0
local function check(name, body)
	checks = checks + 1
	local ok, err = xpcall(body, debug.traceback)
	if ok then print("PASS " .. name) else
		failures = failures + 1
		io.stderr:write("FAIL " .. name .. ": " .. tostring(err) .. "\n")
	end
end
local function rows(sql) return assert(W.query_rows(sql)) end
local function cell(manifest, app) return assert(manifest[today] and manifest[today][app]) end
local function dashboard() return K.get_dashboard_payload({ include_prefetch = false }).metrics_manifest end
local at = math.floor(Clock.now_ms())
K.on_keydown("a", at, "owned-healthy")
K.on_keydown("b", at + 100, "owned-healthy")
K.on_keydown("a", at, "owned-manual")
K.on_keydown("[BS]", at + 100, "owned-manual")
K.on_keydown("b", at + 200, "owned-manual")
K.on_keydown("[BS]", at, "owned-correction-only")
check("healthy ordinary characters retain in-memory and live canonical count", function()
	assert(K.get_app_stats()["owned-healthy"].keystrokes == 2)
	assert(cell(dashboard(), "owned-healthy").chars == 2)
end)
check("manual correction marker does not inflate canonical in-memory and live chars", function()
	print("OBSERVE live manual=" .. tostring(cell(dashboard(), "owned-manual").chars)
		.. " correction-only=" .. tostring(cell(dashboard(), "owned-correction-only").chars))
	assert(K.get_app_stats()["owned-manual"].keystrokes == 2)
	assert(cell(dashboard(), "owned-manual").chars == 2)
	assert(cell(dashboard(), "owned-correction-only").chars == 0)
end)
K.flush()
print("SQL owned-manual=" .. table.concat(rows("SELECT chars FROM agg_app_day WHERE app='owned-manual';"), ","))
print("SQL classes=" .. table.concat(rows("SELECT letter+digit+punct+space+other FROM agg_app_day_chars_class WHERE app='owned-manual';"), ","))
print("SQL hourly=" .. table.concat(rows("SELECT SUM(c) FROM agg_app_day_hourly WHERE app='owned-manual';"), ","))
check("native raw correction protocol retains literal source bytes and all three events", function()
	assert(rows("SELECT hex(text),json_array_length(events_json) FROM events_typing WHERE app='owned-manual';")[1] == "615B42535D62|3")
	assert(rows("SELECT bs_total FROM agg_app_day_errors WHERE app='owned-manual';")[1] == "1")
end)
check("native daily character scalar agrees with literal two typed characters", function()
	assert(rows("SELECT chars FROM agg_app_day WHERE app='owned-manual';")[1] == "2")
	assert(rows("SELECT COALESCE(SUM(chars),0) FROM agg_app_day WHERE app='owned-correction-only';")[1] == "0")
end)
check("native class and ordinary-hour character totals exclude manual markers", function()
	assert(rows("SELECT letter+digit+punct+space+other FROM agg_app_day_chars_class WHERE app='owned-manual';")[1] == "2")
	assert(rows("SELECT SUM(c) FROM agg_app_day_hourly WHERE app='owned-manual';")[1] == "2")
	assert(rows("SELECT chars FROM agg_app_day WHERE app='owned-healthy';")[1] == "2")
end)
check("actual Reader and dashboard publish canonical scalar two and correction-only zero", function()
	for _, manifest in ipairs({ R.read_manifest(path), dashboard() }) do
		assert(cell(manifest, "owned-manual").chars == 2)
		assert(cell(manifest, "owned-correction-only").chars == 0)
		assert(cell(manifest, "owned-manual").bs_total == 1)
	end
end)
local raw = table.concat(rows("SELECT id,hex(text),hex(events_json) FROM events_typing ORDER BY id;"), "\n")
K.flush()
check("empty repeated flush preserves accepted native raw bytes and character totals", function()
	assert(table.concat(rows("SELECT id,hex(text),hex(events_json) FROM events_typing ORDER BY id;"), "\n") == raw)
	assert(rows("SELECT chars FROM agg_app_day WHERE app='owned-manual';")[1] == "2")
	assert(rows("SELECT chars FROM agg_app_day WHERE app='owned-healthy';")[1] == "2")
end)
K.on_keydown("c", at + 300, "owned-manual")
K.on_keydown("[BS]", at + 400, "owned-manual")
K.flush()
check("second native correction flush adds only the one admitted character delta", function()
	assert(rows("SELECT chars FROM agg_app_day WHERE app='owned-manual';")[1] == "3")
	assert(rows("SELECT bs_total FROM agg_app_day_errors WHERE app='owned-manual';")[1] == "2")
	assert(rows("SELECT COUNT(*) FROM events_typing WHERE app='owned-manual';")[1] == "2")
end)
check("core healthy Reader and dashboard remain two after unrelated corrections", function()
	assert(cell(R.read_manifest(path), "owned-healthy").chars == 2)
	assert(cell(dashboard(), "owned-healthy").chars == 2)
end)
W.close_db()
local function remove_owned(file_path)
	local stat = assert(uv.fs_lstat(file_path))
	if stat.type == "directory" then
		for name in uv.fs_scandir_next, assert(uv.fs_scandir(file_path)) do remove_owned(file_path .. "/" .. name) end
		assert(uv.fs_rmdir(file_path))
	else assert(uv.fs_unlink(file_path)) end
end
remove_owned(root)
print(string.format("Native core manual-marker scalar: %d checks, %d failures", checks, failures))
assert(checks == 9)
os.exit(failures == 0 and 0 or 1)
