; _generated/personal_file_descriptors.ahk

; Generated by tools/codegen/codegen-personal-file-descriptors.cjs; do not edit.
; Source: _shared/modules/hotstrings/personal_files.json.

/** Additional-file policy applies only after explicit native owner adoption. */
PersonalFileDefaultEnabled() => true
PersonalFilePriorityTier() => "package"
PersonalFileDefaultDelay() => 0
PersonalFileScanMaxDepth() => 16

/** Builds an exact relative personal-source identity without choosing a runtime group. */
PersonalFileDescribe(Components) {
	if !(Components is Array) || Components.Length == 0
		throw TypeError("Invalid personal-file components.")
	Copied := [], Encoded := [], Labels := []
	for _, Component in Components {
		if !(Component is String) || Component == "" || Component == "." || Component == ".." || InStr(Component, "/")
			throw TypeError("Invalid personal-file component.")
		Size := StrPut(Component, "UTF-8")
		Bytes := Buffer(Size, 0)
		StrPut(Component, Bytes, "UTF-8")
		if !(StrGet(Bytes, "UTF-8") == Component)
			throw TypeError("Invalid personal-file Unicode.")
		Hex := ""
		loop Size - 1
			Hex .= Format("{:02x}", NumGet(Bytes, A_Index - 1, "UChar"))
		Copied.Push(Component)
		Encoded.Push(Hex)
		Labels.Push(Component)
	}
	Last := Copied[Copied.Length]
	Extension := ".toml"
	if StrLower(SubStr(Last, -StrLen(Extension))) != Extension
		throw TypeError("Personal source is not a TOML filename.")
	Labels[Labels.Length] := SubStr(Last, 1, StrLen(Last) - StrLen(Extension))
	Identity := "personal-file:", Label := ""
	for Position, Hex in Encoded
		Identity .= (Position > 1 ? ":" : "") . Hex
	for Position, Part in Labels
		Label .= (Position > 1 ? " / " : "") . Part
	return Map("id", Identity, "components", Copied, "label", Label)
}

/** Returns exact components only for canonical reversible descriptor identities. */
PersonalFileComponents(Identity) {
	Namespace := "personal-file:"
	if !(Identity is String) || !(SubStr(Identity, 1, StrLen(Namespace)) == Namespace)
		return 0
	Body := SubStr(Identity, StrLen(Namespace) + 1)
	if Body == "" || SubStr(Body, 1, 1) == ":" || SubStr(Body, -1) == ":" || InStr(Body, ":" . ":")
		return 0
	Decoded := []
	for _, Part in StrSplit(Body, ":") {
		if Mod(StrLen(Part), 2) || RegExMatch(Part, "[^0-9a-f]")
			return 0
		Bytes := Buffer(StrLen(Part) // 2 + 1, 0)
		loop StrLen(Part) // 2
			NumPut("UChar", Integer("0x" . SubStr(Part, A_Index * 2 - 1, 2)), Bytes, A_Index - 1)
		Decoded.Push(StrGet(Bytes, "UTF-8"))
	}
	try {
		Descriptor := PersonalFileDescribe(Decoded)
		if !(Descriptor["id"] == Identity)
			return 0
		return Descriptor["components"]
	} catch {
		return 0
	}
}

/** Validates the exact descriptor shape rather than trusting supplied ids or labels. */
PersonalFileDescriptorValid(Descriptor) {
	if !(Descriptor is Map) || Descriptor.Count != 3 || !Descriptor.Has("id") || !Descriptor.Has("components") || !Descriptor.Has("label")
		return false
	for DescriptorKey in Descriptor {
		if !(DescriptorKey == "id") && !(DescriptorKey == "components") && !(DescriptorKey == "label")
			return false
	}
	if !(Descriptor["id"] is String) || !(Descriptor["label"] is String) || !(Descriptor["components"] is Array)
		return false
	try {
		Expected := PersonalFileDescribe(Descriptor["components"])
		return Expected["id"] == Descriptor["id"] && Expected["label"] == Descriptor["label"]
	} catch {
		return false
	}
}

/** Neutral policy classifies an exact canonical path; it never adopts a capability. */
PersonalFilePreferenceDefault(Path) {
	try Parts := TOML_ParseKeyPath(Path, true)
	catch
		return ""
	if Parts.Length < 3 || Parts[1] != "hotstrings" || !PersonalFileComponents(Parts[3])
		return ""
	if (Parts.Length == 3 && Parts[2] == "groups")
		|| (Parts.Length == 4 && Parts[2] == "modules" && Parts[4] != "")
		return PersonalFileDefaultEnabled()
	return ""
}

/** Returns an independent owned snapshot for each producer and consumer. */
PersonalFileDescriptorCopy(Descriptor) {
	if !PersonalFileDescriptorValid(Descriptor)
		throw TypeError("Invalid personal-file descriptor.")
	return PersonalFileDescribe(Descriptor["components"])
}
