--- static/ergopti_plus/linux/tests/unit/modules/llm/test_ollama_retained_installer.lua
--- Receives the actual live retained installer; original path fixtures stay exact.
local helpers = require("tests.helpers")
local fixture = require("tests.support.ollama_retained_fixture")
helpers.describe("Retained Linux Ollama installer", function()
 helpers.it("ordinary live transaction uses retained download same-FD adoption and extract only", function()
  local f = fixture(); local op = f.start(); f.through(9)
  local expected = { "tar-version", "tar-help", "mv-help", "zstd", "HTTP", "ADOPT", "EXTRACT", "PUBLISH", "ARTIFACT_FINISH" }
  assert(#f.calls == 9); for i, program in ipairs(expected) do assert(f.calls[i].program == program) end
  assert(op:is_settled() and op.result.ok and op.result.installed and f.cleanup == 1 and #f.completions == 1)
  assert(f.artifact_closed and f.prepares == 1)
 end)
 helpers.it("download callback cannot admit same-FD hash before physical retirement", function()
  local f = fixture(); local op = f.start(); f.through(4)
  local download = f.calls[5]; download.deliver()
  assert(#f.calls == 5 and not op:is_settled() and f.cleanup == 0)
  download.retire(); assert(f.calls[6].program == "ADOPT")
  op:cancel(); f.calls[6].retire(); assert(op:is_settled())
 end)
 helpers.it("same-FD hash callback cannot admit extraction before physical retirement", function()
  local f = fixture(); local op = f.start(); f.through(5)
  local hash = f.calls[6]; hash.deliver()
  assert(#f.calls == 6 and not op:is_settled() and f.cleanup == 0)
  hash.retire(); assert(f.calls[7].program == "EXTRACT")
  op:cancel(); f.calls[7].retire(); assert(f.calls[8].program == "ARTIFACT_FINISH")
  f.calls[8].retire(); assert(op:is_settled())
 end)
 helpers.it("missing authentic second completion refuses without hash or extraction", function()
  local f = fixture(); f.missing_completion = true; local op = f.start(); f.through(5)
  assert(op:is_settled() and not op.result.ok and op.result.error == "archive_download_failed")
  assert(#f.calls == 5 and f.artifact_closed and not f.files.published)
 end)
 helpers.it("checksum refusal cannot extract or publish", function()
  local f = fixture(); f.bad_hash = true; local op = f.start(); f.through(6)
  assert(op:is_settled() and not op.result.ok and op.result.error == "archive_checksum_mismatch")
  assert(#f.calls == 6 and not f.files.published and f.cleanup == 1)
 end)
 helpers.it("cancelled retained download keeps stage until real producer retirement", function()
  local f = fixture(); local op = f.start(); f.through(4)
  op:cancel(); assert(not op:is_settled() and f.cleanup == 0 and f.artifact_signalled and f.calls[5].signals > 0)
  f.calls[5].retire(); assert(op:is_settled() and f.cleanup == 1 and #f.completions == 0 and #f.calls == 5)
 end)
 helpers.it("late archive cleanup is a separate physical gate before file cleanup", function()
  local f = fixture(); local op = f.start(); f.through(8)
  assert(f.calls[9].program == "ARTIFACT_FINISH" and not op:is_settled() and f.cleanup == 0)
  f.calls[9].deliver(); assert(not op:is_settled() and f.cleanup == 0)
  f.calls[9].retire(); assert(op:is_settled() and f.cleanup == 1 and f.current)
 end)
 helpers.it("refused output brand retires without any path download fallback", function()
  local f = fixture(); f.refuse_target = true; local op = f.start(); f.through(4)
  assert(op:is_settled() and not op.result.ok and #f.calls == 4 and f.artifact_closed and f.cleanup == 1)
 end)
 helpers.it("foreign publication is preserved and cannot be claimed installed", function()
  local f = fixture(); f.foreign = true; local op = f.start(); f.through(9)
  assert(op:is_settled() and not op.result.ok and not op.result.installed)
  assert(op.result.error == "install_publication_not_owned" and f.artifact_closed)
 end)
end)
