[project]
name = "ergopti"
version = "2.2.0"
description = "Ergopti drivers generation and configuration tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "lxml>=6.0.2",
    "pyyaml>=6.0.3",
    "toml>=0.10.2",
]
