--- modules/llm/parser.lua

--- ==============================================================================
--- MODULE: LLM Output Parser
--- DESCRIPTION:
--- Strips conversational fillers and applies a Wagner-Fischer diffing
--- algorithm to align LLM predictions perfectly with the user's active buffer.
--- ==============================================================================

local M = {}

local utils  = require("lib.text_utils")
local Logger = require("lib.logger")
local LOG    = "llm.parser"





-- =======================================
-- =======================================
-- ======= 1/ Cleanup & Extraction =======
-- =======================================
-- =======================================

--- Enforces strict word limits by truncating excess and rejecting if below minimum.
--- @param text string The predicted next words.
--- @param min_w number Minimum allowed words.
--- @param max_w number Maximum allowed words (0 for unlimited).
--- @return string|nil The processed string, or nil if below minimum.
local function enforce_word_limits(text, min_w, max_w)
	if type(text) ~= "string" or text == "" then
		return (min_w > 0) and nil or ""
	end
	local count = 0
	local rebuilt = ""
	for w, s in text:gmatch("(%S+)(%s*)") do
		count = count + 1
		if max_w > 0 and count > max_w then break end
		rebuilt = rebuilt .. w
		if max_w <= 0 or count < max_w then rebuilt = rebuilt .. s end
	end
	rebuilt = rebuilt:gsub("%s+$", "")
	if count < min_w then return nil end
	return rebuilt
end

--- Strips conversational filler and markdown from the model’s raw text.
--- @param text string The raw output from the LLM.
--- @return string The cleaned text.
local function clean_model_output(text)
	if type(text) ~= "string" then return "" end
	
	text = utils.unescape_text(text)
	text = text:gsub("%*%*", ""):gsub("`", ""):gsub("\"", "")
	text = text:gsub("<[^>]->", "")
	
	text = text:gsub("^Voici la suite%s*:?%s*", "")
	text = text:gsub("^Je propose%s*:?%s*", "")
	text = text:gsub("^[Ss]uite%s+[Ff]inale%s*[:%.%-]*%s*", "")
	text = text:gsub("</body>%s*</html>", "")
	text = text:gsub("^[Ss][Uu][Ii][Tt][Ee]%s*:%s*", "")
	
	text = text:gsub("%[[Tt][Aa][Ii][Ll]_[Cc][Oo][Rr][Rr][Ee][Cc][Tt][Ee][Dd]%]", "TAIL_CORRECTED:")
	text = text:gsub("%[[Nn][Ee][Xx][Tt]_[Ww][Oo][Rr][Dd][Ss]%]", "NEXT_WORDS:")
	text = text:gsub("[Tt][Aa][Ii][Ll]_[Cc][Oo][Rr][Rr][Ee][Cc][Tt][Ee][Dd]%s*:", "TAIL_CORRECTED:")
	text = text:gsub("[Nn][Ee][Xx][Tt]_[Ww][Oo][Rr][Dd][Ss]%s*:", "NEXT_WORDS:")
	
	return text
end

--- Removes XML-like thinking tags from the model’s response to isolate the final answer.
--- @param text string The raw response containing potential thinking blocks.
--- @return string The response without thinking tags.
function M.strip_thinking(text)
	if type(text) ~= "string" then return "" end
	text = text:gsub("<think>.-</think>%s*", "")
	text = text:gsub("</think>%s*", "")
	return text
end

--- Splits batch output into individual prediction blocks based on separators.
--- @param raw string The concatenated batch output.
--- @return table An array of string blocks.
function M.split_blocks(raw)
	local blocks = {}
	for block in (raw .. "==="):gmatch("(.-)===") do
		local clean = block:gsub("^%s+", ""):gsub("%s+$", "")
		if clean ~= "" then table.insert(blocks, clean) end
	end
	if #blocks == 0 then table.insert(blocks, raw) end
	return blocks
end





-- ========================================
-- ========================================
-- ======= 2/ Core Processing Logic =======
-- ========================================
-- ========================================

--- Parses explicit prompt tags to determine insertions and deletions securely.
--- @param full_text string The full user context provided to the LLM.
--- @param tail_text string The current end of the user’s input.
--- @param block string The raw block of text generated by the model.
--- @return table|nil A table containing prediction data or nil if invalid.
function M.process_prediction(full_text, tail_text, block)
	Logger.debug(LOG, "Parsing model output block…")
	
	local Core = require("modules.llm.init")
	local min_w = tonumber(hs.settings.get("llm_min_words")) or Core.DEFAULT_STATE.llm_min_words
	local max_w = tonumber(hs.settings.get("llm_max_words")) or Core.DEFAULT_STATE.llm_max_words
	
	-- Normalize apostrophes to prevent false positive corrections in the diffing engine
	full_text = type(full_text) == "string" and full_text:gsub("'", "’") or ""
	tail_text = type(tail_text) == "string" and tail_text:gsub("'", "’") or ""
	block     = type(block) == "string" and block:gsub("'", "’") or ""
	
	block = clean_model_output(block)
	
	local is_advanced = block:find("TAIL_CORRECTED") or block:find("NEXT_WORDS")
	
	if is_advanced then
		local tc = block:match("TAIL_CORRECTED%s*:%s*(.-)[\r\n]+") or block:match("TAIL_CORRECTED%s*:%s*(.-)$") or ""
		local nw = block:match("NEXT_WORDS%s*:%s*(.-)[\r\n]+") or block:match("NEXT_WORDS%s*:%s*(.-)$") or ""

		local function trim(s)
			return s:match("^%s*(.-)%s*$") or ""
		end

		tc = trim(tc:gsub("%s*%]$", ""):gsub("^\"", ""):gsub("\"$", ""))
		nw = trim(nw:gsub("%s*%]$", ""):gsub("^\"", ""):gsub("\"$", ""))
		
		-- Enforce typography normalisation on model predictions to match input state
		tc = tc:gsub("'", "’")
		nw = nw:gsub("'", "’")
		
		nw = nw:gsub("^[%s%.…]+", ""):gsub("[%s%.…]+$", "")

		-- Apply strict word limits before any diffing evaluation
		nw = enforce_word_limits(nw, min_w, max_w)
		if not nw then return nil end

		if tc == "" and nw ~= "" then
			tc = trim((tail_text or ""):gsub("^\"", ""):gsub("\"$", ""))
		end

		if tc == "" and nw == "" then return nil end

		local normalized_full = (full_text or "")
		local tc_norm = tc
		
		-- Restore trailing spaces entered by the user
		local tail_trailing_space = normalized_full:match("([%s\194\160\226\128\175]+)$")
		if tail_trailing_space and not tc_norm:match("[%s\194\160\226\128\175]$") then
			tc_norm = tc_norm .. tail_trailing_space
		end

		-- Smart spacing merge to prevent LLM cutting mid-word without space
		local last_char = utils.utf8_sub(tc_norm, -1)
		local first_char = utils.utf8_sub(nw, 1, 1)
		local needs_space = not (last_char:match("[%s'’%-]") or last_char == "\194\160" or last_char == "\226\128\175" or first_char:match("[%s.,;)%}%%%]]") or nw == "")
		
		local nw_norm = nw
		if needs_space then 
			nw_norm = " " .. nw_norm 
		end

		-- Build the absolute complete intended string from the LLM
		local full_llm = tc_norm .. nw_norm
		
		-- Sliding window alignment
		local search_start = math.max(1, #normalized_full - 300)
		local best_c_len = -1
		local best_suffix = ""
		
		for i = search_start, #normalized_full do
			local b = normalized_full:byte(i)
			if b < 0x80 or b >= 0xC0 then
				local suffix = normalized_full:sub(i)
				local c_len = utils.get_common_prefix_utf8(suffix, full_llm)
				if c_len > best_c_len then
					best_c_len = c_len
					best_suffix = suffix
				end
			end
		end
		
		if best_c_len < 2 and #full_llm > 5 then
			best_suffix = (tail_text or "")
			best_c_len = utils.get_common_prefix_utf8(best_suffix, full_llm)
		end

		local tail_len = utils.utf8_len(tail_text)
		if best_c_len < tail_len * 0.4 and utils.utf8_len(tc_norm) < tail_len * 0.4 then return nil end

		local deletes = utils.utf8_len(best_suffix) - best_c_len
		local to_type = utils.utf8_sub(full_llm, best_c_len + 1)

		if to_type:gsub("[%s%.…]", "") == "" then return nil end

		local has_corr = false
		local chunks = {}
		local display_nw = ""

		-- If deletes > 0, the LLM actively modified or removed a user character
		if deletes > 0 then
			has_corr = true
			
			local prefix = utils.utf8_sub(full_llm, 1, best_c_len)
			local word_start_char = 1
			
			-- Look backwards to find the start of the corrected word
			for i = utils.utf8_len(prefix), 1, -1 do
				local c = utils.utf8_sub(prefix, i, i)
				if c == " " or c == "\n" or c == "\t" or c == "\194\160" or c == "\226\128\175" then
					word_start_char = i + 1
					break
				end
			end

			-- Look forwards to isolate ONLY the corrected word, leaving the rest to nw
			local word_end_char = utils.utf8_len(full_llm)
			for i = best_c_len + 1, utils.utf8_len(full_llm) do
				local c = utils.utf8_sub(full_llm, i, i)
				if c == " " or c == "\n" or c == "\t" or c == "\194\160" or c == "\226\128\175" then
					word_end_char = i - 1
					break
				end
			end

			local display_orig = utils.utf8_sub(best_suffix, word_start_char)
			local display_corr = utils.utf8_sub(full_llm, word_start_char, word_end_char)
			
			chunks = utils.diff_strings(display_orig, display_corr)
			display_nw = utils.utf8_sub(full_llm, word_end_char + 1)
		else
			has_corr = false
			chunks = {}
			display_nw = to_type
		end

		return { 
			deletes = deletes, 
			to_type = to_type, 
			nw = display_nw, 
			has_corrections = has_corr, 
			chunks = chunks 
		}
		
	else
		-- Basic / Raw Mode: Grab only the first line to truncate chatty paragraphs
		local nw = block:gsub("^%s+", ""):gsub("%s+$", "")
		nw = nw:match("([^\n\r]+)") or nw
		nw = nw:gsub("^%[?[Nn][Ee][Xx][Tt]%]?%s*:?%s*", "")
		nw = nw:gsub("^[Ss][Uu][Ii][Tt][Ee]%s*:%s*", "")
		nw = nw:gsub("^[Ss]uite%s+[Ff]inale%s*[:%.%-]*%s*", "")
		nw = nw:gsub("^[-•*]+%s*", "")
		nw = nw:gsub("^[%s%.…]+", ""):gsub("[%s%.…]+$", "")
		nw = nw:gsub("'", "’")
		
		if nw:find("www%.") or nw:find("http") or nw:find("</") then return nil end
		
		-- Robust overlap mitigation using word-by-word comparison for basic models
		local full_words = {}
		for w in (full_text or ""):gmatch("%S+") do table.insert(full_words, w) end
		
		local nw_words = {}
		for w in nw:gmatch("%S+") do table.insert(nw_words, w) end
		
		local start_idx = math.max(1, #full_words - 20)
		for i = start_idx, #full_words do
			local buf_suffix_count = #full_words - i + 1
			if buf_suffix_count <= #nw_words then
				local match = true
				for j = 1, buf_suffix_count do
					local bw = full_words[i + j - 1]:lower():gsub("[%p%c]", "")
					local pw = nw_words[j]:lower():gsub("[%p%c]", "")
					if bw ~= pw or bw == "" then
						match = false
						break
					end
				end
				
				if match then
					local remaining = {}
					for j = buf_suffix_count + 1, #nw_words do
						table.insert(remaining, nw_words[j])
					end
					nw = table.concat(remaining, " ")
					break
				end
			end
		end
		
		nw = nw:gsub("%s*%]$", ""):gsub("%s+$", "")

		-- Apply strict word limits before any diffing evaluation
		nw = enforce_word_limits(nw, min_w, max_w)
		if not nw then return nil end

		local to_type = nw
		local deletes = 0
		
		-- Smart spacing taking UTF-8 apostrophes and raw bytes into account for basic mode
		if to_type ~= "" and tail_text ~= "" then
			local t_last = utils.utf8_sub(tail_text, -1)
			local is_space = t_last:match("[%s]") or t_last == "\194\160" or t_last == "\226\128\175"
			local is_apos  = t_last:match("['’]")
			local type_start = utils.utf8_sub(to_type, 1, 1)
			
			if not is_space and not is_apos and not type_start:match("[%s.,;?!]") then
				to_type = " " .. to_type
				nw = " " .. nw
			end
		end

		if to_type:gsub("[%s%.…]", "") == "" then return nil end
		
		Logger.info(LOG, "Fallback text parsed successfully.")
		return { deletes = deletes, to_type = to_type, nw = nw, has_corrections = false, chunks = {} }
	end
end

return M
