#!/usr/bin/env python3
"""
Generate hotstring TOML files from an AutoHotkey source file.

For every Features["CategoryName"]["SubName"] block found in the AHK file,
one TOML file named <category_name>.toml is written in the same directory as
this script.  Each sub-block becomes a [[sub_name]] section inside that file.

A [_meta] / [_meta.sections] TOML table is prepended to each file so that
Hammerspoon can display human-readable descriptions in its menu.

Hand-crafted sub-blocks (e_deadkey, HashtagQuote, ChevronEqual, EqualString)
have no AHK source block; they are injected as sections into their parent
category TOML files (SFBsReduction and Rolls respectively).
"""

import json
import re
import sys
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Optional

sys.path.append(str(Path(__file__).resolve().parent.parent))

from utilities.logger import get_error_count, logger, reset_error_count


# Header prepended to every generated TOML file.
def get_toml_header() -> list[str]:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return [
        "# DO NOT EDIT THIS FILE DIRECTLY.",
        f"# This file was automatically generated by 0_generate_hotstrings.py on {now}. Any manual changes will be overwritten.",
        '# All entries use: trigger = { output = "replacement", is_word = true/false, auto_expand = true/false, is_case_sensitive = true/false, final_result = true/false }',
        "",
    ]


# Human-readable file-level labels used in the Hammerspoon menu.
FILE_DESCRIPTIONS: dict[str, str] = {
    "DistancesReduction": "Réduction des distances",
    "SFBsReduction": "Réduction des SFBs",
    "Rolls": "Roulements",
    "Autocorrection": "Autocorrection",
    "MagicKey": "Touche ★ et expansion de texte",
    "Personal": "Personnel",
}

# All generated TOML files land in this directory (next to this script).
OUTPUT_DIR = Path(__file__).parent

# Minimum output length above which final_result is set to True.
# Must match PASTE_THRESHOLD in keymap.lua: outputs longer than this are
# inserted via clipboard paste, so any sub-sequence could re-trigger a
# hotstring if re-scanning is not suppressed.
_FINAL_RESULT_THRESHOLD: int = 30


def _needs_final_result(output: str) -> bool:
    """Return True when expanded text should not be re-scanned for hotstrings.

    Criteria (any one is sufficient):
    - Output contains ``@``: likely an e-mail address.
    - Output length exceeds ``_FINAL_RESULT_THRESHOLD``: pasted via clipboard.
    - Output has **no letters** (a–z, A–Z, accented U+00C0–U+024F) **and** at
      least **2 distinct non-space characters**: this catches operator
      sequences like ``/*``, ``<=``, ``:=``, ``!=``, ``("`` which could
      re-trigger symbol-based hotstrings, while leaving simple repeated-char
      outputs like ``--``, ``==``, ``;;`` untouched (only 1 distinct char).

    Args:
        output: Expanded replacement text.

    Returns:
        ``True`` when the output should be marked ``final_result = true``.
    """
    if "@" in output or len(output) > _FINAL_RESULT_THRESHOLD:
        return True
    if re.search(r"[a-zA-Z\u00C0-\u024F]", output):
        return False
    # No letters: check for 2+ distinct non-space chars (operator sequence).
    distinct_non_space = {c for c in output if not c.isspace()}
    return len(distinct_non_space) >= 2


# Categories whose TOML files are gitignored and must never appear in the
# committed _index.json (Hammerspoon will load them outside of that index).
_PRIVATE_CATEGORIES: frozenset[str] = frozenset({"personal"})


def normalize_name(name: str) -> str:
    """Convert an AHK block name to a TOML-safe identifier.

    Lowercases, strips accents, and replaces non-alphanumeric characters with
    underscores.

    Args:
            name: Original AHK block name (e.g. "SFBsReduction", "IÉ").

    Returns:
            Normalised identifier (e.g. "sfbsreduction", "i_e").
    """
    name = name.lower()
    name = unicodedata.normalize("NFD", name)
    name = "".join(c for c in name if unicodedata.category(c) != "Mn")
    name = re.sub(r"[^a-z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name


def escape_toml_string(text: str) -> str:
    """Escape special characters for a TOML double-quoted basic string.

    Handles backslashes, double-quotes, and control characters that would
    break TOML parsing if emitted literally (newlines inside inline tables
    are forbidden by TOML 1.0 and break the line-by-line toml_reader).

    Args:
            text: Raw string value.

    Returns:
            Escaped string safe to embed between TOML double-quotes.
    """
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    text = text.replace("\n", "\\n")
    text = text.replace("\t", "\\t")
    text = text.replace("\r", "\\r")
    return text


def process_autohotkey_escapes(text: str) -> str:
    """Replace AHK escape sequences with their actual characters.

    Backtick-escape sequences (AHK2 style) are resolved.  Cursor-movement
    tokens such as ``{Left}``, ``{Right}``, etc. are **kept** as literal
    strings so that the Hammerspoon keymap module can emit the corresponding
    key press at expansion time.

    Args:
            text: Text containing AHK escape sequences.

    Returns:
            Text with escape sequences expanded, cursor tokens preserved.
    """
    replacements: dict[str, str] = {
        '`"': '"',
        "`'": "'",
        "``": "`",
        "`n": "\n",
        "`t": "\t",
        "`r": "\r",
        "`{": "{",
        "`}": "}",
        # Note: "" (two consecutive quotes) in an AHK2 string literal is the
        # in-string escape for a single literal ".  However, the regex now
        # consumes "" as an atomic unit before the closing-quote terminator,
        # and in the SendInput context of CreateHotstring, "" means TWO
        # literal quote characters the user wants typed.  We therefore keep
        # "" as-is here so that both quotes reach the TOML output.
    }
    for seq, replacement in replacements.items():
        text = text.replace(seq, replacement)
    return text


# ---------------------------------------------------------------------------
# AHK variable substitution & string-concatenation collapsing
# ---------------------------------------------------------------------------

# Map AHK global variable names → their compile-time value as a quoted AHK
# string literal so that they can be inlined before regexes are applied.
_AHK_VARIABLE_SUBSTITUTIONS: list[tuple[str, str]] = [
    # SpaceAroundSymbols is " " when the feature is enabled (the default).
    (r"\bSpaceAroundSymbols\b", '" "'),
    # ScriptInformation["MagicKey"] resolves to the magic-key character ★.
    (r'ScriptInformation\["MagicKey"\]', '"★"'),
]

# Patterns that indicate loop-level or callback-level hotstring registrations
# that cannot be statically resolved; they are skipped silently (no warning).
_UNRESOLVABLE_PATTERNS = re.compile(
    r"\bLetter\b"  # for Letter in StrSplit("abc...")
    r"|\bVowel\b"  # for Vowel in DeadkeyMappingCircumflex
    r"|\bcombo\b"  # combo parameter inside CreateHotstringCombo body
    r"|(?<![A-Za-z])value\b"  # value parameter (function body)
    r"|\bcreatehotstring\b.*\bfrom\b"  # CreateHotstring("", from, to)
    r"|=>.+"  # arrow-function callback (AHK2 syntax)
    r"|\bhotstringhandler\b"  # internal handler call
    r"|\bPersonalInformation\b"  # runtime private-data dictionary
    r"|\bPersonalInformationHotstrings\b"  # runtime private-data collection
    r"|\bGeneratePersonalInformation"  # custom generator function
    r"|\bCreateHotstringCombo"  # custom combo-hotstring functions
    r"|\bCreateDeadkeyHotstring\b",  # custom dead-key hotstring function
    re.IGNORECASE,
)

# Collapse adjacent AHK string concatenations: "a" . "b" → "ab".
# AHK2 uses backtick (not backslash) for in-string escaping, so the group
# pattern is simply [^"] (no backslash-escape handling needed here).
_CONCAT_RE = re.compile(r'"([^"]*)"\s*\.\s*"([^"]*)"')


def _collapse_ahk_string_concat(line: str) -> str:
    """Collapse ``"a" . "b"`` AHK concatenations into ``"ab"`` repeatedly.

    Args:
            line: AHK source line, possibly containing string concatenations.

    Returns:
            Line with all adjacent string literals merged.
    """
    prev: Optional[str] = None
    while prev != line:
        prev = line
        line = _CONCAT_RE.sub(
            lambda m: '"' + m.group(1) + m.group(2) + '"', line
        )
    return line


def preprocess_ahk_line(line: str) -> str:
    """Substitute known AHK variables and collapse string concatenations.

    Replaces compile-time global variable references (e.g. ``SpaceAroundSymbols``,
    ``ScriptInformation["MagicKey"]``) with their resolved string-literal values,
    then collapses adjacent ``"a" . "b"`` segments into ``"ab"``.

    Args:
            line: A single logical AHK statement (may be a joined multi-line call).

    Returns:
            The preprocessed line, ready for regex-based hotstring extraction.
    """
    for pattern, replacement in _AHK_VARIABLE_SUBSTITUTIONS:
        line = re.sub(pattern, replacement, line)
    return _collapse_ahk_string_concat(line)


# ---------------------------------------------------------------------------
# Description extraction
# ---------------------------------------------------------------------------


def _parse_ahk_desc_expr(expr: str) -> str:
    """Resolve an AHK string-concatenation expression into a plain string.

    Replaces ``ScriptInformation["..."]`` references with ``★`` and joins all
    double-quoted fragments.

    Args:
            expr: Raw AHK expression after ``Description:``, e.g.
                    ``"text " . ScriptInformation["MagicKey"] . " suite"``.

    Returns:
            Resolved plain string, e.g. ``"text ★ suite"``.
    """
    # Split on the AHK concatenation operator ' . ' (always surrounded by spaces).
    # Using \s+ (not \s*) avoids splitting on literal dots inside quoted strings
    # (e.g. "ê. = u." or "$eq.not$").
    tokens = re.split(r"\s+\.\s+", expr.strip().rstrip(","))
    parts: list[str] = []
    for tok in tokens:
        tok = tok.strip()
        if tok.startswith('"') and tok.endswith('"'):
            # Plain quoted literal — unescape AHK backtick sequences
            parts.append(process_autohotkey_escapes(tok[1:-1]))
        elif "ScriptInformation" in tok:
            parts.append("★")
        # else: skip things like numbers, booleans, etc.
    return "".join(parts)


def parse_ahk_descriptions(content: str) -> dict[str, dict[str, str]]:
    """Extract per-section descriptions from the ``Features`` map in *content*.

    Scans the AHK source for ``"SubName", { ... Description: ... }`` blocks
    and records the resolved description text for each ``(category, sub)`` pair.

    Args:
            content: Full AHK file content.

    Returns:
            ``{AHK_category_name: {AHK_sub_name: description_string}}``
    """
    # Locate the Features map block
    features_start = content.find("global Features := Map(")
    if features_start < 0:
        return {}

    # The Features map is followed by the first top-level if/hotstring block.
    # We only scan the initial declarations section.
    first_if = re.search(
        r"^\s*if\s+Features\[", content[features_start:], re.MULTILINE
    )
    features_text = (
        content[features_start : features_start + first_if.start()]
        if first_if
        else content[features_start : features_start + 20_000]
    )

    result: dict[str, dict[str, str]] = {}

    # Regexes to track context
    cat_re = re.compile(r'"([A-Za-z]+)",\s*Map\(')
    sub_re = re.compile(r'"([^"]+)",\s*\{')
    desc_re = re.compile(r"Description:\s*(.*)")

    lines = features_text.splitlines()
    current_cat: Optional[str] = None
    current_sub: Optional[str] = None
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        cm = cat_re.search(line)
        if cm and cm.group(1) != "__Order":
            current_cat = cm.group(1)
            current_sub = None

        sm = sub_re.search(line)
        if sm:
            cand = sm.group(1)
            if cand not in ("__Order",) and not cand.startswith("-"):
                current_sub = cand

        dm = desc_re.search(line)
        if dm and current_cat and current_sub:
            desc_expr = dm.group(1).strip()
            # Collect continuation lines when the expression is incomplete:
            # either it ends with the concatenation operator '.' or it ends
            # with an open bracket (e.g. ScriptInformation[ split across lines).
            while (
                desc_expr.rstrip(",").rstrip().endswith(".")
                or desc_expr.rstrip().endswith("[")
            ) and i + 1 < len(lines):
                i += 1
                desc_expr += " " + lines[i].strip()
            desc = _parse_ahk_desc_expr(desc_expr)
            if desc:
                result.setdefault(current_cat, {})[current_sub] = desc

        i += 1

    # Also scan standalone  Features["Cat"] := Map(...)  declarations that
    # appear outside the main global map (e.g. section 2 of the private file).
    standalone_cat_re = re.compile(r'Features\["([A-Za-z]+)"\]\s*:=\s*Map\(')
    for standalone_m in standalone_cat_re.finditer(content):
        cat_name = standalone_m.group(1)
        block_text = content[standalone_m.end() :]
        close_m = re.search(r"^\)", block_text, re.MULTILINE)
        if close_m:
            block_text = block_text[: close_m.start()]
        current_sub = None
        for bline in block_text.splitlines():
            bline_s = bline.strip()
            sm2 = sub_re.search(bline_s)
            if sm2:
                cand = sm2.group(1)
                if cand not in ("__Order",) and not cand.startswith("-"):
                    current_sub = cand
            dm = desc_re.search(bline_s)
            if dm and current_sub:
                desc = _parse_ahk_desc_expr(dm.group(1).strip())
                if desc:
                    result.setdefault(cat_name, {})[current_sub] = desc

    return result


def parse_ahk_orders(content: str) -> dict[str, list[str]]:
    """Extract the ``__Order`` list for every category in the AHK Features map.

    Separators (``"-"``) are preserved as ``"-"``; all other entries are
    normalized with :func:`normalize_name` to match the TOML section keys.
    Sections not mentioned in ``__Order`` but present in the data will be
    appended (in their original position) by the caller.

    Args:
        content: Full AHK file content.

    Returns:
        ``{category_name: [normalized_sub, "-", ...]}``
    """
    features_start = content.find("global Features := Map(")
    if features_start < 0:
        return {}

    first_if = re.search(
        r"^\s*if\s+Features\[", content[features_start:], re.MULTILINE
    )
    features_text = (
        content[features_start : features_start + first_if.start()]
        if first_if
        else content[features_start : features_start + 20_000]
    )

    result: dict[str, list[str]] = {}
    cat_re = re.compile(r'"([A-Za-z]+)",\s*Map\(')
    order_start_re = re.compile(r'"__Order"\s*,\s*\[')

    lines = features_text.splitlines()
    current_cat: Optional[str] = None
    i = 0

    while i < len(lines):
        line = lines[i]

        cm = cat_re.search(line)
        if cm and cm.group(1) != "__Order":
            current_cat = cm.group(1)

        if current_cat and order_start_re.search(line):
            # Collect the full array text — may span multiple lines
            array_text = ""
            # Take the portion after "["
            bracket_pos = line.find("[")
            array_text += line[bracket_pos + 1 :]
            # Consume continuation lines until the closing "]"
            while "]" not in array_text and i + 1 < len(lines):
                i += 1
                array_text += " " + lines[i]
            # Strip everything after the closing "]"
            close = array_text.find("]")
            if close >= 0:
                array_text = array_text[:close]
            # Extract all quoted items
            items: list[str] = re.findall(r'"([^"]+)"', array_text)
            normalized: list[str] = [
                "-" if item == "-" else normalize_name(item) for item in items
            ]
            result[current_cat] = normalized

        i += 1

    # Also scan standalone  Features["Cat"] := Map(...)  declarations.
    standalone_cat_re = re.compile(r'Features\["([A-Za-z]+)"\]\s*:=\s*Map\(')
    order_start_re_local = re.compile(r'"__Order"\s*,\s*\[')
    for standalone_m in standalone_cat_re.finditer(content):
        cat_name = standalone_m.group(1)
        block_text = content[standalone_m.end() :]
        close_m = re.search(r"^\)", block_text, re.MULTILINE)
        if close_m:
            block_text = block_text[: close_m.start()]
        for j, bline in enumerate(block_text.splitlines()):
            if order_start_re_local.search(bline):
                bracket_pos = bline.find("[")
                array_text = bline[bracket_pos + 1 :]
                remaining = block_text.splitlines()[j + 1 :]
                k = 0
                while "]" not in array_text and k < len(remaining):
                    array_text += " " + remaining[k]
                    k += 1
                close_bracket = array_text.find("]")
                if close_bracket >= 0:
                    array_text = array_text[:close_bracket]
                items: list[str] = re.findall(r'"([^"]+)"', array_text)
                normalized: list[str] = [
                    "-" if item == "-" else normalize_name(item)
                    for item in items
                ]
                result[cat_name] = normalized
                break

    return result


def parse_ahk_top_level_order(content: str) -> list[str]:
    """Extract the top-level ``__Order`` list from the AHK Features map.

    Returns the normalized category names in the order defined at the root of
    ``global Features := Map(...)`` (i.e. the order of the main categories,
    not the sub-sections within each category).

    Args:
            content: Full AHK file content.

    Returns:
            List of normalized category names in the defined order.  Separators
            (``"-"``) are excluded.
    """
    features_start = content.find("global Features := Map(")
    if features_start < 0:
        return []

    first_if = re.search(
        r"^\s*if\s+Features\[", content[features_start:], re.MULTILINE
    )
    features_text = (
        content[features_start : features_start + first_if.start()]
        if first_if
        else content[features_start : features_start + 20_000]
    )

    cat_re = re.compile(r'"([A-Za-z]+)",\s*Map\(')
    order_start_re = re.compile(r'"__Order"\s*,\s*\[')

    lines = features_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        # Stop as soon as we reach the first category Map – the top-level
        # __Order must come before any sub-Map definition.
        if cat_re.search(line):
            break
        order_m = order_start_re.search(line)
        if order_m:
            bracket_pos = line.find("[")
            array_text = line[bracket_pos + 1 :]
            while "]" not in array_text and i + 1 < len(lines):
                i += 1
                array_text += " " + lines[i]
            close = array_text.find("]")
            if close >= 0:
                array_text = array_text[:close]
            items: list[str] = re.findall(r'"([^"]+)"', array_text)
            return [normalize_name(it) for it in items if it != "-"]
        i += 1
    return []


def parse_ahk_circumflex_map(content: str) -> dict[str, str]:
    """Parse the ``DeadkeyMappingCircumflex`` global map from the AHK source.

    The map contains alternating key / value string pairs; each pair
    ``key, value`` produces one entry ``{key: value}`` in the returned dict.
    Line comments (``; …``) are stripped before extraction so they cannot
    interfere with the quoted-string scan.

    Args:
            content: Full AHK file content.

    Returns:
            Mapping of dead-key character to replacement character.  Excludes
            nothing — callers decide which entries to use.
    """
    marker = "global DeadkeyMappingCircumflex := Map("
    start = content.find(marker)
    if start < 0:
        logger.warning("DeadkeyMappingCircumflex not found in AHK source.")
        return {}

    # Walk forward to find the matching closing paren.
    idx = start + len(marker)
    depth = 1
    while idx < len(content) and depth > 0:
        c = content[idx]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        idx += 1
    map_body = content[start + len(marker) : idx - 1]

    # Strip inline comments so semicolons inside them can't interfere.
    # A naive line.find(";") would incorrectly truncate at the ";" key entry,
    # so we track whether we are inside a double-quoted string first.
    def _strip_comment(line: str) -> str:
        in_str = False
        for i, ch in enumerate(line):
            if ch == '"':
                in_str = not in_str
            elif ch == ";" and not in_str:
                return line[:i]
        return line

    clean_lines: list[str] = [
        _strip_comment(line) for line in map_body.splitlines()
    ]
    clean_body = "\n".join(clean_lines)

    # Extract all double-quoted literal strings.  AHK2 uses backtick for
    # in-string escaping, so [^"] is safe as the non-capturing inner pattern.
    strings = re.findall(r'"([^"]*)"', clean_body)

    # Pair up: even index = key, odd index = value.
    result: dict[str, str] = {}
    for i in range(0, len(strings) - 1, 2):
        result[strings[i]] = strings[i + 1]
    return result


# ---------------------------------------------------------------------------


def _extract_brace_body(content: str, match_end: int) -> str:
    """Return the text between the braces of a block whose opening brace
    was consumed at *match_end*.

    Args:
            content: Full file content.
            match_end: Index just past the opening ``{``.

    Returns:
            Body text (without surrounding braces), or empty string on failure.
    """
    idx = match_end
    depth = 1
    while idx < len(content) and depth > 0:
        if content[idx] == "{":
            depth += 1
        elif content[idx] == "}":
            depth -= 1
        idx += 1
    return content[match_end : idx - 1] if depth == 0 else ""


def find_all_blocks(content: str) -> dict[str, dict[str, str]]:
    """Discover every ``Features["Cat"]["Sub"]`` block in *content*.

    Multiple occurrences of the same ``(cat, sub)`` pair are concatenated so
    that split blocks (e.g. when a condition references two features) are
    merged transparently.

    Args:
            content: Full AHK file content.

    Returns:
            ``{category: {sub_name: body_text}}`` – names in their original casing.
    """
    # Match lines like:
    #   if Features["Cat"]["Sub"].Enabled {
    #   if Features["Cat"]["Sub"] {
    #   if Features["Cat"]["Sub"].Enabled and Features["X"]["Y"].Enabled {
    pattern = re.compile(
        r"(?:^|(?<=\n))\s*(?:} else )?if\s+"
        r'Features\["(?P<cat>[^"]+)"\]\["(?P<sub>[^"]+)"\]'
        r"(?:\.Enabled)?\b[^{]*\{",
    )

    result: dict[str, dict[str, str]] = {}
    for m in pattern.finditer(content):
        cat = m.group("cat")
        sub = m.group("sub")
        body = _extract_brace_body(content, m.end())
        if not body.strip():
            continue
        result.setdefault(cat, {}).setdefault(sub, "")
        result[cat][sub] += ("\n" if result[cat][sub] else "") + body

    return result


# ---------------------------------------------------------------------------
# Hotstring parsing
# ---------------------------------------------------------------------------


def _extract_hotstring_from_line(
    line: str,
) -> tuple[Optional[str], Optional[str], bool, bool, bool, bool, bool]:
    """Parse one (possibly multi-line-joined) AHK call and return its fields.

    Applies :func:`preprocess_ahk_line` first so that known AHK global
    variables (``SpaceAroundSymbols``, ``ScriptInformation["MagicKey"]``) are
    resolved and adjacent string literals are merged before the regexes run.

    Args:
            line: A single logical AHK statement, with whitespace normalised.

    Returns:
            ``(trigger, output, is_word, auto_expand, case_sensitive,
            final_result, strict_case)`` where *trigger* and *output* are
            ``None`` when no hotstring was found. ``final_result`` is extracted
            from an explicit ``Map("FinalResult", True/False)`` argument if
            present, otherwise derived automatically from the output via
            :func:`_needs_final_result`. ``strict_case`` is ``True`` when the
            original AHK flags contained a ``C`` modifier on a plain
            ``CreateHotstring`` call — this indicates a case-sensitive match
            that the AHK loader must reinstate by re-adding ``C`` to its
            generated flag string (``CreateCaseSensitiveHotstrings`` already
            emits per-variant hotstrings with their own ``C`` flag, so this
            field is only meaningful when *case_sensitive* is ``False``).
    """
    # Resolve variables and collapse string concatenations upfront.
    line = preprocess_ahk_line(line)

    case_sensitive = "CreateCaseSensitiveHotstrings" in line

    # Try from most-specific to most-generic.
    patterns: list[str] = [
        # Standard CreateHotstring / CreateCaseSensitiveHotstrings.
        (
            r"(?:CreateCaseSensitiveHotstrings|CreateHotstring)\s*\(\s*"
            r'"(?P<opts>[^"]*)",\s*'
            r'"(?P<trig>(?:[^"`\\]|\\.|`.|"")*)",\s*'
            r'"(?P<out>(?:[^"`\\]|\\.|`.|"")*)",?\s*'
        ),
        # Hotstring() legacy format
        (
            r"Hotstrings?\s*\("
            r'(?:\s*"(?P<opts>[^"]*)",)?'
            r'\s*"(?P<trig>[^"]+?)"'
            r'\s*,\s*"(?P<out>[^"]+?)"'
            r"\s*\)"
        ),
    ]

    for pat in patterns:
        m = re.search(pat, line, re.DOTALL)
        if not m:
            continue
        opts = m.group("opts") or ""
        trigger = process_autohotkey_escapes(m.group("trig"))
        output = process_autohotkey_escapes(m.group("out"))
        auto_expand = "*" in opts
        is_word = "?" not in opts
        # ``C`` on a plain ``CreateHotstring`` call forces exact-case matching.
        # We only track it when the call is NOT CreateCaseSensitiveHotstrings,
        # since the latter already synthesises per-variant hotstrings, each
        # carrying its own ``C`` flag — re-capturing ``C`` there would be
        # redundant and would falsely collapse the multi-variant expansion.
        strict_case = ("C" in opts) and not case_sensitive

        # --- NOUVELLE LOGIQUE POUR FINAL_RESULT ---
        # On cherche un argument "FinalResult", True|False|1|0 dans la suite de la ligne
        explicit_fr_match = re.search(
            r'"FinalResult"\s*,\s*(true|false|1|0)\b',
            line[m.end() :],
            re.IGNORECASE,
        )

        if explicit_fr_match:
            val = explicit_fr_match.group(1).lower()
            final_result = val in ("true", "1")
        else:
            final_result = _needs_final_result(output)
        # ------------------------------------------

        return (
            trigger,
            output,
            is_word,
            auto_expand,
            case_sensitive,
            final_result,
            strict_case,
        )

    return None, None, False, False, False, False, False


def _strip_ahk_inline_comment(line: str) -> str:
    """Strip an AHK inline comment (``; ...``) from *line*.

    Respects double-quoted string literals so that semicolons inside quotes
    are not treated as comment starters.  AHK backtick escapes (`` `x ``) are
    handled inside strings.

    Args:
            line: A single AHK statement line.

    Returns:
            The line with the inline comment removed, stripped of trailing
            whitespace.
    """
    in_string = False
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "`" and in_string:
            # AHK backtick escape: skip the next character unconditionally
            i += 2
            continue
        if ch == '"':
            in_string = not in_string
        elif ch == ";" and not in_string:
            return line[:i].rstrip()
        i += 1
    return line


def _extract_inline_comment(line: str) -> str:
    """Return the AHK inline comment (without the leading ``;``) from *line*.

    Uses the same string-literal-aware scan as :func:`_strip_ahk_inline_comment`
    so semicolons inside quoted strings are not misread as comment starters.

    Args:
            line: A single AHK statement line (may already be stripped).

    Returns:
            The trimmed comment text, or an empty string when there is no
            inline comment.
    """
    in_string = False
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "`" and in_string:
            i += 2
            continue
        if ch == '"':
            in_string = not in_string
        elif ch == ";" and not in_string:
            return line[i + 1 :].strip()
        i += 1
    return ""


_AHK1_HOTSTRING_HEADER_RE = re.compile(r":([^:\n]*):([^:\n]+)::\s*\{")


def _extract_send_instant_output(block: str) -> str:
    """Extract and normalise the output string from a ``SendInstant(...)`` call.

    Handles both single-line strings and multi-line AHK2 continuation-section
    strings (``"\\n(\\n...\\n)"``) .  Double-quote escape (``""`` → ``"``) and
    backtick escapes are applied to the extracted content.

    Args:
        block: Body text of a ``:*:trigger:: { ... }`` block (between the
               braces), with no surrounding braces.

    Returns:
        Normalised output text, or empty string if no ``SendInstant`` found.
    """
    # Single-line: SendInstant("text here")
    single_m = re.search(r'SendInstant\("([^"\n]*)"\)', block)
    if single_m:
        return process_autohotkey_escapes(single_m.group(1))

    # Multi-line continuation section: SendInstant("\n(\n...\n)"\n)
    # The string literal ends with )" where ) closes the continuation section
    # and " closes the string.
    multi_m = re.search(r'SendInstant\("\s*\n(.*?)\)"', block, re.DOTALL)
    if not multi_m:
        return ""

    raw = multi_m.group(1)

    # Strip the AHK2 continuation-section ( / ) marker lines if present.
    # The opening ( is the first non-empty line; the closing ) was consumed by
    # the )" in the regex, so only the ( line needs to be stripped here.
    lines = raw.split("\n")
    while lines and re.match(r"^\s*\(\s*$", lines[0]):
        lines.pop(0)

    # Dedent: remove common leading whitespace from non-empty lines.
    non_empty = [li for li in lines if li.strip()]
    if non_empty:
        min_indent = min(len(li) - len(li.lstrip()) for li in non_empty)
        lines = [
            li[min_indent:] if len(li) >= min_indent else li for li in lines
        ]

    content = "\n".join(lines).strip()

    # AHK2 in-string double-quote escape inside continuation sections: "" → "
    content = content.replace('""', '"')

    # Apply remaining backtick escapes.
    return process_autohotkey_escapes(content)


def _extract_legacy_hotstrings(
    body: str,
) -> list[tuple[str, str, bool, bool, bool, bool, bool]]:
    """Parse AHK1-style ``:*:trigger:: { SendInstant(...) }`` hotstrings.

    These use the legacy AHK label syntax rather than ``CreateHotstring()``.
    The trigger options (e.g. ``*`` for auto-expand) are parsed from the
    colon-prefix.  The output text is extracted from ``SendInstant()`` and
    optional trailing key tokens are appended from ``SendFinalResult()``.

    Args:
        body: Raw body text of a ``Features[...][...]`` block.

    Returns:
        List of ``(trigger, output, is_word, auto_expand, case_sensitive,
        final_result, strict_case)`` 7-tuples, one per discovered legacy
        hotstring.  ``strict_case`` mirrors the ``_extract_hotstring_from_line``
        contract but is always ``False`` here — legacy entries are funnelled
        through ``CreateCaseSensitiveHotstrings`` whose per-variant synthesis
        already handles case, so re-flagging ``C`` would be redundant.
    """
    results: list[tuple[str, str, bool, bool, bool, bool, bool]] = []
    pos = 0
    while pos < len(body):
        header_m = _AHK1_HOTSTRING_HEADER_RE.search(body, pos)
        if not header_m:
            break

        opts_str = header_m.group(1)  # e.g. "*" or "*C"
        trigger = header_m.group(2).strip()

        # Walk forward from the opening brace, counting balanced braces.
        # Braces inside string literals (between pairs of ") are ignored so
        # that AHK key tokens like {Left} do not confuse the depth counter.
        brace_start = header_m.end()
        depth = 1
        idx = brace_start
        in_str = False
        while idx < len(body) and depth > 0:
            ch = body[idx]
            if ch == "`" and in_str:
                idx += 2  # AHK backtick escape – skip next char
                continue
            if ch == '"':
                in_str = not in_str
            elif not in_str:
                if ch == "{":
                    depth += 1
                elif ch == "}":
                    depth -= 1
            idx += 1
        block = body[brace_start : idx - 1]
        pos = idx

        auto_expand = "*" in opts_str
        is_word = True
        # Mirror the convention used by CreateHotstring vs
        # CreateCaseSensitiveHotstrings: the tuple element means "was this
        # extracted from the CaseSensitive variant?" which entries_to_toml_lines
        # then inverts (str(not case_sensitive)) when writing is_case_sensitive.
        # AHK1 `:C:` option = case-sensitive; absence = case-insensitive (False).
        is_case_sensitive = "C" in opts_str

        output = _extract_send_instant_output(block)
        if not output:
            continue

        # Append key tokens from an optional SendFinalResult("{...}") call.
        final_m = re.search(r'SendFinalResult\("([^"]+)"\)', block)
        if final_m:
            output += final_m.group(1)

        results.append(
            (
                trigger,
                output,
                is_word,
                auto_expand,
                is_case_sensitive,
                _needs_final_result(output),
                False,
            )
        )

    return results


_COMMENTED_OUT_RE = re.compile(
    r"^\s*;+\s*(?:CreateHotstring|CreateCaseSensitiveHotstrings)\s*\("
)


def parse_body(
    body: str,
    *,
    skip_identity: bool = True,
) -> list[tuple[str, str, bool, bool, bool, bool, str, bool, bool]]:
    """Extract all hotstring entries from a block body.

    Section-header comments (``; === Name ===``) are ignored – every entry
    just goes into a flat list.  Duplicate triggers within the same body are
    silently dropped (first occurrence wins).

    In addition to active ``CreateHotstring`` calls, single-line
    **commented-out** hotstrings are also captured (and flagged as disabled
    in the returned tuple) so that downstream callers can carry them over to
    the TOML files.  Trailing ``; …`` comments on an active hotstring line
    are preserved as well.

    Args:
            body: Raw body text of a ``Features[...][...]`` block.
            skip_identity: When ``True`` (default), non-auto-expand hotstrings
                    where trigger equals output are dropped (they are genuine
                    no-ops: they need an end-key to fire and would just retype
                    the trigger).  Auto-expand (``*``) identity hotstrings are
                    **always** kept regardless of this flag: they are guard
                    entries that prevent shorter triggers from firing inside a
                    longer word (e.g. ``prochaine`` blocks shorter SFB
                    corrections that would otherwise match inside it).  Pass
                    ``False`` to also keep non-auto-expand identity entries
                    (used for the ``Repeat`` section).

    Returns:
            Deduplicated list of
            ``(trigger, output, is_word, auto_expand, case_sensitive,
            final_result, comment, is_disabled, strict_case)`` 9-tuples where
            ``comment`` is the trailing ``; …`` note (or empty string),
            ``is_disabled`` marks hotstrings that were commented out in
            the AHK source, and ``strict_case`` forwards the ``C`` flag bit
            from :func:`_extract_hotstring_from_line` so downstream emitters
            can re-apply it to the generated TOML.
    """
    entries: list[tuple[str, str, bool, bool, bool, bool, str, bool, bool]] = []
    seen: set[str] = set()

    # First pass: extract AHK1-style :*:trigger:: { SendInstant(...) } blocks
    # before the line-by-line scan so those triggers are registered in `seen`
    # and their multi-line bodies do not confuse the CreateHotstring parser.
    for legacy in _extract_legacy_hotstrings(body):
        trig, out, iw, ae, cs, fr, sc = legacy
        if skip_identity and trig == out:
            continue
        if trig not in seen:
            seen.add(trig)
            entries.append((trig, out, iw, ae, cs, fr, "", False, sc))

    lines = body.split("\n")
    i = 0

    while i < len(lines):
        raw_line = lines[i]
        line = raw_line.strip()
        if not line:
            i += 1
            continue

        # Handle single-line commented-out hotstrings (e.g. ``; CreateHotstring(...)``).
        # Multi-line commented-out blocks are not supported: in practice every
        # disabled entry in the AHK source fits on one line.
        if _COMMENTED_OUT_RE.match(raw_line):
            uncommented = re.sub(r"^\s*;+\s*", "", line, count=1)
            disabled_reason = _extract_inline_comment(uncommented)
            code_part = _strip_ahk_inline_comment(uncommented)
            (
                trigger,
                output,
                is_word,
                auto_expand,
                case_sensitive,
                final_result,
                strict_case,
            ) = _extract_hotstring_from_line(code_part)
            if trigger and output and trigger not in seen:
                seen.add(trigger)
                entries.append(
                    (
                        trigger,
                        output,
                        is_word,
                        auto_expand,
                        case_sensitive,
                        final_result,
                        disabled_reason,
                        True,
                        strict_case,
                    )
                )
            i += 1
            continue

        if line.startswith(";"):
            i += 1
            continue

        # Join continuation lines for multi-line calls — also covers bare
        # ``Hotstring(`` (low-level callback form with no ``Create`` prefix).
        _is_open_call = (
            "CreateCaseSensitiveHotstrings(" in line
            or "CreateHotstring(" in line
            or bool(re.search(r"(?<![A-Za-z])Hotstring\s*\(", line))
        )
        # Track the last source line that contributed to the joined statement
        # so we can extract the trailing ``; …`` comment from that specific
        # line (the comment lives on the line carrying the closing parenthesis).
        last_contrib_i = i
        if _is_open_call and not _strip_ahk_inline_comment(line).endswith(")"):
            j = i + 1
            while j < len(lines) and not _strip_ahk_inline_comment(
                line
            ).endswith(")"):
                next_fragment = lines[j].strip()
                # Ignore standalone comment lines; they corrupt the joined expression.
                if not next_fragment.startswith(";"):
                    # Strip inline comments before joining so that embedded
                    # "; comment" text does not mask the closing ")" in the
                    # loop condition check.
                    stripped_fragment = _strip_ahk_inline_comment(next_fragment)
                    if stripped_fragment:
                        line += " " + stripped_fragment
                        last_contrib_i = j
                j += 1
            i = j
        else:
            i += 1

        tail_comment = _extract_inline_comment(lines[last_contrib_i])

        (
            trigger,
            output,
            is_word,
            auto_expand,
            case_sensitive,
            final_result,
            strict_case,
        ) = _extract_hotstring_from_line(line)

        if trigger and output:
            # Skip non-auto-expand identity hotstrings (trigger == output)
            # by default: without the ``*`` flag they would need an end-key
            # to fire and, upon firing, would simply retype the trigger —
            # a genuine no-op in Hammerspoon.
            # Auto-expand (``*``) identity hotstrings are guard entries that
            # prevent shorter triggers from firing inside a longer word
            # (e.g. ``prochaine`` blocks shorter SFB-correction triggers that
            # would otherwise match inside it).  They must always be kept,
            # regardless of the section.
            if skip_identity and trigger == output and not auto_expand:
                pass
            elif trigger not in seen:
                seen.add(trigger)
                entries.append(
                    (
                        trigger,
                        output,
                        is_word,
                        auto_expand,
                        case_sensitive,
                        final_result,
                        tail_comment,
                        False,
                        strict_case,
                    )
                )
        elif any(
            kw in line
            for kw in (
                "CreateHotstring",
                "CreateCaseSensitiveHotstrings",
                "Hotstring",
            )
        ):
            # Silently skip patterns that are inherently unresolvable at parse
            # time (loop variables, callback lambdas, etc.).
            if not _UNRESOLVABLE_PATTERNS.search(line):
                logger.warning(
                    "Failed to parse: %s",
                    (line[:120] + "...") if len(line) > 120 else line,
                )

    return entries


# ---------------------------------------------------------------------------
# TOML rendering
# ---------------------------------------------------------------------------


def entries_to_toml_lines(
    entries: list[tuple[str, str, bool, bool, bool, bool, str, bool]],
) -> list[str]:
    """Render a list of hotstring entries as TOML assignment lines.

    Each entry is an 8-tuple ``(trigger, output, is_word, auto_expand,
    case_sensitive, final_result, comment, is_disabled)``.  The
    ``final_result`` field is always written (``true`` or ``false``) so that
    Hammerspoon can rely on its presence without a default-value fallback.
    A non-empty *comment* is appended as an inline ``# …`` note and
    *is_disabled* entries are prefixed with ``# `` so the whole TOML
    assignment becomes a comment (mirroring an AHK ``; CreateHotstring(...)``
    line).

    Args:
            entries: Hotstring tuples produced by :func:`parse_body`.

    Returns:
            One TOML line per entry.
    """
    lines = []
    for row in entries:
        trigger, output, is_word, auto_expand, case_sensitive = row[:5]
        final_result: bool = row[5] if len(row) > 5 else False  # type: ignore[index]
        comment: str = row[6] if len(row) > 6 else ""  # type: ignore[index]
        is_disabled: bool = row[7] if len(row) > 7 else False  # type: ignore[index]
        strict_case: bool = row[8] if len(row) > 8 else False  # type: ignore[index]
        t = escape_toml_string(trigger)
        o = escape_toml_string(output)
        line = (
            f'"{t}" = {{ output = "{o}"'
            f", is_word = {str(is_word).lower()}"
            f", auto_expand = {str(auto_expand).lower()}"
            f", is_case_sensitive = {str(not case_sensitive).lower()}"
            f", final_result = {str(final_result).lower()}"
        )
        # Emit the optional ``is_case_sensitive_strict`` flag only when set so
        # the common case (default ``false``) stays untouched and TOML diffs
        # remain minimal. The AHK loader treats a missing field as ``false``.
        if strict_case:
            line += ", is_case_sensitive_strict = true"
        line += " }"
        if comment:
            line += f"  # {comment}"
        if is_disabled:
            line = "# " + line
        lines.append(line)
    return lines


def write_category_toml(
    category: str,
    sub_blocks: dict[
        str, list[tuple[str, str, bool, bool, bool, bool, str, bool]]
    ],
    section_descriptions: Optional[dict[str, str]] = None,
    section_order: Optional[list[str]] = None,
) -> int:
    """Write one TOML file for *category* and return the total entry count.

    The filename is :func:`normalize_name` applied to *category*.
    Each sub-block becomes a ``[[sub_name]]`` array-of-tables section.
    A leading ``[_meta]`` table carries the human-readable descriptions used
    by the Hammerspoon menu, including an optional ``sections_order`` array
    that records the original AHK ``__Order`` list for faithful menu ordering.

    Args:
            category: Original AHK category name (e.g. ``"MagicKey"``).
            sub_blocks: Mapping of sub-block names to their hotstring entries.
            section_descriptions: Optional ``{AHK_sub_name: description}`` mapping
                    extracted from the AHK Features map.
            section_order: Optional ordered list of *normalised* section names
                    (with ``"-"`` as separator sentinel) extracted from the AHK
                    ``__Order`` array.  Sections not listed are appended at the
                    end.  When ``None``, the insertion order of *sub_blocks* is
                    kept.

    Returns:
            Total number of entries written.
    """
    filename = normalize_name(category) + ".toml"
    output_file = OUTPUT_DIR / filename

    lines = get_toml_header()

    # ── Build final section order ─────────────────────────────────────────────
    known_subs = list(sub_blocks.keys())
    norm_known = [normalize_name(s) for s in known_subs]

    if section_order:
        ordered: list[str] = []
        seen_norm: set[str] = set()
        for item in section_order:
            if item == "-":
                ordered.append("-")
            elif item in norm_known and item not in seen_norm:
                ordered.append(item)
                seen_norm.add(item)
        # Append any sub that was not referenced in __Order
        for norm in norm_known:
            if norm not in seen_norm:
                ordered.append(norm)
                seen_norm.add(norm)
    else:
        ordered = norm_known

    # ── [_meta] block ────────────────────────────────────────────────────────
    file_desc = FILE_DESCRIPTIONS.get(category, "")
    lines.append("[_meta]")
    lines.append(f'description = "{escape_toml_string(file_desc)}"')

    # Write sections_order as a TOML inline array (preserves order + separators)
    toml_items = ", ".join(f'"{item}"' for item in ordered)
    lines.append(f"sections_order = [{toml_items}]")
    lines.append("")

    if section_descriptions:
        lines.append("[_meta.sections]")
        for sub_name in sub_blocks:
            norm = normalize_name(sub_name)
            desc = section_descriptions.get(sub_name, "")
            if desc:
                lines.append(f'{norm} = "{escape_toml_string(desc)}"')
        lines.append("")

    # ── section data — written in the resolved order ──────────────────────────
    norm_to_orig = {normalize_name(s): s for s in known_subs}
    total = 0
    for item in ordered:
        if item == "-":
            continue  # separators have no data block
        orig = norm_to_orig.get(item)
        if orig is None:
            continue
        entries = sub_blocks.get(orig, [])
        if not entries:
            continue
        lines.append(f"[[{item}]]")
        lines.extend(entries_to_toml_lines(entries))
        lines.append("")
        total += len(entries)

    if total == 0:
        logger.warning("Skipping %s – no entries found", filename)
        return 0

    # Nouvelle logique : comparer le contenu généré (hors date) à l'existant
    def strip_date(toml: str) -> str:
        return "\n".join(
            [
                line
                for line in toml.splitlines()
                if not line.startswith(
                    "# This file was automatically generated by 0_generate_hotstrings.py on "
                )
            ]
        )

    new_content = "\n".join(lines)
    if output_file.exists():
        existing_content = output_file.read_text(encoding="utf-8")
        if (
            strip_date(new_content).strip()
            == strip_date(existing_content).strip()
        ):
            # Pas de changement hors date, ne pas écraser
            logger.info("Unchanged %s (only date would differ)", filename)
            return total

    output_file.write_text(new_content, encoding="utf-8")
    logger.info("Written %s (%d entries)", filename, total)
    return total


# ---------------------------------------------------------------------------
# Handcrafted section data (no AHK source – injected into parent TOMLs)
# ---------------------------------------------------------------------------


def _comment_entries() -> list[tuple[str, str, bool, bool, bool, bool, str, bool]]:
    r"""Return entries for the Comment roll: ``\"`` ➜ ``/*`` and ``"\`` ➜ ``*/``.

    The AHK source uses backtick-escaped double-quotes inside the string
    literals (``\`"`` and `` `"\``).  These sequences match
    ``_UNRESOLVABLE_PATTERNS`` and are silently skipped by the parser,
    so they must be hand-crafted.
    """
    return [
        ('\\"', "/*", False, True, False, _needs_final_result("/*"), "", False),
        ('"\\', "*/", False, True, False, _needs_final_result("*/"), "", False),
    ]


# Vowel keys following ê that use is_word=False so the hotstring fires
# mid-word (e.g. "coêut" → "coût").  Non-vowel keys keep is_word=True.
_ECIRCUMFLEX_VOWEL_KEYS: frozenset[str] = frozenset("aAiIoOuUàÀèÈéÉêÊ")


def _deadkey_ecircumflex_entries(
    circumflex_map: dict[str, str],
) -> list[tuple[str, str, bool, bool, bool, bool, str, bool]]:
    """Generate hotstring entries for all ``ê``+key combinations.

    Iterates the full ``DeadkeyMappingCircumflex`` and produces one
    ``(trigger, output, is_word, auto_expand, case_sensitive)`` tuple per
    entry.  Excluded keys:

    - ``"e"`` / ``"E"``: handled by the dedicated ``ECircumflexE`` section
      (``êe`` ➜ ``œ``).
    - ``"t"`` / ``"T"``: reserved so that ``être`` can be typed normally.

    Since both the vowel shortcuts (``CreateCaseSensitiveHotstrings``) and the
    remaining dead-key shortcuts (``CreateDeadkeyHotstring``) use the AHK ``C``
    flag, each (key, value) pair from the map is emitted as a distinct
    case-sensitive entry.

    ``is_word`` behaviour depends on the following key:

    - **Vowel keys** (``_ECIRCUMFLEX_VOWEL_KEYS``): ``is_word=False`` so the
      hotstring fires even mid-word, e.g. ``coêut`` ➜ ``coût``.
    - **Non-vowel keys**: ``is_word=True`` mirrors the AHK
      ``ShouldActivateDeadkey`` logic – the combination only fires at a word
      boundary, preventing mid-word false positives like ``mêm`` in ``même``.

    Args:
            circumflex_map: Parsed ``{key: value}`` dict from the AHK source.

    Returns:
            Ordered list of hotstring entry tuples.
    """
    excluded = {"e", "E", "t", "T"}
    return [
        (
            f"ê{key}",
            value,
            key not in _ECIRCUMFLEX_VOWEL_KEYS,
            True,
            False,
            _needs_final_result(value),
            "",
            False,
        )
        for key, value in circumflex_map.items()
        if key not in excluded
    ]


def _hashtag_quote_entries() -> list[tuple[str, str, bool, bool, bool, bool, str, bool]]:
    """Return entries for the HashtagQuote roll: (# ➜ (" and [# ➜ [\'.

    This roll is implemented via a ``#HotIf`` block in AHK (not a standard
    ``CreateHotstring`` call) and therefore cannot be parsed automatically.
    When the last character sent is ``(`` or ``[``, pressing the AltGr-mapped
    ``#`` key outputs a double-quote instead.
    """
    return [
        ("(#", '("', False, True, False, _needs_final_result('("'), "", False),
        ("[#", '["', False, True, False, _needs_final_result('["'), "", False),
    ]


def _chevron_equal_entries() -> list[tuple[str, str, bool, bool, bool, bool, str, bool]]:
    """Return entries for the ChevronEqual roll: <% ➜ <= and >% ➜ >=.

    This roll is also implemented via a ``#HotIf`` block in AHK and is not
    captured by the standard block parser.  When the last character sent is
    ``<`` or ``>``, pressing the AltGr-mapped ``%`` key outputs ``=``.
    """
    return [
        ("<%", "<=", False, True, False, _needs_final_result("<="), "", False),
        (">%", ">=", False, True, False, _needs_final_result(">="), "", False),
    ]


def _equal_string_entries() -> list[tuple[str, str, bool, bool, bool, bool, str, bool]]:
    """Return corrected entries for the EqualString roll: [) ➜ = "".

    The AHK source uses consecutive backtick-escaped double-quotes
    (`` `"`" ``) followed by a cursor-movement command.  This pattern
    confuses the string-concatenation collapsing regex, so the automatic
    parser yields a truncated output (a bare backtick).  These hand-crafted
    entries override the broken parsed ones with the correct expansion.
    """
    return [
        (" [)", ' = ""', False, True, False, _needs_final_result(' = ""'), "", False),
        ("[)", ' = ""', False, True, False, _needs_final_result(' = ""'), "", False),
    ]


# Mapping from AHK sub-section names (any casing; normalised internally) to the
# Lua module identifier that handles them at runtime.  Each entry here is a
# section that appears in the AHK ``__Order`` list but produces no TOML entries
# because its logic lives entirely outside the keymap TOML pipeline.
# Hammerspoon reads this via ``module_sections`` in ``_index.json`` and renders
# the corresponding toggle item inline within the parent group's sub-menu.
_MODULE_SECTIONS: dict[str, str] = {
    "TextExpansionPersonalInformation": "personal_info",
}


def build_handcrafted_sections(
    content: str,
) -> dict[
    str,
    dict[
        str,
        tuple[list[tuple[str, str, bool, bool, bool, bool, str, bool]], str],
    ],
]:
    """Build the hand-crafted sections dict from the parsed AHK source.

    Some AHK sub-sections cannot be parsed automatically (``#HotIf`` context
    blocks, backtick-escaped literals, etc.).  This function constructs them
    from well-known helpers and from data parsed directly out of *content*.

    Args:
            content: Full text of the AHK source file.

    Returns:
            Nested dict  ``{AHK_category: {sub_name: (entries, description)}}``.
    """
    circumflex_map = parse_ahk_circumflex_map(content)
    return {
        "Rolls": {
            # Comment uses backtick-escaped double-quotes in AHK — the
            # unresolvable-pattern filter drops them during normal parsing.
            "Comment": (
                _comment_entries(),
                '\\" \u279c /* et "\\ \u279c */',
            ),
            # HashtagQuote and ChevronEqual are #HotIf blocks in AHK — they
            # use GetLastSentCharacterAt() context logic and are never emitted
            # by a CreateHotstring() call, so the parser misses them entirely.
            "HashtagQuote": (
                _hashtag_quote_entries(),
                '(# \u279c (" et [# \u279c ["',
            ),
            "ChevronEqual": (
                _chevron_equal_entries(),
                "<% \u279c <= et >% \u279c >=",
            ),
            # EqualString: AHK source concatenates two backtick-escaped
            # double-quotes + {Left}; the concat-collapsing regex yields a
            # truncated output.  Correct expansion is = "".
            "EqualString": (
                _equal_string_entries(),
                '[ ) \u279c = ""',
            ),
        },
        "DistancesReduction": {
            # Key must match the AHK __Order entry exactly so the normalised
            # name ("deadkeyecircumflex") lands in the right TOML position.
            # Description is None so parse_ahk_descriptions() value is kept.
            "DeadKeyECircumflex": (
                _deadkey_ecircumflex_entries(circumflex_map),
                None,
            ),
        },
    }


def main(
    ahk_file: Path,
) -> None:
    """Extract all AHK hotstring blocks and write one TOML file per category."""
    reset_error_count()

    logger.info("=" * 80)
    logger.info("AutoHotkey → TOML hotstring generator")
    logger.info("=" * 80)

    content = ahk_file.read_text(encoding="utf-8")
    all_blocks = find_all_blocks(content)
    logger.info(
        "Found %d categories: %s",
        len(all_blocks),
        sorted(all_blocks.keys()),
    )

    # Parse description map once, shared across all categories.
    all_descriptions = parse_ahk_descriptions(content)
    logger.info(
        "Extracted descriptions for %d categories",
        len(all_descriptions),
    )

    all_orders = parse_ahk_orders(content)
    logger.info(
        "Extracted __Order for %d categories: %s",
        len(all_orders),
        sorted(all_orders.keys()),
    )

    # --- Determine global category order from AHK top-level __Order --------
    top_level_order = parse_ahk_top_level_order(content)
    logger.info(
        "Top-level __Order: %s",
        top_level_order,
    )

    handcrafted = build_handcrafted_sections(content)

    # Sub-sections that must preserve identity hotstrings (trigger == output)
    # because they act as guards preventing shorter triggers from firing inside
    # longer words (e.g. ``honnê`` blocks ``nnê → nnu`` inside ``honnête``).
    _IDENTITY_SECTIONS: frozenset[str] = frozenset({"Repeat"})

    total_entries = 0
    for category, subs in all_blocks.items():
        sub_entries: dict[
            str, list[tuple[str, str, bool, bool, bool, bool, str, bool]]
        ] = {
            sub_name: parse_body(
                body,
                skip_identity=sub_name not in _IDENTITY_SECTIONS,
            )
            for sub_name, body in subs.items()
        }
        # Inject hand-crafted sections that belong to this category.
        for sub_name, (entries, section_desc) in handcrafted.get(
            category, {}
        ).items():
            sub_entries[sub_name] = entries
            # Only override the AHK-parsed description when the hand-crafted
            # section explicitly provides one (i.e. description is not None).
            if section_desc is not None:
                all_descriptions.setdefault(category, {})[sub_name] = (
                    section_desc
                )
        total_entries += write_category_toml(
            category,
            sub_entries,
            section_descriptions=all_descriptions.get(category),
            section_order=all_orders.get(category),
        )

    # --- Write _index.json so Hammerspoon can restore the AHK menu order ----
    # Keep only names whose TOML file was actually written (non-empty categories).
    # Exclude private categories: their TOML files are gitignored and must not
    # appear in the committed _index.json.
    written_names = {p.stem for p in OUTPUT_DIR.glob("*.toml")}
    ordered: list[str] = [
        name
        for name in top_level_order
        if name in written_names and name not in _PRIVATE_CATEGORIES
    ]
    # Append any written TOML not listed in top_level_order, alphabetically.
    for name in sorted(written_names - set(ordered) - _PRIVATE_CATEGORIES):
        ordered.append(name)

    # Build module_sections: tell Lua which placeholder sub-sections (those
    # absent from TOML because handled by a separate Lua module) map to which
    # Lua module identifier.  Keyed by normalised category / section name.
    # Each value is a dict with at least ``mod_id``; ``description`` is added
    # when an AHK description is available for the sub-section.
    _module_secs_norm: dict[str, str] = {
        normalize_name(k): v for k, v in _MODULE_SECTIONS.items()
    }
    module_sections: dict[str, dict[str, dict[str, str]]] = {}
    for category, subs_order in all_orders.items():
        normalized_cat = normalize_name(category)
        for item in subs_order:
            if item == "-":
                continue
            module = _module_secs_norm.get(item)
            if module:
                entry: dict[str, str] = {"mod_id": module}
                # Look up the AHK-parsed description for this sub-section.
                original_name = next(
                    (k for k in _MODULE_SECTIONS if normalize_name(k) == item),
                    None,
                )
                if original_name:
                    desc = (
                        all_descriptions.get(category, {})
                        or all_descriptions.get(
                            next(
                                (
                                    c
                                    for c in all_descriptions
                                    if normalize_name(c) == normalized_cat
                                ),
                                "",
                            ),
                            {},
                        )
                    ).get(original_name)
                    if desc:
                        entry["description"] = desc
                module_sections.setdefault(normalized_cat, {})[item] = entry

    index_path = OUTPUT_DIR / "_index.json"
    index_path.write_text(
        json.dumps(
            {"categories_order": ordered, "module_sections": module_sections},
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    logger.info(
        "Written %s → categories_order: %s, module_sections: %s",
        index_path.name,
        ordered,
        module_sections,
    )

    # Remove obsolete standalone TOML files now embedded in their parent.
    for orphan_name in ("e_deadkey.toml",):
        orphan_path = OUTPUT_DIR / orphan_name
        if orphan_path.exists():
            orphan_path.unlink()
            logger.info(
                "Removed %s (entries now embedded in parent TOML)", orphan_name
            )

    errors = get_error_count()
    logger.info("=" * 80)
    if errors == 0:
        logger.success(
            "Done – %d categories processed, %d entries, no errors.",
            len(all_blocks),
            total_entries,
        )
    else:
        logger.error(
            "Done – %d categories processed, %d entries, %d error(s).",
            len(all_blocks),
            total_entries,
            errors,
        )


if __name__ == "__main__":
    # Allow a local machine override via a gitignored file.
    # Create ".local_ahk_path" next to this script and put the absolute path
    # to your private AHK file on the first line, e.g.:
    #   /Users/you/private-config/ErgoptiPlus.ahk
    local_override = Path(__file__).parent / ".local_ahk_path"
    if local_override.exists():
        ahk_path = Path(local_override.read_text(encoding="utf-8").strip())
    else:
        ahk_path = (
            Path(__file__).parent.parent / "autohotkey" / "ErgoptiPlus.ahk"
        )
    main(ahk_path)
