#!/usr/bin/env python3
"""
Generate hotstring TOML files from an AutoHotkey source file.

For every Features["CategoryName"]["SubName"] block found in the AHK file,
one TOML file named <category_name>.toml is written in the same directory as
this script.  Each sub-block becomes a [[sub_name]] section inside that file.

A [_meta] / [_meta.sections] TOML table is prepended to each file so that
Hammerspoon can display human-readable descriptions in its menu.

Hand-crafted sub-blocks (apostrophe, e_deadkey) have no AHK source block;
they are injected as sections into their parent category TOML files
(Autocorrection and SFBsReduction respectively).
"""

import re
import sys
import unicodedata
from pathlib import Path
from typing import Optional

sys.path.append(str(Path(__file__).resolve().parent.parent))

from utilities.logger import get_error_count, logger, reset_error_count

# Header prepended to every generated TOML file.
TOML_HEADER: list[str] = [
    "# DO NOT EDIT THIS FILE DIRECTLY.",
    "# This file is automatically generated. Any manual changes will be overwritten.",
    '# All entries use: trigger = { output = "replacement", is_word = true/false, auto_expand = true/false }',
    "",
]

# Human-readable file-level labels used in the Hammerspoon menu.
FILE_DESCRIPTIONS: dict[str, str] = {
    "DistancesReduction": "Réduction des distances de frappe",
    "SFBsReduction": "Réduction des SFBs (Same Finger Bigrams)",
    "Rolls": "Roulements — substitutions par combinaisons de touches",
    "Autocorrection": "Corrections automatiques",
    "MagicKey": "Touche magique ★",
}

# All generated TOML files land in this directory (next to this script).
OUTPUT_DIR = Path(__file__).parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def normalize_name(name: str) -> str:
    """Convert an AHK block name to a TOML-safe identifier.

    Lowercases, strips accents, and replaces non-alphanumeric characters with
    underscores.

    Args:
            name: Original AHK block name (e.g. "SFBsReduction", "IÉ").

    Returns:
            Normalised identifier (e.g. "sfbsreduction", "i_e").
    """
    name = name.lower()
    name = unicodedata.normalize("NFD", name)
    name = "".join(c for c in name if unicodedata.category(c) != "Mn")
    name = re.sub(r"[^a-z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name


def escape_toml_string(text: str) -> str:
    """Escape backslashes and double-quotes for a TOML double-quoted string.

    Args:
            text: Raw string value.

    Returns:
            Escaped string safe to embed between TOML double-quotes.
    """
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    return text


def process_autohotkey_escapes(text: str) -> str:
    """Replace AHK escape sequences with their actual characters.

    Args:
            text: Text containing AHK escape sequences.

    Returns:
            Text with escape sequences expanded.
    """
    replacements: dict[str, str] = {
        '`"': '"',
        "`'": "'",
        "``": "`",
        "`n": "\n",
        "`t": "\t",
        "`r": "\r",
        "`{": "{",
        "`}": "}",
        # Cursor-positioning sequences that must simply be removed
        '""{Left}': '"',
        '"{Left}': "",
        "{Left}": "",
        "{Right}": "",
        "{Up}": "",
        "{Down}": "",
        "{Home}": "",
        "{End}": "",
    }
    for seq, replacement in replacements.items():
        text = text.replace(seq, replacement)
    return text


# ---------------------------------------------------------------------------
# AHK variable substitution & string-concatenation collapsing
# ---------------------------------------------------------------------------

# Map AHK global variable names → their compile-time value as a quoted AHK
# string literal so that they can be inlined before regexes are applied.
_AHK_VARIABLE_SUBSTITUTIONS: list[tuple[str, str]] = [
    # SpaceAroundSymbols is " " when the feature is enabled (the default).
    (r"\bSpaceAroundSymbols\b", '" "'),
    # ScriptInformation["MagicKey"] resolves to the magic-key character ★.
    (r'ScriptInformation\["MagicKey"\]', '"★"'),
]

# Patterns that indicate loop-level or callback-level hotstring registrations
# that cannot be statically resolved; they are skipped silently (no warning).
_UNRESOLVABLE_PATTERNS = re.compile(
    r"\bLetter\b"  # for Letter in StrSplit("abc...")
    r"|\bVowel\b"  # for Vowel in DeadkeyMappingCircumflex
    r"|\bcombo\b"  # combo parameter inside CreateHotstringCombo body
    r"|(?<![A-Za-z])value\b"  # value parameter (function body)
    r"|\bcreatehotstring\b.*\bfrom\b"  # CreateHotstring("", from, to)
    r"|=>.+"  # arrow-function callback (AHK2 syntax)
    r"|\bhotstringhandler\b"  # internal handler call
    r"|\bPersonalInformation\b"  # runtime private-data dictionary
    r"|\bPersonalInformationHotstrings\b"  # runtime private-data collection
    r"|\bGeneratePersonalInformation"  # custom generator function
    r"|\bCreateHotstringCombo"  # custom combo-hotstring functions
    r"|\bCreateDeadkeyHotstring\b"  # custom dead-key hotstring function
    r"|[`]\"",  # AHK2 backtick-escaped double-quote inside a string literal
    re.IGNORECASE,
)

# Collapse adjacent AHK string concatenations: "a" . "b" → "ab".
# AHK2 uses backtick (not backslash) for in-string escaping, so the group
# pattern is simply [^"] (no backslash-escape handling needed here).
_CONCAT_RE = re.compile(r'"([^"]*)"\s*\.\s*"([^"]*)"')


def _collapse_ahk_string_concat(line: str) -> str:
    """Collapse ``"a" . "b"`` AHK concatenations into ``"ab"`` repeatedly.

    Args:
            line: AHK source line, possibly containing string concatenations.

    Returns:
            Line with all adjacent string literals merged.
    """
    prev: Optional[str] = None
    while prev != line:
        prev = line
        line = _CONCAT_RE.sub(
            lambda m: '"' + m.group(1) + m.group(2) + '"', line
        )
    return line


def preprocess_ahk_line(line: str) -> str:
    """Substitute known AHK variables and collapse string concatenations.

    Replaces compile-time global variable references (e.g. ``SpaceAroundSymbols``,
    ``ScriptInformation["MagicKey"]``) with their resolved string-literal values,
    then collapses adjacent ``"a" . "b"`` segments into ``"ab"``.

    Args:
            line: A single logical AHK statement (may be a joined multi-line call).

    Returns:
            The preprocessed line, ready for regex-based hotstring extraction.
    """
    for pattern, replacement in _AHK_VARIABLE_SUBSTITUTIONS:
        line = re.sub(pattern, replacement, line)
    return _collapse_ahk_string_concat(line)


# ---------------------------------------------------------------------------
# Description extraction
# ---------------------------------------------------------------------------


def _parse_ahk_desc_expr(expr: str) -> str:
    """Resolve an AHK string-concatenation expression into a plain string.

    Replaces ``ScriptInformation["..."]`` references with ``★`` and joins all
    double-quoted fragments.

    Args:
            expr: Raw AHK expression after ``Description:``, e.g.
                    ``"text " . ScriptInformation["MagicKey"] . " suite"``.

    Returns:
            Resolved plain string, e.g. ``"text ★ suite"``.
    """
    # Split on the AHK concatenation operator ' . ' (always surrounded by spaces).
    # Using \s+ (not \s*) avoids splitting on literal dots inside quoted strings
    # (e.g. "ê. = u." or "$eq.not$").
    tokens = re.split(r"\s+\.\s+", expr.strip().rstrip(","))
    parts: list[str] = []
    for tok in tokens:
        tok = tok.strip()
        if tok.startswith('"') and tok.endswith('"'):
            # Plain quoted literal — unescape AHK backtick sequences
            parts.append(process_autohotkey_escapes(tok[1:-1]))
        elif "ScriptInformation" in tok:
            parts.append("★")
        # else: skip things like numbers, booleans, etc.
    return "".join(parts)


def parse_ahk_descriptions(content: str) -> dict[str, dict[str, str]]:
    """Extract per-section descriptions from the ``Features`` map in *content*.

    Scans the AHK source for ``"SubName", { ... Description: ... }`` blocks
    and records the resolved description text for each ``(category, sub)`` pair.

    Args:
            content: Full AHK file content.

    Returns:
            ``{AHK_category_name: {AHK_sub_name: description_string}}``
    """
    # Locate the Features map block
    features_start = content.find("global Features := Map(")
    if features_start < 0:
        return {}

    # The Features map is followed by the first top-level if/hotstring block.
    # We only scan the initial declarations section.
    first_if = re.search(
        r"^\s*if\s+Features\[", content[features_start:], re.MULTILINE
    )
    features_text = (
        content[features_start : features_start + first_if.start()]
        if first_if
        else content[features_start : features_start + 20_000]
    )

    result: dict[str, dict[str, str]] = {}

    # Regexes to track context
    cat_re = re.compile(r'"([A-Za-z]+)",\s*Map\(')
    sub_re = re.compile(r'"([^"]+)",\s*\{')
    desc_re = re.compile(r"Description:\s*(.*)")

    lines = features_text.splitlines()
    current_cat: Optional[str] = None
    current_sub: Optional[str] = None
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        cm = cat_re.search(line)
        if cm and cm.group(1) != "__Order":
            current_cat = cm.group(1)
            current_sub = None

        sm = sub_re.search(line)
        if sm:
            cand = sm.group(1)
            if cand not in ("__Order",) and not cand.startswith("-"):
                current_sub = cand

        dm = desc_re.search(line)
        if dm and current_cat and current_sub:
            desc_expr = dm.group(1).strip()
            # Collect continuation lines when the expression is incomplete:
            # either it ends with the concatenation operator '.' or it ends
            # with an open bracket (e.g. ScriptInformation[ split across lines).
            while (
                desc_expr.rstrip(",").rstrip().endswith(".")
                or desc_expr.rstrip().endswith("[")
            ) and i + 1 < len(lines):
                i += 1
                desc_expr += " " + lines[i].strip()
            desc = _parse_ahk_desc_expr(desc_expr)
            if desc:
                result.setdefault(current_cat, {})[current_sub] = desc

        i += 1

    return result


# ---------------------------------------------------------------------------
# AHK file discovery
# ---------------------------------------------------------------------------


def get_latest_ahk_file() -> Path:
    """Return the path to the most recent ErgoptiPlus AHK file.

    Returns:
            Path to the latest versioned AHK file.

    Raises:
            FileNotFoundError: When no matching file exists in the autohotkey dir.
    """
    ahk_dir = Path(__file__).parent.parent / "autohotkey"
    candidates = list(ahk_dir.glob("ErgoptiPlus_v*.*.*.ahk"))
    if not candidates:
        raise FileNotFoundError(f"No AutoHotkey files found in {ahk_dir}")

    def _version_key(p: Path) -> tuple[int, int, int]:
        m = re.search(r"v(\d+)\.(\d+)\.(\d+)", p.name)
        return (
            (int(m.group(1)), int(m.group(2)), int(m.group(3)))
            if m
            else (0, 0, 0)
        )

    candidates.sort(key=_version_key, reverse=True)
    latest = candidates[0]
    logger.info("Detected AHK file: %s", latest.name)
    return latest


# ---------------------------------------------------------------------------
# Block discovery
# ---------------------------------------------------------------------------


def _extract_brace_body(content: str, match_end: int) -> str:
    """Return the text between the braces of a block whose opening brace
    was consumed at *match_end*.

    Args:
            content: Full file content.
            match_end: Index just past the opening ``{``.

    Returns:
            Body text (without surrounding braces), or empty string on failure.
    """
    idx = match_end
    depth = 1
    while idx < len(content) and depth > 0:
        if content[idx] == "{":
            depth += 1
        elif content[idx] == "}":
            depth -= 1
        idx += 1
    return content[match_end : idx - 1] if depth == 0 else ""


def find_all_blocks(content: str) -> dict[str, dict[str, str]]:
    """Discover every ``Features["Cat"]["Sub"]`` block in *content*.

    Multiple occurrences of the same ``(cat, sub)`` pair are concatenated so
    that split blocks (e.g. when a condition references two features) are
    merged transparently.

    Args:
            content: Full AHK file content.

    Returns:
            ``{category: {sub_name: body_text}}`` – names in their original casing.
    """
    # Match lines like:
    #   if Features["Cat"]["Sub"].Enabled {
    #   if Features["Cat"]["Sub"] {
    #   if Features["Cat"]["Sub"].Enabled and Features["X"]["Y"].Enabled {
    pattern = re.compile(
        r"(?:^|(?<=\n))\s*(?:} else )?if\s+"
        r'Features\["(?P<cat>[^"]+)"\]\["(?P<sub>[^"]+)"\]'
        r"(?:\.Enabled)?\b[^{]*\{",
    )

    result: dict[str, dict[str, str]] = {}
    for m in pattern.finditer(content):
        cat = m.group("cat")
        sub = m.group("sub")
        body = _extract_brace_body(content, m.end())
        if not body.strip():
            continue
        result.setdefault(cat, {}).setdefault(sub, "")
        result[cat][sub] += ("\n" if result[cat][sub] else "") + body

    return result


# ---------------------------------------------------------------------------
# Hotstring parsing
# ---------------------------------------------------------------------------


def _extract_hotstring_from_line(
    line: str,
) -> tuple[Optional[str], Optional[str], bool, bool, bool]:
    """Parse one (possibly multi-line-joined) AHK call and return its fields.

    Applies :func:`preprocess_ahk_line` first so that known AHK global
    variables (``SpaceAroundSymbols``, ``ScriptInformation["MagicKey"]``) are
    resolved and adjacent string literals are merged before the regexes run.

    Args:
            line: A single logical AHK statement, with whitespace normalised.

    Returns:
            ``(trigger, output, is_word, auto_expand, case_sensitive)`` where
            *trigger* and *output* are ``None`` when no hotstring was found.
    """
    # Resolve variables and collapse string concatenations upfront.
    line = preprocess_ahk_line(line)

    case_sensitive = "CreateCaseSensitiveHotstrings" in line

    # Try from most-specific to most-generic.
    patterns: list[str] = [
        # Complex escape: backtick-quoted output
        (
            r"(?:CreateCaseSensitiveHotstrings|CreateHotstring)\s*\(\s*"
            r'"(?P<opts>[^"]*)",\s*'
            r'"(?P<trig>(?:[^"\\]|\\.)*)",\s*'
            r'"(?P<out>`"[^"]*)"'
        ),
        # Standard CreateHotstring / CreateCaseSensitiveHotstrings
        (
            r"(?:CreateCaseSensitiveHotstrings|CreateHotstring)\s*\(\s*"
            r'"(?P<opts>[^"]*)",\s*'
            r'"(?P<trig>(?:[^"\\]|\\.)*)",\s*'
            r'"(?P<out>(?:[^"\\]|\\.)*)"'
        ),
        # Hotstring() legacy format
        (
            r"Hotstrings?\s*\("
            r'(?:\s*"(?P<opts>[^"]*)",)?'
            r'\s*"(?P<trig>[^"]+?)"'
            r'\s*,\s*"(?P<out>[^"]+?)"'
            r"\s*\)"
        ),
    ]

    for pat in patterns:
        m = re.search(pat, line, re.DOTALL)
        if not m:
            continue
        opts = m.group("opts") or ""
        trigger = process_autohotkey_escapes(m.group("trig"))
        output = process_autohotkey_escapes(m.group("out"))
        auto_expand = "*" in opts
        is_word = "?" not in opts
        return trigger, output, is_word, auto_expand, case_sensitive

    return None, None, False, False, False


def _strip_ahk_inline_comment(line: str) -> str:
    """Strip an AHK inline comment (``; ...``) from *line*.

    Respects double-quoted string literals so that semicolons inside quotes
    are not treated as comment starters.  AHK backtick escapes (`` `x ``) are
    handled inside strings.

    Args:
            line: A single AHK statement line.

    Returns:
            The line with the inline comment removed, stripped of trailing
            whitespace.
    """
    in_string = False
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "`" and in_string:
            # AHK backtick escape: skip the next character unconditionally
            i += 2
            continue
        if ch == '"':
            in_string = not in_string
        elif ch == ";" and not in_string:
            return line[:i].rstrip()
        i += 1
    return line


def parse_body(
    body: str,
) -> list[tuple[str, str, bool, bool, bool]]:
    """Extract all hotstring entries from a block body.

    Section-header comments (``; === Name ===``) are ignored – every entry
    just goes into a flat list.  Duplicate triggers within the same body are
    silently dropped (first occurrence wins).

    Args:
            body: Raw body text of a ``Features[...][...]`` block.

    Returns:
            Deduplicated list of
            ``(trigger, output, is_word, auto_expand, case_sensitive)`` tuples.
    """
    entries: list[tuple[str, str, bool, bool, bool]] = []
    seen: set[str] = set()
    lines = body.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i].strip()
        if not line or line.startswith(";"):
            i += 1
            continue

        # Join continuation lines for multi-line calls — also covers bare
        # ``Hotstring(`` (low-level callback form with no ``Create`` prefix).
        _is_open_call = (
            "CreateCaseSensitiveHotstrings(" in line
            or "CreateHotstring(" in line
            or bool(re.search(r"(?<![A-Za-z])Hotstring\s*\(", line))
        )
        if _is_open_call and not _strip_ahk_inline_comment(line).endswith(")"):
            j = i + 1
            while j < len(lines) and not _strip_ahk_inline_comment(
                line
            ).endswith(")"):
                next_fragment = lines[j].strip()
                # Ignore standalone comment lines; they corrupt the joined expression.
                if not next_fragment.startswith(";"):
                    line += " " + next_fragment
                j += 1
            i = j
        else:
            i += 1

        trigger, output, is_word, auto_expand, case_sensitive = (
            _extract_hotstring_from_line(line)
        )

        if trigger and output:
            # Skip identity hotstrings (trigger == output): they are no-ops in
            # Hammerspoon and only exist in AHK to block longer hotstrings.
            if trigger == output:
                pass
            elif trigger not in seen:
                seen.add(trigger)
                entries.append(
                    (trigger, output, is_word, auto_expand, case_sensitive)
                )
        elif any(
            kw in line
            for kw in (
                "CreateHotstring",
                "CreateCaseSensitiveHotstrings",
                "Hotstring",
            )
        ):
            # Silently skip patterns that are inherently unresolvable at parse
            # time (loop variables, callback lambdas, etc.).
            if not _UNRESOLVABLE_PATTERNS.search(line):
                logger.warning(
                    "Failed to parse: %s",
                    (line[:120] + "...") if len(line) > 120 else line,
                )

    return entries


# ---------------------------------------------------------------------------
# TOML rendering
# ---------------------------------------------------------------------------


def entries_to_toml_lines(
    entries: list[tuple[str, str, bool, bool, bool]],
) -> list[str]:
    """Render a list of hotstring entries as TOML assignment lines.

    Args:
            entries: Hotstring tuples produced by :func:`parse_body`.

    Returns:
            One TOML line per entry.
    """
    lines = []
    for trigger, output, is_word, auto_expand, case_sensitive in entries:
        t = escape_toml_string(trigger)
        o = escape_toml_string(output)
        lines.append(
            f'"{t}" = {{ output = "{o}"'
            f", is_word = {str(is_word).lower()}"
            f", auto_expand = {str(auto_expand).lower()}"
            f", is_case_sensitive = {str(not case_sensitive).lower()} }}"
        )
    return lines


def write_category_toml(
    category: str,
    sub_blocks: dict[str, list[tuple[str, str, bool, bool, bool]]],
    section_descriptions: Optional[dict[str, str]] = None,
) -> int:
    """Write one TOML file for *category* and return the total entry count.

    The filename is :func:`normalize_name` applied to *category*.
    Each sub-block becomes a ``[[sub_name]]`` array-of-tables section.
    A leading ``[_meta]`` table carries the human-readable descriptions used
    by the Hammerspoon menu.

    Args:
            category: Original AHK category name (e.g. ``"MagicKey"``).
            sub_blocks: Mapping of sub-block names to their hotstring entries.
            section_descriptions: Optional ``{AHK_sub_name: description}`` mapping
                    extracted from the AHK Features map.

    Returns:
            Total number of entries written.
    """
    filename = normalize_name(category) + ".toml"
    output_file = OUTPUT_DIR / filename

    lines = TOML_HEADER.copy()

    # ── [_meta] block ────────────────────────────────────────────────────────
    file_desc = FILE_DESCRIPTIONS.get(category, "")
    lines.append("[_meta]")
    lines.append(f'description = "{escape_toml_string(file_desc)}"')
    lines.append("")

    if section_descriptions:
        lines.append("[_meta.sections]")
        for sub_name in sub_blocks:
            norm = normalize_name(sub_name)
            desc = section_descriptions.get(sub_name, "")
            if desc:
                lines.append(f'{norm} = "{escape_toml_string(desc)}"')
        lines.append("")

    # ── section data ─────────────────────────────────────────────────────────
    total = 0
    for sub_name, entries in sub_blocks.items():
        if not entries:
            continue
        lines.append(f"[[{normalize_name(sub_name)}]]")
        lines.extend(entries_to_toml_lines(entries))
        lines.append("")
        total += len(entries)

    if total == 0:
        logger.warning("Skipping %s – no entries found", filename)
        return 0

    output_file.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Written %s (%d entries)", filename, total)
    return total


# ---------------------------------------------------------------------------
# Handcrafted section data (no AHK source – injected into parent TOMLs)
# ---------------------------------------------------------------------------


def _apostrophe_entries() -> list[tuple[str, str, bool, bool, bool]]:
    """Return hotstring entries for the typographic-apostrophe section."""
    chars = ["a", "e", "i", "o", "u", "y", "é", "ê", "è", "r", "t"]
    return [(f"'{c}", f"\u2019{c}", False, True, False) for c in chars]


def _e_deadkey_entries() -> list[tuple[str, str, bool, bool, bool]]:
    """Return hotstring entries for the ê dead-key circumflex section."""
    return [
        ("êa", "â", False, True, False),
        ("êe", "œ", False, True, False),
        ("êi", "î", False, True, False),
        ("êo", "ô", False, True, False),
        ("êu", "û", False, True, False),
        ("êy", "ŷ", False, True, False),
    ]


def _hashtag_quote_entries() -> list[tuple[str, str, bool, bool, bool]]:
    """Return entries for the HashtagQuote roll: (# ➜ (" and [# ➜ [\'.

    This roll is implemented via a ``#HotIf`` block in AHK (not a standard
    ``CreateHotstring`` call) and therefore cannot be parsed automatically.
    When the last character sent is ``(`` or ``[``, pressing the AltGr-mapped
    ``#`` key outputs a double-quote instead.
    """
    return [
        ("(#", '("', False, True, False),
        ("[#", '["', False, True, False),
    ]


def _chevron_equal_entries() -> list[tuple[str, str, bool, bool, bool]]:
    """Return entries for the ChevronEqual roll: <% ➜ <= and >% ➜ >=.

    This roll is also implemented via a ``#HotIf`` block in AHK and is not
    captured by the standard block parser.  When the last character sent is
    ``<`` or ``>``, pressing the AltGr-mapped ``%`` key outputs ``=``.
    """
    return [
        ("<%", "<=", False, True, False),
        (">%", ">=", False, True, False),
    ]


def _equal_string_entries() -> list[tuple[str, str, bool, bool, bool]]:
    """Return corrected entries for the EqualString roll: [) ➜ = "".

    The AHK source uses consecutive backtick-escaped double-quotes
    (`` `"`" ``) followed by a cursor-movement command.  This pattern
    confuses the string-concatenation collapsing regex, so the automatic
    parser yields a truncated output (a bare backtick).  These hand-crafted
    entries override the broken parsed ones with the correct expansion.
    """
    return [
        (" [)", ' = ""', False, True, False),
        ("[)", ' = ""', False, True, False),
    ]


# Sub-blocks to inject into specific category TOMLs.
# Format: { AHK_category: { sub_name: (entries, section_description) } }
_HANDCRAFTED_SECTIONS: dict[
    str, dict[str, tuple[list[tuple[str, str, bool, bool, bool]], str]]
] = {
    "Autocorrection": {
        "apostrophe": (
            _apostrophe_entries(),
            "Remplace l'apostrophe droite par l'apostrophe typographique \u2019"
            " devant les voyelles et consonnes fréquentes",
        ),
    },
    "Rolls": {
        # HashtagQuote and ChevronEqual are #HotIf blocks in AHK — they use
        # GetLastSentCharacterAt() context logic and are never emitted by a
        # CreateHotstring() call, so the parser misses them entirely.
        "HashtagQuote": (
            _hashtag_quote_entries(),
            '(# \u279c (" et [# \u279c ["',
        ),
        "ChevronEqual": (
            _chevron_equal_entries(),
            "<% \u279c <= et >% \u279c >=",
        ),
        # EqualString is parsed automatically but the output is wrong: the
        # AHK source concatenates two backtick-escaped double-quotes followed
        # by {Left}, which the concat-collapsing regex cannot handle. The
        # correct expansion is = "" (cursor left is stripped).
        "EqualString": (
            _equal_string_entries(),
            '[ ) \u279c = ""',
        ),
    },
    "DistancesReduction": {
        "e_deadkey": (
            _e_deadkey_entries(),
            "Ê agit comme touche morte : êa→â, êe→œ, êi→î, êo→ô, êu→û, êy→ŷ",
        ),
    },
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """Extract all AHK hotstring blocks and write one TOML file per category."""
    reset_error_count()

    logger.info("=" * 80)
    logger.info("AutoHotkey → TOML hotstring generator")
    logger.info("=" * 80)

    try:
        ahk_file = get_latest_ahk_file()
    except FileNotFoundError as exc:
        logger.error("%s", exc)
        return

    content = ahk_file.read_text(encoding="utf-8")
    all_blocks = find_all_blocks(content)
    logger.info(
        "Found %d categories: %s",
        len(all_blocks),
        sorted(all_blocks.keys()),
    )

    # Parse description map once, shared across all categories.
    all_descriptions = parse_ahk_descriptions(content)
    logger.info(
        "Extracted descriptions for %d categories",
        len(all_descriptions),
    )

    total_entries = 0
    for category, subs in all_blocks.items():
        sub_entries: dict[str, list[tuple[str, str, bool, bool, bool]]] = {
            sub_name: parse_body(body) for sub_name, body in subs.items()
        }
        # Inject hand-crafted sections that belong to this category.
        for sub_name, (entries, section_desc) in _HANDCRAFTED_SECTIONS.get(
            category, {}
        ).items():
            sub_entries[sub_name] = entries
            all_descriptions.setdefault(category, {})[sub_name] = section_desc
        total_entries += write_category_toml(
            category,
            sub_entries,
            section_descriptions=all_descriptions.get(category),
        )

    # Remove obsolete standalone TOML files now embedded in their parent.
    for orphan_name in ("apostrophe.toml", "e_deadkey.toml"):
        orphan_path = OUTPUT_DIR / orphan_name
        if orphan_path.exists():
            orphan_path.unlink()
            logger.info(
                "Removed %s (entries now embedded in parent TOML)", orphan_name
            )

    errors = get_error_count()
    logger.info("=" * 80)
    if errors == 0:
        logger.success(
            "Done – %d categories processed, %d entries, no errors.",
            len(all_blocks),
            total_entries,
        )
    else:
        logger.error(
            "Done – %d categories processed, %d entries, %d error(s).",
            len(all_blocks),
            total_entries,
            errors,
        )


if __name__ == "__main__":
    main()
