# ====================
# ====================
# ======= Menu =======
# ====================
# ====================

[menu]
categories_order = ["distancesreduction", "sfbsreduction", "rolls", "autocorrection", "magickey"]



# ======================================================================
# ===== Modules.Dynamichotstrings.Textexpansionpersonalinformation =====
# ======================================================================

[modules.dynamichotstrings.textexpansionpersonalinformation]
mod_id = "personal_info"