--- infra/manifest_reader.lua

--- ==============================================================================
--- MODULE: Features Manifest Reader (Hammerspoon)
--- DESCRIPTION:
--- Thin runtime API over the codegen'd `_generated/features_manifest.lua`, which
--- is produced by `npm run build:manifest` from the single source of truth at
--- `_shared/modules/features/manifest.toml`. This is the macOS counterpart of the AHK
--- `infra/manifest_reader.ahk` — the AHK driver already builds its entire
--- `Features` map from the manifest, so reading the same manifest here makes the
--- cross-driver feature defaults a genuine single source instead of hand-copied
--- `DEFAULT_STATE` tables.
---
--- FEATURES & RATIONALE:
--- 1. cwd-independent load: the manifest is located relative to THIS file via
---    `debug.getinfo` + `loadfile`, so it resolves identically under Hammerspoon
---    and the headless test runner regardless of the working directory or
---    `package.path` (mirrors `ui/tooltip/config.lua`).
--- 2. Fail fast: a missing/malformed manifest, or a lookup for an unknown path,
---    raises an error rather than silently returning nil — the manifest is
---    committed and regenerated by the build, so a miss is a real misconfiguration.
--- 3. O(1) lookups via a path index built once at load.
---
--- SCOPE: this reader currently exposes only what the macOS modules consume
--- today (per-path default lookup). The AHK-style whole-`Features`-map builder is
--- intentionally not ported until a module needs it (no speculative code).
--- ==============================================================================

local M = {}
local Logger = require("infra.logger")
local LOG = "manifest_reader"




-- =================================
-- =================================
-- ======= 1/ Manifest load ========
-- =================================
-- =================================

--- Loads the generated manifest module by absolute path, relative to this file.
--- macos/infra/manifest_reader.lua -> macos -> _generated/features_manifest.lua.
--- @return table The manifest table (version / section_order / sections / features).
local function load_manifest()
	local src   = debug.getinfo(1, "S").source:gsub("^@", "")
	local dir   = src:match("^(.*)[/\\][^/\\]+$") or src   -- .../macos/lib
	local macos = dir:match("^(.*)[/\\][^/\\]+$") or dir   -- .../macos
	local path  = macos .. "/_generated/features_manifest.lua"

	local chunk, load_err = loadfile(path)
	if not chunk then
		error("[manifest_reader] cannot load generated manifest (" .. tostring(load_err)
			.. ") — run `npm run build:manifest`.")
	end
	local ok, mod = pcall(chunk)
	if not ok or type(mod) ~= "table" or type(mod.features) ~= "table" then
		error("[manifest_reader] generated manifest did not return a valid table: " .. tostring(mod))
	end
	return mod
end

local _manifest = load_manifest()
local _defaults = require("config_defaults").new(_manifest)

-- Path index built once at load for O(1) lookups.
local _path_index = {}
for _, entry in ipairs(_manifest.features) do
	_path_index[entry.path] = entry
end

-- Metadata and unrelated preferences must not perform native hardware probes.
-- Every value projection that includes the backend still resolves the same owner.
local BACKEND_PATH = "llm.models.selected"
local platform_resolved = false
local function resolve_platform(path)
	if platform_resolved then return end
	if path ~= nil and path ~= BACKEND_PATH and BACKEND_PATH:sub(1, #path + 1) ~= path .. "." then return end
	local backend = require("modules.llm.backend_detector").auto_default()
	local entry = assert(_path_index[BACKEND_PATH], "platform backend declaration missing")
	entry.default, entry.recommended = backend, backend
	platform_resolved = true
end

local function resolve_scope(scope, direct_only)
	local declaration = assert(_manifest.scopes[scope], "unknown configuration scope")
	for _, prefix in ipairs(declaration.prefixes or {}) do resolve_platform(prefix) end
	if not direct_only then
		for _, child in ipairs(declaration.includes or {}) do resolve_scope(child) end
	end
end

Logger.done(LOG, "Features manifest loaded (v%s, %d feature(s)).",
	tostring(_manifest.version), #_manifest.features)




-- =====================================
-- =====================================
-- ======= 2/ Public accessors =========
-- =====================================
-- =====================================

--- Manifest format version string (e.g. "2.0.0").
--- @return string
function M.version()
	return _manifest.version
end

--- Flat array of feature entries (path / id / section / default / type / …).
--- @return table
function M.features()
	resolve_platform()
	return _manifest.features
end

--- Returns the manifest entry for a canonical feature path, or nil when absent.
--- @param path string The canonical dotted path (e.g. the menu/config key).
--- @return table|nil
function M.find_entry_by_path(path)
	resolve_platform(path)
	return _path_index[path]
end

--- Returns declaration metadata without resolving a native platform default.
--- Type admission does not need the backend or any hardware-derived value.
--- @param path string Canonical feature path.
--- @return table|nil entry Published declaration, or nil when unknown.
function M.find_declared_entry_by_path(path)
	return _path_index[path]
end

--- Returns the default value declared for a feature path. FAIL-FAST when the
--- path is unknown — use this to source a module's `DEFAULT_STATE` from the
--- single manifest source so a renamed/removed feature surfaces loudly instead
--- of silently defaulting to nil.
--- @param path string
--- @return any The declared default (primitive or table).
function M.default_for(path)
	resolve_platform(path)
	return _defaults.default_for(path)
end

--- Returns a detached recommended value; never used as an absence fallback.
--- @param path string Canonical feature path.
--- @return any value
function M.recommended_for(path)
	resolve_platform(path)
	return _defaults.recommended_for(path)
end

--- @return boolean declared Whether a path has a manifest-owned neutral value.
function M.has_default(path) return _defaults.has_default(path) end

--- Returns a detached nested document containing every neutral manifest value.
--- @return table defaults
function M.document_defaults()
	resolve_platform()
	return _defaults.document_defaults()
end

--- Returns the manifest-owned configuration scopes.
--- @return table scopes
function M.scopes() return _defaults.scopes() end

--- Produces an explicit set or delete operation relative to neutral absence.
--- @param path string Canonical feature path.
--- @param value any Desired value.
--- @return table operation
function M.sparse_operation(path, value)
	resolve_platform(path)
	return _defaults.operation(path, value)
end

--- Produces selected recommended writes or neutral deletions.
--- @param scope string Scope identifier.
--- @param mode string `recommended` or `clear`.
--- @param owners table|nil Exact host parameter validators.
--- @return table operations
function M.scope_operations(scope, mode, owned_paths, owners)
	resolve_scope(scope)
	return _defaults.scope_operations(scope, mode, owned_paths, owners)
end

--- Collects dynamic paths from explicit runtime owners for one scope.
--- @param scope string Scope identifier.
--- @param providers table Named callbacks returning owned path arrays.
--- @param owners table|nil Exact host parameter validators.
--- @return table paths
function M.scope_inventory(scope, providers, owners) return _defaults.scope_inventory(scope, providers, owners) end

--- Separates config operations from required external preset owners.
--- @param scope string Scope identifier.
--- @param mode string Recommended restoration or clear.
--- @param owned_paths table|nil Explicit runtime-owned paths.
--- @param owners table|nil Exact host parameter validators.
--- @return table plan
function M.scope_plan(scope, mode, owned_paths, owners)
	resolve_scope(scope)
	return _defaults.scope_plan(scope, mode, owned_paths, owners)
end

function M.direct_scope_operations(scope, mode, owned_paths, owners)
	resolve_scope(scope, true)
	return _defaults.direct_scope_operations(scope, mode, owned_paths, owners)
end

function M.direct_scope_plan(scope, mode, owned_paths, owners)
	resolve_scope(scope, true)
	return _defaults.direct_scope_plan(scope, mode, owned_paths, owners)
end




-- ==========================================
-- ==========================================
-- ======= 2/ Platform Coverage =============
-- ==========================================
-- ==========================================

--- Every feature this driver does NOT have, with whatever explains each one.
---
--- `M.features` above is the list of features macOS HAS: the generator filters
--- it per platform, so a feature restricted to Windows simply does not appear
--- there. That is why the absences are shipped as their own table — without it
--- the driver cannot know a feature exists at all, and `reason_key` was a field
--- no code anywhere could read.
---
--- @return table Array of { path, section, description_key, reason_key, platforms }.
function M.unavailable()
	return _manifest.unavailable or {}
end

--- Splits the absences into the ones that say why and the ones that do not.
---
--- The unexplained half is the point: it is what the user meets as a menu with
--- a row missing and nothing anywhere saying whether that is deliberate,
--- unimplemented, or impossible. Reporting the two counts side by side is what
--- turns `test-platform-restrictions-explained.cjs`'s frozen number into
--- something a person can see rather than a figure in a test log.
---
--- @return table explained Absences carrying a reason_key.
--- @return table silent Absences carrying none.
function M.coverage_gaps()
	local explained, silent = {}, {}
	for _, entry in ipairs(M.unavailable()) do
		if type(entry.reason_key) == "string" and entry.reason_key ~= "" then
			explained[#explained + 1] = entry
		else
			silent[#silent + 1] = entry
		end
	end
	return explained, silent
end

return M
