-- What this script does:
-- 1) Three-finger tap to toggle selection mode (click-and-drag)
-- 2) Three-finger gestures for tab navigation
-- 3) Change volume with left Option + scroll

local gestures = require("modules.gestures")
local scroll = require("modules.scroll")
local keymap = require("modules.keymap")
local shortcuts = require("modules.shortcuts")
local personal_info = require("modules.personal_info")
local dynamic_hotstrings = require("modules.dynamic_hotstrings")
local repeat_keys = require("modules.repeat_keys")
local script_control = require("modules.script_control")

-- Initial startup of modules
gestures.start()
scroll.start()
-- Also start the shortcuts module (`shortcuts`)
shortcuts.start()
-- (keymap already starts itself via your `keymap.lua`)
-- repeat_keys is registered after TOML hotstrings to ensure lowest priority
-- (it acts as a fallback when no other hotstring matches)




---------------------------------------------------------------------------
-- TOML hotstrings (loaded directly from ../hotstrings/*.toml)
---------------------------------------------------------------------------
-- Absolute path to this Hammerspoon config directory
-- Derive absolute path to this Hammerspoon config directory from this file's
-- location so the config remains portable across machines.
local script_path = debug.getinfo(1, "S").source
if script_path:sub(1, 1) == "@" then
    script_path = script_path:sub(2)
end
local base_dir = script_path:match("^(.*[/\\])") or "./"
if not base_dir:match("[/\\]$") then
    base_dir = base_dir .. "/"
end
local hotstrings_dir = base_dir .. "../hotstrings/"
local config_file    = base_dir .. "config.json"

-- ── Prime hs.settings from config.json BEFORE loading any TOML ──────────────
-- config.json is the single source of truth.  Section states stored there are
-- written into hs.settings so that keymap.load_toml loads the right entries.
-- If config.json is absent, hs.settings keeps its default (nil = all enabled).
do
    local fh = io.open(config_file, "r")
    if fh then
        local raw = fh:read("*a"); fh:close()
        local ok, cfg = pcall(function() return hs.json.decode(raw) end)
        if ok and type(cfg) == "table" and type(cfg.section_states) == "table" then
            for grp, secs in pairs(cfg.section_states) do
                if type(secs) == "table" then
                    for sec_name, enabled in pairs(secs) do
                        local key = "hotstrings_section_" .. grp .. "_" .. sec_name
                        -- nil = enabled (default), false = disabled.
                        -- NOTE: `enabled and nil or false` is a Lua anti-pattern:
                        -- `true and nil` = nil, then `nil or false` = false, so it
                        -- always evaluates to false regardless of `enabled`.  Use
                        -- an explicit if/else instead.
                        if enabled ~= false then
                            hs.settings.set(key, nil)
                        else
                            hs.settings.set(key, false)
                        end
                    end
                end
            end
        end
    end
end

-- Try to read the AHK-defined category order from _index.json (generated by
-- 0_generate_hotstrings.py).  Falls back to alphabetical sort when absent.
local ordered_names  = nil
local module_sections = nil
do
    local idx_fh = io.open(hotstrings_dir .. "_index.json", "r")
    if idx_fh then
        local raw = idx_fh:read("*a"); idx_fh:close()
        local ok, data = pcall(function() return hs.json.decode(raw) end)
        if ok and data then
            if type(data.categories_order) == "table" then
                ordered_names = data.categories_order
            end
            if type(data.module_sections) == "table" then
                module_sections = data.module_sections
            end
        end
    end
end

-- Build the ordered list of .toml filenames: _index.json order first, then
-- any remaining files (not listed) appended alphabetically.
local toml_set = {}
for fname in hs.fs.dir(hotstrings_dir) do
    if fname:match("%.toml$") then
        local name = fname:match("^(.-)%.toml$")
        toml_set[name] = fname
    end
end

-- Private/personal TOML files (absent from _index.json) are loaded first so
-- their hotstrings have the highest priority.  When the same trigger exists in
-- both a common file and personal.toml, the personal mapping wins.
local PRIVATE_STEMS = { personal = true }

local toml_fnames = {}

-- 1) Personal files first (highest priority).
local personal_fnames = {}
for stem, fname in pairs(toml_set) do
    if PRIVATE_STEMS[stem] then
        personal_fnames[#personal_fnames + 1] = fname
    end
end
table.sort(personal_fnames)
for _, fname in ipairs(personal_fnames) do
    local stem = fname:match("^(.-)%.toml$")
    toml_fnames[#toml_fnames + 1] = fname
    toml_set[stem] = nil  -- mark as consumed
end

-- 2) _index.json order (public categories).
if ordered_names then
    for _, name in ipairs(ordered_names) do
        if toml_set[name] then
            toml_fnames[#toml_fnames + 1] = toml_set[name]
            toml_set[name] = nil  -- mark as consumed
        end
    end
end

-- 3) Append any remaining files not covered above, sorted alphabetically.
local remaining = {}
for _, fname in pairs(toml_set) do remaining[#remaining + 1] = fname end
table.sort(remaining)
for _, fname in ipairs(remaining) do toml_fnames[#toml_fnames + 1] = fname end

-- Load each TOML file as an independent keymap group (group name = stem).
local hotfiles = {}  -- group names passed to the menu
for _, fname in ipairs(toml_fnames) do
    local name = fname:match("^(.-)%.toml$")
    keymap.load_toml(name, hotstrings_dir .. fname)
    hotfiles[#hotfiles + 1] = name
end


---------------------------------------------------------------------------
-- Repeat keys (registered last = lowest priority, fallback if nothing else matches)
-- Registered under the "magickey" group so they are removed/re-added together
-- with that group when the repeat section is toggled.  Without a group context
-- these entries would have group=nil and could never be disabled.
-- A post-load hook ensures they are also re-added after any enable_group /
-- reload_group_inplace call (e.g. when toggling a magickey section).
---------------------------------------------------------------------------
local function register_repeat_keys()
    keymap.set_group_context("magickey")
    repeat_keys.start(keymap)
    keymap.set_group_context(nil)
end
register_repeat_keys()
-- Re-sort once after appending the repeat entries (load_toml already sorted
-- magickey entries; repeat_keys adds more entries that need to be merged in).
keymap.sort_mappings()
keymap.set_post_load_hook("magickey", register_repeat_keys)

---------------------------------------------------------------------------
-- Personal information shortcuts (loaded after base_dir is resolved)
-- keymap is passed so personal_info can register an interceptor that
-- handles @<letters>★ expansions with highest priority in the chain.
---------------------------------------------------------------------------
personal_info.start(base_dir, keymap)

---------------------------------------------------------------------------
-- Dynamic hotstrings (dt★ → date, phone/SSN prefix expansion, …)
-- Started AFTER personal_info so the @-combo interceptor has higher priority
-- (personal_info registers first = interceptor chain position [1]).
-- register_personal_data supplies the private phone/SSN data loaded by
-- personal_info without coupling the two modules directly.
-- "dynamichotstrings" is appended to hotfiles so it appears in the menu.
---------------------------------------------------------------------------
dynamic_hotstrings.start(keymap)
dynamic_hotstrings.register_personal_data(
    personal_info.get_info(),
    personal_info.get_trigger_char()
)
hotfiles[#hotfiles + 1] = "dynamichotstrings"

---------------------------------------------------------------------------
-- Menubar menu (Hammerspoon Menubar)
---------------------------------------------------------------------------
-- External menu module
local menu = require("modules.menu")
menu.start(base_dir, hotfiles, gestures, scroll, keymap, shortcuts, personal_info, module_sections, script_control)

---------------------------------------------------------------------------
-- Script control shortcuts (AltGr+Return = pause/resume, AltGr+Backspace = reload)
---------------------------------------------------------------------------
script_control.start(keymap, shortcuts, gestures, scroll)

---------------------------------------------------------------------------
-- Shutdown callback: restore macOS gesture prefs before Hammerspoon exits
-- so the user gets their system gestures back on quit or reload.
---------------------------------------------------------------------------
hs.shutdownCallback = function()
    gestures.restore_all_overrides()
end
