# Text Expansion - Magic Sample
# Format: [[section]]
# All entries use: trigger = { output = "replacement", is_word = true/false, auto_expand = true/false }

"a★" = { output = "ainsi", is_word = true, auto_expand = true }
"avv★" = { output = "avez-vous", is_word = true, auto_expand = true }
"b★" = { output = "bonjour", is_word = true, auto_expand = true }
"bcp★" = { output = "beaucoup", is_word = true, auto_expand = true }
"c★" = { output = "c’est", is_word = true, auto_expand = true }
"cad★" = { output = "c’est-à-dire", is_word = true, auto_expand = true }
"cb★" = { output = "combien", is_word = true, auto_expand = true }
"ct★" = { output = "c’était", is_word = true, auto_expand = true }
"dé★" = { output = "déjà", is_word = true, auto_expand = true }
"ê★" = { output = "être", is_word = true, auto_expand = true }
"ecq★" = { output = "est-ce que", is_word = true, auto_expand = true }
"eef★" = { output = "en effet", is_word = true, auto_expand = true }
"ex★" = { output = "exemple", is_word = true, auto_expand = true }
"f★" = { output = "faire", is_word = true, auto_expand = true }
"g★" = { output = "j’ai", is_word = true, auto_expand = true }
"gf★" = { output = "j’ai fait", is_word = true, auto_expand = true }
"gt★" = { output = "j’étais", is_word = true, auto_expand = true }
"h★" = { output = "heure", is_word = true, auto_expand = true }
"ia★" = { output = "intelligence artificielle", is_word = true, auto_expand = true }
"m★" = { output = "mais", is_word = true, auto_expand = true }
"mr★" = { output = "monsieur", is_word = true, auto_expand = true }
"n★" = { output = "nouveau", is_word = true, auto_expand = true }
"nb★" = { output = "nombre", is_word = true, auto_expand = true }
"new★" = { output = "nouveau", is_word = true, auto_expand = true }
"orga★" = { output = "organisation", is_word = true, auto_expand = true }
"p★" = { output = "prendre", is_word = true, auto_expand = true }
"pb★" = { output = "problème", is_word = true, auto_expand = true }
"pcq★" = { output = "parce que", is_word = true, auto_expand = true }
"pd★" = { output = "pendant", is_word = true, auto_expand = true }
"pê★" = { output = "peut-être", is_word = true, auto_expand = true }
"pex★" = { output = "par exemple", is_word = true, auto_expand = true }
"pg★" = { output = "pas grave", is_word = true, auto_expand = true }
"q★" = { output = "question", is_word = true, auto_expand = true }
"qcq★" = { output = "qu’est-ce que", is_word = true, auto_expand = true }
"qqch★" = { output = "quelque chose", is_word = true, auto_expand = true }
"r★" = { output = "rien", is_word = true, auto_expand = true }
"rdv★" = { output = "rendez-vous", is_word = true, auto_expand = true }
"rs★" = { output = "résultat", is_word = true, auto_expand = true }
"s★" = { output = "sous", is_word = true, auto_expand = true }
"stp★" = { output = "s’il te plaît", is_word = true, auto_expand = true }
"svp★" = { output = "s’il vous plaît", is_word = true, auto_expand = true }
"t★" = { output = "très", is_word = true, auto_expand = true }
"tb★" = { output = "très bien", is_word = true, auto_expand = true }
"tt★" = { output = "télétravail", is_word = true, auto_expand = true }
"tv★" = { output = "télévision", is_word = true, auto_expand = true }
"usa★" = { output = "États-Unis", is_word = true, auto_expand = true }
"v★" = { output = "version", is_word = true, auto_expand = true }
"wk★" = { output = "week-end", is_word = true, auto_expand = true }
"wiki★" = { output = "Wikipédia", is_word = true, auto_expand = true }
"x★" = { output = "exemple", is_word = true, auto_expand = true }
"yc★" = { output = "y compris", is_word = true, auto_expand = true }
"yt★" = { output = "YouTube", is_word = true, auto_expand = true }
