--- lib/manifest_reader.lua

--- ==============================================================================
--- MODULE: Features Manifest Reader (Linux)
--- DESCRIPTION:
--- Thin runtime API over the codegen'd `_generated/features_manifest.lua`, which
--- is produced by `npm run build:manifest` from the single source of truth at
--- `_shared/modules/features/manifest.toml`. This is the Linux counterpart of
--- `macos/lib/manifest_reader.lua` and `windows/lib/manifest_reader.ahk`.
---
--- WHY THIS MODULE EXISTS:
--- Linux was the only driver with no features manifest at all — the codegen
--- emitted one for Windows and macOS and stopped there — so the Linux keylogger
--- had nowhere to read the cross-driver privacy toggles from. That is why it ran
--- unconditionally, with no off switch and no private-browsing filter, while the
--- other two drivers read all four flags from the shared manifest.
---
--- FEATURES & RATIONALE:
--- 1. cwd-independent load: the manifest is located relative to THIS file via
---    `debug.getinfo` + `loadfile`, so it resolves identically under the daemon
---    and the headless test runner regardless of the working directory or
---    `package.path`.
--- 2. Fail fast: a missing or malformed manifest, or a lookup for an unknown
---    path, raises rather than returning nil. The manifest is committed and
---    regenerated by the build, so a miss is a real misconfiguration — and a
---    privacy toggle that silently reads nil would disable the filter it names.
--- 3. O(1) lookups via a path index built once at load.
--- ==============================================================================

local M = {}

local Logger = require("logger.shim")

local LOG = "lib.manifest_reader"




-- =================================
-- =================================
-- ======= 1/ Manifest Load ========
-- =================================
-- =================================

--- Loads the generated manifest module by absolute path, relative to this file.
--- linux/lib/manifest_reader.lua -> linux -> _generated/features_manifest.lua.
--- @return table The manifest table (version / section_order / sections / features).
local function load_manifest()
	local src    = debug.getinfo(1, "S").source:gsub("^@", "")
	local dir    = src:match("^(.*)[/\\][^/\\]+$") or src   -- .../linux/lib
	local driver = dir:match("^(.*)[/\\][^/\\]+$") or dir   -- .../linux
	local path   = driver .. "/_generated/features_manifest.lua"

	local chunk, load_err = loadfile(path)
	if not chunk then
		error("[manifest_reader] cannot load generated manifest (" .. tostring(load_err)
			.. ") — run `npm run build:manifest`.")
	end
	local ok, mod = pcall(chunk)
	if not ok or type(mod) ~= "table" or type(mod.features) ~= "table" then
		error("[manifest_reader] generated manifest did not return a valid table: " .. tostring(mod))
	end
	return mod
end

local _manifest = load_manifest()

-- Path index built once at load for O(1) lookups.
local _path_index = {}
for _, entry in ipairs(_manifest.features) do
	_path_index[entry.path] = entry
end

Logger.done(LOG, "Features manifest loaded (v%s, %d feature(s)).",
	tostring(_manifest.version), #_manifest.features)




-- =====================================
-- =====================================
-- ======= 2/ Public Accessors =========
-- =====================================
-- =====================================

--- Manifest format version string (e.g. "2.0.0").
--- @return string
function M.version()
	return _manifest.version
end

--- Flat array of feature entries (path / id / section / default / type / …).
--- @return table
function M.features()
	return _manifest.features
end

--- Returns the manifest entry for a canonical feature path, or nil when absent.
--- @param path string The canonical dotted path (e.g. the menu/config key).
--- @return table|nil
function M.find_entry_by_path(path)
	return _path_index[path]
end

--- Returns the default value declared for a feature path. FAIL-FAST when the
--- path is unknown, so a renamed or removed feature surfaces loudly instead of
--- silently defaulting to nil.
--- @param path string
--- @return any The declared default (primitive or table).
function M.default_for(path)
	local entry = _path_index[path]
	if not entry then
		error(string.format("[manifest_reader] no manifest entry for path '%s'", tostring(path)))
	end
	return entry.default
end

return M
