--- tests/unit/platform/remap/test_generator_combos_without_tap_holds.lua

--- ==============================================================================
--- MODULE: Key Combinations Work Without The Tap-Holds
--- DESCRIPTION:
--- Builds the real rule graph from the shipped catalogues with the Tap-Holds
--- off and the key combinations on, then replays the hold slots through the
--- Karabiner v16.0.0 model (tests/support/karabiner_model.lua): « Hold 1 +
--- tap 2 » and « Hold 1 + hold 2 » type their action. With the Tap-Holds on,
--- the graph is the one the combinations generated before.
---
--- ROOT CAUSES ENCODED:
--- 1. The hold slots of a pair match only while key 1's held variable is set,
---    and only key 1's own tap-hold rule set it: with the Tap-Holds off that
---    rule was dropped, so key 1 + key 2 typed the native keys instead of the
---    action, although the combinations had their own switch on (decision of
---    2026-09-29: only that switch governs them).
--- 2. The Tap-Holds-on graph was only compared with itself (switch absent
---    against on), so a change the new code made to both went unseen: it is
---    pinned against the graph 85708c92 generated.
--- ==============================================================================

local helpers        = require("tests.helpers")
local KarabinerModel = require("tests.support.karabiner_model")
local SourceFile     = require("tests.support.source_file")

local TOKEN    = "0123456789abcdef0123456789abcdef"
local DATA_DIR = helpers.driver_root() .. "platform/remap/data/"

-- The rule graph each shipped preset generates with the Tap-Holds on, as
-- generated by 85708c92, the last revision before the combinations could be
-- rebuilt without the Tap-Holds: rule count and digest() of the rules. Change
-- a pin only for an intended change of the Tap-Holds-on rules; the failure
-- message prints the new digest. Intended changes since: the recommended
-- layer hold taps the F19 exit sentinel on release (layer-wheel-slots), and
-- the shared script chords add the Delete chord's running and paused rules in
-- the shared slot order (script-chords-three-os-2026-09-30).
-- CapsWord control edges now notify the keymap before every variable write.
-- Exact hand-modifier variants preserve native output and isolate those tags;
-- historical migration snapshot pins remain unchanged (capsword-control-signal).
local TAP_HOLDS_ON_PINS = {
	default     = { rules = 24, digest = "3ba59a303df80b4f" },
	recommended = { rules = 30, digest = "2da61660630da029" },
}

--- Returns the key codes an engine posted at key_down, in order, with the
--- flags each one carried.
--- @param engine table Karabiner model engine.
--- @return table typed { { key_code, flags } }
local function typed(engine)
	local result = {}
	for _, emission in ipairs(engine:emissions()) do
		if emission.phase == "down" and emission.key_code then
			result[#result + 1] = { key_code = emission.key_code, flags = emission.flags }
		end
	end
	return result
end

--- Whether one of the typed keys is key_code, pressed with no modifier flag.
--- @param keys table Result of typed().
--- @param key_code string Expected output key.
--- @return boolean found
local function typed_bare(keys, key_code)
	for _, key in ipairs(keys) do
		if key.key_code == key_code and next(key.flags) == nil then return true end
	end
	return false
end

--- Serializes a value canonically: map keys sorted, numbers typed, so two
--- graphs serialize equal exactly when their rules are equal.
--- @param value any Rule graph or part of it.
--- @param out table Output fragments.
local function serialize(value, out)
	local kind = type(value)
	if kind == "table" then
		local keys = {}
		for key in pairs(value) do keys[#keys + 1] = key end
		table.sort(keys, function(a, b)
			if type(a) ~= type(b) then return type(a) < type(b) end
			return a < b
		end)
		out[#out + 1] = "{"
		for _, key in ipairs(keys) do
			serialize(key, out)
			out[#out + 1] = "="
			serialize(value[key], out)
			out[#out + 1] = ","
		end
		out[#out + 1] = "}"
	elseif kind == "string" then
		out[#out + 1] = string.format("%q", value)
	elseif kind == "number" then
		out[#out + 1] = math.type(value) == "integer" and string.format("%d", value)
			or string.format("%.17g", value) .. "f"
	elseif kind == "boolean" then
		out[#out + 1] = tostring(value)
	else
		error("unexpected " .. kind .. " in a rule graph")
	end
end

--- The FNV-1a 64-bit digest of a rule graph's canonical serialization: a pin
--- short enough to live in the test, which any change to one rule moves.
--- @param rules table Generated rules.
--- @return string digest Sixteen hexadecimal digits.
local function digest(rules)
	local out = {}
	serialize(rules, out)
	local text = table.concat(out)
	local hash = -3750763034362895579 -- 0xcbf29ce484222325 as a signed integer
	for index = 1, #text do
		hash = (hash ~ text:byte(index)) * 1099511628211
	end
	return string.format("%016x", hash)
end

--- Describes typed keys for a failure message.
--- @param keys table Result of typed().
--- @return string
local function describe(keys)
	local parts = {}
	for _, key in ipairs(keys) do
		local flags = {}
		for flag in pairs(key.flags) do flags[#flags + 1] = flag end
		table.sort(flags)
		parts[#parts + 1] = key.key_code .. "[" .. table.concat(flags, "+") .. "]"
	end
	return table.concat(parts, " ")
end

helpers.with_fresh_modules({
	"adapters.file_system",
	"infra.config_paths",
	"infra.keycodes",
	"infra.logger",
	"infra.toml.codec",
	"platform.remap.config",
	"platform.remap.generator",
	"toml_codec",
}, function()
	package.loaded["infra.logger"] = helpers.make_logger_stub()
	package.loaded["infra.config_paths"] = {
		get_config_dir = function() return "/tmp/ergopti_test" end,
	}
	package.loaded["infra.keycodes"] = {
		to_name                 = function(code) return "key_" .. tostring(code) end,
		F13_KARABINER_RETURN    = 105,
		F14_KARABINER_BACKSPACE = 107,
		F15_KARABINER_ESCAPE    = 113,
		F20_LAYER_NAV_ENTERED   = 90,
		F19_LAYER_NAV_EXITED    = 80,
	}
	local toml_stub = { encode = function() return "" end, decode = function() return {} end }
	package.loaded["toml_codec"] = toml_stub
	package.loaded["infra.toml.codec"] = toml_stub
	package.loaded["adapters.file_system"] = {
		read = SourceFile.read,
		read_with_status = function(path) return SourceFile.read(path), "ok" end,
	}

	local Config    = helpers.load_with_stubs("platform.remap.config")
	local Generator = helpers.load_with_stubs("platform.remap.generator")
	local LeaseContract = require("platform.remap.lease_contract")

	--- The deployed name of a key's held variable: scoped to the generation.
	--- @param key_code string Physical key.
	--- @return string name
	local function held_var(key_code)
		return assert(LeaseContract.runtime_variable_name("ke_held_" .. key_code, TOKEN))
	end

	local actions = assert(Config.load_available_actions(DATA_DIR .. "actions.json"))
	local keys    = assert(Config.load_tap_hold_keys(DATA_DIR .. "tap_hold_keys.json"))
	local combos  = assert(Config.load_mod_combos(DATA_DIR .. "mod_combos.json"))
	local non_canonical = Config.compute_non_canonical_combos(combos)

	--- Builds a graph from a state.
	--- @param state table Remap state.
	--- @return table rules The generated complex_modifications rules.
	local function rules_of(state)
		local config, err = Generator.build_karabiner_json(
			state, actions, keys, combos, non_canonical, DATA_DIR, TOKEN)
		assert(config, "generation failed: " .. tostring(err))
		return config.profiles[1].complex_modifications.rules
	end

	--- The shipped default state with one pair's slots set.
	--- @param tap_holds boolean|nil Tap-Holds switch.
	--- @param combinations boolean|nil Key-combinations switch; nil is absent.
	--- @param pair string|nil Combo id.
	--- @param slots table|nil { combo, tap, hold }.
	--- @return table state
	local function state_with(tap_holds, combinations, pair, slots)
		local state = Config.build_default_state(keys, combos)
		state.tap_holds_enabled = tap_holds
		state.mod_combos_enabled = combinations
		if pair then state.mod_combos_config[pair] = slots end
		return state
	end

	--- Starts a Karabiner model on an ACTIVE lease.
	--- @param rules table Generated rules.
	--- @return table engine
	local function engine_for(rules)
		return KarabinerModel.new(rules, { variables = { [Generator.mode_variable_name(TOKEN)] = 1 } })
	end

	--- Whether a rule of the graph sets a key's held variable at its key_down.
	--- @param rules table Generated rules.
	--- @param key_code string Physical key.
	--- @return boolean sets
	local function tracks(rules, key_code)
		for _, rule in ipairs(rules) do
			for _, manipulator in ipairs(rule.manipulators or {}) do
				if manipulator.from and manipulator.from.key_code == key_code then
					for _, event in ipairs(manipulator.to or {}) do
						if event.set_variable and event.set_variable.name == held_var(key_code) then return true end
					end
				end
			end
		end
		return false
	end

	--- Counts the rules whose description contains text.
	--- @param rules table Generated rules.
	--- @param text string Plain substring.
	--- @return number count
	local function count(rules, text)
		local found = 0
		for _, rule in ipairs(rules) do
			if tostring(rule.description):find(text, 1, true) then found = found + 1 end
		end
		return found
	end

	helpers.describe("key combinations without the Tap-Holds (combos-without-tap-holds)", function()
		-- A modifier key 1: its native flag is held, and must not reach the action.
		helpers.it("Hold Cmd + hold Tab types the hold action, bare (combos-without-tap-holds)", function()
			local rules = rules_of(state_with(false, true, "lcmd_tab",
				{ combo = "none", tap = "none", hold = "delete_fwd" }))
			local engine = engine_for(rules)
			engine:down("left_command")
			engine:down("tab")
			local keys_typed = typed(engine)
			helpers.assert_true(typed_bare(keys_typed, "delete_forward"),
				"the hold slot types its action without Cmd: " .. describe(keys_typed))
			engine:up("tab")
			engine:up("left_command")
			helpers.assert_eq(engine:variable(held_var("left_command")), 0, "key 1's release clears its variable")
		end)

		helpers.it("Hold Esc + tap Tab types the tap action (combos-without-tap-holds)", function()
			local rules = rules_of(state_with(false, true, "esc_tab",
				{ combo = "none", tap = "arrow_left", hold = "none" }))
			local engine = engine_for(rules)
			engine:down("escape")
			engine:tap("tab")
			local keys_typed = typed(engine)
			helpers.assert_true(typed_bare(keys_typed, "left_arrow"),
				"the tap slot types its action: " .. describe(keys_typed))
			for _, key in ipairs(keys_typed) do
				helpers.assert_true(key.key_code ~= "tab", "Tab is not typed natively: " .. describe(keys_typed))
			end
		end)

		-- Key 1 is its native key with the Tap-Holds off (decision of
		-- 2026-09-29: its rule only tracks its held variable and passes the key
		-- through). A non-modifier key 1 is therefore typed, and a lock key
		-- toggles, before its slot fires: pinned so a change is deliberate.
		helpers.it("a non-modifier key 1 is typed natively before its slot (key1-pass-through)", function()
			local cases = {
				{ pair = "ret_tab", key1 = "return_or_enter", tap2 = true,
					slots = { combo = "none", tap = "arrow_left", hold = "none" }, action = "left_arrow" },
				{ pair = "caps_tab", key1 = "caps_lock", tap2 = true,
					slots = { combo = "none", tap = "arrow_left", hold = "none" }, action = "left_arrow" },
				{ pair = "bsp_tab", key1 = "delete_or_backspace", tap2 = false,
					slots = { combo = "none", tap = "none", hold = "delete_fwd" }, action = "delete_forward" },
			}
			for _, case in ipairs(cases) do
				local engine = engine_for(rules_of(state_with(false, true, case.pair, case.slots)))
				engine:down(case.key1)
				if case.tap2 then engine:tap("tab") else engine:down("tab") end
				local keys_typed = typed(engine)
				local context = case.pair .. ": " .. describe(keys_typed)
				helpers.assert_eq(#keys_typed, 2, context)
				helpers.assert_eq(keys_typed[1].key_code, case.key1, context .. " — key 1 is typed first")
				helpers.assert_eq(keys_typed[2].key_code, case.action, context .. " — then the slot's action")
				helpers.assert_true(next(keys_typed[2].flags) == nil, context .. " — the action is bare")
				helpers.assert_eq(engine:variable(held_var(case.key1)), 1, context)
			end
		end)

		-- The chord slot was built from key 1's tap-hold even with the Tap-Holds
		-- off: Cmd gauche + Cmd droit entered the navigation layer (F20, here
		-- key_90) that only left Command's hold may enter. Key 1 is native in
		-- that graph: the chord types ⌥⌫, then left Command stays a held Cmd.
		helpers.it("the recommended LCmd + RCmd chord types ⌥⌫ with no layer (chord-without-tap-holds)", function()
			local state = Config.build_recommended_state(keys, combos)
			state.tap_holds_enabled = false
			state.mod_combos_enabled = true
			local engine = engine_for(rules_of(state))
			helpers.assert_true(engine:chord({ "left_command", "right_command" }) ~= nil, "a chord rule takes both keys")
			local keys_typed = typed(engine)
			local context = describe(keys_typed)
			helpers.assert_eq(#keys_typed, 2, context)
			helpers.assert_eq(keys_typed[1].key_code, "delete_or_backspace", context)
			helpers.assert_eq(keys_typed[1].flags, { left_option = true }, context .. " — ⌥ only, no Cmd")
			helpers.assert_eq(keys_typed[2].key_code, "left_command", context .. " — then the native Cmd, no layer")
			engine:up("right_command")
			engine:up("left_command")
		end)

		helpers.it("key 1 only tracks its variable and passes through (combos-without-tap-holds)", function()
			local rules = rules_of(state_with(false, true, "lcmd_tab",
				{ combo = "none", tap = "none", hold = "delete_fwd" }))
			local engine = engine_for(rules)
			engine:down("left_command")
			helpers.assert_eq(engine:variable(held_var("left_command")), 1)
			helpers.assert_true(engine:pressed().left_command == true, "Cmd stays a native Cmd")
			engine:up("left_command")
			helpers.assert_eq(engine:variable(held_var("left_command")), 0)
			helpers.assert_eq(tracks(rules, "left_command"), true)
			helpers.assert_eq(tracks(rules, "escape"), false, "a key that is no key 1 of a hold slot stays native")
			helpers.assert_eq(tracks(rules, "tab"), false, "key 2 stays native")
		end)

		helpers.it("with the Tap-Holds on the graph is unchanged by the switch (combos-without-tap-holds)", function()
			local recommended = Config.build_recommended_state(keys, combos)
			recommended.tap_holds_enabled = true
			local absent = rules_of(recommended)
			recommended.mod_combos_enabled = true
			helpers.assert_eq(rules_of(recommended), absent, "an absent switch is on")
		end)

		-- Comparing the new generator with itself cannot see a change it makes
		-- to both graphs: the Tap-Holds-on graph of the shipped presets is
		-- pinned as 85708c92 generated it, before the combinations could be
		-- rebuilt without the Tap-Holds.
		helpers.it("with the Tap-Holds on the presets generate the pinned graph (tap-holds-on-pin)", function()
			local builders = {
				default = Config.build_default_state,
				recommended = Config.build_recommended_state,
			}
			for _, preset in ipairs({ "default", "recommended" }) do
				for _, combinations in ipairs({ "absent", "on" }) do
					local state = builders[preset](keys, combos)
					state.tap_holds_enabled = true
					state.mod_combos_enabled = combinations == "on" or nil
					local rules = rules_of(state)
					local pin = TAP_HOLDS_ON_PINS[preset]
					local context = preset .. " preset, key combinations " .. combinations
					helpers.assert_eq(#rules, pin.rules, context .. ": rule count")
					helpers.assert_eq(digest(rules), pin.digest, context
						.. ": the Tap-Holds-on rules changed; re-pin only for an intended change")
				end
			end
		end)

		helpers.it("the pin moves when one Tap-Holds-on manipulator changes (tap-holds-on-pin)", function()
			local state = Config.build_recommended_state(keys, combos)
			state.tap_holds_enabled = true
			local rules = rules_of(state)
			local before = digest(rules)
			local mutated = false
			for _, rule in ipairs(rules) do
				local manipulator = rule.manipulators and rule.manipulators[1]
				if not mutated and manipulator and tostring(rule.description):find("[var-based]", 1, true) then
					manipulator.from.modifiers = manipulator.from.modifiers or {}
					manipulator.from.modifiers.mandatory = { "left_shift" }
					mutated = true
				end
			end
			helpers.assert_true(mutated, "the recommended preset has a var-based combination to mutate")
			helpers.assert_true(digest(rules) ~= before, "a changed manipulator changes the digest")
		end)

		helpers.it("the combinations switched off generate no combination rule (combos-without-tap-holds)",
			function()
				for _, tap_holds in ipairs({ true, false }) do
					local rules = rules_of(state_with(tap_holds, false, "lcmd_tab",
						{ combo = "escape", tap = "none", hold = "delete_fwd" }))
					helpers.assert_eq(count(rules, "[var-based]"), 0)
					helpers.assert_eq(count(rules, "[chord]"), 0)
					if not tap_holds then
						helpers.assert_eq(tracks(rules, "left_command"), false, "no held variable is tracked for them")
					end
				end
			end)
	end)
end)
