--- tests/unit/modules/shortcuts/test_physical_pause_observation.lua

--- Drives actual pause writers with independent before/after receipt expectations.
--- Native APIs are adversarial doubles; this does not prove installed macOS input.
local helpers = require("tests.helpers")
local fixture = require("tests.support.pause_transaction_fixture")
local describe, it = helpers.describe, helpers.it
local function last(records) return records[#records] end

local function with_context(options, callback)
	options = options or {}
	return helpers.with_stub_scope({"keylogger.physical_lifecycle_observation","adapters.physical_observation_clock"},function()
		return fixture.with_context(options,function(script,ctx)
			local reads,records,owner,token=0,{},{}
			hs.timer.absoluteTime=function() reads=reads+1; return reads end
			ctx.clock_reads=function() return reads end
			ctx.observe_records=records
			ctx.observe_owner=owner
			if options.unbound ~= true then
				token=script.bind_physical_pause_observer(owner,options.capacity or 100,function(record,observed_token)
					records[#records+1]=record
					if options.receive then return options.receive(script,ctx,record,observed_token) end
					return true
				end)
				helpers.assert_true(token~=nil)
			end
			return callback(script,ctx,records,owner,token)
		end)
	end)
end
local function commit_pause(script,ctx)
	helpers.assert_eq(script.pause_all(),true)
	ctx.fire_deferred()
	ctx.pause_callback(true,"paused")
end
local function commit_resume(script,ctx)
	helpers.assert_eq(script.resume_all(),true)
	ctx.fire_deferred()
	ctx.resume_callback(true,"resumed")
end
local function denied(records)
	helpers.assert_eq(last(records).allowed,false)
	helpers.assert_eq(last(records).complete,false)
end

describe("Actual pause writer observer ordering",function()
	it("throwing observer preserves actual native effects and the existing callback",function()
		with_context({receive=function(_,_,record) if record.source~="binding" then error("observer exploded") end;return true end},function(script,ctx,records)
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_eq(ctx.calls.input_drain,1);helpers.assert_eq(ctx.calls.admission_acquire,1)
			helpers.assert_eq(ctx.calls.admission_release,1)
			helpers.assert_eq(ctx.calls.karabiner_pause,1);helpers.assert_eq(ctx.calls.karabiner_resume,1)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true,false}))
			helpers.assert_eq(#records,2)
			script.stop()
		end)
	end)
	it("detach and replacement during boundary cannot complete the old pause",function()
		local replacement_records={}
		with_context({receive=function(script,ctx,record,observed_token)
			if record.source=="pause" then
				helpers.assert_eq(script.unbind_physical_pause_observer(ctx.observe_owner,observed_token),true)
				helpers.assert_true(script.bind_physical_pause_observer({},100,function(r) replacement_records[#replacement_records+1]=r;return true end)~=nil)
			end
			return true
		end},function(script,ctx,records)
			commit_pause(script,ctx)
			helpers.assert_eq(ctx.calls.input_drain,1);helpers.assert_eq(ctx.calls.admission_acquire,1)
			helpers.assert_eq(ctx.calls.karabiner_pause,1)
			helpers.assert_eq(#replacement_records,1)
			helpers.assert_eq(replacement_records[1].source,"binding")
			helpers.assert_eq(replacement_records[1].complete,false)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true}))
			script.stop()
		end)
	end)
	it("pause receiver reentry joins the existing actual native owner",function()
		with_context({receive=function(script,_,record)
			if record.source=="pause" then helpers.assert_eq(script.pause_all(),true) end
			return true
		end},function(script,ctx,records)
			commit_pause(script,ctx)
			helpers.assert_eq(ctx.calls.input_drain,1);helpers.assert_eq(ctx.calls.admission_acquire,1)
			helpers.assert_eq(ctx.calls.karabiner_pause,1)
			helpers.assert_eq(#ctx.pause_callbacks,1)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true}))
			denied(records);helpers.assert_eq(#records,2)
			script.stop()
		end)
	end)
	it("resume receiver reentry joins the existing actual native owner",function()
		with_context({receive=function(script,_,record)
			if record.source=="resume" then helpers.assert_eq(script.resume_all(),true) end
			return true
		end},function(script,ctx,records)
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_eq(ctx.calls.karabiner_resume,1)
			helpers.assert_eq(#ctx.resume_callbacks,1)
			helpers.assert_eq(ctx.calls.admission_release,1)
			helpers.assert_eq(ctx.admission_fence,nil)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true,false}))
			denied(records)
			script.stop()
		end)
	end)

	it("unbound pause/resume retain native effect and query inventories",function()
		with_context({unbound=true},function(script,ctx,records)
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_eq(ctx.calls.input_drain,1)
			helpers.assert_eq(ctx.calls.admission_acquire,1)
			helpers.assert_eq(ctx.calls.admission_release,1)
			helpers.assert_eq(ctx.calls.karabiner_pause,1)
			helpers.assert_eq(ctx.calls.karabiner_resume,1)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true,false}))
			helpers.assert_eq(ctx.clock_reads(),0);helpers.assert_eq(#records,0)
			script.stop()
		end)
	end)
	it("binding seeds denial without changing the existing pause callback",function()
		with_context({},function(script,ctx,records)
			helpers.assert_eq(#records,1);helpers.assert_eq(last(records).source,"binding")
			helpers.assert_eq(ctx.calls.input_drain,nil)
			helpers.assert_eq(ctx.calls.admission_acquire,nil)
			helpers.assert_eq(script.is_paused(),false);denied(records)
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true,false}))
			script.stop()
		end)
	end)
	it("denies before the first foreign synthetic-input drain",function()
		with_context({input_drain_deferred=true},function(script,ctx,records)
			local native=package.loaded["adapters.synthetic_input"]
			local original=native.when_idle
			native.when_idle=function(...)
				helpers.assert_eq(last(records).source,"pause")
				helpers.assert_eq(last(records).stage,"boundary");denied(records)
				return original(...)
			end
			helpers.assert_eq(script.pause_all(),true)
			helpers.assert_eq(#records,2);denied(records)
			ctx.input_idle_callbacks[1]();ctx.fire_deferred();ctx.pause_callback(true,"paused")
			helpers.assert_eq(last(records).complete,true)
			script.stop()
		end)
	end)
	it("pending native PAUSED does not complete before actual local commit",function()
		with_context({},function(script,ctx,records)
			helpers.assert_eq(script.pause_all(),true);ctx.fire_deferred();denied(records)
			helpers.assert_eq(script.is_paused(),false)
			ctx.hooks.keymap_pause=function() denied(records) end
			ctx.pause_callback(true,"paused")
			helpers.assert_eq(last(records).complete,true)
			helpers.assert_eq(last(records).paused,true)
			helpers.assert_eq(last(records).admission_released,false)
			helpers.assert_eq(last(records).settled,true)
			helpers.assert_eq(last(records).allowed,false)
			script.stop()
		end)
	end)
	it("resync during resume is still denied until admission and pause commit",function()
		with_context({},function(script,ctx,records)
			commit_pause(script,ctx)
			ctx.hooks.keylogger_resync=function()
				denied(records);helpers.assert_eq(script.is_paused(),true)
				helpers.assert_true(ctx.admission_fence~=nil)
			end
			commit_resume(script,ctx)
			helpers.assert_eq(last(records).complete,true)
			helpers.assert_eq(last(records).paused,false)
			helpers.assert_eq(last(records).admission_released,true)
			helpers.assert_eq(last(records).allowed,false)
			script.stop()
		end)
	end)
	it("completion follows exact admission release and existing singleton publication",function()
		with_context({},function(script,ctx,records)
			local callback_calls=0
			script.set_on_pause_change(function(value)
				callback_calls=callback_calls+1
				helpers.assert_eq(script.is_paused(),value)
				denied(records)
			end)
			commit_pause(script,ctx)
			local native=package.loaded["adapters.synthetic_input"]
			local original=native.release_admission_fence
			native.release_admission_fence=function(token)
				denied(records);helpers.assert_true(token==ctx.admission_fence)
				return original(token)
			end
			commit_resume(script,ctx)
			helpers.assert_eq(callback_calls,2)
			helpers.assert_eq(last(records).complete,true)
			helpers.assert_eq(ctx.calls.admission_release,1)
			helpers.assert_eq(ctx.admission_fence,nil)
			script.stop()
		end)
	end)
	it("failed native pause emits incomplete without changing legacy callbacks",function()
		with_context({},function(script,ctx,records)
			script.pause_all();ctx.fire_deferred();ctx.pause_callback(false,"native failed")
			helpers.assert_eq(last(records).stage,"incomplete");denied(records)
			helpers.assert_eq(script.is_paused(),false)
			helpers.assert_eq(#ctx.pause_listener,0)
			script.stop()
		end)
	end)
	it("foreign drain refusal stays denied and a retry owns a new writer",function()
		local options={input_drain_deferred=true,input_drain_accepted=false}
		with_context(options,function(script,ctx,records)
			helpers.assert_eq(script.pause_all(),false);denied(records)
			helpers.assert_eq(last(records).stage,"incomplete")
			options.input_drain_accepted=true
			helpers.assert_eq(script.pause_all(),true)
			ctx.input_idle_callbacks[2]();ctx.fire_deferred();ctx.pause_callback(true,"retry-paused")
			helpers.assert_eq(last(records).complete,true)
			script.stop()
		end)
	end)
	it("admission acquisition refusal cannot complete",function()
		with_context({admission_refused=true},function(script,ctx,records)
			script.pause_all()
			denied(records);helpers.assert_eq(last(records).stage,"incomplete")
			helpers.assert_eq(ctx.calls.karabiner_pause,nil)
			script.stop()
		end)
	end)
	it("unknown native enabled state keeps the owned observer denied",function()
		with_context({get_enabled_mode="nil"},function(script,ctx,records)
			script.pause_all();denied(records)
			helpers.assert_eq(last(records).stage,"incomplete")
			helpers.assert_eq(ctx.calls.karabiner_pause,nil)
			script.stop()
		end)
	end)
	it("local pause refusal remains denied through native rollback",function()
		with_context({pause_failure={step="gestures_pause",mode="false"}},function(script,ctx,records)
			script.pause_all();ctx.fire_deferred();ctx.pause_callback(true,"paused")
			denied(records);helpers.assert_eq(last(records).stage,"boundary")
			ctx.resume_callback(true,"rolled-back")
			denied(records);helpers.assert_eq(last(records).stage,"incomplete")
			helpers.assert_eq(#ctx.pause_listener,0)
			script.stop()
		end)
	end)
	it("failed admission release stays denied until rollback then exact retry",function()
		with_context({admission_release_failures=1},function(script,ctx,records)
			commit_pause(script,ctx)
			script.resume_all();ctx.fire_deferred();ctx.resume_callback(true,"native-resumed")
			denied(records);helpers.assert_eq(last(records).stage,"boundary")
			ctx.pause_callbacks[2](true,"re-paused")
			denied(records);helpers.assert_eq(last(records).stage,"incomplete")
			helpers.assert_true(ctx.admission_fence~=nil)
			commit_resume(script,ctx)
			helpers.assert_eq(last(records).complete,true)
			helpers.assert_eq(ctx.admission_fence,nil)
			script.stop()
		end)
	end)
	it("local-only transitions still require actual commit and admission release",function()
		with_context({integration_enabled=false},function(script,ctx,records)
			helpers.assert_eq(script.pause_all(),true)
			helpers.assert_eq(last(records).complete,true);helpers.assert_eq(last(records).paused,true)
			helpers.assert_eq(script.resume_all(),true)
			helpers.assert_eq(last(records).complete,true)
			helpers.assert_eq(last(records).admission_released,true)
			helpers.assert_eq(ctx.calls.karabiner_pause,nil)
			helpers.assert_eq(ctx.calls.karabiner_resume,nil)
			script.stop()
		end)
	end)
	it("cancelled drain cannot leave an old ticket for the next request",function()
		with_context({input_drain_deferred=true},function(script,ctx,records)
			script.pause_all();script.resume_all();ctx.input_idle_callbacks[1]()
			denied(records);helpers.assert_eq(last(records).stage,"incomplete")
			script.pause_all();ctx.input_idle_callbacks[2]();ctx.fire_deferred();ctx.pause_callback(true,"paused")
			helpers.assert_eq(last(records).complete,true)
			script.stop()
		end)
	end)
	it("duplicate native completion cannot issue another receipt",function()
		with_context({},function(script,ctx,records)
			commit_pause(script,ctx)
			local count=#records
			ctx.pause_callback(true,"duplicate")
			helpers.assert_eq(#records,count)
			script.stop()
		end)
	end)
	it("binding during an existing transition cannot complete its old writer",function()
		with_context({},function(script,ctx,records,owner,token)
			script.pause_all();ctx.fire_deferred()
			helpers.assert_eq(script.unbind_physical_pause_observer(owner,token),true)
			local replacement_records={}
			helpers.assert_true(script.bind_physical_pause_observer({},100,function(record) replacement_records[#replacement_records+1]=record;return true end)~=nil)
			ctx.pause_callback(true,"paused")
			helpers.assert_eq(#replacement_records,1)
			helpers.assert_eq(replacement_records[1].complete,false)
			script.stop()
		end)
	end)
	it("observer refusal cannot cancel native effects or existing publication",function()
		with_context({receive=function(_,_,record) return record.source=="binding" end},function(script,ctx,records)
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_eq(script.is_paused(),false)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener,{true,false}))
			helpers.assert_eq(ctx.calls.karabiner_pause,1)
			helpers.assert_eq(ctx.calls.karabiner_resume,1)
			helpers.assert_eq(#records,2)
			script.stop()
		end)
	end)
	it("exact owner and token reject forged equality",function()
		with_context({},function(script,ctx,records,owner,token)
			local forged=setmetatable({},{__eq=function() error("equality forgery") end})
			helpers.assert_eq(script.unbind_physical_pause_observer(forged,token),false)
			helpers.assert_eq(script.unbind_physical_pause_observer(owner,forged),false)
			helpers.assert_eq(script.unbind_physical_pause_observer(owner,token),true)
			local reads=ctx.clock_reads()
			commit_pause(script,ctx);commit_resume(script,ctx)
			helpers.assert_eq(ctx.clock_reads(),reads)
			script.stop()
		end)
	end)
	it("stop invalidates current observation before foreign native cleanup",function()
		with_context({},function(script,ctx,records)
			commit_pause(script,ctx)
			local native=package.loaded["adapters.synthetic_input"]
			local original=native.release_admission_fence
			native.release_admission_fence=function(token)
				helpers.assert_eq(last(records).source,"stop");denied(records)
				return original(token)
			end
			helpers.assert_eq(script.stop(),true)
			denied(records);helpers.assert_eq(last(records).source,"stop")
		end)
	end)
	it("same-state no-op adds no clock or observer query",function()
		with_context({},function(script,ctx,records)
			local count,reads=#records,ctx.clock_reads()
			helpers.assert_eq(script.resume_all(),true)
			helpers.assert_eq(#records,count);helpers.assert_eq(ctx.clock_reads(),reads)
			script.stop()
		end)
	end)
end)

describe("Shared asynchronous pause ownership",function()
	local function actor_fixture()
		local now,records,failures=0,{},{}
		local actor=require("keylogger.physical_lifecycle_observation").new("pause",function() now=now+1;return now end,function(reason) failures[#failures+1]=reason end)
		local owner={}
		local token=actor.bind(owner,100,function(record) records[#records+1]=record;return true end)
		return actor,records,owner,token,failures
	end
	local function snapshot(paused,released)
		return function() return {paused=paused,transition_generation=2,admission_released=released,settled=true} end
	end
	it("async pending writer stays denied until its exact finish",function()
		local actor,records=actor_fixture()
		local ticket=actor.begin("pause")
		denied(records)
		helpers.assert_eq(actor.finish({},snapshot(true,false),true),false)
		helpers.assert_eq(actor.finish(ticket,snapshot(true,false),true),true)
		helpers.assert_eq(last(records).complete,true)
		helpers.assert_eq(last(records).allowed,false)
	end)
	it("resume cannot complete before exact admission release",function()
		local actor,records=actor_fixture()
		local ticket=actor.begin("resume")
		actor.finish(ticket,snapshot(false,false),true)
		denied(records)
	end)
	it("foreign target or unset settlement cannot complete",function()
		local actor,records=actor_fixture()
		local ticket=actor.begin("pause")
		actor.finish(ticket,snapshot(false,true),true);denied(records)
		ticket=actor.begin("resume")
		actor.finish(ticket,function() return {paused=false,transition_generation=2,admission_released=true,settled=false} end,true)
		denied(records)
	end)
	it("old owner finish skips all snapshot queries after replacement",function()
		local actor,records,owner,token=actor_fixture()
		local ticket=actor.begin("pause")
		actor.unbind(owner,token)
		local replacement={}
		helpers.assert_true(actor.bind(replacement,100,function(record) records[#records+1]=record;return true end)~=nil)
		local queries=0
		actor.finish(ticket,function() queries=queries+1;return {} end,true)
		helpers.assert_eq(queries,0);helpers.assert_eq(last(records).source,"binding")
		local new_ticket=actor.begin("resume")
		actor.finish(new_ticket,snapshot(false,true),true)
		helpers.assert_eq(last(records).complete,true)
	end)
	it("async writer reentry retires current completion",function()
		local actor,records,_,_,failures=actor_fixture()
		local ticket=actor.begin("pause")
		actor.begin("resume")
		actor.finish(ticket,snapshot(true,false),true)
		denied(records);helpers.assert_eq(#failures,1)
	end)
	it("missing pause facts cannot complete and never permit history",function()
		local actor,records=actor_fixture()
		local ticket=actor.begin("pause")
		actor.finish(ticket,function() return {transition_generation=2,admission_released=false,settled=true} end,true)
		denied(records);helpers.assert_eq(last(records).fields_complete,false)
	end)
end)

helpers.describe("asynchronous completion retains its outer frame",function()
	helpers.it("same-ticket snapshot reentry cannot forge completion",function()
		local now,records,refusals=0,{},0
		local actor=require("keylogger.physical_lifecycle_observation").new("pause",function() now=now+1;return now end,function() refusals=refusals+1 end)
		helpers.assert_true(actor.bind({},20,function(record) records[#records+1]=record;return true end)~=nil)
		local ticket=actor.begin("pause")
		local function settled() return {paused=true,transition_generation=2,admission_released=false,settled=true} end
		local inner
		local outer=actor.finish(ticket,function()
			inner=actor.finish(ticket,settled,true)
			return settled()
		end,false)
		helpers.assert_eq(inner,false,"Nested completion must not acknowledge another terminal")
		helpers.assert_eq(outer,false)
		helpers.assert_eq(records[#records].complete,false,"Nested snapshot is never native commit evidence")
		helpers.assert_eq(refusals,1)
	end)
end)

helpers.describe("actual pause subscriber refusal interface", function()
	local function observe_refusal(mode, callback)
		return with_context({ unbound = true }, function(script, ctx)
			local owner, records, count, token, scope = {}, {}, 0, nil, nil
			local facts = {}
			local reason
			token, reason, scope = script.bind_physical_pause_observer(owner, mode == "budget" and 1 or 100,
				function(record)
					records[#records + 1] = record
					if record.source == "binding" then return true end
					if mode == "throw" then error("Actual receiver refused") end
					return false
				end, function(refusal_reason, exact_token)
					count = count + 1
					facts.reason, facts.token = refusal_reason, exact_token
					facts.current = scope.current(owner, exact_token)
					facts.detached = scope.detach(owner, exact_token)
					facts.inside_retired = scope.retired(owner, exact_token)
				end)
			helpers.assert_true(token ~= nil); helpers.assert_eq(reason, nil)
			callback(script, ctx, owner, token, scope, facts, records, function() return count end)
		end)
	end
	local function check_actual_pause(mode)
		observe_refusal(mode, function(script, ctx, owner, token, scope, facts, records, count)
			helpers.assert_eq(script.pause_all(), true)
			-- Inspect observations outside both protected receiver/refusal callbacks.
			helpers.assert_eq(count(), 1)
			helpers.assert_true(rawequal(facts.token, token))
			helpers.assert_eq(facts.reason, mode == "budget" and "Lifecycle receipt budget exhausted" or "Lifecycle subscriber refused receipt")
			helpers.assert_eq(facts.current, false)
			helpers.assert_eq(facts.detached, true)
			helpers.assert_eq(facts.inside_retired, false)
			helpers.assert_eq(scope.retired(owner, token), false)
			ctx.fire_deferred(); ctx.pause_callback(true, "paused")
			helpers.assert_eq(scope.retired(owner, token), true)
			helpers.assert_eq(ctx.calls.input_drain, 1); helpers.assert_eq(ctx.calls.admission_acquire, 1)
			helpers.assert_eq(ctx.calls.karabiner_pause, 1)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener, { true }))
			commit_resume(script, ctx)
			helpers.assert_eq(count(), 1)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener, { true, false }))
			script.stop()
		end)
	end
	helpers.it("forwards exact budget refusal after revocation and retains the actual pending writer", function()
		check_actual_pause("budget")
	end)
	helpers.it("forwards exact receiver refusal without changing native pause/resume effects", function()
		check_actual_pause("reject")
	end)
	helpers.it("forwards contained receiver throws once and retains outer completion debt", function()
		check_actual_pause("throw")
	end)
	helpers.it("bootstrap refusal keeps original token reason and scope after a successor binds", function()
		with_context({ unbound = true }, function(script, ctx)
			local owner, next_owner, observed_token, count = {}, {}, nil, 0
			local facts = {}
			local token, reason, scope = script.bind_physical_pause_observer(owner, 20, function(_, exact)
				observed_token = exact; return false
			end, function(refusal_reason, exact)
				count = count + 1; facts.reason, facts.token = refusal_reason, exact
				facts.detached = script.unbind_physical_pause_observer(owner, exact)
				facts.next_token, facts.next_reason, facts.next_scope = script.bind_physical_pause_observer(next_owner, 20, function() return true end)
			end)
			helpers.assert_eq(count, 1); helpers.assert_eq(token, nil)
			helpers.assert_eq(reason, "Lifecycle bootstrap refused")
			helpers.assert_eq(facts.reason, "Lifecycle subscriber refused receipt")
			helpers.assert_true(rawequal(facts.token, observed_token)); helpers.assert_eq(facts.detached, true)
			helpers.assert_true(rawequal(scope.identity(owner), observed_token))
			helpers.assert_eq(scope.identity(next_owner), nil)
			helpers.assert_eq(scope.current(owner, observed_token), false)
			helpers.assert_eq(scope.retired(owner, observed_token), true)
			helpers.assert_true(facts.next_token ~= nil); helpers.assert_eq(facts.next_reason, nil)
			helpers.assert_eq(facts.next_scope.current(next_owner, facts.next_token), true)
			helpers.assert_eq(script.unbind_physical_pause_observer(next_owner, facts.next_token), true)
			helpers.assert_eq(ctx.calls.input_drain, nil); helpers.assert_eq(ctx.calls.admission_acquire, nil)
			script.stop()
		end)
	end)
	helpers.it("preserves the actor refusal reason for an invalid optional notification port", function()
		with_context({ unbound = true }, function(script, ctx)
			local reads = ctx.clock_reads()
			local token, reason, scope = script.bind_physical_pause_observer({}, 20, function() return true end, {})
			helpers.assert_eq(token, nil); helpers.assert_eq(reason, "Invalid lifecycle subscription"); helpers.assert_eq(scope, nil)
			helpers.assert_eq(ctx.clock_reads(), reads)
			commit_pause(script, ctx); commit_resume(script, ctx)
			helpers.assert_eq(ctx.clock_reads(), reads)
			helpers.assert_true(helpers.deep_equal(ctx.pause_listener, { true, false }))
			script.stop()
		end)
	end)
end)
