--- _shared/lua/window_titles.lua

--- Generated by tools/codegen/codegen-window-titles.cjs; do not edit.
--- Source: _shared/ui/apps.manifest.json window_title.
local M = {}
local PREFIX = "ErgoptiPlus"
local SEPARATOR = " — "
local TITLE_KEYS = {
	["action_picker"] = "dialog.action_picker.label",
	["changelog"] = "changelog_window.window_title",
	["config_cleanup"] = "dialog.unused_keys.title",
	["download_window"] = "download_window.window_title",
	["error_dialog"] = "common.error_title",
	["healthcheck"] = "menu.debug.healthcheck",
	["hotstring_editor"] = "editor.hotstrings.window_title",
	["hotstrings_config_window"] = "hs_config.window_title",
	["layer_editor"] = "layer_editor.window_title",
	["layout_manager"] = "layout_manager.window_title",
	["metrics_apps"] = "metrics_apps.window_title",
	["metrics_typing"] = "metrics_apps.title",
	["model_browser"] = "model_browser.window_title",
	["numeric_prompt"] = "numeric_prompt.window_title",
	["onboarding"] = "onboarding.window_title",
	["paths_editor"] = "menu.paths.window_title",
	["permission_dialog"] = "permission_dialog.window_title",
	["personal_info_editor"] = "editor.personal_info.window_title",
	["physical_shortcuts"] = "physical_shortcuts.window_title",
	["prompt_editor"] = "prompt_editor.title_new",
	["token_prompt"] = "token_prompt.window_title",
	["update_check"] = "update_check.window_title",
}
local PRESENTATIONS = {
	["action_picker"] = {
		["keyboard_slot_selection"] = { title_key = "dialog.keyboard_shortcut.title_prefix", label_key = "dialog.keyboard_shortcut.prompt", platforms = {"hs"} },
	},
}

--- Compose a native caption from an already-translated, brandless label.
--- @param label string|nil
--- @return string
function M.compose(label)
	if type(label) ~= "string" or label == "" then return PREFIX end
	if PREFIX == "" then return label end
	return PREFIX .. SEPARATOR .. label
end

--- Returns the shared, brandless translation key for a supported UI app.
--- @param app_id string
--- @return string|nil
function M.key_for_app(app_id)
	return TITLE_KEYS[app_id]
end

--- Returns a bounded projection from the private compiled declaration.
--- @param app_id string Existing UI app identity.
--- @param presentation_id string Explicit contextual identity.
--- @param platform string Native platform id.
--- @return table|nil
function M.presentation_for_app(app_id, presentation_id, platform)
	if type(app_id) ~= "string" or type(presentation_id) ~= "string" or type(platform) ~= "string" then return nil end
	local app = rawget(PRESENTATIONS, app_id)
	if type(app) ~= "table" or getmetatable(app) ~= nil then return nil end
	local entry = rawget(app, presentation_id)
	if type(entry) ~= "table" or getmetatable(entry) ~= nil then return nil end
	local platforms = rawget(entry, "platforms")
	if type(platforms) ~= "table" or getmetatable(platforms) ~= nil then return nil end
	for _, native in ipairs(platforms) do
		if native == platform then
			local declared_platforms = {}
			for index, value in ipairs(platforms) do declared_platforms[index] = value end
			return { title_key = rawget(entry, "title_key"), label_key = rawget(entry, "label_key"), platforms = declared_platforms }
		end
	end
	return nil
end

return M
