--- _shared/lua/window_titles.lua

--- Generated by tools/codegen/codegen-window-titles.cjs; do not edit.
--- Source: _shared/ui/apps.manifest.json window_title.
local M = {}
local PREFIX = "ErgoptiPlus"
local SEPARATOR = " — "
local TITLE_KEYS = {
	["action_picker"] = "dialog.action_picker.label",
	["changelog"] = "changelog_window.window_title",
	["config_cleanup"] = "dialog.unused_keys.title",
	["download_window"] = "download_window.window_title",
	["error_dialog"] = "common.error_title",
	["healthcheck"] = "menu.debug.healthcheck",
	["hotstring_editor"] = "editor.hotstrings.window_title",
	["hotstrings_config_window"] = "hs_config.window_title",
	["layer_editor"] = "layer_editor.window_title",
	["layout_manager"] = "layout_manager.window_title",
	["metrics_apps"] = "metrics_apps.window_title",
	["metrics_typing"] = "metrics_apps.title",
	["model_browser"] = "model_browser.window_title",
	["numeric_prompt"] = "numeric_prompt.window_title",
	["onboarding"] = "onboarding.window_title",
	["paths_editor"] = "menu.paths.window_title",
	["permission_dialog"] = "permission_dialog.window_title",
	["personal_info_editor"] = "editor.personal_info.window_title",
	["physical_shortcuts"] = "physical_shortcuts.window_title",
	["prompt_editor"] = "prompt_editor.title_new",
	["token_prompt"] = "token_prompt.window_title",
	["update_check"] = "update_check.window_title",
}

--- Compose a native caption from an already-translated, brandless label.
--- @param label string|nil
--- @return string
function M.compose(label)
	if type(label) ~= "string" or label == "" then return PREFIX end
	if PREFIX == "" then return label end
	return PREFIX .. SEPARATOR .. label
end

--- Returns the shared, brandless translation key for a supported UI app.
--- @param app_id string
--- @return string|nil
function M.key_for_app(app_id)
	return TITLE_KEYS[app_id]
end

return M
