# Ergopti+ Keylayout Mappings Configuration
# This file defines the mappings for dead keys and special combinations in Ergopti+

[roll_ck]
"cx" = "ck"

[e]
"eé" = "ez"

[e_acute_sfb]
"éê" = "eo"
"éà" = "ié"

[e_grave_y]
"èy" = "aî"

[e_circumflex_deadkey]
"êa" = "â"
"êà" = "æ"
"êe" = "œ"
"êé" = "oe"
"êi" = "î"
"êo" = "ô"
"êu" = "û"

[roll_wh]
"hc" = "wh"

[roll_ct]
"p'" = "ct"

[roll_sk]
"sx" = "sk"

[y_e_grave]
"yè" = "â"



# ===============================
# === Symbols and punctuation ===
# ===============================

[rolls_hashtag]
"#!" = " := "
"#(" = '")'
"#[" = '"]'

[rolls_chevron_left]
"<@" = "</"
"<%" = " <= "

[rolls_chevron_right]
">%" = " >= "

[rolls_parenthesis_left]
"(#" = '("'

[rolls_bracket_left]
"[#" = '["'
"[)" = ' = "'

[rolls_bracket_right]
"]#" = '"]'

[rolls_exclamation_mark]
"!#" = " != "

[rolls_backslash]
'\"' = "/*"

[rolls_quote]
'"\' = "*/"

[rolls_dollar]
"$=" = " => "

[rolls_equal]
"=$" = " <= "
"=+" = " ➜ "

[rolls_plus]
"+?" = " -> "

[rolls_question_mark]
"?+" = " <- "