# Text Expansion - Magic Sample
# Format simple : trigger = output
# Chaque entrée : trigger = expansion

"a★" = "ainsi"
"avv★" = "avez-vous"
"b★" = "bonjour"
"bcp★" = "beaucoup"
"c★" = "c'est"
"cad★" = "c'est-à-dire"
"cb★" = "combien"
"ct★" = "c'était"
"dé★" = "déjà"
"ê★" = "être"
"ecq★" = "est-ce que"
"eef★" = "en effet"
"ex★" = "exemple"
"f★" = "faire"
"g★" = "j'ai"
"gf★" = "j'ai fait"
"gt★" = "j'étais"
"h★" = "heure"
"ia★" = "intelligence artificielle"
"m★" = "mais"
"mr★" = "monsieur"
"n★" = "nouveau"
"nb★" = "nombre"
"new★" = "nouveau"
"orga★" = "organisation"
"p★" = "prendre"
"pb★" = "problème"
"pcq★" = "parce que"
"pd★" = "pendant"
"pê★" = "peut-être"
"pex★" = "par exemple"
"pg★" = "pas grave"
"q★" = "question"
"qcq★" = "qu'est-ce que"
"qqch★" = "quelque chose"
"r★" = "rien"
"rdv★" = "rendez-vous"
"rs★" = "résultat"
"s★" = "sous"
"stp★" = "s'il te plaît"
"svp★" = "s'il vous plaît"
"t★" = "très"
"tb★" = "très bien"
"tt★" = "télétravail"
"tv★" = "télévision"
"usa★" = "États-Unis"
"v★" = "version"
"wk★" = "week-end"
"wiki★" = "Wikipédia"
"x★" = "exemple"
"yc★" = "y compris"
"yt★" = "YouTube"