--- _shared/lua/brightness_actions_data.lua

--- Generated by tools/codegen/codegen-brightness-actions.cjs; do not edit.
--- Source: _shared/modules/actions/brightness.json.
return {
	["version"] = 1,
	["step_percent"] = 5,
	["worker_timeout_ms"] = 3000,
	["worker_poll_ms"] = 50,
	["max_receipt_bytes"] = 8192,
	["max_displays"] = 16,
	["actions"] = {
		["brightness_up"] = {
			["direction"] = 1,
			["macos_system"] = "BRIGHTNESS_UP",
			["karabiner_consumer"] = "display_brightness_increment",
			["linux_key"] = "XF86MonBrightnessUp",
			["linux_code"] = 225,
		},
		["brightness_down"] = {
			["direction"] = -1,
			["macos_system"] = "BRIGHTNESS_DOWN",
			["karabiner_consumer"] = "display_brightness_decrement",
			["linux_key"] = "XF86MonBrightnessDown",
			["linux_code"] = 224,
		},
	},
	["linux_program"] = "brightnessctl",
	["linux_class"] = "backlight",
}
