#!/usr/bin/env bash
# tools/dev/install-hammerspoon.sh

# ==============================================================================
# MODULE: Hammerspoon dev-bootstrap installer
# DESCRIPTION:
# Configures stock Hammerspoon to boot the Ergopti+ driver directly from this
# repo clone, with zero copying.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"

while [ "${REPO_ROOT}" != "/" ] && [ ! -f "${REPO_ROOT}/static/ergopti_plus/macos/init.lua" ]; do
	REPO_ROOT="$(cd "${REPO_ROOT}/.." && pwd)"
done

DRIVER_DIR="${REPO_ROOT}/static/ergopti_plus/macos"
HS_CONFIG_DIR="${HOME}/.hammerspoon"
HS_INIT="${HS_CONFIG_DIR}/init.lua"
XDG_HS_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/hammerspoon"
XDG_HS_INIT="${XDG_HS_CONFIG_DIR}/init.lua"

if [ ! -f "${DRIVER_DIR}/init.lua" ]; then
	echo "ERROR: cannot find Ergopti+ driver at ${DRIVER_DIR}/init.lua" >&2
	echo "       expected to find repo root containing static/ergopti_plus/macos/init.lua" >&2
	exit 1
fi

if [ ! -d "/Applications/Hammerspoon.app" ]; then
	echo "WARNING: Hammerspoon.app not found in /Applications."
	echo "         Download stock Hammerspoon from https://www.hammerspoon.org/"
	echo "         before the bootstrap will be picked up."
	echo
fi

backup_init_if_needed() {
	local init_path="$1"

	if [ -f "${init_path}" ]; then
		if grep -q "Ergopti+ dev bootstrap" "${init_path}" 2>/dev/null \
			&& grep -q "${DRIVER_DIR}" "${init_path}" 2>/dev/null; then
			echo "Existing bootstrap already points at this clone — refreshing in place (${init_path})."
		else
			local backup_path="${init_path}.backup.$(date -u +%Y%m%dT%H%M%SZ)"
			mv "${init_path}" "${backup_path}"
			echo "Previous Hammerspoon init backed up to:"
			echo "  ${backup_path}"
		fi
	fi
}

write_bootstrap_init() {
	local init_path="$1"

	cat > "${init_path}" <<EOF
-- ${init_path}
-- Ergopti+ dev bootstrap (auto-generated by tools/dev/install-hammerspoon.sh)
-- Edits to this file will be overwritten the next time the installer runs.
-- To revert: delete this file and rename the most recent init.lua.backup.* back.

local DRIVER = "${DRIVER_DIR}"

package.path = DRIVER .. "/?.lua;" .. DRIVER .. "/?/init.lua;" .. package.path

-- One-keypress dev reload. Bound BEFORE the driver loads so a broken driver
-- can still be reloaded after editing the offending file.
hs.hotkey.bind({ "cmd", "ctrl" }, "R", function()
	hs.reload()
end)

dofile(DRIVER .. "/init.lua")
EOF
}

mkdir -p "${HS_CONFIG_DIR}" "${XDG_HS_CONFIG_DIR}"

backup_init_if_needed "${HS_INIT}"
backup_init_if_needed "${XDG_HS_INIT}"

write_bootstrap_init "${HS_INIT}"
write_bootstrap_init "${XDG_HS_INIT}"

echo "Wrote bootstrap to ${HS_INIT}"
echo "Wrote bootstrap to ${XDG_HS_INIT}"
echo "  → delegates to ${DRIVER_DIR}/init.lua"
echo "  → Cmd+Ctrl+R triggers hs.reload() during dev"

# Old setups may force Hammerspoon to a stale config path via MJConfigFile.
# Pin it to the freshly generated bootstrap and clear MJConfigDir override.
if command -v defaults >/dev/null 2>&1; then
	defaults write org.hammerspoon.Hammerspoon MJConfigFile "${HS_INIT}" >/dev/null 2>&1 || true
	defaults delete org.hammerspoon.Hammerspoon MJConfigDir >/dev/null 2>&1 || true
	echo "  → normalized org.hammerspoon.Hammerspoon MJConfigFile to ${HS_INIT}"
fi

if command -v hs >/dev/null 2>&1; then
	echo
	echo "Triggering hs.reload() via the hs CLI…"
	hs -c "hs.reload()" >/dev/null 2>&1 || true
	echo "Done. Watch the Hammerspoon Console (menubar > Console) for boot logs."
else
	echo
	echo "Hammerspoon CLI not installed — open Hammerspoon's menubar > Console,"
	echo "then File > Install Command Line Tool to enable auto-reload next time."
	echo "For now: click 'Reload Config' in the Hammerspoon menubar manually."
fi
