; ui/menu/menu_actions.ahk

; ==============================================================================
; MODULE: Tray Menu / Misc Actions
; DESCRIPTION:
; Standalone tray actions: metrics-frequency setter, open-personal-shortcuts, and the log-folder / today-log / error-log openers, with the personal-shortcuts file template.
;
; Split out of ui/tray_menu.ahk (the module split). tray_menu.ahk remains the module
; index: it declares the shared menu globals and #Include-s this file. Every
; function here is hoisted into the global namespace, so load order across the
; menu/*.ahk files is irrelevant.
; ==============================================================================




; Returns a menu callback bound to a specific check interval (in seconds).
; Defined here rather than inline inside the menu builder so AHK captures the
; value at call time — fat-arrow closures defined inside the loop would all
; share the same loop-variable reference and persist only the last preset.
_MakeFreqSetter(Seconds) {
	return (*) => Updater_SetCheckInterval(Seconds)
}


; Opens personal_shortcuts.ahk in Notepad. Same function the gesture binding
; uses (modules/gestures.ahk:GestureEditPersonalShortcuts), but kept callable
; from the tray menu so the user has both entry points.
OpenPersonalShortcuts(*) {
	Path := ScriptInformation["PersonalAhkPath"]
	if !EnsurePersonalShortcutsFile(Path, false) {
		ConfigReportPersistenceFailure("the personal shortcuts bootstrap")
		return false
	}
	try {
		Run('notepad.exe "' . Path . '"')
		return true
	} catch as Err {
		try LoggerError("Menu", "Could not open personal shortcuts at '{1}': {2}.", Path, Err.Message)
		return false
	}
}

; The three log rows of the Debug menu, shared with the gesture and shortcut
; actions. The work lives in ui/log_openers.ahk, which asks the logger for every
; path at the moment of the click; three copies of the old
; <ConfigDir>\autohotkey\logs\ formula used to live here.

OpenLogsFolder(*) {
	return LogOpeners_OpenFolder()
}

OpenTodayLog(*) {
	return LogOpeners_OpenTodayLog()
}

OpenErrorLog(*) {
	return LogOpeners_OpenTodayErrors()
}

; Minimal template for personal_shortcuts.ahk — created on first launch so the
; user has a starter file with the canonical header. The header below is the
; same one the user is expected to keep at the top of their personal file, so
; both views stay perfectly aligned across ErgoptiPlus updates.
PersonalShortcutsTemplate() {
	return "; personal_shortcuts.ahk`n"
	. ";`n"
	. "; ==============================================================================`n"
	. "; MODULE: Personal Shortcuts`n"
	. "; DESCRIPTION:`n"
	. "; User-defined hotkeys layered on top of the ErgoptiPlus driver. Loaded into`n"
	. "; the driver via a forwarding stub generated by EnsurePersonalShortcutsFile, so`n"
	. "; this file lives at <ConfigDirPath>/personal_shortcuts.ahk and survives`n"
	. "; ErgoptiPlus updates without any manual copying.`n"
	. ";`n"
	. "; FEATURES & RATIONALE:`n"
	. "; 1. Toggle-gated bindings — every binding is wrapped in`n"
	. ';    #HotIf PersonalFeatureEnabled(' . '"' . '<Name>' . '"' . ') so the matching' . "`n"
	. ";    tray-menu checkbox in « 🎯 Raccourcis » → « Raccourcis personnels » fully controls`n"
	. ";    whether the binding fires, with persistence in the configuration INI.`n"
	. "; 2. Two-section layout — every feature is registered in section 1 and bound`n"
	. ";    (along with any helper functions it needs) in section 2 with matching`n"
	. ";    subsection numbering. The at-a-glance roster of available toggles and the`n"
	. ";    wiring of each one are each easy to scan in isolation.`n"
	. "; 3. AHK input level 2 is already set by the parent driver before this file is`n"
	. ";    included, so personal hotkeys override the layout's remappings without`n"
	. ";    this file needing its own #InputLevel directives.`n"
	. ";`n"
	. "; ADDING A FEATURE — drop a RegisterPersonalFeature call into section 1 and`n"
	. "; the matching #HotIf-gated binding into section 2. The toggle then appears`n"
	. "; in the tray under « 🎯 Raccourcis » → « Raccourcis personnels ». Example:`n"
	. ";`n"
	. ';     RegisterPersonalFeature(' . '"' . 'lock_screen' . '"' . ', true,' . "`n"
	. ';         ' . '"' . 'Lock the workstation with Ctrl + Alt + L' . '"' . ')' . "`n"
	. ";`n"
	. ';     #HotIf PersonalFeatureEnabled(' . '"' . 'lock_screen' . '"' . ')' . "`n"
	. ';     ^!l:: DllCall(' . '"' . 'user32\LockWorkStation' . '"' . ')' . "`n"
	. ";     #HotIf`n"
	. "; ==============================================================================`n"
	. "`n"
	. "#Requires AutoHotkey v2.0`n"
	. "`n"
	. "`n"
	. "`n"
	. "`n"
	. "`n"
	. "; =======================================`n"
	. "; =======================================`n"
	. "; ======= 1/ Feature Registration =======`n"
	. "; =======================================`n"
	. "; =======================================`n"
	. "`n"
	. "; (Add RegisterPersonalFeature calls here — see the example in the header.)`n"
	. "`n"
	. "`n"
	. "`n"
	. "`n"
	. "`n"
	. "; ==================================`n"
	. "; ==================================`n"
	. "; ======= 2/ Hotkey Bindings =======`n"
	. "; ==================================`n"
	. "; ==================================`n"
	. "`n"
	. "; (Add #HotIf-gated hotkey blocks here — see the example in the header.)`n"
	. "`n"
}
