--- _generated/action_catalogue.lua
--- AUTO-GENERATED from _shared/modules/actions/actions.toml.
--- DO NOT EDIT BY HAND — run `npm run codegen:action-catalogue` to refresh.

--- ==============================================================================
--- MODULE: Action Catalogue (macOS)
--- DESCRIPTION:
--- Every action the macOS driver offers, already filtered to its platform:
--- the picker order with heading levels and locale keys, the modifier-chord
--- block the driver expands from its own chord registry, and per-action
--- metadata (label key, parameter kind, confirmation, requirements). The
--- driver loads this table instead of parsing the shared TOML at runtime.
--- ==============================================================================

return {
	platform = "hs",
	sg_items = {
		{ kind = "action", id = "none" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_input" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.mouse_nav" },
		{ kind = "action", id = "left_click_toggle" },
		{ kind = "action", id = "right_click_toggle" },
		{ kind = "action", id = "lookup" },
		{ kind = "action", id = "system_app_switcher" },
		{ kind = "action", id = "app_previous" },
		{ kind = "action", id = "app_previous_screen" },
		{ kind = "action", id = "alt_tab_windows" },
		{ kind = "action", id = "alt_tab_monitor" },
		{ kind = "action", id = "cmd_shift_tab" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.edition" },
		{ kind = "action", id = "paste_plain" },
		{ kind = "action", id = "save" },
		{ kind = "action", id = "opt_backspace" },
		{ kind = "action", id = "opt_delete_fwd" },
		{ kind = "action", id = "cmd_backspace" },
		{ kind = "action", id = "cmd_delete_fwd" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.keys" },
		{ kind = "action", id = "enter" },
		{ kind = "action", id = "tab" },
		{ kind = "action", id = "escape" },
		{ kind = "action", id = "backspace" },
		{ kind = "action", id = "delete" },
		{ kind = "action", id = "send_key" },
		{ kind = "action", id = "send_shortcut" },
		{ kind = "action", id = "send_text" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_windows" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.tabs" },
		{ kind = "action", id = "tab_new" },
		{ kind = "action", id = "tab_close" },
		{ kind = "action", id = "tab_prev" },
		{ kind = "action", id = "tab_next" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.windows" },
		{ kind = "action", id = "win_app_prev" },
		{ kind = "action", id = "win_app_next" },
		{ kind = "action", id = "close_window" },
		{ kind = "action", id = "fullscreen" },
		{ kind = "action", id = "snap_left" },
		{ kind = "action", id = "snap_right" },
		{ kind = "action", id = "maximize" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.spaces" },
		{ kind = "action", id = "space_prev" },
		{ kind = "action", id = "space_next" },
		{ kind = "action", id = "space_prev_wrap" },
		{ kind = "action", id = "space_next_wrap" },
		{ kind = "action", id = "mission_control" },
		{ kind = "action", id = "app_expose" },
		{ kind = "action", id = "minimize_all" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_text" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.cursor" },
		{ kind = "action", id = "arrow_up" },
		{ kind = "action", id = "arrow_down" },
		{ kind = "action", id = "arrow_left" },
		{ kind = "action", id = "arrow_right" },
		{ kind = "action", id = "word_prev" },
		{ kind = "action", id = "word_next" },
		{ kind = "action", id = "line_up" },
		{ kind = "action", id = "line_down" },
		{ kind = "action", id = "line_start" },
		{ kind = "action", id = "line_end" },
		{ kind = "action", id = "para_prev" },
		{ kind = "action", id = "para_next" },
		{ kind = "action", id = "doc_start" },
		{ kind = "action", id = "doc_end" },
		{ kind = "action", id = "home" },
		{ kind = "action", id = "end" },
		{ kind = "action", id = "page_up" },
		{ kind = "action", id = "page_down" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.selection" },
		{ kind = "action", id = "sel_up" },
		{ kind = "action", id = "sel_down" },
		{ kind = "action", id = "sel_left" },
		{ kind = "action", id = "sel_right" },
		{ kind = "action", id = "sel_word_prev" },
		{ kind = "action", id = "sel_word_next" },
		{ kind = "action", id = "select_word" },
		{ kind = "action", id = "select_line" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.text_transform" },
		{ kind = "action", id = "selection_uppercase" },
		{ kind = "action", id = "selection_lowercase" },
		{ kind = "action", id = "selection_titlecase" },
		{ kind = "action", id = "uppercase_selection" },
		{ kind = "action", id = "titlecase_selection" },
		{ kind = "action", id = "wrap_selection" },
		{ kind = "action", id = "surround_parens" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.ai" },
		{ kind = "action", id = "llm_generate_prediction" },
		{ kind = "action", id = "llm_prompt_prediction" },
		{ kind = "action", id = "llm_predict_raw" },
		{ kind = "action", id = "llm_predict_basic" },
		{ kind = "action", id = "llm_predict_advanced" },
		{ kind = "action", id = "llm_predict_batch_advanced" },
		{ kind = "action", id = "llm_predict_rewrite" },
		{ kind = "action", id = "llm_predict_tone_familiar" },
		{ kind = "action", id = "llm_predict_tone_neutral" },
		{ kind = "action", id = "llm_predict_tone_formal" },
		{ kind = "action", id = "llm_predict_tone_very_formal" },
		{ kind = "action", id = "llm_predict_translate_en" },
		{ kind = "action", id = "llm_predict_translate_ja" },
		{ kind = "action", id = "llm_tone_more_formal" },
		{ kind = "action", id = "llm_tone_more_familiar" },
		{ kind = "action", id = "llm_tone_more_formal_cycle" },
		{ kind = "action", id = "llm_tone_more_familiar_cycle" },
		{ kind = "action", id = "llm_live_prompt_toggle" },
		{ kind = "action", id = "llm_screen_region" },
		{ kind = "action", id = "llm_screen_full" },
		{ kind = "action", id = "llm_screen_error" },
		{ kind = "action", id = "llm_translate_selection" },
		{ kind = "action", id = "llm_agent_selection" },
		{ kind = "action", id = "llm_agent_command" },
		{ kind = "action", id = "llm_agent_auto_toggle" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.modifier_chords" },
		{ kind = "modifier_chords", level = 2, group_key = "sg_actions.sg_order.header.modifier_chord_group" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_media" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.media" },
		{ kind = "action", id = "vol_up" },
		{ kind = "action", id = "vol_down" },
		{ kind = "action", id = "mute" },
		{ kind = "action", id = "brightness_up" },
		{ kind = "action", id = "brightness_down" },
		{ kind = "action", id = "track_play" },
		{ kind = "action", id = "track_next" },
		{ kind = "action", id = "track_prev" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.screenshot" },
		{ kind = "action", id = "screenshot_window_clipboard" },
		{ kind = "action", id = "screenshot_window_save" },
		{ kind = "action", id = "screenshot_region_clipboard" },
		{ kind = "action", id = "screenshot_region_save" },
		{ kind = "action", id = "screenshot_fullscreen_clipboard" },
		{ kind = "action", id = "screenshot_fullscreen_save" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_system" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.system" },
		{ kind = "action", id = "lock_screen" },
		{ kind = "action", id = "notification_center" },
		{ kind = "action", id = "spotlight" },
		{ kind = "action", id = "show_desktop" },
		{ kind = "action", id = "sleep_displays" },
		{ kind = "action", id = "toggle_dark_mode" },
		{ kind = "action", id = "mic_mute_toggle" },
		{ kind = "action", id = "clear_clipboard" },
		{ kind = "action", id = "center_mouse" },
		{ kind = "action", id = "open_app" },
		{ kind = "action", id = "run_program" },
		{ kind = "action", id = "quit_frontmost_app" },
		{ kind = "action", id = "force_quit_frontmost" },
		{ kind = "action", id = "empty_trash" },
		{ kind = "action", id = "eject_all_disks" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.file_actions" },
		{ kind = "action", id = "remove_quarantine_selection" },
		{ kind = "action", id = "make_executable_selection" },
		{ kind = "action", id = "open_terminal_here" },
		{ kind = "action", id = "new_text_file_here" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.system_actions" },
		{ kind = "action", id = "screen_capture" },
		{ kind = "action", id = "screen_capture_instant" },
		{ kind = "action", id = "open_url" },
		{ kind = "action", id = "open_downloads" },
		{ kind = "action", id = "open_file_manager" },
		{ kind = "action", id = "open_system_settings" },
		{ kind = "action", id = "pick_color" },
		{ kind = "action", id = "open_emoji_picker" },
		{ kind = "action", id = "activity_simulation" },
		{ kind = "action", id = "display_mirror_toggle" },
		{ kind = "action", id = "search_web" },
		{ kind = "action", id = "copy_selected_path" },
		{ kind = "action", id = "teleport_mouse" },
		{ kind = "action", id = "spotlight_mouse" },
		{ kind = "action", id = "toggle_capslock" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.tapholds" },
		{ kind = "action", id = "layer_on" },
		{ kind = "action", id = "layer_off" },
		{ kind = "action", id = "capsword" },
		{ kind = "action", id = "sticky_shift" },
		{ kind = "action", id = "sticky_ctrl" },
		{ kind = "action", id = "sticky_cmd" },
		{ kind = "action", id = "sticky_option" },
		{ kind = "action", id = "sticky_cmd_shift" },
		{ kind = "action", id = "sticky_cmd_option" },
		{ kind = "action", id = "sticky_cmd_ctrl" },
		{ kind = "action", id = "sticky_option_shift" },
		{ kind = "action", id = "sticky_option_ctrl" },
		{ kind = "action", id = "sticky_ctrl_shift" },
		{ kind = "action", id = "sticky_cmd_option_shift" },
		{ kind = "action", id = "sticky_cmd_option_ctrl" },
		{ kind = "action", id = "sticky_cmd_shift_ctrl" },
		{ kind = "action", id = "sticky_option_shift_ctrl" },
		{ kind = "action", id = "sticky_hyper" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_app" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.ui" },
		{ kind = "action", id = "open_metrics_typing" },
		{ kind = "action", id = "open_metrics_apps" },
		{ kind = "action", id = "open_hotstrings_editor" },
		{ kind = "action", id = "open_paths_editor" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.files" },
		{ kind = "action", id = "open_script_source" },
		{ kind = "action", id = "open_personal_shortcuts" },
		{ kind = "action", id = "open_personal_hotstrings" },
		{ kind = "action", id = "open_personal_info" },
		{ kind = "action", id = "open_config" },
		{ kind = "action", id = "open_logs_folder" },
		{ kind = "action", id = "open_today_log" },
		{ kind = "action", id = "open_error_log" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.script" },
		{ kind = "action", id = "script_pause_toggle" },
		{ kind = "action", id = "script_reload" },
		{ kind = "action", id = "script_save_reload" },
		{ kind = "action", id = "script_quit" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.debug" },
		{ kind = "action", id = "open_console" },
	},
	ax_items = { "tabs", "char", "char_sel", "line_arrow", "line_sel", "words", "words_sel", "windows", "spaces", "volume", "brightness", "tracks", "lines", "line_bounds", "paragraphs", "document" },
	actions = {
		["activity_simulation"] = { family = "sg", label_key = "sg_actions.activity_simulation" },
		["alt_tab_monitor"] = { family = "sg", label_key = "sg_actions.alt_tab_monitor" },
		["alt_tab_windows"] = { family = "sg", label_key = "sg_actions.alt_tab_windows" },
		["app_expose"] = { family = "sg", label_key = "sg_actions.app_expose" },
		["app_previous"] = { family = "sg", label_key = "sg_actions.app_previous" },
		["app_previous_screen"] = { family = "sg", label_key = "sg_actions.app_previous_screen" },
		["arrow_down"] = { family = "sg", label_key = "sg_actions.arrow_down" },
		["arrow_left"] = { family = "sg", label_key = "sg_actions.arrow_left" },
		["arrow_right"] = { family = "sg", label_key = "sg_actions.arrow_right" },
		["arrow_up"] = { family = "sg", label_key = "sg_actions.arrow_up" },
		["backspace"] = { family = "sg", label_key = "sg_actions.backspace" },
		["brightness"] = { family = "ax", label_key = "ax_actions.brightness" },
		["brightness_down"] = { family = "sg", label_key = "sg_actions.brightness_down" },
		["brightness_up"] = { family = "sg", label_key = "sg_actions.brightness_up" },
		["capsword"] = { family = "sg", label_key = "sg_actions.capsword" },
		["center_mouse"] = { family = "sg", label_key = "sg_actions.center_mouse" },
		["char"] = { family = "ax", label_key = "ax_actions.char" },
		["char_sel"] = { family = "ax", label_key = "ax_actions.char_sel" },
		["clear_clipboard"] = { family = "sg", label_key = "sg_actions.clear_clipboard" },
		["close_window"] = { family = "sg", label_key = "sg_actions.close_window" },
		["cmd_backspace"] = { family = "sg", label_key = "sg_actions.cmd_backspace" },
		["cmd_delete_fwd"] = { family = "sg", label_key = "sg_actions.cmd_delete_fwd" },
		["cmd_shift_tab"] = { family = "sg", label_key = "sg_actions.cmd_shift_tab" },
		["copy_selected_path"] = { family = "sg", label_key = "sg_actions.copy_selected_path" },
		["delete"] = { family = "sg", label_key = "sg_actions.delete" },
		["display_mirror_toggle"] = { family = "sg", label_key = "sg_actions.display_mirror_toggle" },
		["doc_end"] = { family = "sg", label_key = "sg_actions.doc_end" },
		["doc_start"] = { family = "sg", label_key = "sg_actions.doc_start" },
		["document"] = { family = "ax", label_key = "ax_actions.document" },
		["eject_all_disks"] = { family = "sg", label_key = "sg_actions.eject_all_disks" },
		["empty_trash"] = { family = "sg", label_key = "sg_actions.empty_trash", confirm = true },
		["end"] = { family = "sg", label_key = "sg_actions.end" },
		["enter"] = { family = "sg", label_key = "sg_actions.enter" },
		["escape"] = { family = "sg", label_key = "sg_actions.escape" },
		["force_quit_frontmost"] = { family = "sg", label_key = "sg_actions.force_quit_frontmost", confirm = true },
		["fullscreen"] = { family = "sg", label_key = "sg_actions.fullscreen" },
		["home"] = { family = "sg", label_key = "sg_actions.home" },
		["layer_off"] = { family = "sg", label_key = "sg_actions.layer_off" },
		["layer_on"] = { family = "sg", label_key = "sg_actions.layer_on" },
		["left_click_toggle"] = { family = "sg", label_key = "sg_actions.left_click_toggle" },
		["line_arrow"] = { family = "ax", label_key = "ax_actions.line_arrow" },
		["line_bounds"] = { family = "ax", label_key = "ax_actions.line_bounds" },
		["line_down"] = { family = "sg", label_key = "sg_actions.line_down" },
		["line_end"] = { family = "sg", label_key = "sg_actions.line_end" },
		["line_sel"] = { family = "ax", label_key = "ax_actions.line_sel" },
		["line_start"] = { family = "sg", label_key = "sg_actions.line_start" },
		["line_up"] = { family = "sg", label_key = "sg_actions.line_up" },
		["lines"] = { family = "ax", label_key = "ax_actions.lines" },
		["llm_agent_auto_toggle"] = { family = "sg", label_key = "sg_actions.llm_agent_auto_toggle" },
		["llm_agent_command"] = { family = "sg", label_key = "sg_actions.llm_agent_command" },
		["llm_agent_selection"] = { family = "sg", label_key = "sg_actions.llm_agent_selection" },
		["llm_generate_prediction"] = { family = "sg", label_key = "sg_actions.llm_generate_prediction" },
		["llm_live_prompt_toggle"] = { family = "sg", label_key = "sg_actions.llm_live_prompt_toggle", parameter = "llm_prompt" },
		["llm_predict_advanced"] = { family = "sg", label_key = "sg_actions.llm_predict_advanced" },
		["llm_predict_basic"] = { family = "sg", label_key = "sg_actions.llm_predict_basic" },
		["llm_predict_batch_advanced"] = { family = "sg", label_key = "sg_actions.llm_predict_batch_advanced" },
		["llm_predict_raw"] = { family = "sg", label_key = "sg_actions.llm_predict_raw" },
		["llm_predict_rewrite"] = { family = "sg", label_key = "sg_actions.llm_predict_rewrite" },
		["llm_predict_tone_familiar"] = { family = "sg", label_key = "sg_actions.llm_predict_tone_familiar" },
		["llm_predict_tone_formal"] = { family = "sg", label_key = "sg_actions.llm_predict_tone_formal" },
		["llm_predict_tone_neutral"] = { family = "sg", label_key = "sg_actions.llm_predict_tone_neutral" },
		["llm_predict_tone_very_formal"] = { family = "sg", label_key = "sg_actions.llm_predict_tone_very_formal" },
		["llm_predict_translate_en"] = { family = "sg", label_key = "sg_actions.llm_predict_translate_en" },
		["llm_predict_translate_ja"] = { family = "sg", label_key = "sg_actions.llm_predict_translate_ja" },
		["llm_prompt_prediction"] = { family = "sg", label_key = "sg_actions.llm_prompt_prediction", parameter = "llm_prompt" },
		["llm_screen_error"] = { family = "sg", label_key = "sg_actions.llm_screen_error", parameter = "llm_vision" },
		["llm_screen_full"] = { family = "sg", label_key = "sg_actions.llm_screen_full", parameter = "llm_vision" },
		["llm_screen_region"] = { family = "sg", label_key = "sg_actions.llm_screen_region", parameter = "llm_vision" },
		["llm_tone_more_familiar"] = { family = "sg", label_key = "sg_actions.llm_tone_more_familiar" },
		["llm_tone_more_familiar_cycle"] = { family = "sg", label_key = "sg_actions.llm_tone_more_familiar_cycle" },
		["llm_tone_more_formal"] = { family = "sg", label_key = "sg_actions.llm_tone_more_formal" },
		["llm_tone_more_formal_cycle"] = { family = "sg", label_key = "sg_actions.llm_tone_more_formal_cycle" },
		["llm_translate_selection"] = { family = "sg", label_key = "sg_actions.llm_translate_selection", parameter = "llm_language" },
		["lock_screen"] = { family = "sg", label_key = "sg_actions.lock_screen" },
		["lookup"] = { family = "sg", label_key = "sg_actions.lookup" },
		["make_executable_selection"] = { family = "sg", label_key = "sg_actions.make_executable_selection" },
		["maximize"] = { family = "sg", label_key = "sg_actions.maximize" },
		["mic_mute_toggle"] = { family = "sg", label_key = "sg_actions.mic_mute_toggle" },
		["minimize_all"] = { family = "sg", label_key = "sg_actions.minimize_all" },
		["mission_control"] = { family = "sg", label_key = "sg_actions.mission_control" },
		["mute"] = { family = "sg", label_key = "sg_actions.mute" },
		["new_text_file_here"] = { family = "sg", label_key = "sg_actions.new_text_file_here" },
		["none"] = { family = "sg", label_key = "sg_actions.none" },
		["notification_center"] = { family = "sg", label_key = "sg_actions.notification_center" },
		["open_app"] = { family = "sg", label_key = "sg_actions.open_app", parameter = "app" },
		["open_config"] = { family = "sg", label_key = "sg_actions.open_config" },
		["open_console"] = { family = "sg", label_key = "sg_actions.open_console" },
		["open_downloads"] = { family = "sg", label_key = "sg_actions.open_downloads" },
		["open_emoji_picker"] = { family = "sg", label_key = "sg_actions.open_emoji_picker" },
		["open_error_log"] = { family = "sg", label_key = "sg_actions.open_error_log" },
		["open_file_manager"] = { family = "sg", label_key = "sg_actions.open_file_manager" },
		["open_hotstrings_editor"] = { family = "sg", label_key = "sg_actions.open_hotstrings_editor" },
		["open_logs_folder"] = { family = "sg", label_key = "sg_actions.open_logs_folder" },
		["open_metrics_apps"] = { family = "sg", label_key = "sg_actions.open_metrics_apps" },
		["open_metrics_typing"] = { family = "sg", label_key = "sg_actions.open_metrics_typing" },
		["open_paths_editor"] = { family = "sg", label_key = "sg_actions.open_paths_editor" },
		["open_personal_hotstrings"] = { family = "sg", label_key = "sg_actions.open_personal_hotstrings" },
		["open_personal_info"] = { family = "sg", label_key = "sg_actions.open_personal_info" },
		["open_personal_shortcuts"] = { family = "sg", label_key = "sg_actions.open_personal_shortcuts" },
		["open_script_source"] = { family = "sg", label_key = "sg_actions.open_script_source" },
		["open_system_settings"] = { family = "sg", label_key = "sg_actions.open_system_settings" },
		["open_terminal_here"] = { family = "sg", label_key = "sg_actions.open_terminal_here" },
		["open_today_log"] = { family = "sg", label_key = "sg_actions.open_today_log" },
		["open_url"] = { family = "sg", label_key = "sg_actions.open_url", parameter = "url" },
		["opt_backspace"] = { family = "sg", label_key = "sg_actions.opt_backspace" },
		["opt_delete_fwd"] = { family = "sg", label_key = "sg_actions.opt_delete_fwd" },
		["page_down"] = { family = "sg", label_key = "sg_actions.page_down" },
		["page_up"] = { family = "sg", label_key = "sg_actions.page_up" },
		["para_next"] = { family = "sg", label_key = "sg_actions.para_next" },
		["para_prev"] = { family = "sg", label_key = "sg_actions.para_prev" },
		["paragraphs"] = { family = "ax", label_key = "ax_actions.paragraphs" },
		["paste_plain"] = { family = "sg", label_key = "sg_actions.paste_plain" },
		["pick_color"] = { family = "sg", label_key = "sg_actions.pick_color" },
		["quit_frontmost_app"] = { family = "sg", label_key = "sg_actions.quit_frontmost_app" },
		["remove_quarantine_selection"] = { family = "sg", label_key = "sg_actions.remove_quarantine_selection", confirm = true },
		["right_click_toggle"] = { family = "sg", label_key = "sg_actions.right_click_toggle" },
		["run_program"] = { family = "sg", label_key = "sg_actions.run_program", parameter = "program" },
		["save"] = { family = "sg", label_key = "sg_actions.save" },
		["screen_capture"] = { family = "sg", label_key = "sg_actions.screen_capture" },
		["screen_capture_instant"] = { family = "sg", label_key = "sg_actions.screen_capture_instant" },
		["screenshot_fullscreen_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_fullscreen_clipboard" },
		["screenshot_fullscreen_save"] = { family = "sg", label_key = "sg_actions.screenshot_fullscreen_save" },
		["screenshot_region_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_region_clipboard" },
		["screenshot_region_save"] = { family = "sg", label_key = "sg_actions.screenshot_region_save" },
		["screenshot_window_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_window_clipboard" },
		["screenshot_window_save"] = { family = "sg", label_key = "sg_actions.screenshot_window_save" },
		["script_pause_toggle"] = { family = "sg", label_key = "sg_actions.script_pause_toggle" },
		["script_quit"] = { family = "sg", label_key = "sg_actions.script_quit" },
		["script_reload"] = { family = "sg", label_key = "sg_actions.script_reload" },
		["script_save_reload"] = { family = "sg", label_key = "sg_actions.script_save_reload" },
		["search_web"] = { family = "sg", label_key = "sg_actions.search_web", parameter = "search_url" },
		["sel_down"] = { family = "sg", label_key = "sg_actions.sel_down" },
		["sel_left"] = { family = "sg", label_key = "sg_actions.sel_left" },
		["sel_right"] = { family = "sg", label_key = "sg_actions.sel_right" },
		["sel_up"] = { family = "sg", label_key = "sg_actions.sel_up" },
		["sel_word_next"] = { family = "sg", label_key = "sg_actions.sel_word_next" },
		["sel_word_prev"] = { family = "sg", label_key = "sg_actions.sel_word_prev" },
		["select_line"] = { family = "sg", label_key = "sg_actions.select_line" },
		["select_word"] = { family = "sg", label_key = "sg_actions.select_word" },
		["selection_lowercase"] = { family = "sg", label_key = "sg_actions.selection_lowercase" },
		["selection_titlecase"] = { family = "sg", label_key = "sg_actions.selection_titlecase" },
		["selection_uppercase"] = { family = "sg", label_key = "sg_actions.selection_uppercase" },
		["send_key"] = { family = "sg", label_key = "sg_actions.send_key", parameter = "key" },
		["send_shortcut"] = { family = "sg", label_key = "sg_actions.send_shortcut", parameter = "shortcut" },
		["send_text"] = { family = "sg", label_key = "sg_actions.send_text", parameter = "text" },
		["show_desktop"] = { family = "sg", label_key = "sg_actions.show_desktop" },
		["sleep_displays"] = { family = "sg", label_key = "sg_actions.sleep_displays" },
		["snap_left"] = { family = "sg", label_key = "sg_actions.snap_left" },
		["snap_right"] = { family = "sg", label_key = "sg_actions.snap_right" },
		["space_next"] = { family = "sg", label_key = "sg_actions.space_next" },
		["space_next_wrap"] = { family = "sg", label_key = "sg_actions.space_next_wrap" },
		["space_prev"] = { family = "sg", label_key = "sg_actions.space_prev" },
		["space_prev_wrap"] = { family = "sg", label_key = "sg_actions.space_prev_wrap" },
		["spaces"] = { family = "ax", label_key = "ax_actions.spaces" },
		["spotlight"] = { family = "sg", label_key = "sg_actions.spotlight" },
		["spotlight_mouse"] = { family = "sg", label_key = "sg_actions.spotlight_mouse" },
		["sticky_cmd"] = { family = "sg", label_key = "sg_actions.sticky_cmd" },
		["sticky_cmd_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_cmd_ctrl" },
		["sticky_cmd_option"] = { family = "sg", label_key = "sg_actions.sticky_cmd_option" },
		["sticky_cmd_option_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_cmd_option_ctrl" },
		["sticky_cmd_option_shift"] = { family = "sg", label_key = "sg_actions.sticky_cmd_option_shift" },
		["sticky_cmd_shift"] = { family = "sg", label_key = "sg_actions.sticky_cmd_shift" },
		["sticky_cmd_shift_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_cmd_shift_ctrl" },
		["sticky_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_ctrl" },
		["sticky_ctrl_shift"] = { family = "sg", label_key = "sg_actions.sticky_ctrl_shift" },
		["sticky_hyper"] = { family = "sg", label_key = "sg_actions.sticky_hyper" },
		["sticky_option"] = { family = "sg", label_key = "sg_actions.sticky_option" },
		["sticky_option_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_option_ctrl" },
		["sticky_option_shift"] = { family = "sg", label_key = "sg_actions.sticky_option_shift" },
		["sticky_option_shift_ctrl"] = { family = "sg", label_key = "sg_actions.sticky_option_shift_ctrl" },
		["sticky_shift"] = { family = "sg", label_key = "sg_actions.sticky_shift" },
		["surround_parens"] = { family = "sg", label_key = "sg_actions.surround_parens" },
		["system_app_switcher"] = { family = "sg", label_key = "sg_actions.system_app_switcher" },
		["tab"] = { family = "sg", label_key = "sg_actions.tab" },
		["tab_close"] = { family = "sg", label_key = "sg_actions.tab_close" },
		["tab_new"] = { family = "sg", label_key = "sg_actions.tab_new" },
		["tab_next"] = { family = "sg", label_key = "sg_actions.tab_next" },
		["tab_prev"] = { family = "sg", label_key = "sg_actions.tab_prev" },
		["tabs"] = { family = "ax", label_key = "ax_actions.tabs" },
		["teleport_mouse"] = { family = "sg", label_key = "sg_actions.teleport_mouse" },
		["titlecase_selection"] = { family = "sg", label_key = "sg_actions.titlecase_selection" },
		["toggle_capslock"] = { family = "sg", label_key = "sg_actions.toggle_capslock" },
		["toggle_dark_mode"] = { family = "sg", label_key = "sg_actions.toggle_dark_mode" },
		["track_next"] = { family = "sg", label_key = "sg_actions.track_next" },
		["track_play"] = { family = "sg", label_key = "sg_actions.track_play" },
		["track_prev"] = { family = "sg", label_key = "sg_actions.track_prev" },
		["tracks"] = { family = "ax", label_key = "ax_actions.tracks" },
		["uppercase_selection"] = { family = "sg", label_key = "sg_actions.uppercase_selection" },
		["vol_down"] = { family = "sg", label_key = "sg_actions.vol_down" },
		["vol_up"] = { family = "sg", label_key = "sg_actions.vol_up" },
		["volume"] = { family = "ax", label_key = "ax_actions.volume" },
		["win_app_next"] = { family = "sg", label_key = "sg_actions.win_app_next" },
		["win_app_prev"] = { family = "sg", label_key = "sg_actions.win_app_prev" },
		["windows"] = { family = "ax", label_key = "ax_actions.windows" },
		["word_next"] = { family = "sg", label_key = "sg_actions.word_next" },
		["word_prev"] = { family = "sg", label_key = "sg_actions.word_prev" },
		["words"] = { family = "ax", label_key = "ax_actions.words" },
		["words_sel"] = { family = "ax", label_key = "ax_actions.words_sel" },
		["wrap_selection"] = { family = "sg", label_key = "sg_actions.wrap_selection", parameter = "wrap_pair" },
	},
	karabiner_aliases = {
		["alt_tab_apps"] = "app_previous",
		["alt_tab_apps_list"] = "app_previous",
		["cmd_tab"] = "app_previous",
		["cycle_windows_in_app"] = "win_app_next",
		["delete_fwd"] = "delete",
		["return"] = "enter",
	},
}
