--- _generated/hid_key_identity.lua
--- AUTO-GENERATED from _shared/data/keycodes/physical_keys.json.
--- DO NOT EDIT BY HAND — run `npm run codegen:hid-key-identity:hs` to refresh.

--- ==============================================================================
--- MODULE: HID Key Identity (macOS)
--- DESCRIPTION:
--- Every registry key by HID usage page and usage, with the macOS virtual
--- keycode the metrics store for it. `kc` is the same on every registry form;
--- a key whose keycode depends on the keyboard type carries one keycode per
--- form instead. modules/keylogger/physical_key_identity.lua owns the policy
--- that reads it.
--- ==============================================================================

return {
	forms = { "ansi", "iso" },
	pages = {
		[7] = {
			[4] = { code = "KeyA", kc = 0 },
			[5] = { code = "KeyB", kc = 11 },
			[6] = { code = "KeyC", kc = 8 },
			[7] = { code = "KeyD", kc = 2 },
			[8] = { code = "KeyE", kc = 14 },
			[9] = { code = "KeyF", kc = 3 },
			[10] = { code = "KeyG", kc = 5 },
			[11] = { code = "KeyH", kc = 4 },
			[12] = { code = "KeyI", kc = 34 },
			[13] = { code = "KeyJ", kc = 38 },
			[14] = { code = "KeyK", kc = 40 },
			[15] = { code = "KeyL", kc = 37 },
			[16] = { code = "KeyM", kc = 46 },
			[17] = { code = "KeyN", kc = 45 },
			[18] = { code = "KeyO", kc = 31 },
			[19] = { code = "KeyP", kc = 35 },
			[20] = { code = "KeyQ", kc = 12 },
			[21] = { code = "KeyR", kc = 15 },
			[22] = { code = "KeyS", kc = 1 },
			[23] = { code = "KeyT", kc = 17 },
			[24] = { code = "KeyU", kc = 32 },
			[25] = { code = "KeyV", kc = 9 },
			[26] = { code = "KeyW", kc = 13 },
			[27] = { code = "KeyX", kc = 7 },
			[28] = { code = "KeyY", kc = 16 },
			[29] = { code = "KeyZ", kc = 6 },
			[30] = { code = "Digit1", kc = 18 },
			[31] = { code = "Digit2", kc = 19 },
			[32] = { code = "Digit3", kc = 20 },
			[33] = { code = "Digit4", kc = 21 },
			[34] = { code = "Digit5", kc = 23 },
			[35] = { code = "Digit6", kc = 22 },
			[36] = { code = "Digit7", kc = 26 },
			[37] = { code = "Digit8", kc = 28 },
			[38] = { code = "Digit9", kc = 25 },
			[39] = { code = "Digit0", kc = 29 },
			[40] = { code = "Enter", kc = 36 },
			[41] = { code = "Escape", kc = 53 },
			[42] = { code = "Backspace", kc = 51 },
			[43] = { code = "Tab", kc = 48 },
			[44] = { code = "Space", kc = 49 },
			[45] = { code = "Minus", kc = 27 },
			[46] = { code = "Equal", kc = 24 },
			[47] = { code = "BracketLeft", kc = 33 },
			[48] = { code = "BracketRight", kc = 30 },
			[49] = { code = "Backslash", kc = 42 },
			[51] = { code = "Semicolon", kc = 41 },
			[52] = { code = "Quote", kc = 39 },
			[53] = { code = "Backquote", ansi = 50, iso = 10 },
			[54] = { code = "Comma", kc = 43 },
			[55] = { code = "Period", kc = 47 },
			[56] = { code = "Slash", kc = 44 },
			[57] = { code = "CapsLock", kc = 57 },
			[58] = { code = "F1", kc = 122 },
			[59] = { code = "F2", kc = 120 },
			[60] = { code = "F3", kc = 99 },
			[61] = { code = "F4", kc = 118 },
			[62] = { code = "F5", kc = 96 },
			[63] = { code = "F6", kc = 97 },
			[64] = { code = "F7", kc = 98 },
			[65] = { code = "F8", kc = 100 },
			[66] = { code = "F9", kc = 101 },
			[67] = { code = "F10", kc = 109 },
			[68] = { code = "F11", kc = 103 },
			[69] = { code = "F12", kc = 111 },
			[73] = { code = "Insert", kc = 114 },
			[74] = { code = "Home", kc = 115 },
			[75] = { code = "PageUp", kc = 116 },
			[76] = { code = "Delete", kc = 117 },
			[77] = { code = "End", kc = 119 },
			[78] = { code = "PageDown", kc = 121 },
			[79] = { code = "ArrowRight", kc = 124 },
			[80] = { code = "ArrowLeft", kc = 123 },
			[81] = { code = "ArrowDown", kc = 125 },
			[82] = { code = "ArrowUp", kc = 126 },
			[83] = { code = "NumLock", kc = 71 },
			[84] = { code = "NumpadDivide", kc = 75 },
			[85] = { code = "NumpadMultiply", kc = 67 },
			[86] = { code = "NumpadSubtract", kc = 78 },
			[87] = { code = "NumpadAdd", kc = 69 },
			[88] = { code = "NumpadEnter", kc = 76 },
			[89] = { code = "Numpad1", kc = 83 },
			[90] = { code = "Numpad2", kc = 84 },
			[91] = { code = "Numpad3", kc = 85 },
			[92] = { code = "Numpad4", kc = 86 },
			[93] = { code = "Numpad5", kc = 87 },
			[94] = { code = "Numpad6", kc = 88 },
			[95] = { code = "Numpad7", kc = 89 },
			[96] = { code = "Numpad8", kc = 91 },
			[97] = { code = "Numpad9", kc = 92 },
			[98] = { code = "Numpad0", kc = 82 },
			[99] = { code = "NumpadDecimal", kc = 65 },
			[100] = { code = "IntlBackslash", ansi = 10, iso = 50 },
			[101] = { code = "ContextMenu", kc = 110 },
			[224] = { code = "ControlLeft", kc = 59 },
			[225] = { code = "ShiftLeft", kc = 56 },
			[226] = { code = "AltLeft", kc = 58 },
			[227] = { code = "MetaLeft", kc = 55 },
			[228] = { code = "ControlRight", kc = 62 },
			[229] = { code = "ShiftRight", kc = 60 },
			[230] = { code = "AltRight", kc = 61 },
			[231] = { code = "MetaRight", kc = 54 },
		},
		[12] = {
			[226] = { code = "AudioVolumeMute", kc = 74 },
			[233] = { code = "AudioVolumeUp", kc = 72 },
			[234] = { code = "AudioVolumeDown", kc = 73 },
		},
	},
}
