# ====================
# ====================
# ======= Meta =======
# ====================
# ====================

[_meta]
color = "#fb8c00"
delay = 0.5
show_tooltip = true
description = { fr = "Réduction des SFBs", en = "SFB reduction", de = "SFB-Reduktion", es = "Reducción de SFBs", zh = "SFB 减少" }
sections_order = ["comma", "-", "ecirc", "egrave", "-", "bu", "ie"]



# =========================
# ===== Meta.Sections =====
# =========================

[_meta.sections]
bu = { fr = "À + ★/U corrige 2 SFBs : à★ = bu et àu = ub", en = "À + ★/U fixes 2 SFBs: à★ = bu and àu = ub", de = "À + ★/U korrigiert 2 SFBs: à★ = bu und àu = ub", es = "À + ★/U corrige 2 SFBs: à★ = bu y àu = ub", zh = "À + ★/U 修正 2 个 SFB：à★ = bu 和 àu = ub" }
comma = { fr = "Virgule + Consonne corrige de très nombreux SFBs : ,t = pt, ,d= ds, ,p = xp, …", en = "Comma + Consonant fixes many SFBs: ,t = pt, ,d = ds, ,p = xp, …", de = "Komma + Konsonant korrigiert viele SFBs: ,t = pt, ,d = ds, ,p = xp, …", es = "Coma + Consonante corrige muchos SFBs: ,t = pt, ,d = ds, ,p = xp, …", zh = "逗号 + 辅音修正大量 SFB：,t = pt，,d = ds，,p = xp，…" }
ecirc = { fr = "Ê + touche sur la main gauche corrige 4 SFBs : êé = oe, éê = eo, ê, = u, et ê. = u.", en = "Ê + left-hand key fixes 4 SFBs: êé = oe, éê = eo, ê, = u, and ê. = u.", de = "Ê + Linke-Hand-Taste korrigiert 4 SFBs: êé = oe, éê = eo, ê, = u, und ê. = u.", es = "Ê + tecla de la mano izquierda corrige 4 SFBs: êé = oe, éê = eo, ê, = u, y ê. = u.", zh = "Ê + 左手键修正 4 个 SFB：êé = oe，éê = eo，ê, = u，ê. = u" }
egrave = { fr = "È + touche Y corrige 2 SFBs : èy = aî et yè = â", en = "È + Y key fixes 2 SFBs: èy = aî and yè = â", de = "È + Y-Taste korrigiert 2 SFBs: èy = aî und yè = â", es = "È + tecla Y corrige 2 SFBs: èy = aî y yè = â", zh = "È + Y 键修正 2 个 SFB：èy = aî 和 yè = â" }
ie = { fr = "À + É corrige 2 SFBs : éà = ié et àé = éi", en = "À + É fixes 2 SFBs: éà = ié and àé = éi", de = "À + É korrigiert 2 SFBs: éà = ié und àé = éi", es = "À + É corrige 2 SFBs: éà = ié y àé = éi", zh = "À + É 修正 2 个 SFB：éà = ié 和 àé = éi" }





# ==================
# ==================
# ======= Bu =======
# ==================
# ==================

[[bu]]
"e mà★" = { output = "e mise à jour", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"es mà★" = { output = "es mises à jour", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"il a mà★" = { output = "il a mis à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"la mà★" = { output = "la mise à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"ma mà★" = { output = "ma mise à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"mià★" = { output = "mise à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"mà★" = { output = "mettre à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"pià★" = { output = "pièce jointe", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"ta mà★" = { output = "ta mise à jour", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"tà★" = { output = "toujours", is_word = true, auto_expand = true, is_case_sensitive = false, final_result = false }
"àu" = { output = "ub", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"à★" = { output = "bu", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }





# =====================
# =====================
# ======= Comma =======
# =====================
# =====================

[[comma]]
",d" = { output = "ds", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",f" = { output = "fl", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",g" = { output = "gl", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",h" = { output = "ph", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",l" = { output = "cl", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",m" = { output = "ms", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",n" = { output = "nl", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",p" = { output = "xp", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",q" = { output = "qu’", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",r" = { output = "rq", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",t" = { output = "pt", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",v" = { output = "dv", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
",z" = { output = "bj", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }





# =====================
# =====================
# ======= Ecirc =======
# =====================
# =====================

[[ecirc]]
"éê" = { output = "eo", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"ê," = { output = "u,", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"ê." = { output = "u.", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"êé" = { output = "oe", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }





# ======================
# ======================
# ======= Egrave =======
# ======================
# ======================

[[egrave]]
"yè" = { output = "â", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"èy" = { output = "aî", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }





# ==================
# ==================
# ======= Ie =======
# ==================
# ==================

[[ie]]
"ié★" = { output = "ébu", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"àé" = { output = "éi", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }
"éà" = { output = "ié", is_word = false, auto_expand = true, is_case_sensitive = false, final_result = false }