// Sources/ErgoptiPlus/ManagedBootstrapPolicy.generated.swift
// Generated by tools/codegen/codegen-managed-bootstrap.cjs; do not edit.
// Sources: _shared/modules/llm/managed_ollama_bootstrap.json and network/proxy_policy.json.

enum ManagedNetworkBootstrapPolicy {
	static let maximumMetadataBytes = 1048576
	static let hmacDomain = "ERGOPTI_NATIVE_NETWORK_BOOTSTRAP_V1\n"
	static let trustEnvironment = ["SSL_CERT_FILE","SSL_CERT_DIR"]
	static let allowedEnvironment = ["http_proxy","HTTP_PROXY","https_proxy","HTTPS_PROXY","all_proxy","ALL_PROXY","no_proxy","NO_PROXY","SSL_CERT_FILE","SSL_CERT_DIR"]
	static let maximumProxyBytes = 65536
	static let maximumCertificateBytes = 16777216
	static let maximumCertificateFiles = 1024
}
