// Sources/ErgoptiPlus/WindowTitles.generated.swift
// Generated by tools/codegen/codegen-window-titles.cjs; do not edit.
// Source: _shared/ui/apps.manifest.json window_title.

/// Native launcher captions use the same policy as all three runtime hosts.
enum WindowTitles {
	/// Composes a native caption from an already-translated, brandless label.
	static func compose(_ label: String? = nil) -> String {
		let prefix = "ErgoptiPlus"
		let separator = " — "
		guard let label, !label.isEmpty else { return prefix }
		guard !prefix.isEmpty else { return label }
		return prefix + separator + label
	}
}
