-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/brands.toml
local keymap = require("keymap")

keymap.add("autohotkey", "AutoHotkey", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("citroen", "Citroën", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("chatgpt", "ChatGPT", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("insee", "INSEE", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("latex", "LaTeX", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("lualatex", "LuaLaTeX", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("mbti", "MBTI", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("nasa", "NASA", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("nlp", "NLP", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("optimot", "Optimot", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("onedrive", "OneDrive", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("onenote", "OneNote", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("outlook", "Outlook", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("powerbi", "PowerBI", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("pnl", "PNL", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("powerpoint", "PowerPoint", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("sharepoint", "SharePoint", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("vscode", "VSCode", {is_word = true, auto_expand = false, is_case_sensitive = true})