-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/brands.toml
local keymap = require("keymap")

keymap.add("autohotkey", "AutoHotkey", false, false, true)
keymap.add("citroen", "Citroën", false, false, true)
keymap.add("chatgpt", "ChatGPT", false, false, true)
keymap.add("insee", "INSEE", false, false, true)
keymap.add("latex", "LaTeX", false, false, true)
keymap.add("lualatex", "LuaLaTeX", false, false, true)
keymap.add("mbti", "MBTI", false, false, true)
keymap.add("nasa", "NASA", false, false, true)
keymap.add("nlp", "NLP", false, false, true)
keymap.add("optimot", "Optimot", false, false, true)
keymap.add("onedrive", "OneDrive", false, false, true)
keymap.add("onenote", "OneNote", false, false, true)
keymap.add("outlook", "Outlook", false, false, true)
keymap.add("powerbi", "PowerBI", false, false, true)
keymap.add("pnl", "PNL", false, false, true)
keymap.add("powerpoint", "PowerPoint", false, false, true)
keymap.add("sharepoint", "SharePoint", false, false, true)
keymap.add("vscode", "VSCode", false, false, true)