-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/brands.toml
local keymap = require("keymap")

keymap.add("autohotkey", "AutoHotkey", false)
keymap.add("citroen", "Citroën", false)
keymap.add("chatgpt", "ChatGPT", false)
keymap.add("insee", "INSEE", false)
keymap.add("latex", "LaTeX", false)
keymap.add("lualatex", "LuaLaTeX", false)
keymap.add("mbti", "MBTI", false)
keymap.add("nasa", "NASA", false)
keymap.add("nlp", "NLP", false)
keymap.add("optimot", "Optimot", false)
keymap.add("onedrive", "OneDrive", false)
keymap.add("onenote", "OneNote", false)
keymap.add("outlook", "Outlook", false)
keymap.add("powerbi", "PowerBI", false)
keymap.add("pnl", "PNL", false)
keymap.add("powerpoint", "PowerPoint", false)
keymap.add("sharepoint", "SharePoint", false)
keymap.add("vscode", "VSCode", false)