-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/errors.toml
local keymap = require("keymap")

keymap.add("(_", "( ", false, true)
keymap.add(")_", ") ", false, true)
keymap.add("+_", "+ ", false, true)
keymap.add("#_", "# ", false, true)
keymap.add("$_", "$ ", false, true)
keymap.add("=_", "= ", false, true)
keymap.add("[_", "[ ", false, true)
keymap.add("]_", "] ", false, true)
keymap.add("~_", "~ ", false, true)
keymap.add("*_", "* ", false, true)
keymap.add("OUi", "Oui", false, true)
keymap.add("eua", "eau", true, true)
keymap.add("aeu", "eau", true, true)
keymap.add("oiu", "oui", true, true)
keymap.add("poru", "pour", false, true)
keymap.add("acceuil", "accueil", false, true)