-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/errors.toml
local keymap = require("keymap")

keymap.add("(_", "( ", false)
keymap.add(")_", ") ", false)
keymap.add("+_", "+ ", false)
keymap.add("#_", "# ", false)
keymap.add("$_", "$ ", false)
keymap.add("=_", "= ", false)
keymap.add("[_", "[ ", false)
keymap.add("]_", "] ", false)
keymap.add("~_", "~ ", false)
keymap.add("*_", "* ", false)
keymap.add("OUi", "Oui", false)
keymap.add("eua", "eau", true)
keymap.add("aeu", "eau", true)
keymap.add("oiu", "oui", true)
keymap.add("poru", "pour", false)
keymap.add("acceuil", "accueil", false)