-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/magic.toml
local keymap = require("keymap")

keymap.add("ae★", "æ", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("oe★", "œ", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("1er★", "premier", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("1ere★", "première", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("2e★", "deuxième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("3e★", "troisième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("4e★", "quatrième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("5e★", "cinquième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("6e★", "sixième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("7e★", "septième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("8e★", "huitième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("9e★", "neuvième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("10e★", "dixième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("11e★", "onzième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("12e★", "douzième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("20e★", "vingtième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("100e★", "centième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("1000e★", "millième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("2s★", "2 secondes", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("//★", "rapport", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("+m★", "meilleur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("a★", "ainsi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("abr★", "abréviation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("actu★", "actualité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("add★", "addresse", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("admin★", "administrateur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("afr★", "à faire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ah★", "aujourd’hui", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ahk★", "AutoHotkey", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("ajd★", "aujourd’hui", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("algo★", "algorithme", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("alpha★", "alphabétique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("amé★", "amélioration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("amélio★", "amélioration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("anc★", "ancien", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ano★", "anomalie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("anniv★", "anniversaire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("apm★", "après-midi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("apad★", "à partir de", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("app★", "application", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("appart★", "appartement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("appli★", "application", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("approx★", "approximation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("archi★", "architecture", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("asso★", "association", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("asap★", "le plus rapidement possible", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("atd★", "attend", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("att★", "attention", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("aud★", "aujourd’hui", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("aug★", "augmentation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("auj★", "aujourd’hui", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("auto★", "automatique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("av★", "avant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("avv★", "avez-vous", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("avvd★", "avez-vous déjà", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("b★", "bonjour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bc★", "because", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bcp★", "beaucoup", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bdd★", "base de données", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bdds★", "bases de données", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bea★", "beaucoup", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bec★", "because", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bib★", "bibliographie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("biblio★", "bibliographie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bjr★", "bonjour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("brain★", "brainstorming", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("br★", "bonjour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bsr★", "bonsoir", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bv★", "bravo", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bvn★", "bienvenue", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bwe★", "bon week-end", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("bwk★", "bon week-end", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("c★", "c’est", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cad★", "c’est-à-dire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("camp★", "campagne", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("carac★", "caractère", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("caract★", "caractéristique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cb★", "combien", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cc★", "copier-coller", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ccé★", "copié-collé", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ccl★", "conclusion", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cdg★", "Charles de Gaulle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cdt★", "cordialement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("certif★", "certification", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("chg★", "charge", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("chap★", "chapitre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("chr★", "chercher", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ci★", "ci-joint", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cj★", "ci-joint", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("coeff★", "coefficient", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cog★", "cognition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cogv★", "cognitive", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("comp★", "comprendre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cond★", "condition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("conds★", "conditions", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("config★", "configuration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("chgt★", "changement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cnp★", "ce n’est pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("contrib★", "contribution", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("couv★", "couverture", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cpd★", "cependant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cr★", "compte-rendu", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ct★", "c’était", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ctb★", "c’est très bien", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cv★", "ça va ?", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("cvt★", "ça va toi ?", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ctc★", "Est-ce que cela te convient ?", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("cvc★", "Est-ce que cela vous convient ?", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("dac★", "d’accord", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ddl★", "download", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dé★", "déjà", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dê★", "d’être", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("déc★", "décembre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dec★", "décembre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dedt★", "d’emploi du temps", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("déf★", "définition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("def★", "définition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("défs★", "définitions", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("démo★", "démonstration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("demo★", "démonstration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dep★", "département", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("deux★", "deuxième", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("desc★", "description", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dev★", "développeur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dév★", "développeur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("devt★", "développement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dico★", "dictionnaire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("diff★", "différence", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("difft★", "différent", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dim★", "dimension", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dimi★", "diminution", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("la dispo★", "la disposition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ta dispo★", "ta disposition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("une dispo★", "une disposition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dispo★", "disponible", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("distri★", "distributeur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("distrib★", "distributeur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dj★", "déjà", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dm★", "donne-moi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("la doc★", "la documentation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("une doc★", "une documentation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("doc★", "document", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("docs★", "documents", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dp★", "de plus", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dsl★", "désolé", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dtm★", "détermine", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("dvlp★", "développe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("e★", "est", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("echant★", "échantillon", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("echants★", "échantillons", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eco★", "économie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ecq★", "est-ce que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("edt★", "emploi du temps", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eef★", "en effet", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("elt★", "élément", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("elts★", "éléments", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eo★", "en outre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("enc★", "encore", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eng★", "english", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("enft★", "en fait", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ens★", "ensemble", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ent★", "entreprise", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("env★", "environ", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ep★", "épisode", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eps★", "épisodes", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eq★", "équation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ety★", "étymologie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("eve★", "événement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("evtl★", "éventuel", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("evtle★", "éventuelle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("evtlt★", "éventuellement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ex★", "exemple", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("exo★", "exercice", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("exp★", "expérience", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("expo★", "exposition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("é★", "écart", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("éco★", "économie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ém★", "écris-moi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("éq★", "équation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ê★", "être", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("êt★", "es-tu", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("f★", "faire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fam★", "famille", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fb★", "Facebook", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fc★", "fonction", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fct★", "fonction", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fea★", "feature", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("feat★", "feature", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fev★", "février", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fi★", "financier", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fiè★", "financière", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ff★", "Firefox", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fig★", "figure", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fl★", "falloir", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("freq★", "fréquence", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("fr★", "France", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("frs★", "français", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("g★", "j’ai", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("g1r★", "j’ai une réunion", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gar★", "garantie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gars★", "garanties", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gd★", "grand", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gg★", "Google", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ges★", "gestion", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gf★", "J’ai fait", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gmag★", "J’ai mis à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gov★", "government", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gouv★", "gouvernement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("indiv★", "individuel", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gpa★", "je n’ai pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gt★", "j’étais", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("gvt★", "gouvernement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("h★", "heure", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("his★", "historique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("histo★", "historique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("hyp★", "hypothèse", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ia★", "intelligence artificielle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("id★", "identifiant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("idf★", "Île-de-France", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("idk★", "I don’t know", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ids★", "identifiants", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("img★", "image", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("imgs★", "images", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("imm★", "immeuble", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("imo★", "in my opinion", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("imp★", "impossible", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("inf★", "inférieur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("info★", "information", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("infos★", "informations", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("insta★", "Instagram", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("intart★", "intelligence artificielle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("inter★", "international", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("intro★", "introduction", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("j★", "bonjour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ja★", "jamais", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("janv★", "janvier", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jm★", "j’aime", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jms★", "jamais", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jnsp★", "je ne sais pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("js★", "je suis", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jsp★", "je ne sais pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jtm★", "je t’aime", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ju★", "jusque", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ju'★", "jusqu’", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jus★", "jusque", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jusq★", "jusqu’", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jus'★", "jusqu’", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("jui★", "juillet", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("k★", "contacter", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("kb★", "keyboard", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("kbd★", "keyboard", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("kn★", "construction", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("lê★", "l’être", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ledt★", "l’emploi du temps", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("lex★", "l’exemple", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("lim★", "limite", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("m★", "mais", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ma★", "madame", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("maj★", "mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("màj★", "mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("math★", "mathématique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("manip★", "manipulation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("maths★", "mathématiques", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("max★", "maximum", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("md★", "milliard", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mds★", "milliards", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mdav★", "merci d’avance", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mdb★", "merci de bien vouloir", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mdl★", "modèle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mdp★", "mot de passe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mdps★", "mots de passe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("méthodo★", "méthodologie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("min★", "minimum", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mio★", "million", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mios★", "millions", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mjo★", "mettre à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ml★", "machine learning", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mm★", "même", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mme★", "madame", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("modif★", "modification", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mom★", "moi-même", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mq★", "montre que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mr★", "monsieur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mrc★", "merci", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("msg★", "message", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mtn★", "maintenant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("moy★", "moyenne", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mutu★", "mutualiser", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mvt★", "mouvement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("n★", "nouveau", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nav★", "navigation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nb★", "nombre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nean★", "néanmoins", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("new★", "nouveau", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("newe★", "nouvelle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nimp★", "n’importe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("niv★", "niveau", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("norm★", "normalement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nota★", "notamment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("notm★", "notamment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nouv★", "nouvelle", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nov★", "novembre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("now★", "maintenant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("np★", "ne pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("nrj★", "énergie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ns★", "nous", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("num★", "numéro", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("o-★", "au moins", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("o+★", "au plus", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("obj★", "objectif", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("obs★", "observation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("oct★", "octobre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("odj★", "ordre du jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("opé★", "opération", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("oqp★", "occupé", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ordi★", "ordinateur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("org★", "organisation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("orga★", "organisation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ortho★", "orthographe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("out★", "Où es-tu ?", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("outv★", "Où êtes-vous ?", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("ouv★", "ouverture", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("p★", "prendre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("p//★", "par rapport", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("par★", "paragraphe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("param★", "paramètre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pb★", "problème", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pcq★", "parce que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pck★", "parce que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pckil★", "parce qu’il", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pcquil★", "parce qu’il", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pcquon★", "parce qu’on", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pckon★", "parce qu’on", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pd★", "pendant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pdt★", "pendant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pdv★", "point de vue", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pdvs★", "points de vue", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("perf★", "performance", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("perso★", "personne", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pê★", "peut-être", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("péri★", "périmètre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("périm★", "périmètre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("peut-ê★", "peut-être", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pex★", "par exemple", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pf★", "portefeuille", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pg★", "pas grave", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pgm★", "programme", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pi★", "pour information", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pic★", "picture", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pics★", "pictures", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("piè★", "pièce jointe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pj★", "pièce jointe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pjs★", "pièces jointes", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pk★", "pourquoi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pls★", "please", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("poum★", "plus ou moins", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("poss★", "possible", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pourcent★", "pourcentage", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ppt★", "PowerPoint", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pq★", "pourquoi", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prd★", "produit", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prem★", "premier", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prez★", "présentation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prg★", "programme", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prio★", "priorité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pro★", "professionnel", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prob★", "problème", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("proba★", "probabilité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prod★", "production", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prof★", "professeur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prog★", "programme", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prop★", "propriété", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("propo★", "proposition", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("props★", "propriétés", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pros★", "professionnels", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prot★", "professionnellement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("prov★", "provision", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("psycha★", "psychanalyse", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("psycho★", "psychologie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("psb★", "possible", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("psy★", "psychologie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pt★", "point", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ptf★", "portefeuille", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pts★", "points", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pub★", "publicité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pvv★", "pouvez-vous", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("py★", "python", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("q★", "question", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qc★", "qu’est-ce", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qcq★", "qu’est-ce que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qcq'★", "qu’est-ce qu’", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qq★", "quelque", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qqch★", "quelque chose", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qqs★", "quelques", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("qqn★", "quelqu’un", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("quasi★", "quasiment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ques★", "question", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("quid★", "qu’en est-il de", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("r★", "rien", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rapidt★", "rapidement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rdv★", "rendez-vous", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ré★", "réunion", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rés★", "réunions", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rép★", "répertoire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("résil★", "résiliation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("reco★", "recommandation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ref★", "référence", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rep★", "répertoire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rex★", "retour d’expérience", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rmq★", "remarque", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rpz★", "représente", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("rs★", "résultat", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("seg★", "segment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("segm★", "segment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sep★", "septembre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sept★", "septembre", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("simpl★", "simplement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("situ★", "situation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("smth★", "something", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("srx★", "sérieux", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sécu★", "sécurité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("st★", "s’était", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("stat★", "statistique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sth★", "something", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("stp★", "s’il te plaît", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("strat★", "stratégique", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("stream★", "streaming", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("suff★", "suffisant", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sufft★", "suffisamment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("supé★", "supérieur", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("surv★", "survenance", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("svp★", "s’il vous plaît", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("svt★", "souvent", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sya★", "s’il y a", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("syn★", "synonyme", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sync★", "synchronisation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("syncro★", "synchronisation", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("sys★", "système", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("t★", "très", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tb★", "très bien", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("temp★", "temporaire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tes★", "tu es", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tél★", "téléphone", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("teq★", "telle que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("teqs★", "telles que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tfk★", "qu’est-ce que tu fais ?", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tgh★", "together", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("théo★", "théorie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("thm★", "théorème", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tj★", "toujours", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tjr★", "toujours", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tlm★", "tout le monde", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tq★", "tel que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tqs★", "tels que", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tout★", "toutefois", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tra★", "travail", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("trad★", "traduction", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("trav★", "travail", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("trkl★", "tranquille", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tt★", "télétravail", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tv★", "télévision", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ty★", "thank you", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("typo★", "typographie", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("une amé★", "une amélioration", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("uniq★", "uniquement", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("usa★", "États-Unis", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("v★", "version", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("var★", "variable", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vav★", "vis-à-vis", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("verif★", "vérification", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vérif★", "vérification", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vocab★", "vocabulaire", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("volat★", "volatilité", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vrm★", "vraiment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vrmt★", "vraiment", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("vs★", "vous êtes", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("w★", "with", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("wd★", "Windows", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("wk★", "week-end", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("wknd★", "week-end", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("wiki★", "Wikipédia", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("x★", "exemple", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ya★", "il y a", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("yapa★", "il n’y a pas", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("yatil★", "y a-t-il", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("yc★", "y compris", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("yt★", "YouTube", {is_word = true, auto_expand = true, is_case_sensitive = true})