-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/magic.toml
local keymap = require("keymap")

keymap.add("ae★", "æ", true, true, false)
keymap.add("oe★", "œ", true, true, false)
keymap.add("1er★", "premier", false, true, false)
keymap.add("1ere★", "première", false, true, false)
keymap.add("2e★", "deuxième", false, true, false)
keymap.add("3e★", "troisième", false, true, false)
keymap.add("4e★", "quatrième", false, true, false)
keymap.add("5e★", "cinquième", false, true, false)
keymap.add("6e★", "sixième", false, true, false)
keymap.add("7e★", "septième", false, true, false)
keymap.add("8e★", "huitième", false, true, false)
keymap.add("9e★", "neuvième", false, true, false)
keymap.add("10e★", "dixième", false, true, false)
keymap.add("11e★", "onzième", false, true, false)
keymap.add("12e★", "douzième", false, true, false)
keymap.add("20e★", "vingtième", false, true, false)
keymap.add("100e★", "centième", false, true, false)
keymap.add("1000e★", "millième", false, true, false)
keymap.add("2s★", "2 secondes", false, true, false)
keymap.add("//★", "rapport", false, true, false)
keymap.add("+m★", "meilleur", false, true, false)
keymap.add("a★", "ainsi", false, true, false)
keymap.add("abr★", "abréviation", false, true, false)
keymap.add("actu★", "actualité", false, true, false)
keymap.add("add★", "addresse", false, true, false)
keymap.add("admin★", "administrateur", false, true, false)
keymap.add("afr★", "à faire", false, true, false)
keymap.add("ah★", "aujourd’hui", false, true, false)
keymap.add("ahk★", "AutoHotkey", false, true, true)
keymap.add("ajd★", "aujourd’hui", false, true, false)
keymap.add("algo★", "algorithme", false, true, false)
keymap.add("alpha★", "alphabétique", false, true, false)
keymap.add("amé★", "amélioration", false, true, false)
keymap.add("amélio★", "amélioration", false, true, false)
keymap.add("anc★", "ancien", false, true, false)
keymap.add("ano★", "anomalie", false, true, false)
keymap.add("anniv★", "anniversaire", false, true, false)
keymap.add("apm★", "après-midi", false, true, false)
keymap.add("apad★", "à partir de", false, true, false)
keymap.add("app★", "application", false, true, false)
keymap.add("appart★", "appartement", false, true, false)
keymap.add("appli★", "application", false, true, false)
keymap.add("approx★", "approximation", false, true, false)
keymap.add("archi★", "architecture", false, true, false)
keymap.add("asso★", "association", false, true, false)
keymap.add("asap★", "le plus rapidement possible", false, true, false)
keymap.add("atd★", "attend", false, true, false)
keymap.add("att★", "attention", false, true, false)
keymap.add("aud★", "aujourd’hui", false, true, false)
keymap.add("aug★", "augmentation", false, true, false)
keymap.add("auj★", "aujourd’hui", false, true, false)
keymap.add("auto★", "automatique", false, true, false)
keymap.add("av★", "avant", false, true, false)
keymap.add("avv★", "avez-vous", false, true, false)
keymap.add("avvd★", "avez-vous déjà", false, true, false)
keymap.add("b★", "bonjour", false, true, false)
keymap.add("bc★", "because", false, true, false)
keymap.add("bcp★", "beaucoup", false, true, false)
keymap.add("bdd★", "base de données", false, true, false)
keymap.add("bdds★", "bases de données", false, true, false)
keymap.add("bea★", "beaucoup", false, true, false)
keymap.add("bec★", "because", false, true, false)
keymap.add("bib★", "bibliographie", false, true, false)
keymap.add("biblio★", "bibliographie", false, true, false)
keymap.add("bjr★", "bonjour", false, true, false)
keymap.add("brain★", "brainstorming", false, true, false)
keymap.add("br★", "bonjour", false, true, false)
keymap.add("bsr★", "bonsoir", false, true, false)
keymap.add("bv★", "bravo", false, true, false)
keymap.add("bvn★", "bienvenue", false, true, false)
keymap.add("bwe★", "bon week-end", false, true, false)
keymap.add("bwk★", "bon week-end", false, true, false)
keymap.add("c★", "c’est", false, true, false)
keymap.add("cad★", "c’est-à-dire", false, true, false)
keymap.add("camp★", "campagne", false, true, false)
keymap.add("carac★", "caractère", false, true, false)
keymap.add("caract★", "caractéristique", false, true, false)
keymap.add("cb★", "combien", false, true, false)
keymap.add("cc★", "copier-coller", false, true, false)
keymap.add("ccé★", "copié-collé", false, true, false)
keymap.add("ccl★", "conclusion", false, true, false)
keymap.add("cdg★", "Charles de Gaulle", false, true, false)
keymap.add("cdt★", "cordialement", false, true, false)
keymap.add("certif★", "certification", false, true, false)
keymap.add("chg★", "charge", false, true, false)
keymap.add("chap★", "chapitre", false, true, false)
keymap.add("chr★", "chercher", false, true, false)
keymap.add("ci★", "ci-joint", false, true, false)
keymap.add("cj★", "ci-joint", false, true, false)
keymap.add("coeff★", "coefficient", false, true, false)
keymap.add("cog★", "cognition", false, true, false)
keymap.add("cogv★", "cognitive", false, true, false)
keymap.add("comp★", "comprendre", false, true, false)
keymap.add("cond★", "condition", false, true, false)
keymap.add("conds★", "conditions", false, true, false)
keymap.add("config★", "configuration", false, true, false)
keymap.add("chgt★", "changement", false, true, false)
keymap.add("cnp★", "ce n’est pas", false, true, false)
keymap.add("contrib★", "contribution", false, true, false)
keymap.add("couv★", "couverture", false, true, false)
keymap.add("cpd★", "cependant", false, true, false)
keymap.add("cr★", "compte-rendu", false, true, false)
keymap.add("ct★", "c’était", false, true, false)
keymap.add("ctb★", "c’est très bien", false, true, false)
keymap.add("cv★", "ça va ?", false, true, false)
keymap.add("cvt★", "ça va toi ?", false, true, false)
keymap.add("ctc★", "Est-ce que cela te convient ?", false, true, true)
keymap.add("cvc★", "Est-ce que cela vous convient ?", false, true, true)
keymap.add("dac★", "d’accord", false, true, false)
keymap.add("ddl★", "download", false, true, false)
keymap.add("dé★", "déjà", false, true, false)
keymap.add("dê★", "d’être", false, true, false)
keymap.add("déc★", "décembre", false, true, false)
keymap.add("dec★", "décembre", false, true, false)
keymap.add("dedt★", "d’emploi du temps", false, true, false)
keymap.add("déf★", "définition", false, true, false)
keymap.add("def★", "définition", false, true, false)
keymap.add("défs★", "définitions", false, true, false)
keymap.add("démo★", "démonstration", false, true, false)
keymap.add("demo★", "démonstration", false, true, false)
keymap.add("dep★", "département", false, true, false)
keymap.add("deux★", "deuxième", false, true, false)
keymap.add("desc★", "description", false, true, false)
keymap.add("dev★", "développeur", false, true, false)
keymap.add("dév★", "développeur", false, true, false)
keymap.add("devt★", "développement", false, true, false)
keymap.add("dico★", "dictionnaire", false, true, false)
keymap.add("diff★", "différence", false, true, false)
keymap.add("difft★", "différent", false, true, false)
keymap.add("dim★", "dimension", false, true, false)
keymap.add("dimi★", "diminution", false, true, false)
keymap.add("la dispo★", "la disposition", false, true, false)
keymap.add("ta dispo★", "ta disposition", false, true, false)
keymap.add("une dispo★", "une disposition", false, true, false)
keymap.add("dispo★", "disponible", false, true, false)
keymap.add("distri★", "distributeur", false, true, false)
keymap.add("distrib★", "distributeur", false, true, false)
keymap.add("dj★", "déjà", false, true, false)
keymap.add("dm★", "donne-moi", false, true, false)
keymap.add("la doc★", "la documentation", false, true, false)
keymap.add("une doc★", "une documentation", false, true, false)
keymap.add("doc★", "document", false, true, false)
keymap.add("docs★", "documents", false, true, false)
keymap.add("dp★", "de plus", false, true, false)
keymap.add("dsl★", "désolé", false, true, false)
keymap.add("dtm★", "détermine", false, true, false)
keymap.add("dvlp★", "développe", false, true, false)
keymap.add("e★", "est", false, true, false)
keymap.add("echant★", "échantillon", false, true, false)
keymap.add("echants★", "échantillons", false, true, false)
keymap.add("eco★", "économie", false, true, false)
keymap.add("ecq★", "est-ce que", false, true, false)
keymap.add("edt★", "emploi du temps", false, true, false)
keymap.add("eef★", "en effet", false, true, false)
keymap.add("elt★", "élément", false, true, false)
keymap.add("elts★", "éléments", false, true, false)
keymap.add("eo★", "en outre", false, true, false)
keymap.add("enc★", "encore", false, true, false)
keymap.add("eng★", "english", false, true, false)
keymap.add("enft★", "en fait", false, true, false)
keymap.add("ens★", "ensemble", false, true, false)
keymap.add("ent★", "entreprise", false, true, false)
keymap.add("env★", "environ", false, true, false)
keymap.add("ep★", "épisode", false, true, false)
keymap.add("eps★", "épisodes", false, true, false)
keymap.add("eq★", "équation", false, true, false)
keymap.add("ety★", "étymologie", false, true, false)
keymap.add("eve★", "événement", false, true, false)
keymap.add("evtl★", "éventuel", false, true, false)
keymap.add("evtle★", "éventuelle", false, true, false)
keymap.add("evtlt★", "éventuellement", false, true, false)
keymap.add("ex★", "exemple", false, true, false)
keymap.add("exo★", "exercice", false, true, false)
keymap.add("exp★", "expérience", false, true, false)
keymap.add("expo★", "exposition", false, true, false)
keymap.add("é★", "écart", false, true, false)
keymap.add("éco★", "économie", false, true, false)
keymap.add("ém★", "écris-moi", false, true, false)
keymap.add("éq★", "équation", false, true, false)
keymap.add("ê★", "être", false, true, false)
keymap.add("êt★", "es-tu", false, true, false)
keymap.add("f★", "faire", false, true, false)
keymap.add("fam★", "famille", false, true, false)
keymap.add("fb★", "Facebook", false, true, false)
keymap.add("fc★", "fonction", false, true, false)
keymap.add("fct★", "fonction", false, true, false)
keymap.add("fea★", "feature", false, true, false)
keymap.add("feat★", "feature", false, true, false)
keymap.add("fev★", "février", false, true, false)
keymap.add("fi★", "financier", false, true, false)
keymap.add("fiè★", "financière", false, true, false)
keymap.add("ff★", "Firefox", false, true, false)
keymap.add("fig★", "figure", false, true, false)
keymap.add("fl★", "falloir", false, true, false)
keymap.add("freq★", "fréquence", false, true, false)
keymap.add("fr★", "France", false, true, true)
keymap.add("frs★", "français", false, true, false)
keymap.add("g★", "j’ai", false, true, false)
keymap.add("g1r★", "j’ai une réunion", false, true, false)
keymap.add("gar★", "garantie", false, true, false)
keymap.add("gars★", "garanties", false, true, false)
keymap.add("gd★", "grand", false, true, false)
keymap.add("gg★", "Google", false, true, false)
keymap.add("ges★", "gestion", false, true, false)
keymap.add("gf★", "J’ai fait", false, true, false)
keymap.add("gmag★", "J’ai mis à jour", false, true, false)
keymap.add("gov★", "government", false, true, false)
keymap.add("gouv★", "gouvernement", false, true, false)
keymap.add("indiv★", "individuel", false, true, false)
keymap.add("gpa★", "je n’ai pas", false, true, false)
keymap.add("gt★", "j’étais", false, true, false)
keymap.add("gvt★", "gouvernement", false, true, false)
keymap.add("h★", "heure", false, true, false)
keymap.add("his★", "historique", false, true, false)
keymap.add("histo★", "historique", false, true, false)
keymap.add("hyp★", "hypothèse", false, true, false)
keymap.add("ia★", "intelligence artificielle", false, true, false)
keymap.add("id★", "identifiant", false, true, false)
keymap.add("idf★", "Île-de-France", false, true, false)
keymap.add("idk★", "I don’t know", false, true, false)
keymap.add("ids★", "identifiants", false, true, false)
keymap.add("img★", "image", false, true, false)
keymap.add("imgs★", "images", false, true, false)
keymap.add("imm★", "immeuble", false, true, false)
keymap.add("imo★", "in my opinion", false, true, false)
keymap.add("imp★", "impossible", false, true, false)
keymap.add("inf★", "inférieur", false, true, false)
keymap.add("info★", "information", false, true, false)
keymap.add("infos★", "informations", false, true, false)
keymap.add("insta★", "Instagram", false, true, true)
keymap.add("intart★", "intelligence artificielle", false, true, false)
keymap.add("inter★", "international", false, true, false)
keymap.add("intro★", "introduction", false, true, false)
keymap.add("j★", "bonjour", false, true, false)
keymap.add("ja★", "jamais", false, true, false)
keymap.add("janv★", "janvier", false, true, false)
keymap.add("jm★", "j’aime", false, true, false)
keymap.add("jms★", "jamais", false, true, false)
keymap.add("jnsp★", "je ne sais pas", false, true, false)
keymap.add("js★", "je suis", false, true, false)
keymap.add("jsp★", "je ne sais pas", false, true, false)
keymap.add("jtm★", "je t’aime", false, true, false)
keymap.add("ju★", "jusque", false, true, false)
keymap.add("ju'★", "jusqu’", false, true, false)
keymap.add("jus★", "jusque", false, true, false)
keymap.add("jusq★", "jusqu’", false, true, false)
keymap.add("jus'★", "jusqu’", false, true, false)
keymap.add("jui★", "juillet", false, true, false)
keymap.add("k★", "contacter", false, true, false)
keymap.add("kb★", "keyboard", false, true, false)
keymap.add("kbd★", "keyboard", false, true, false)
keymap.add("kn★", "construction", false, true, false)
keymap.add("lê★", "l’être", false, true, false)
keymap.add("ledt★", "l’emploi du temps", false, true, false)
keymap.add("lex★", "l’exemple", false, true, false)
keymap.add("lim★", "limite", false, true, false)
keymap.add("m★", "mais", false, true, false)
keymap.add("ma★", "madame", false, true, false)
keymap.add("maj★", "mise à jour", false, true, false)
keymap.add("màj★", "mise à jour", false, true, false)
keymap.add("math★", "mathématique", false, true, false)
keymap.add("manip★", "manipulation", false, true, false)
keymap.add("maths★", "mathématiques", false, true, false)
keymap.add("max★", "maximum", false, true, false)
keymap.add("md★", "milliard", false, true, false)
keymap.add("mds★", "milliards", false, true, false)
keymap.add("mdav★", "merci d’avance", false, true, false)
keymap.add("mdb★", "merci de bien vouloir", false, true, false)
keymap.add("mdl★", "modèle", false, true, false)
keymap.add("mdp★", "mot de passe", false, true, false)
keymap.add("mdps★", "mots de passe", false, true, false)
keymap.add("méthodo★", "méthodologie", false, true, false)
keymap.add("min★", "minimum", false, true, false)
keymap.add("mio★", "million", false, true, false)
keymap.add("mios★", "millions", false, true, false)
keymap.add("mjo★", "mettre à jour", false, true, false)
keymap.add("ml★", "machine learning", false, true, false)
keymap.add("mm★", "même", false, true, false)
keymap.add("mme★", "madame", false, true, false)
keymap.add("modif★", "modification", false, true, false)
keymap.add("mom★", "moi-même", false, true, false)
keymap.add("mq★", "montre que", false, true, false)
keymap.add("mr★", "monsieur", false, true, false)
keymap.add("mrc★", "merci", false, true, false)
keymap.add("msg★", "message", false, true, false)
keymap.add("mtn★", "maintenant", false, true, false)
keymap.add("moy★", "moyenne", false, true, false)
keymap.add("mutu★", "mutualiser", false, true, false)
keymap.add("mvt★", "mouvement", false, true, false)
keymap.add("n★", "nouveau", false, true, false)
keymap.add("nav★", "navigation", false, true, false)
keymap.add("nb★", "nombre", false, true, false)
keymap.add("nean★", "néanmoins", false, true, false)
keymap.add("new★", "nouveau", false, true, false)
keymap.add("newe★", "nouvelle", false, true, false)
keymap.add("nimp★", "n’importe", false, true, false)
keymap.add("niv★", "niveau", false, true, false)
keymap.add("norm★", "normalement", false, true, false)
keymap.add("nota★", "notamment", false, true, false)
keymap.add("notm★", "notamment", false, true, false)
keymap.add("nouv★", "nouvelle", false, true, false)
keymap.add("nov★", "novembre", false, true, false)
keymap.add("now★", "maintenant", false, true, false)
keymap.add("np★", "ne pas", false, true, false)
keymap.add("nrj★", "énergie", false, true, false)
keymap.add("ns★", "nous", false, true, false)
keymap.add("num★", "numéro", false, true, false)
keymap.add("o-★", "au moins", false, true, false)
keymap.add("o+★", "au plus", false, true, false)
keymap.add("obj★", "objectif", false, true, false)
keymap.add("obs★", "observation", false, true, false)
keymap.add("oct★", "octobre", false, true, false)
keymap.add("odj★", "ordre du jour", false, true, false)
keymap.add("opé★", "opération", false, true, false)
keymap.add("oqp★", "occupé", false, true, false)
keymap.add("ordi★", "ordinateur", false, true, false)
keymap.add("org★", "organisation", false, true, false)
keymap.add("orga★", "organisation", false, true, false)
keymap.add("ortho★", "orthographe", false, true, false)
keymap.add("out★", "Où es-tu ?", false, true, true)
keymap.add("outv★", "Où êtes-vous ?", false, true, true)
keymap.add("ouv★", "ouverture", false, true, false)
keymap.add("p★", "prendre", false, true, false)
keymap.add("p//★", "par rapport", false, true, false)
keymap.add("par★", "paragraphe", false, true, false)
keymap.add("param★", "paramètre", false, true, false)
keymap.add("pb★", "problème", false, true, false)
keymap.add("pcq★", "parce que", false, true, false)
keymap.add("pck★", "parce que", false, true, false)
keymap.add("pckil★", "parce qu’il", false, true, false)
keymap.add("pcquil★", "parce qu’il", false, true, false)
keymap.add("pcquon★", "parce qu’on", false, true, false)
keymap.add("pckon★", "parce qu’on", false, true, false)
keymap.add("pd★", "pendant", false, true, false)
keymap.add("pdt★", "pendant", false, true, false)
keymap.add("pdv★", "point de vue", false, true, false)
keymap.add("pdvs★", "points de vue", false, true, false)
keymap.add("perf★", "performance", false, true, false)
keymap.add("perso★", "personne", false, true, false)
keymap.add("pê★", "peut-être", false, true, false)
keymap.add("péri★", "périmètre", false, true, false)
keymap.add("périm★", "périmètre", false, true, false)
keymap.add("peut-ê★", "peut-être", false, true, false)
keymap.add("pex★", "par exemple", false, true, false)
keymap.add("pf★", "portefeuille", false, true, false)
keymap.add("pg★", "pas grave", false, true, false)
keymap.add("pgm★", "programme", false, true, false)
keymap.add("pi★", "pour information", false, true, false)
keymap.add("pic★", "picture", false, true, false)
keymap.add("pics★", "pictures", false, true, false)
keymap.add("piè★", "pièce jointe", false, true, false)
keymap.add("pj★", "pièce jointe", false, true, false)
keymap.add("pjs★", "pièces jointes", false, true, false)
keymap.add("pk★", "pourquoi", false, true, false)
keymap.add("pls★", "please", false, true, false)
keymap.add("poum★", "plus ou moins", false, true, false)
keymap.add("poss★", "possible", false, true, false)
keymap.add("pourcent★", "pourcentage", false, true, false)
keymap.add("ppt★", "PowerPoint", false, true, false)
keymap.add("pq★", "pourquoi", false, true, false)
keymap.add("prd★", "produit", false, true, false)
keymap.add("prem★", "premier", false, true, false)
keymap.add("prez★", "présentation", false, true, false)
keymap.add("prg★", "programme", false, true, false)
keymap.add("prio★", "priorité", false, true, false)
keymap.add("pro★", "professionnel", false, true, false)
keymap.add("prob★", "problème", false, true, false)
keymap.add("proba★", "probabilité", false, true, false)
keymap.add("prod★", "production", false, true, false)
keymap.add("prof★", "professeur", false, true, false)
keymap.add("prog★", "programme", false, true, false)
keymap.add("prop★", "propriété", false, true, false)
keymap.add("propo★", "proposition", false, true, false)
keymap.add("props★", "propriétés", false, true, false)
keymap.add("pros★", "professionnels", false, true, false)
keymap.add("prot★", "professionnellement", false, true, false)
keymap.add("prov★", "provision", false, true, false)
keymap.add("psycha★", "psychanalyse", false, true, false)
keymap.add("psycho★", "psychologie", false, true, false)
keymap.add("psb★", "possible", false, true, false)
keymap.add("psy★", "psychologie", false, true, false)
keymap.add("pt★", "point", false, true, false)
keymap.add("ptf★", "portefeuille", false, true, false)
keymap.add("pts★", "points", false, true, false)
keymap.add("pub★", "publicité", false, true, false)
keymap.add("pvv★", "pouvez-vous", false, true, false)
keymap.add("py★", "python", false, true, false)
keymap.add("q★", "question", false, true, false)
keymap.add("qc★", "qu’est-ce", false, true, false)
keymap.add("qcq★", "qu’est-ce que", false, true, false)
keymap.add("qcq'★", "qu’est-ce qu’", false, true, false)
keymap.add("qq★", "quelque", false, true, false)
keymap.add("qqch★", "quelque chose", false, true, false)
keymap.add("qqs★", "quelques", false, true, false)
keymap.add("qqn★", "quelqu’un", false, true, false)
keymap.add("quasi★", "quasiment", false, true, false)
keymap.add("ques★", "question", false, true, false)
keymap.add("quid★", "qu’en est-il de", false, true, false)
keymap.add("r★", "rien", false, true, false)
keymap.add("rapidt★", "rapidement", false, true, false)
keymap.add("rdv★", "rendez-vous", false, true, false)
keymap.add("ré★", "réunion", false, true, false)
keymap.add("rés★", "réunions", false, true, false)
keymap.add("rép★", "répertoire", false, true, false)
keymap.add("résil★", "résiliation", false, true, false)
keymap.add("reco★", "recommandation", false, true, false)
keymap.add("ref★", "référence", false, true, false)
keymap.add("rep★", "répertoire", false, true, false)
keymap.add("rex★", "retour d’expérience", false, true, false)
keymap.add("rmq★", "remarque", false, true, false)
keymap.add("rpz★", "représente", false, true, false)
keymap.add("rs★", "résultat", false, true, false)
keymap.add("seg★", "segment", false, true, false)
keymap.add("segm★", "segment", false, true, false)
keymap.add("sep★", "septembre", false, true, false)
keymap.add("sept★", "septembre", false, true, false)
keymap.add("simpl★", "simplement", false, true, false)
keymap.add("situ★", "situation", false, true, false)
keymap.add("smth★", "something", false, true, false)
keymap.add("srx★", "sérieux", false, true, false)
keymap.add("sécu★", "sécurité", false, true, false)
keymap.add("st★", "s’était", false, true, false)
keymap.add("stat★", "statistique", false, true, false)
keymap.add("sth★", "something", false, true, false)
keymap.add("stp★", "s’il te plaît", false, true, false)
keymap.add("strat★", "stratégique", false, true, false)
keymap.add("stream★", "streaming", false, true, false)
keymap.add("suff★", "suffisant", false, true, false)
keymap.add("sufft★", "suffisamment", false, true, false)
keymap.add("supé★", "supérieur", false, true, false)
keymap.add("surv★", "survenance", false, true, false)
keymap.add("svp★", "s’il vous plaît", false, true, false)
keymap.add("svt★", "souvent", false, true, false)
keymap.add("sya★", "s’il y a", false, true, false)
keymap.add("syn★", "synonyme", false, true, false)
keymap.add("sync★", "synchronisation", false, true, false)
keymap.add("syncro★", "synchronisation", false, true, false)
keymap.add("sys★", "système", false, true, false)
keymap.add("t★", "très", false, true, false)
keymap.add("tb★", "très bien", false, true, false)
keymap.add("temp★", "temporaire", false, true, false)
keymap.add("tes★", "tu es", false, true, false)
keymap.add("tél★", "téléphone", false, true, false)
keymap.add("teq★", "telle que", false, true, false)
keymap.add("teqs★", "telles que", false, true, false)
keymap.add("tfk★", "qu’est-ce que tu fais ?", false, true, false)
keymap.add("tgh★", "together", false, true, false)
keymap.add("théo★", "théorie", false, true, false)
keymap.add("thm★", "théorème", false, true, false)
keymap.add("tj★", "toujours", false, true, false)
keymap.add("tjr★", "toujours", false, true, false)
keymap.add("tlm★", "tout le monde", false, true, false)
keymap.add("tq★", "tel que", false, true, false)
keymap.add("tqs★", "tels que", false, true, false)
keymap.add("tout★", "toutefois", false, true, false)
keymap.add("tra★", "travail", false, true, false)
keymap.add("trad★", "traduction", false, true, false)
keymap.add("trav★", "travail", false, true, false)
keymap.add("trkl★", "tranquille", false, true, false)
keymap.add("tt★", "télétravail", false, true, false)
keymap.add("tv★", "télévision", false, true, false)
keymap.add("ty★", "thank you", false, true, false)
keymap.add("typo★", "typographie", false, true, false)
keymap.add("une amé★", "une amélioration", false, true, false)
keymap.add("uniq★", "uniquement", false, true, false)
keymap.add("usa★", "États-Unis", false, true, true)
keymap.add("v★", "version", false, true, false)
keymap.add("var★", "variable", false, true, false)
keymap.add("vav★", "vis-à-vis", false, true, false)
keymap.add("verif★", "vérification", false, true, false)
keymap.add("vérif★", "vérification", false, true, false)
keymap.add("vocab★", "vocabulaire", false, true, false)
keymap.add("volat★", "volatilité", false, true, false)
keymap.add("vrm★", "vraiment", false, true, false)
keymap.add("vrmt★", "vraiment", false, true, false)
keymap.add("vs★", "vous êtes", false, true, false)
keymap.add("w★", "with", false, true, false)
keymap.add("wd★", "Windows", false, true, false)
keymap.add("wk★", "week-end", false, true, false)
keymap.add("wknd★", "week-end", false, true, false)
keymap.add("wiki★", "Wikipédia", false, true, true)
keymap.add("x★", "exemple", false, true, false)
keymap.add("ya★", "il y a", false, true, false)
keymap.add("yapa★", "il n’y a pas", false, true, false)
keymap.add("yatil★", "y a-t-il", false, true, false)
keymap.add("yc★", "y compris", false, true, false)
keymap.add("yt★", "YouTube", false, true, true)