-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/minus.toml
local keymap = require("keymap")

keymap.add("aije", "ai-je", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("astu", "as-tu", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("atil", "a-t-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("aton", "a-t-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("auratelle", "aura-t-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("auratil", "aura-t-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("auraton", "aura-t-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("dismoi", "dis-moi", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("ditelle", "dit-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("ditil", "dit-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("distu", "dis-tu", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("diton", "dit-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("doisje", "dois-je", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("doitelle", "doit-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("doitil", "doit-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("doiton", "doit-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("estu", "es-tu", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("estil", "est-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("eston", "est-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("fautelle", "faut-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("fautil", "faut-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("fauton", "faut-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("peutil", "peut-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("peutelle", "peut-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("peuton", "peut-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("peuxtu", "peux-tu", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("puisje", "puis-je", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("vatelle", "va-t-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("vatil", "va-t-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("vaton", "va-t-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("veutelle", "veut-elle", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("veutil", "veut-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("veuton", "veut-on", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("veuxtu", "veux-tu", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("yatil", "y a-t-il", {is_word = true, auto_expand = false, is_case_sensitive = false})
keymap.add("vonsn", "vons-n", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("vezv", "vez-v", {is_word = false, auto_expand = true, is_case_sensitive = false})