-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/minus.toml
local keymap = require("keymap")

keymap.add("aije", "ai-je", false)
keymap.add("astu", "as-tu", false)
keymap.add("atil", "a-t-il", false)
keymap.add("aton", "a-t-on", false)
keymap.add("auratelle", "aura-t-elle", false)
keymap.add("auratil", "aura-t-il", false)
keymap.add("auraton", "aura-t-on", false)
keymap.add("dismoi", "dis-moi", false)
keymap.add("ditelle", "dit-elle", false)
keymap.add("ditil", "dit-il", false)
keymap.add("distu", "dis-tu", false)
keymap.add("diton", "dit-on", false)
keymap.add("doisje", "dois-je", false)
keymap.add("doitelle", "doit-elle", false)
keymap.add("doitil", "doit-il", false)
keymap.add("doiton", "doit-on", false)
keymap.add("estu", "es-tu", false)
keymap.add("estil", "est-il", false)
keymap.add("eston", "est-on", false)
keymap.add("fautelle", "faut-elle", false)
keymap.add("fautil", "faut-il", false)
keymap.add("fauton", "faut-on", false)
keymap.add("peutil", "peut-il", false)
keymap.add("peutelle", "peut-elle", false)
keymap.add("peuton", "peut-on", false)
keymap.add("peuxtu", "peux-tu", false)
keymap.add("puisje", "puis-je", false)
keymap.add("vatelle", "va-t-elle", false)
keymap.add("vatil", "va-t-il", false)
keymap.add("vaton", "va-t-on", false)
keymap.add("veutelle", "veut-elle", false)
keymap.add("veutil", "veut-il", false)
keymap.add("veuton", "veut-on", false)
keymap.add("veuxtu", "veux-tu", false)
keymap.add("yatil", "y a-t-il", false)
keymap.add("vonsn", "vons-n", true)
keymap.add("vezv", "vez-v", true)