-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/names.toml
local keymap = require("keymap")

keymap.add("alexei", "Alexeï", false)
keymap.add("anais", "Anaïs", false)
keymap.add("azerbaidjan", "Azerbaïdjan", false)
keymap.add("benoit", "Benoît", false)
keymap.add("caraibes", "Caraïbes", false)
keymap.add("cleopatre", "Cléopâtre", false)
keymap.add("cléopatre", "Cléopâtre", false)
keymap.add("dubai", "Dubaï", false)
keymap.add("gaetan", "Gaëtan", false)
keymap.add("hanoi", "Hanoï", false)
keymap.add("israel", "Israël", false)
keymap.add("jerome", "Jérôme", false)
keymap.add("jérome", "Jérôme", false)
keymap.add("joel", "Joël", false)
keymap.add("mickael", "Mickaël", false)
keymap.add("noel", "Noël", false)
keymap.add("Quatar", "Qatar", false)
keymap.add("raphael", "Raphaël", false)
keymap.add("serguei", "Sergueï", false)
keymap.add("shanghai", "Shanghaï", false)
keymap.add("taiwan", "Taïwan", false)
keymap.add("thais", "Thaïs", false)
keymap.add("thailande", "Thaïlande", false)
keymap.add("tolstoi", "Tolstoï", false)