-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/names.toml
local keymap = require("keymap")

keymap.add("alexei", "Alexeï", false, false, true)
keymap.add("anais", "Anaïs", false, false, true)
keymap.add("azerbaidjan", "Azerbaïdjan", false, false, true)
keymap.add("benoit", "Benoît", false, false, true)
keymap.add("caraibes", "Caraïbes", false, false, true)
keymap.add("cleopatre", "Cléopâtre", false, false, true)
keymap.add("cléopatre", "Cléopâtre", false, false, true)
keymap.add("dubai", "Dubaï", false, false, true)
keymap.add("gaetan", "Gaëtan", false, false, true)
keymap.add("hanoi", "Hanoï", false, false, true)
keymap.add("israel", "Israël", false, false, true)
keymap.add("jerome", "Jérôme", false, false, true)
keymap.add("jérome", "Jérôme", false, false, true)
keymap.add("joel", "Joël", false, false, true)
keymap.add("mickael", "Mickaël", false, false, true)
keymap.add("noel", "Noël", false, false, true)
keymap.add("Quatar", "Qatar", false, true, true)
keymap.add("raphael", "Raphaël", false, false, true)
keymap.add("serguei", "Sergueï", false, false, true)
keymap.add("shanghai", "Shanghaï", false, false, true)
keymap.add("taiwan", "Taïwan", false, false, true)
keymap.add("thais", "Thaïs", false, false, true)
keymap.add("thailande", "Thaïlande", false, false, true)
keymap.add("tolstoi", "Tolstoï", false, false, true)