-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/names.toml
local keymap = require("keymap")

keymap.add("alexei", "Alexeï", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("anais", "Anaïs", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("azerbaidjan", "Azerbaïdjan", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("benoit", "Benoît", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("caraibes", "Caraïbes", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("cleopatre", "Cléopâtre", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("cléopatre", "Cléopâtre", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("dubai", "Dubaï", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("gaetan", "Gaëtan", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("hanoi", "Hanoï", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("israel", "Israël", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("jerome", "Jérôme", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("jérome", "Jérôme", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("joel", "Joël", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("mickael", "Mickaël", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("noel", "Noël", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("Quatar", "Qatar", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("raphael", "Raphaël", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("serguei", "Sergueï", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("shanghai", "Shanghaï", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("taiwan", "Taïwan", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("thais", "Thaïs", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("thailande", "Thaïlande", {is_word = true, auto_expand = false, is_case_sensitive = true})
keymap.add("tolstoi", "Tolstoï", {is_word = true, auto_expand = false, is_case_sensitive = true})