-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/rolls.toml
local keymap = require("keymap")

keymap.add("<@", "</", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("eé", "ez", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("\\\"", "/*", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("\"\\", "*/", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("#(", "\")", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("#[", "\"]", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("#]", "\"]", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("hc", "wh", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(" #ç", " := ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" #!", " := ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("#ç", " := ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("#!", " := ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" ç#", " != ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" !#", " != ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("ç#", " != ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("!#", " != ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("xlsx", "xlsx", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("sx", "sk", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("cx", "ck", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(" [)", " = \"", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("[)", " = \"", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("nt'", "n’t", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" =+", " ➜ ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("=+", " ➜ ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" $=", " => ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("$=", " => ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" =$", " <= ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("=$", " <= ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" +?", " -> ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("+?", " -> ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(" ?+", " <- ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("?+", " <- ", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("p ?", "p ?", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("p'", "ct", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("(#", "(\"", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("[#", "[\"", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add("<%", "<=", {is_word = false, auto_expand = true, is_case_sensitive = true})
keymap.add(">%", ">=", {is_word = false, auto_expand = true, is_case_sensitive = true})