-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/rolls.toml
local keymap = require("keymap")

keymap.add("<@", "</", true)
keymap.add("eé", "ez", true)
keymap.add("\\\"", "/*", true)
keymap.add("\"\\", "*/", true)
keymap.add("#(", "\")", true)
keymap.add("#[", "\"]", true)
keymap.add("#]", "\"]", true)
keymap.add("hc", "wh", true)
keymap.add(" #ç", " := ", true)
keymap.add(" #!", " := ", true)
keymap.add("#ç", " := ", true)
keymap.add("#!", " := ", true)
keymap.add(" ç#", " != ", true)
keymap.add(" !#", " != ", true)
keymap.add("ç#", " != ", true)
keymap.add("!#", " != ", true)
keymap.add("xlsx", "xlsx", true)
keymap.add("sx", "sk", true)
keymap.add("cx", "ck", true)
keymap.add(" [)", " = \"", true)
keymap.add("[)", " = \"", true)
keymap.add("nt'", "n't", true)
keymap.add(" =+", " ➜ ", true)
keymap.add("=+", " ➜ ", true)
keymap.add(" $=", " => ", true)
keymap.add("$=", " => ", true)
keymap.add(" =$", " <= ", true)
keymap.add("=$", " <= ", true)
keymap.add(" +?", " -> ", true)
keymap.add("+?", " -> ", true)
keymap.add(" ?+", " <- ", true)
keymap.add("?+", " <- ", true)
keymap.add("p ?", "p ?", true)
keymap.add("p'", "ct", true)
keymap.add("(#", "(\"", true)
keymap.add("[#", "[\"", true)
keymap.add("<%", "<=", true)
keymap.add(">%", ">=", true)