-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/rolls.toml
local keymap = require("keymap")

keymap.add("<@", "</", true, true)
keymap.add("eé", "ez", true, true)
keymap.add("\\\"", "/*", true, true)
keymap.add("\"\\", "*/", true, true)
keymap.add("#(", "\")", true, true)
keymap.add("#[", "\"]", true, true)
keymap.add("#]", "\"]", true, true)
keymap.add("hc", "wh", true, true)
keymap.add(" #ç", " := ", true, true)
keymap.add(" #!", " := ", true, true)
keymap.add("#ç", " := ", true, true)
keymap.add("#!", " := ", true, true)
keymap.add(" ç#", " != ", true, true)
keymap.add(" !#", " != ", true, true)
keymap.add("ç#", " != ", true, true)
keymap.add("!#", " != ", true, true)
keymap.add("xlsx", "xlsx", true, true)
keymap.add("sx", "sk", true, true)
keymap.add("cx", "ck", true, true)
keymap.add(" [)", " = \"", true, true)
keymap.add("[)", " = \"", true, true)
keymap.add("nt'", "n't", true, true)
keymap.add(" =+", " ➜ ", true, true)
keymap.add("=+", " ➜ ", true, true)
keymap.add(" $=", " => ", true, true)
keymap.add("$=", " => ", true, true)
keymap.add(" =$", " <= ", true, true)
keymap.add("=$", " <= ", true, true)
keymap.add(" +?", " -> ", true, true)
keymap.add("+?", " -> ", true, true)
keymap.add(" ?+", " <- ", true, true)
keymap.add("?+", " <- ", true, true)
keymap.add("p ?", "p ?", true, true)
keymap.add("p'", "ct", true, true)
keymap.add("(#", "(\"", true, true)
keymap.add("[#", "[\"", true, true)
keymap.add("<%", "<=", true, true)
keymap.add(">%", ">=", true, true)