-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/suffixes.toml
local keymap = require("keymap")

keymap.add("àa", "aire", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àc", "ction", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("càd", "could", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("shàd", "should", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àd", "would", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àê", "able", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àf", "iste", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àg", "ought", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àh", "ight", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("ài", "ying", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àk", "ique", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àl", "elle", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àp", "ence", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àm", "isme", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àn", "ation", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àq", "ique", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àr", "erre", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("às", "ement", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àt", "ettre", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àv", "ment", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àx", "ieux", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àz", "ez-vous", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("à'", "ance", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("à’", "ance", {is_word = false, auto_expand = true, is_case_sensitive = false})