-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/comma.toml
local keymap = require("keymap")

keymap.add(",f", "fl", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",g", "gl", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",h", "ph", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",z", "bj", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",v", "dv", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",n", "nl", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",t", "pt", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",r", "rq", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",q", "qu’", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",m", "ms", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",d", "ds", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",l", "cl", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",p", "xp", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",à", "j", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",a", "ja", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",e", "je", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",é", "jé", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",i", "ji", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",o", "jo", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",u", "ju", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",ê", "ju", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",'", "j’", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",è", "z", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",y", "k", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",c", "ç", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",x", "où", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add(",s", "q", {is_word = false, auto_expand = true, is_case_sensitive = false})