-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/suffixes.toml
local keymap = require("keymap")

keymap.add("àa", "aire", true)
keymap.add("àc", "ction", true)
keymap.add("càd", "could", true)
keymap.add("shàd", "should", true)
keymap.add("àd", "would", true)
keymap.add("àê", "able", true)
keymap.add("àf", "iste", true)
keymap.add("àg", "ought", true)
keymap.add("àh", "ight", true)
keymap.add("ài", "ying", true)
keymap.add("àk", "ique", true)
keymap.add("àl", "elle", true)
keymap.add("àp", "ence", true)
keymap.add("àm", "isme", true)
keymap.add("àn", "ation", true)
keymap.add("àq", "ique", true)
keymap.add("àr", "erre", true)
keymap.add("às", "ement", true)
keymap.add("àt", "ettre", true)
keymap.add("àv", "ment", true)
keymap.add("àx", "ieux", true)
keymap.add("àz", "ez-vous", true)
keymap.add("à'", "ance", true)
keymap.add("à’", "ance", true)