-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/comma.toml
local keymap = require("keymap")

keymap.add(",f", "fl", true)
keymap.add(",g", "gl", true)
keymap.add(",h", "ph", true)
keymap.add(",z", "bj", true)
keymap.add(",v", "dv", true)
keymap.add(",n", "nl", true)
keymap.add(",t", "pt", true)
keymap.add(",r", "rq", true)
keymap.add(",q", "qu’", true)
keymap.add(",m", "ms", true)
keymap.add(",d", "ds", true)
keymap.add(",l", "cl", true)
keymap.add(",p", "xp", true)
keymap.add(",à", "j", true)
keymap.add(",a", "ja", true)
keymap.add(",e", "je", true)
keymap.add(",é", "jé", true)
keymap.add(",i", "ji", true)
keymap.add(",o", "jo", true)
keymap.add(",u", "ju", true)
keymap.add(",ê", "ju", true)
keymap.add(",'", "j’", true)
keymap.add(",è", "z", true)
keymap.add(",y", "k", true)
keymap.add(",c", "ç", true)
keymap.add(",x", "où", true)
keymap.add(",s", "q", true)