-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/comma.toml
local keymap = require("keymap")

keymap.add(",f", "fl", true, true, false)
keymap.add(",g", "gl", true, true, false)
keymap.add(",h", "ph", true, true, false)
keymap.add(",z", "bj", true, true, false)
keymap.add(",v", "dv", true, true, false)
keymap.add(",n", "nl", true, true, false)
keymap.add(",t", "pt", true, true, false)
keymap.add(",r", "rq", true, true, false)
keymap.add(",q", "qu’", true, true, false)
keymap.add(",m", "ms", true, true, false)
keymap.add(",d", "ds", true, true, false)
keymap.add(",l", "cl", true, true, false)
keymap.add(",p", "xp", true, true, false)
keymap.add(",à", "j", true, true, false)
keymap.add(",a", "ja", true, true, false)
keymap.add(",e", "je", true, true, false)
keymap.add(",é", "jé", true, true, false)
keymap.add(",i", "ji", true, true, false)
keymap.add(",o", "jo", true, true, false)
keymap.add(",u", "ju", true, true, false)
keymap.add(",ê", "ju", true, true, false)
keymap.add(",'", "j’", true, true, false)
keymap.add(",è", "z", true, true, false)
keymap.add(",y", "k", true, true, false)
keymap.add(",c", "ç", true, true, false)
keymap.add(",x", "où", true, true, false)
keymap.add(",s", "q", true, true, false)