-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/plus/suffixes.toml
local keymap = require("keymap")

keymap.add("àa", "aire", true, true, false)
keymap.add("àc", "ction", true, true, false)
keymap.add("càd", "could", true, true, false)
keymap.add("shàd", "should", true, true, false)
keymap.add("àd", "would", true, true, false)
keymap.add("àê", "able", true, true, false)
keymap.add("àf", "iste", true, true, false)
keymap.add("àg", "ought", true, true, false)
keymap.add("àh", "ight", true, true, false)
keymap.add("ài", "ying", true, true, false)
keymap.add("àk", "ique", true, true, false)
keymap.add("àl", "elle", true, true, false)
keymap.add("àp", "ence", true, true, false)
keymap.add("àm", "isme", true, true, false)
keymap.add("àn", "ation", true, true, false)
keymap.add("àq", "ique", true, true, false)
keymap.add("àr", "erre", true, true, false)
keymap.add("às", "ement", true, true, false)
keymap.add("àt", "ettre", true, true, false)
keymap.add("àv", "ment", true, true, false)
keymap.add("àx", "ieux", true, true, false)
keymap.add("àz", "ez-vous", true, true, false)
keymap.add("à'", "ance", true, true, false)
keymap.add("à’", "ance", true, true, false)