-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/sfb_reduction.toml
local keymap = require("keymap")

keymap.add("êé", "oe", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("éê", "eo", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("ê.", "u.", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("ê,", "u,", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("il a mà★", "il a mis à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("la mà★", "la mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ta mà★", "ta mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("ma mà★", "ma mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("e mà★", "e mise à jour", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("es mà★", "es mises à jour", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("mà★", "mettre à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("mià★", "mise à jour", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("pià★", "pièce jointe", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("tà★", "toujours", {is_word = true, auto_expand = true, is_case_sensitive = false})
keymap.add("à★", "bu", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àu", "ub", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("àé", "éi", {is_word = false, auto_expand = true, is_case_sensitive = false})
keymap.add("éà", "ié", {is_word = false, auto_expand = true, is_case_sensitive = false})