-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/symbols.toml
local keymap = require("keymap")

keymap.add("1/★", "⅟", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/2★", "½", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("0/3★", "↉", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/3★", "⅓", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("2/3★", "⅔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/4★", "¼", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("3/4★", "¾", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/5★", "⅕", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("2/5★", "⅖", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("3/5★", "⅗", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("4/5★", "⅘", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/6★", "⅙", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("5/6★", "⅚", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/8★", "⅛", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("3/8★", "⅜", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("5/8★", "⅝", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("7/8★", "⅞", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/7★", "⅐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/9★", "⅑", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("1/10★", "⅒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(0)★", "🄋", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(1)★", "➀", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(2)★", "➁", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(3)★", "➂", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(4)★", "➃", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(5)★", "➄", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(6)★", "➅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(7)★", "➆", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(8)★", "➇", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(9)★", "➈", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(10)★", "➉", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(0n)★", "🄌", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(1n)★", "➊", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(2n)★", "➋", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(3n)★", "➌", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(4n)★", "➍", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(5n)★", "➎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(6n)★", "➏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(7n)★", "➐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(8n)★", "➑", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(9n)★", "➒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(10n)★", "➓", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(0b)★", "𝟎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(1b)★", "𝟏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(2b)★", "𝟐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(3b)★", "𝟑", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(4b)★", "𝟒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(5b)★", "𝟓", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(6b)★", "𝟔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(7b)★", "𝟕", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(8b)★", "𝟖", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(9b)★", "𝟗", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(0g)★", "𝟬", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(1g)★", "𝟭", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(2g)★", "𝟮", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(3g)★", "𝟯", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(4g)★", "𝟰", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(5g)★", "𝟱", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(6g)★", "𝟲", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(7g)★", "𝟳", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(8g)★", "𝟴", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(9g)★", "𝟵", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(infini)★", "∞", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(product)★", "∏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(produit)★", "∏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(coproduct)★", "∐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(coproduit)★", "∐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(forall)★", "∀", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(for all)★", "∀", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(pour tout)★", "∀", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(exist)★", "∃", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(exists)★", "∃", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(vide)★", "∅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(ensemble vide)★", "∅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(void)★", "∅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(empty)★", "∅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(prop)★", "∝", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(proportionnel)★", "∝", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(proportionnal)★", "∝", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(union)★", "∪", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(intersection)★", "⋂", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(appartient)★", "∈", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(inclus)★", "⊂", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non inclus)★", "⊄", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non appartient)★", "∉", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(n’appartient pas)★", "∉", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non)★", "¬", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(et)★", "∧", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(sqrt)★", "√", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(racine)★", "√", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(^)★", "∧", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(v)★", "∨", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(delta)★", "∆", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(nabla)★", "∇", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(<<)★", "≪", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(partial)★", "∂", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(end of proof)★", "∎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(eop)★", "∎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(int)★", "∫", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(s)★", "∫", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(so)★", "∮", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(sso)★", "∯", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(sss)★", "∭", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(ssso)★", "∰", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(=)★", "≡", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(equivalent)★", "⇔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(équivalent)★", "⇔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(implique)★", "⇒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(impliqué)★", "⇒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(imply)★", "⇒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non implique)★", "⇏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non impliqué)★", "⇏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(non équivalent)★", "⇎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(not equivalent)★", "⇎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add(" -> ★", " ➜ ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("-->★", " ➜ ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add(">★", "➢", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("==>★", "⇒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("=/=>★", "⇏", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<==★", "⇐", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<==>★", "⇔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<=/=>★", "⇎", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<=>★", "⇔", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("^|★", "↑", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("|^★", "↓", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("->★", "→", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<-★", "←", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("->>★", "➡", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<<-★", "⬅", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("|->★", "↪", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("<-|★", "↩", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("^|-★", "⭮", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(x)★", "✗", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("[v]★", "☑", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("[x]★", "☒", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("/!\\★", "⚠", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("**★", "⁂", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("°C★", "℃", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(b)★", "•", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(c)★", "©", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("eme★", "ᵉ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("ème★", "ᵉ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("ieme★", "ᵉ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("ième★", "ᵉ", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(o)★", "•", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(r)★", "®", {is_word = true, auto_expand = true, is_case_sensitive = true})
keymap.add("(tm)★", "™", {is_word = true, auto_expand = true, is_case_sensitive = true})