-- Generated from /Users/b519hs/Documents/perso/ergopti/static/drivers/hotstrings/symbols.toml
local keymap = require("keymap")

keymap.add("1/★", "⅟", false, true, true)
keymap.add("1/2★", "½", false, true, true)
keymap.add("0/3★", "↉", false, true, true)
keymap.add("1/3★", "⅓", false, true, true)
keymap.add("2/3★", "⅔", false, true, true)
keymap.add("1/4★", "¼", false, true, true)
keymap.add("3/4★", "¾", false, true, true)
keymap.add("1/5★", "⅕", false, true, true)
keymap.add("2/5★", "⅖", false, true, true)
keymap.add("3/5★", "⅗", false, true, true)
keymap.add("4/5★", "⅘", false, true, true)
keymap.add("1/6★", "⅙", false, true, true)
keymap.add("5/6★", "⅚", false, true, true)
keymap.add("1/8★", "⅛", false, true, true)
keymap.add("3/8★", "⅜", false, true, true)
keymap.add("5/8★", "⅝", false, true, true)
keymap.add("7/8★", "⅞", false, true, true)
keymap.add("1/7★", "⅐", false, true, true)
keymap.add("1/9★", "⅑", false, true, true)
keymap.add("1/10★", "⅒", false, true, true)
keymap.add("(0)★", "🄋", false, true, true)
keymap.add("(1)★", "➀", false, true, true)
keymap.add("(2)★", "➁", false, true, true)
keymap.add("(3)★", "➂", false, true, true)
keymap.add("(4)★", "➃", false, true, true)
keymap.add("(5)★", "➄", false, true, true)
keymap.add("(6)★", "➅", false, true, true)
keymap.add("(7)★", "➆", false, true, true)
keymap.add("(8)★", "➇", false, true, true)
keymap.add("(9)★", "➈", false, true, true)
keymap.add("(10)★", "➉", false, true, true)
keymap.add("(0n)★", "🄌", false, true, true)
keymap.add("(1n)★", "➊", false, true, true)
keymap.add("(2n)★", "➋", false, true, true)
keymap.add("(3n)★", "➌", false, true, true)
keymap.add("(4n)★", "➍", false, true, true)
keymap.add("(5n)★", "➎", false, true, true)
keymap.add("(6n)★", "➏", false, true, true)
keymap.add("(7n)★", "➐", false, true, true)
keymap.add("(8n)★", "➑", false, true, true)
keymap.add("(9n)★", "➒", false, true, true)
keymap.add("(10n)★", "➓", false, true, true)
keymap.add("(0b)★", "𝟎", false, true, true)
keymap.add("(1b)★", "𝟏", false, true, true)
keymap.add("(2b)★", "𝟐", false, true, true)
keymap.add("(3b)★", "𝟑", false, true, true)
keymap.add("(4b)★", "𝟒", false, true, true)
keymap.add("(5b)★", "𝟓", false, true, true)
keymap.add("(6b)★", "𝟔", false, true, true)
keymap.add("(7b)★", "𝟕", false, true, true)
keymap.add("(8b)★", "𝟖", false, true, true)
keymap.add("(9b)★", "𝟗", false, true, true)
keymap.add("(0g)★", "𝟬", false, true, true)
keymap.add("(1g)★", "𝟭", false, true, true)
keymap.add("(2g)★", "𝟮", false, true, true)
keymap.add("(3g)★", "𝟯", false, true, true)
keymap.add("(4g)★", "𝟰", false, true, true)
keymap.add("(5g)★", "𝟱", false, true, true)
keymap.add("(6g)★", "𝟲", false, true, true)
keymap.add("(7g)★", "𝟳", false, true, true)
keymap.add("(8g)★", "𝟴", false, true, true)
keymap.add("(9g)★", "𝟵", false, true, true)
keymap.add("(infini)★", "∞", false, true, true)
keymap.add("(product)★", "∏", false, true, true)
keymap.add("(produit)★", "∏", false, true, true)
keymap.add("(coproduct)★", "∐", false, true, true)
keymap.add("(coproduit)★", "∐", false, true, true)
keymap.add("(forall)★", "∀", false, true, true)
keymap.add("(for all)★", "∀", false, true, true)
keymap.add("(pour tout)★", "∀", false, true, true)
keymap.add("(exist)★", "∃", false, true, true)
keymap.add("(exists)★", "∃", false, true, true)
keymap.add("(vide)★", "∅", false, true, true)
keymap.add("(ensemble vide)★", "∅", false, true, true)
keymap.add("(void)★", "∅", false, true, true)
keymap.add("(empty)★", "∅", false, true, true)
keymap.add("(prop)★", "∝", false, true, true)
keymap.add("(proportionnel)★", "∝", false, true, true)
keymap.add("(proportionnal)★", "∝", false, true, true)
keymap.add("(union)★", "∪", false, true, true)
keymap.add("(intersection)★", "⋂", false, true, true)
keymap.add("(appartient)★", "∈", false, true, true)
keymap.add("(inclus)★", "⊂", false, true, true)
keymap.add("(non inclus)★", "⊄", false, true, true)
keymap.add("(non appartient)★", "∉", false, true, true)
keymap.add("(n’appartient pas)★", "∉", false, true, true)
keymap.add("(non)★", "¬", false, true, true)
keymap.add("(et)★", "∧", false, true, true)
keymap.add("(sqrt)★", "√", false, true, true)
keymap.add("(racine)★", "√", false, true, true)
keymap.add("(^)★", "∧", false, true, true)
keymap.add("(v)★", "∨", false, true, true)
keymap.add("(delta)★", "∆", false, true, true)
keymap.add("(nabla)★", "∇", false, true, true)
keymap.add("(<<)★", "≪", false, true, true)
keymap.add("(partial)★", "∂", false, true, true)
keymap.add("(end of proof)★", "∎", false, true, true)
keymap.add("(eop)★", "∎", false, true, true)
keymap.add("(int)★", "∫", false, true, true)
keymap.add("(s)★", "∫", false, true, true)
keymap.add("(so)★", "∮", false, true, true)
keymap.add("(sso)★", "∯", false, true, true)
keymap.add("(sss)★", "∭", false, true, true)
keymap.add("(ssso)★", "∰", false, true, true)
keymap.add("(=)★", "≡", false, true, true)
keymap.add("(equivalent)★", "⇔", false, true, true)
keymap.add("(équivalent)★", "⇔", false, true, true)
keymap.add("(implique)★", "⇒", false, true, true)
keymap.add("(impliqué)★", "⇒", false, true, true)
keymap.add("(imply)★", "⇒", false, true, true)
keymap.add("(non implique)★", "⇏", false, true, true)
keymap.add("(non impliqué)★", "⇏", false, true, true)
keymap.add("(non équivalent)★", "⇎", false, true, true)
keymap.add("(not equivalent)★", "⇎", false, true, true)
keymap.add(" -> ★", " ➜ ", false, true, true)
keymap.add("-->★", " ➜ ", false, true, true)
keymap.add(">★", "➢", false, true, true)
keymap.add("==>★", "⇒", false, true, true)
keymap.add("=/=>★", "⇏", false, true, true)
keymap.add("<==★", "⇐", false, true, true)
keymap.add("<==>★", "⇔", false, true, true)
keymap.add("<=/=>★", "⇎", false, true, true)
keymap.add("<=>★", "⇔", false, true, true)
keymap.add("^|★", "↑", false, true, true)
keymap.add("|^★", "↓", false, true, true)
keymap.add("->★", "→", false, true, true)
keymap.add("<-★", "←", false, true, true)
keymap.add("->>★", "➡", false, true, true)
keymap.add("<<-★", "⬅", false, true, true)
keymap.add("|->★", "↪", false, true, true)
keymap.add("<-|★", "↩", false, true, true)
keymap.add("^|-★", "⭮", false, true, true)
keymap.add("(x)★", "✗", false, true, true)
keymap.add("[v]★", "☑", false, true, true)
keymap.add("[x]★", "☒", false, true, true)
keymap.add("/!\\★", "⚠", false, true, true)
keymap.add("**★", "⁂", false, true, true)
keymap.add("°C★", "℃", false, true, true)
keymap.add("(b)★", "•", false, true, true)
keymap.add("(c)★", "©", false, true, true)
keymap.add("eme★", "ᵉ", false, true, true)
keymap.add("ème★", "ᵉ", false, true, true)
keymap.add("ieme★", "ᵉ", false, true, true)
keymap.add("ième★", "ᵉ", false, true, true)
keymap.add("(o)★", "•", false, true, true)
keymap.add("(r)★", "®", false, true, true)
keymap.add("(tm)★", "™", false, true, true)