; _generated/window_titles.ahk

; Generated by tools/codegen/codegen-window-titles.cjs; do not edit.
; Source: _shared/ui/apps.manifest.json window_title.

/**
 * Composes a native caption from an already-translated, brandless label.
 * @param {string} Label - The window's translated name.
 * @returns {string} The shared-policy caption.
 */
WindowTitle(Label := "") {
	Prefix := "ErgoptiPlus"
	Separator := " — "
	if Label == ""
		return Prefix
	if Prefix == ""
		return Label
	return Prefix . Separator . Label
}
