--- _generated/action_catalogue.lua
--- AUTO-GENERATED from _shared/modules/actions/actions.toml.
--- DO NOT EDIT BY HAND — run `npm run codegen:action-catalogue` to refresh.

--- ==============================================================================
--- MODULE: Action Catalogue (Linux)
--- DESCRIPTION:
--- Every action the Linux driver offers, already filtered to its platform:
--- the picker order with heading levels and locale keys, the modifier-chord
--- block the driver expands from its own chord registry, and per-action
--- metadata (label key, parameter kind, confirmation, requirements). The
--- driver loads this table instead of parsing the shared TOML at runtime.
--- ==============================================================================

return {
	platform = "linux",
	sg_items = {
		{ kind = "action", id = "none" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_input" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.mouse_nav" },
		{ kind = "action", id = "left_click_toggle" },
		{ kind = "action", id = "right_click_toggle" },
		{ kind = "action", id = "app_switcher" },
		{ kind = "action", id = "app_window_previous" },
		{ kind = "action", id = "alt_tab_monitor" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.edition" },
		{ kind = "action", id = "copy" },
		{ kind = "action", id = "paste" },
		{ kind = "action", id = "cut" },
		{ kind = "action", id = "undo" },
		{ kind = "action", id = "redo" },
		{ kind = "action", id = "select_all" },
		{ kind = "action", id = "find" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.keys" },
		{ kind = "action", id = "enter" },
		{ kind = "action", id = "tab" },
		{ kind = "action", id = "escape" },
		{ kind = "action", id = "backspace" },
		{ kind = "action", id = "delete" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_windows" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.tabs" },
		{ kind = "action", id = "tab_new" },
		{ kind = "action", id = "tab_close" },
		{ kind = "action", id = "tab_prev" },
		{ kind = "action", id = "tab_next" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.windows" },
		{ kind = "action", id = "win_prev" },
		{ kind = "action", id = "win_next" },
		{ kind = "action", id = "close_window" },
		{ kind = "action", id = "fullscreen" },
		{ kind = "action", id = "snap_left" },
		{ kind = "action", id = "snap_right" },
		{ kind = "action", id = "maximize" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.spaces" },
		{ kind = "action", id = "desktop_prev" },
		{ kind = "action", id = "desktop_next" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_text" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.cursor" },
		{ kind = "action", id = "arrow_up" },
		{ kind = "action", id = "arrow_down" },
		{ kind = "action", id = "arrow_left" },
		{ kind = "action", id = "arrow_right" },
		{ kind = "action", id = "word_prev" },
		{ kind = "action", id = "word_next" },
		{ kind = "action", id = "line_up" },
		{ kind = "action", id = "line_down" },
		{ kind = "action", id = "line_start" },
		{ kind = "action", id = "line_end" },
		{ kind = "action", id = "para_prev" },
		{ kind = "action", id = "para_next" },
		{ kind = "action", id = "doc_start" },
		{ kind = "action", id = "doc_end" },
		{ kind = "action", id = "home" },
		{ kind = "action", id = "end" },
		{ kind = "action", id = "page_up" },
		{ kind = "action", id = "page_down" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.selection" },
		{ kind = "action", id = "sel_up" },
		{ kind = "action", id = "sel_down" },
		{ kind = "action", id = "sel_left" },
		{ kind = "action", id = "sel_right" },
		{ kind = "action", id = "sel_word_prev" },
		{ kind = "action", id = "sel_word_next" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.modifier_chords" },
		{ kind = "modifier_chords", level = 2, group_key = "sg_actions.sg_order.header.modifier_chord_group" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_media" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.media" },
		{ kind = "action", id = "vol_up" },
		{ kind = "action", id = "vol_down" },
		{ kind = "action", id = "mute" },
		{ kind = "action", id = "brightness_up" },
		{ kind = "action", id = "brightness_down" },
		{ kind = "action", id = "track_play" },
		{ kind = "action", id = "track_next" },
		{ kind = "action", id = "track_prev" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.screenshot" },
		{ kind = "action", id = "screenshot_window_clipboard" },
		{ kind = "action", id = "screenshot_window_save" },
		{ kind = "action", id = "screenshot_region_clipboard" },
		{ kind = "action", id = "screenshot_region_save" },
		{ kind = "action", id = "screenshot_fullscreen_clipboard" },
		{ kind = "action", id = "screenshot_fullscreen_save" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_system" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.system" },
		{ kind = "action", id = "lock_screen" },
		{ kind = "action", id = "notification_center" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.system_actions" },
		{ kind = "action", id = "select_line" },
		{ kind = "action", id = "open_url" },
		{ kind = "action", id = "search_web" },
		{ kind = "action", id = "toggle_capslock" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.tapholds" },
		{ kind = "action", id = "ctrl_backspace" },
		{ kind = "action", id = "ctrl_delete" },
		{ kind = "action", id = "space" },
		{ kind = "action", id = "caps_lock" },
		{ kind = "heading", level = 1, key = "sg_actions.sg_order.header.grp_app" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.ui" },
		{ kind = "action", id = "open_metrics_typing" },
		{ kind = "action", id = "open_metrics_apps" },
		{ kind = "action", id = "open_hotstrings_editor" },
		{ kind = "action", id = "open_paths_editor" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.files" },
		{ kind = "action", id = "open_script_source" },
		{ kind = "action", id = "open_personal_shortcuts" },
		{ kind = "action", id = "open_personal_hotstrings" },
		{ kind = "action", id = "open_personal_info" },
		{ kind = "action", id = "open_config" },
		{ kind = "action", id = "open_logs_folder" },
		{ kind = "action", id = "open_today_log" },
		{ kind = "action", id = "open_error_log" },
		{ kind = "heading", level = 2, key = "sg_actions.sg_order.header.script" },
		{ kind = "action", id = "script_pause_toggle" },
		{ kind = "action", id = "script_reload" },
		{ kind = "action", id = "script_save_reload" },
		{ kind = "action", id = "script_quit" },
	},
	ax_items = {},
	actions = {
		["alt_tab_monitor"] = { family = "sg", label_key = "sg_actions.alt_tab_monitor" },
		["app_switcher"] = { family = "sg", label_key = "sg_actions.app_switcher" },
		["app_window_previous"] = { family = "sg", label_key = "sg_actions.app_window_previous" },
		["arrow_down"] = { family = "sg", label_key = "sg_actions.arrow_down" },
		["arrow_left"] = { family = "sg", label_key = "sg_actions.arrow_left" },
		["arrow_right"] = { family = "sg", label_key = "sg_actions.arrow_right" },
		["arrow_up"] = { family = "sg", label_key = "sg_actions.arrow_up" },
		["backspace"] = { family = "sg", label_key = "sg_actions.backspace" },
		["brightness_down"] = { family = "sg", label_key = "sg_actions.brightness_down" },
		["brightness_up"] = { family = "sg", label_key = "sg_actions.brightness_up" },
		["caps_lock"] = { family = "sg", label_key = "sg_actions.caps_lock" },
		["close_window"] = { family = "sg", label_key = "sg_actions.close_window" },
		["copy"] = { family = "sg", label_key = "sg_actions.copy" },
		["ctrl_backspace"] = { family = "sg", label_key = "sg_actions.ctrl_backspace" },
		["ctrl_delete"] = { family = "sg", label_key = "sg_actions.ctrl_delete" },
		["cut"] = { family = "sg", label_key = "sg_actions.cut" },
		["delete"] = { family = "sg", label_key = "sg_actions.delete" },
		["desktop_next"] = { family = "sg", label_key = "sg_actions.desktop_next", requires = { "session:x11" } },
		["desktop_prev"] = { family = "sg", label_key = "sg_actions.desktop_prev", requires = { "session:x11" } },
		["doc_end"] = { family = "sg", label_key = "sg_actions.doc_end" },
		["doc_start"] = { family = "sg", label_key = "sg_actions.doc_start" },
		["end"] = { family = "sg", label_key = "sg_actions.end" },
		["enter"] = { family = "sg", label_key = "sg_actions.enter" },
		["escape"] = { family = "sg", label_key = "sg_actions.escape" },
		["find"] = { family = "sg", label_key = "sg_actions.find" },
		["fullscreen"] = { family = "sg", label_key = "sg_actions.fullscreen" },
		["home"] = { family = "sg", label_key = "sg_actions.home" },
		["left_click_toggle"] = { family = "sg", label_key = "sg_actions.left_click_toggle", requires = { "session:x11", "tool:xdotool" } },
		["line_down"] = { family = "sg", label_key = "sg_actions.line_down" },
		["line_end"] = { family = "sg", label_key = "sg_actions.line_end" },
		["line_start"] = { family = "sg", label_key = "sg_actions.line_start" },
		["line_up"] = { family = "sg", label_key = "sg_actions.line_up" },
		["lock_screen"] = { family = "sg", label_key = "sg_actions.lock_screen" },
		["maximize"] = { family = "sg", label_key = "sg_actions.maximize" },
		["mute"] = { family = "sg", label_key = "sg_actions.mute" },
		["none"] = { family = "sg", label_key = "sg_actions.none" },
		["notification_center"] = { family = "sg", label_key = "sg_actions.notification_center" },
		["open_config"] = { family = "sg", label_key = "sg_actions.open_config" },
		["open_error_log"] = { family = "sg", label_key = "sg_actions.open_error_log" },
		["open_hotstrings_editor"] = { family = "sg", label_key = "sg_actions.open_hotstrings_editor" },
		["open_logs_folder"] = { family = "sg", label_key = "sg_actions.open_logs_folder" },
		["open_metrics_apps"] = { family = "sg", label_key = "sg_actions.open_metrics_apps" },
		["open_metrics_typing"] = { family = "sg", label_key = "sg_actions.open_metrics_typing" },
		["open_paths_editor"] = { family = "sg", label_key = "sg_actions.open_paths_editor" },
		["open_personal_hotstrings"] = { family = "sg", label_key = "sg_actions.open_personal_hotstrings" },
		["open_personal_info"] = { family = "sg", label_key = "sg_actions.open_personal_info" },
		["open_personal_shortcuts"] = { family = "sg", label_key = "sg_actions.open_personal_shortcuts" },
		["open_script_source"] = { family = "sg", label_key = "sg_actions.open_script_source" },
		["open_today_log"] = { family = "sg", label_key = "sg_actions.open_today_log" },
		["open_url"] = { family = "sg", label_key = "sg_actions.open_url", parameter = "url", requires = { "tool:xdg-open" } },
		["page_down"] = { family = "sg", label_key = "sg_actions.page_down" },
		["page_up"] = { family = "sg", label_key = "sg_actions.page_up" },
		["para_next"] = { family = "sg", label_key = "sg_actions.para_next" },
		["para_prev"] = { family = "sg", label_key = "sg_actions.para_prev" },
		["paste"] = { family = "sg", label_key = "sg_actions.paste" },
		["redo"] = { family = "sg", label_key = "sg_actions.redo" },
		["right_click_toggle"] = { family = "sg", label_key = "sg_actions.right_click_toggle", requires = { "session:x11", "tool:xdotool" } },
		["screenshot_fullscreen_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_fullscreen_clipboard" },
		["screenshot_fullscreen_save"] = { family = "sg", label_key = "sg_actions.screenshot_fullscreen_save" },
		["screenshot_region_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_region_clipboard" },
		["screenshot_region_save"] = { family = "sg", label_key = "sg_actions.screenshot_region_save" },
		["screenshot_window_clipboard"] = { family = "sg", label_key = "sg_actions.screenshot_window_clipboard" },
		["screenshot_window_save"] = { family = "sg", label_key = "sg_actions.screenshot_window_save" },
		["script_pause_toggle"] = { family = "sg", label_key = "sg_actions.script_pause_toggle" },
		["script_quit"] = { family = "sg", label_key = "sg_actions.script_quit" },
		["script_reload"] = { family = "sg", label_key = "sg_actions.script_reload" },
		["script_save_reload"] = { family = "sg", label_key = "sg_actions.script_save_reload" },
		["search_web"] = { family = "sg", label_key = "sg_actions.search_web", parameter = "search_url", requires = { "tool:xclip", "tool:xdg-open" } },
		["sel_down"] = { family = "sg", label_key = "sg_actions.sel_down" },
		["sel_left"] = { family = "sg", label_key = "sg_actions.sel_left" },
		["sel_right"] = { family = "sg", label_key = "sg_actions.sel_right" },
		["sel_up"] = { family = "sg", label_key = "sg_actions.sel_up" },
		["sel_word_next"] = { family = "sg", label_key = "sg_actions.sel_word_next" },
		["sel_word_prev"] = { family = "sg", label_key = "sg_actions.sel_word_prev" },
		["select_all"] = { family = "sg", label_key = "sg_actions.select_all" },
		["select_line"] = { family = "sg", label_key = "sg_actions.select_line" },
		["snap_left"] = { family = "sg", label_key = "sg_actions.snap_left" },
		["snap_right"] = { family = "sg", label_key = "sg_actions.snap_right" },
		["space"] = { family = "sg", label_key = "sg_actions.space" },
		["tab"] = { family = "sg", label_key = "sg_actions.tab" },
		["tab_close"] = { family = "sg", label_key = "sg_actions.tab_close" },
		["tab_new"] = { family = "sg", label_key = "sg_actions.tab_new" },
		["tab_next"] = { family = "sg", label_key = "sg_actions.tab_next" },
		["tab_prev"] = { family = "sg", label_key = "sg_actions.tab_prev" },
		["toggle_capslock"] = { family = "sg", label_key = "sg_actions.toggle_capslock" },
		["track_next"] = { family = "sg", label_key = "sg_actions.track_next" },
		["track_play"] = { family = "sg", label_key = "sg_actions.track_play" },
		["track_prev"] = { family = "sg", label_key = "sg_actions.track_prev" },
		["undo"] = { family = "sg", label_key = "sg_actions.undo" },
		["vol_down"] = { family = "sg", label_key = "sg_actions.vol_down" },
		["vol_up"] = { family = "sg", label_key = "sg_actions.vol_up" },
		["win_next"] = { family = "sg", label_key = "sg_actions.win_next" },
		["win_prev"] = { family = "sg", label_key = "sg_actions.win_prev" },
		["word_next"] = { family = "sg", label_key = "sg_actions.word_next" },
		["word_prev"] = { family = "sg", label_key = "sg_actions.word_prev" },
	},
	slots = {
		single = { "tap_2", "tap_3", "tap_4", "tap_5", "swipe_2_left", "swipe_2_right", "swipe_2_up", "swipe_2_down", "swipe_2_left_up", "swipe_2_right_up", "swipe_2_left_down", "swipe_2_right_down", "swipe_3_left", "swipe_3_right", "swipe_3_up", "swipe_3_down", "swipe_3_left_up", "swipe_3_right_up", "swipe_3_left_down", "swipe_3_right_down", "swipe_4_left", "swipe_4_right", "swipe_4_up", "swipe_4_down", "swipe_4_left_up", "swipe_4_right_up", "swipe_4_left_down", "swipe_4_right_down", "swipe_5_left", "swipe_5_right", "swipe_5_up", "swipe_5_down", "swipe_5_left_up", "swipe_5_right_up", "swipe_5_left_down", "swipe_5_right_down" },
		axis = { "swipe_3_horiz", "swipe_4_horiz", "swipe_5_horiz" },
	},
}
