--- modules/llm/bootstrap_retry_generated.lua
--- Generated by tools/codegen/codegen-bootstrap-retry.cjs; do not edit.
--- Source: _shared/modules/network/bootstrap_retry.json.
return {
	admission_seconds = 30,
	idle_seconds = 60,
	retirement_seconds = 600,
	source_sha256 = "33402cf0fe7a4caecece502a8788e98d39de73ee3fd7fc64c6b1b79f200c8820",
}
