--- modules/llm/parser.lua

--- ==============================================================================
--- MODULE: LLM Output Parser (Hammerspoon shim)
--- DESCRIPTION:
--- Hammerspoon-local re-export of the shared, platform-neutral LLM output parser
--- (_shared/lua/llm/parser.lua). The shared module is PURE; the only OS-specific
--- inputs it needs are the min/max word limits, which this shim resolves from the
--- Hammerspoon settings store (falling back to the llm DEFAULT_STATE) and threads
--- into process_prediction's opts. Every other function (strip_thinking,
--- split_blocks) is re-exported unchanged — the same pattern as infra/text_utils.lua.
--- ==============================================================================

local Shared = require("llm.parser")

-- Re-export the shared surface by delegation; only process_prediction is wrapped
-- to inject the OS-specific word limits. strip_thinking / split_blocks resolve
-- straight through to the shared implementation via the metatable __index.
local M = setmetatable({}, { __index = Shared })

--- Resolves the min/max word limits from the Hammerspoon settings store (with the
--- llm DEFAULT_STATE fallback) and delegates to the shared parser. The signature
--- is unchanged for every caller (api_ollama / api_mlx / api_remote /
--- streaming_handler), so the OS coupling lives only here.
--- @param full_text string The full user context provided to the LLM.
--- @param tail_text string The current end of the user’s input.
--- @param block string The raw block of text generated by the model.
--- @return table|nil A table containing prediction data or nil if invalid.
function M.process_prediction(full_text, tail_text, block)
	local Core  = require("modules.llm.init")
	local min_w = tonumber(hs.settings.get("llm_min_words")) or Core.DEFAULT_STATE.llm_min_words
	local max_w = tonumber(hs.settings.get("llm_max_words")) or Core.DEFAULT_STATE.llm_max_words
	return Shared.process_prediction(full_text, tail_text, block,
		{ min_words = min_w, max_words = max_w })
end

return M
