--- tests/unit/adapters/test_managed_prepared_queue.lua

--- ==============================================================================
--- MODULE: Public Managed HTTP Prepared Replacement Controls
--- DESCRIPTION:
--- Uses the actual public wrapper, native engine and shared policy with explicit
--- native process/handle/group acknowledgements. These are models, not OS proof.
--- ==============================================================================

local helpers = require("tests.helpers")
local Ports = require("tests.support.managed_http_native_ports")
local url = "http://127.0.0.1:9000/fixed"
local function options() return { owner = "prepared-owner", timeout_ms = 1000 } end
local wire = "fixed body\nERGOPTI_HTTP_STATUS:200\n"

helpers.describe("public immutable preparation and owned replacement", function()
	helpers.it("converts an admitted header once across real preflight and dispatch", function()
		local client, state = Ports.fresh_client()
		local conversions = 0
		local value = setmetatable({}, { __tostring = function() conversions = conversions + 1; return "fixed value" end })
		local result
		local operation = client.get_owned(url, { ["X-Fixed"] = value }, options(), function(r) result = r end)
		helpers.assert_true(operation.started)
		helpers.assert_eq(conversions, 1)
		helpers.assert_true(state.config:find('header = "X-Fixed: fixed value"', 1, true) ~= nil)
		state.complete_request(1, wire)
		helpers.assert_true(operation:is_settled())
		helpers.assert_true(result.ok)
		helpers.assert_eq(conversions, 1)
	end)
	helpers.it("publishes an initial malformed-header refusal without native allocation", function()
		local client, state = Ports.fresh_client()
		local result, callbacks = nil, 0
		local operation = client.get_owned(url, { ["X-Fixed"] = setmetatable({}, { __tostring = function() error("fixed metadata refusal") end }) }, options(), function(r) result, callbacks = r, callbacks + 1 end)
		helpers.assert_eq(operation.started, false)
		helpers.assert_true(operation:is_settled())
		helpers.assert_eq(#state.requests + #state.handles + #state.deadlines, 0)
		helpers.assert_eq(callbacks, 1)
		helpers.assert_eq(result.ok, false)
	end)
	helpers.it("queues a once-prepared owned replacement until every old close ACK", function()
		local client, state = Ports.fresh_client({ defer_close = true })
		local old, current, conversions = nil, nil, 0
		helpers.assert_true(client.get(url, {}, options(), function(r) old = r end))
		local header = setmetatable({}, { __tostring = function() conversions = conversions + 1; return "fixed successor" end })
		local operation = client.get_owned(url, { ["X-Fixed"] = header }, options(), function(r) current = r end)
		helpers.assert_true(operation.started)
		helpers.assert_eq(conversions, 1)
		helpers.assert_eq(#state.requests, 1)
		helpers.assert_eq(operation:is_settled(), false)
		state.complete_request(1, "", 143)
		helpers.assert_eq(#state.requests, 1)
		helpers.assert_eq(current, nil)
		state.ack_closes()
		helpers.assert_eq(#state.requests, 2)
		helpers.assert_true(state.config:find('header = "X-Fixed: fixed successor"', 1, true) ~= nil)
		helpers.assert_eq(conversions, 1)
		state.complete_request(2, wire)
		helpers.assert_eq(current, nil)
		state.ack_closes()
		helpers.assert_true(operation:is_settled())
		helpers.assert_true(current.ok)
		helpers.assert_eq(old, nil)
	end)
	helpers.it("leaves a valid boolean incumbent running after invalid owned preparation", function()
		local client, state = Ports.fresh_client()
		helpers.assert_true(client.get(url, {}, options(), function() end))
		local kills, result = #state.kills, nil
		local refused = client.get_owned(url, { ["X-Fixed"] = "invalid\0value" }, options(), function(r) result = r end)
		helpers.assert_eq(refused.started, false)
		helpers.assert_true(refused:is_settled())
		helpers.assert_eq(result.ok, false)
		helpers.assert_eq(#state.requests, 1)
		helpers.assert_eq(#state.kills, kills)
		helpers.assert_true(client.isActive("prepared-owner"))
		state.complete_request(1, wire)
	end)
	helpers.it("refuses owned incumbent metadata without evaluating it", function()
		local client, state = Ports.fresh_client()
		local incumbent = client.get_owned(url, {}, options(), function() end)
		local conversions, result = 0, nil
		local header = setmetatable({}, { __tostring = function() conversions = conversions + 1; error("must not convert") end })
		local refused = client.get_owned(url, { ["X-Fixed"] = header }, options(), function(r) result = r end)
		helpers.assert_eq(refused.started, false)
		helpers.assert_true(refused:is_settled())
		helpers.assert_eq(result.error, "previous request cleanup pending")
		helpers.assert_eq(conversions, 0)
		helpers.assert_true(client.isActive("prepared-owner"))
		state.complete_request(1, wire)
		helpers.assert_true(incumbent:is_settled())
	end)
	helpers.it("does not dispatch a cancelled queued successor after predecessor retirement", function()
		local client, state = Ports.fresh_client({ defer_close = true })
		helpers.assert_true(client.get(url, {}, options(), function() end))
		local callbacks = 0
		local successor = client.get_owned(url, {}, options(), function() callbacks = callbacks + 1 end)
		helpers.assert_true(successor.started)
		helpers.assert_eq(successor:cancel(), false)
		state.complete_request(1, "", 143)
		state.ack_closes()
		helpers.assert_true(successor:is_settled())
		helpers.assert_eq(#state.requests, 1)
		helpers.assert_eq(callbacks, 0)
	end)
	helpers.it("expires a queued owned replacement without acquiring a successor child", function()
		local client, state = Ports.fresh_client({ defer_close = true })
		helpers.assert_true(client.get(url, {}, options(), function() end))
		local result
		local successor = client.get_owned(url, {}, { owner = "prepared-owner", timeout_ms = 10 }, function(r) result = r end)
		helpers.assert_true(successor.started)
		state.time = 11
		state.fire_deadlines()
		helpers.assert_eq(result, nil)
		helpers.assert_eq(successor:is_settled(), false)
		helpers.assert_eq(#state.requests, 1)
		state.complete_request(1, "", 143)
		state.ack_closes()
		helpers.assert_true(successor:is_settled())
		helpers.assert_eq(result.error, "timeout")
		helpers.assert_eq(#state.requests, 1)
	end)
	helpers.it("failed successor timer arming does not cancel the valid incumbent", function()
		local client, state = Ports.fresh_client({ refuse_deadline_arm_index = 2, defer_deadline_index = 2 })
		helpers.assert_true(client.get(url, {}, options(), function() end))
		local kills, result = #state.kills, nil
		local successor = client.get_owned(url, {}, options(), function(r) result = r end)
		helpers.assert_eq(successor.started, false)
		helpers.assert_eq(successor:is_settled(), false)
		helpers.assert_eq(result, nil)
		helpers.assert_eq(#state.kills, kills)
		state.deadlines[2].ack()
		helpers.assert_true(successor:is_settled())
		helpers.assert_eq(result.error, "managed-http-deadline-unavailable")
		helpers.assert_true(client.isActive("prepared-owner"))
		state.complete_request(1, wire)
	end)
	helpers.it("cancellation during header conversion cannot acquire a successor child", function()
		local client, state = Ports.fresh_client({ defer_close = true })
		helpers.assert_true(client.get(url, {}, options(), function() end))
		local calls = 0
		local header = setmetatable({}, { __tostring = function() calls = calls + 1; client.cancel("prepared-owner"); return "fixed" end })
		local callbacks = 0
		local successor = client.get_owned(url, { ["X-Fixed"] = header }, options(), function() callbacks = callbacks + 1 end)
		helpers.assert_eq(calls, 1)
		helpers.assert_eq(callbacks, 0)
		helpers.assert_eq(successor.started, false)
		helpers.assert_eq(#state.requests, 1)
		state.complete_request(1, "", 143)
		state.ack_closes()
		helpers.assert_true(successor:is_settled())
		helpers.assert_eq(#state.requests, 1)
		helpers.assert_eq(callbacks, 0)
	end)
end)
