--- _shared/lua/hotstrings/personal_files.lua

--- Generated by tools/codegen/codegen-personal-file-descriptors.cjs; do not edit.
--- Source: _shared/modules/hotstrings/personal_files.json.
local M = {}
local Utf8 = require("compat.utf8")
local NAMESPACE = "personal-file:"
local SEPARATOR = ":"
local LABEL_SEPARATOR = " / "
local EXTENSION = ".toml"

-- Adoption policy is separate from the exact three-field provenance descriptor.
M.additional_default_enabled = true
M.additional_priority_tier = "package"
M.additional_default_delay_seconds = 0
M.additional_scan_max_depth = 16

--- Preserve actual filename components, independent of labels or activation groups.
--- @param components table Dense relative filename components, including .toml.
--- @return table descriptor Fresh id, components and label fields.
function M.describe(components)
	assert(type(components) == "table" and #components > 0, "invalid personal-file components")
	local count, copied, encoded, labels = 0, {}, {}, {}
	for key in pairs(components) do
		assert(type(key) == "number" and key % 1 == 0 and key >= 1 and key <= #components,
			"invalid personal-file component array")
		count = count + 1
	end
	assert(count == #components, "sparse personal-file components")
	for index, component in ipairs(components) do
		assert(type(component) == "string" and component ~= "" and component ~= "." and component ~= ".."
			and not component:find("/", 1, true) and not component:find("\0", 1, true)
			and Utf8.len(component) ~= nil, "invalid personal-file component")
		copied[index], labels[index] = component, component
		encoded[index] = component:gsub(".", function(byte) return string.format("%02x", byte:byte()) end)
	end
	local last = copied[#copied]
	assert(last:sub(-#EXTENSION):lower() == EXTENSION,
		"personal source is not a TOML filename")
	labels[#labels] = last:sub(1, -#EXTENSION - 1)
	return { id = NAMESPACE .. table.concat(encoded, SEPARATOR), components = copied,
		label = table.concat(labels, LABEL_SEPARATOR) }
end

--- Decode only canonical identities; aliases, malformed UTF-8 and traversal refuse.
--- @param id any Canonical identity.
--- @return table|nil components Fresh exact components, or nil on refusal.
function M.components(id)
	if type(id) ~= "string" or id:sub(1, #NAMESPACE) ~= NAMESPACE then return nil end
	local body, decoded = id:sub(#NAMESPACE + 1), {}
	if body == "" or body:sub(1, 1) == SEPARATOR or body:sub(-1) == SEPARATOR
		or body:find(SEPARATOR .. SEPARATOR, 1, true) then return nil end
	for part in body:gmatch("[^:]+") do
		if #part % 2 ~= 0 or part:find("[^0-9a-f]") then return nil end
		decoded[#decoded + 1] = part:gsub("..", function(hex) return string.char(tonumber(hex, 16)) end)
	end
	local ok, descriptor = pcall(M.describe, decoded)
	if not ok or descriptor.id ~= id then return nil end
	return descriptor.components
end

--- Reject forged ids, borrowed labels and extra descriptor fields before transport.
--- @param descriptor any Candidate descriptor.
--- @return boolean
function M.is_descriptor(descriptor)
	if type(descriptor) ~= "table" then return false end
	local count = 0
	for key in pairs(descriptor) do
		if key ~= "id" and key ~= "components" and key ~= "label" then return false end
		count = count + 1
	end
	if count ~= 3 then return false end
	local ok, expected = pcall(M.describe, descriptor.components)
	return ok and expected.id == descriptor.id and expected.label == descriptor.label
end

--- Neutral activation policy for exact canonical file/section preference paths.
--- Classification is not admission to a native capability or source mutation.
--- @param path any Semantic path, with quoted dotted section components.
--- @return boolean|nil
function M.preference_default(path)
	local parts = require("toml_codec.key_path").parse(path, true)
	if not parts or parts[1] ~= "hotstrings" then return nil end
	if #parts == 3 and parts[2] == "groups" and M.components(parts[3]) then
		return M.additional_default_enabled
	end
	if #parts == 4 and parts[2] == "modules" and M.components(parts[3]) and parts[4] ~= "" then
		return M.additional_default_enabled
	end
	return nil
end

--- Own the snapshot so callers cannot mutate another source's provenance.
--- @param descriptor table Valid descriptor.
--- @return table copy
function M.copy(descriptor)
	assert(M.is_descriptor(descriptor), "invalid personal-file descriptor")
	return M.describe(descriptor.components)
end

return M
