# tools/diagnostics/pkgutil_capability_fixture.py
"""TEST ONLY: prepare one inert package and observe actual full-expansion capability.

Package generation is not capability evidence. The ordinary SDK Guardian owns
all children; this preparation retains its original single 25-second deadline.
"""

import base64
import hashlib
import json
import os
from pathlib import Path
import signal
import stat
import subprocess
import sys
import time
import types

ROOT = Path(__file__).resolve().parent
REFERENCE_SHA256 = "5c8e6d89177c23697e6910fa5a2ca7245617cfc066b3b85f04c5b422fe06bc4a"
TOOLS = {"pkgbuild": Path("/usr/bin/pkgbuild"), "pkgutil": Path("/usr/sbin/pkgutil")}
MARKER_NAME = "ergopti-capability.txt"
MARKER = b"Ergopti pkgutil capability fixture\n"
IDENTIFIER = "org.ergopti.test.pkgutil-capability"
PACKAGE_LIMIT = 16384
PACKET_LIMIT = 65536


class Refusal(Exception):
    """Fixed test-only refusal; never supplies install or runtime authority."""


def require(value, code):
    if not value:
        raise Refusal(code)


def captured(path, maximum):
    """Read one bounded real single-link file while retaining its exact identity."""
    descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    try:
        before = os.fstat(descriptor)
        require(
            stat.S_ISREG(before.st_mode)
            and before.st_nlink == 1
            and not before.st_mode & 0o022
            and 0 < before.st_size <= maximum,
            "input_type",
        )
        body = bytearray()
        while len(body) <= before.st_size:
            block = os.read(descriptor, min(65536, before.st_size + 1 - len(body)))
            if not block:
                break
            body.extend(block)
        fields = (
            "st_dev",
            "st_ino",
            "st_mode",
            "st_uid",
            "st_gid",
            "st_size",
            "st_mtime_ns",
            "st_ctime_ns",
        )

        def identity(value):
            return tuple(getattr(value, field) for field in fields)

        require(
            len(body) == before.st_size
            and identity(before) == identity(os.fstat(descriptor)) == identity(path.lstat()),
            "input_changed",
        )
        return bytes(body), identity(before)
    finally:
        os.close(descriptor)


def reference():
    path = ROOT / "installed_vhd_reference_fixture.py"
    body, _ = captured(path, 1048576)
    require(hashlib.sha256(body).hexdigest() == REFERENCE_SHA256, "source_pin")
    module = types.ModuleType("captured_reference")
    module.__file__ = str(path)
    exec(compile(body, str(path), "exec"), module.__dict__)
    return module


def expanded_marker(reference, output):
    """Expected membership and marker bytes are handwritten, never generated by pkgbuild."""
    expected = {
        "Bom": ("file", 0o644),
        "PackageInfo": ("file", 0o644),
        "Payload": ("directory", 0o755),
        "Payload/ergopti-capability.txt": ("file", 0o644),
    }
    actual = reference.inventory(output, maximum_nodes=16, maximum_bytes=65536)
    require(set(actual) == set(expected), "expanded_tree")
    for name, (kind, mode) in expected.items():
        row = actual[name]
        require(
            row["kind"] == kind
            and stat.S_IMODE(row["identity"]["mode"]) == mode
            and row["identity"]["uid"] == os.geteuid(),
            "expanded_tree",
        )
    require(captured(output / "Payload" / MARKER_NAME, 1024)[0] == MARKER, "expanded_marker")
    return actual


def prepare(owner, deadline, reference, stage):
    require(sys.platform == "darwin" and os.geteuid() != 0, "native_prerequisite")
    owner = Path(owner)
    require(
        owner.is_absolute()
        and owner.resolve(strict=True) == owner
        and owner.stat().st_uid == os.geteuid()
        and stat.S_IMODE(owner.stat().st_mode) == 0o700,
        "owner",
    )
    require(os.listdir(owner) == [], "owner_inventory")
    owner_identity = reference.identity(owner.lstat())
    source_images = {
        "generator_probe": (Path(__file__), captured(Path(__file__), 1048576)),
        "original_reference": (
            ROOT / "installed_vhd_reference_fixture.py",
            captured(ROOT / "installed_vhd_reference_fixture.py", 1048576),
        ),
    }
    require(
        hashlib.sha256(source_images["original_reference"][1][0]).hexdigest() == REFERENCE_SHA256,
        "source_pin",
    )
    tool_images = {}
    for name, path in TOOLS.items():
        body, identity = captured(path, 67108864)
        require(identity[3] == 0, "tool_owner")
        tool_images[name] = (body, identity)
    expected_names = set()
    directories = {}
    file_images = {}
    inventories = {}

    def directory_identity(path, mode):
        info = path.lstat()
        require(
            stat.S_ISDIR(info.st_mode)
            and info.st_uid == os.geteuid()
            and stat.S_IMODE(info.st_mode) == mode,
            "directory_changed",
        )
        return reference.identity(info)

    def current():
        reference.remaining(deadline)
        require(reference.identity(owner.lstat()) == owner_identity, "owner_changed")
        require(set(os.listdir(owner)) == expected_names, "owner_inventory")
        for name, path in TOOLS.items():
            require(captured(path, 67108864) == tool_images[name], "tool_changed")
        for path, image in source_images.values():
            require(captured(path, 1048576) == image, "source_changed")
        for path, (mode, identity) in directories.items():
            require(directory_identity(path, mode) == identity, "directory_changed")
        for path, image in file_images.items():
            require(captured(path, PACKAGE_LIMIT) == image, "package_changed")
        for path, inventory in inventories.items():
            require(reference.inventory(path) == inventory, "nested_image_changed")

    source = owner / "payload-source"
    source.mkdir(mode=0o755)
    reference.write_exclusive(source / MARKER_NAME, MARKER, 0o644)
    expected_names.add(source.name)
    source_inventory = reference.inventory(source)
    require(set(source_inventory) == {MARKER_NAME}, "source_inventory")
    require(captured(source / MARKER_NAME, 1024)[0] == MARKER, "source_marker")
    directories[source] = (0o755, directory_identity(source, 0o755))
    inventories[source] = source_inventory
    package = owner / "positive.pkg"
    stage[0] = "generate"
    current()
    reference.native(
        [
            str(TOOLS["pkgbuild"]),
            "--root",
            str(source),
            "--identifier",
            IDENTIFIER,
            "--version",
            "1",
            "--install-location",
            "/",
            str(package),
        ],
        deadline,
    )
    expected_names.add(package.name)
    current()
    require(reference.inventory(source) == source_inventory, "source_changed")
    positive, positive_identity = captured(package, PACKAGE_LIMIT)
    file_images[package] = (positive, positive_identity)
    require(positive.startswith(b"xar!") and len(positive) > 28, "package_shape")
    # A fixed bad magic cannot be confused with an unsupported option: the
    # complete positive expansion must pass before this negative is attempted.
    negative = b"BAD!" + positive[4:]
    bad_package = owner / "corrupt-header.pkg"
    reference.write_exclusive(bad_package, negative)
    expected_names.add(bad_package.name)
    negative_capture = captured(bad_package, PACKAGE_LIMIT)
    file_images[bad_package] = negative_capture
    output = owner / "expanded-positive"
    stage[0] = "expand_positive"
    current()
    require(not os.path.lexists(output), "output_present")
    response = reference.native(
        [str(TOOLS["pkgutil"]), "--expand-full", str(package), str(output)],
        deadline,
    )
    expected_names.add(output.name)
    directories[output] = (0o755, directory_identity(output, 0o755))
    current()
    require(captured(package, PACKAGE_LIMIT) == (positive, positive_identity), "package_changed")
    require(response.stdout == b"" and response.stderr == b"", "expand_output")
    observed_inventory = expanded_marker(reference, output)
    inventories[output] = observed_inventory
    bad_output = owner / "expanded-negative"
    stage[0] = "expand_negative"
    current()
    require(captured(bad_package, PACKAGE_LIMIT) == negative_capture, "package_changed")
    require(not os.path.lexists(bad_output), "output_present")
    try:
        reference.native(
            [str(TOOLS["pkgutil"]), "--expand-full", str(bad_package), str(bad_output)],
            deadline,
        )
    except reference.Refusal as error:
        require(str(error) == "native_status", "negative_transport")
    else:
        raise Refusal("negative_accepted")
    current()
    require(not os.path.lexists(bad_output), "negative_output")
    require(captured(bad_package, PACKAGE_LIMIT) == negative_capture, "package_changed")
    require(reference.inventory(output) == observed_inventory, "expanded_changed")
    require(reference.inventory(source) == source_inventory, "source_changed")
    reference.remaining(deadline)
    packet = {
        "schema": 1,
        "kind": "test_only_pkgutil_capability_fixture",
        "status": "prepared_and_observed",
        "full_expansion_observed": True,
        "corrupt_header_refused": True,
        "negative_status": "verified_nonzero",
        "package_generation_count": 1,
        "deadline_seconds": reference.SECONDS,
        "probe_directory_retired": False,
        "installation_qualified": False,
        "reference_qualified": False,
        "runtime_qualified": False,
        "tool_sha256": {
            name: hashlib.sha256(value[0]).hexdigest() for name, value in tool_images.items()
        },
        "source_sha256": {
            name: hashlib.sha256(image[0]).hexdigest()
            for name, (_path, image) in source_images.items()
        },
        "expected_marker_base64": base64.b64encode(MARKER).decode("ascii"),
        "observed_expanded_inventory": observed_inventory,
        "packages": {
            name: {
                "bytes": len(body),
                "sha256": hashlib.sha256(body).hexdigest(),
                "base64": base64.b64encode(body).decode("ascii"),
            }
            for name, body in [("positive.pkg", positive), ("corrupt-header.pkg", negative)]
        },
    }
    # Build the complete deletion image from already admitted roots, bytes and
    # membership. A fresh unknown member must never become cleanup authority.
    admitted = {}
    for path, (_mode, identity) in directories.items():
        admitted[path.name] = {"identity": identity, "bytes": 0, "kind": "directory"}
    for path, inventory in inventories.items():
        for name, row in inventory.items():
            admitted[path.name + "/" + name] = row
    for path, (body, identity) in file_images.items():
        admitted[path.name] = {
            "identity": dict(zip(["dev", "ino", "mode", "uid", "gid"], identity[:5])),
            "bytes": len(body),
            "kind": "file",
            "sha256": hashlib.sha256(body).hexdigest(),
        }
    current()
    require(reference.inventory(owner) == admitted, "retirement_image")
    require(len(json.dumps(packet, sort_keys=True).encode("utf-8")) <= PACKET_LIMIT, "packet_limit")
    stage[0] = "retire_probe"
    reference.remove_tree(owner, admitted)
    require(not os.path.lexists(owner), "retirement_refused")
    reference.remaining(deadline)
    packet["probe_directory_retired"] = True
    return packet


def main():
    stage = ["entry"]
    reference_module = reference()
    deadline = time.monotonic() + reference_module.SECONDS

    def interrupted(_signum, _frame):
        raise Refusal("deadline")

    previous = signal.signal(signal.SIGALRM, interrupted)
    signal.setitimer(signal.ITIMER_REAL, reference_module.SECONDS)
    old_mask = os.umask(0o022)
    try:
        require(len(sys.argv) == 2, "arguments")
        packet = prepare(Path(sys.argv[1]), deadline, reference_module, stage)
        serialized = json.dumps(packet, sort_keys=True)
        require(len(serialized.encode("utf-8")) <= PACKET_LIMIT, "packet_limit")
        print(serialized)
        return 0
    except (
        Refusal,
        reference_module.Refusal,
        OSError,
        ValueError,
        subprocess.SubprocessError,
    ) as error:
        print(
            json.dumps(
                {
                    "schema": 1,
                    "status": "refused",
                    "stage": stage[0],
                    "reason": str(error)
                    if isinstance(error, (Refusal, reference_module.Refusal))
                    else type(error).__name__,
                    "installation_qualified": False,
                    "reference_qualified": False,
                    "runtime_qualified": False,
                },
                sort_keys=True,
            )
        )
        return 1
    finally:
        os.umask(old_mask)
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, previous)


if __name__ == "__main__":
    sys.exit(main())
