-- static/ergopti_plus/macos/tests/unit/platform/remap/lease_controller/test_real_shell_runner_final_stream.lua
local helpers = require("tests.helpers")
local support = require("tests.support.real_lease_shell_runner_fixture")

local function activate(controller, ctx)
	local starts = {}
	helpers.assert_true(controller.start(function(ok) starts[#starts + 1] = ok end))
	local task = ctx.tasks[#ctx.tasks]
	helpers.assert_eq(task.args[1], "--karabiner-lease-worker")
	helpers.assert_eq(task.start_calls, 1)
	helpers.assert_eq(starts, {})
	task:emit("READY\n")
	helpers.assert_eq(starts, { true })
	helpers.assert_eq(controller.status(), "active")
	return task
end

helpers.describe("real lease controller through real final-stream adapter", function()
	helpers.it("final STOP suffix reaches real controller after completion before original deadline", function()
		support.with_fixture(function(controller, ctx)
			local task = activate(controller, ctx)
			local stopped = {}
			helpers.assert_true(controller.stop("synthetic final suffix", function(ok) stopped[#stopped + 1] = ok end))
			helpers.assert_eq(task.inputs, { "STOP\n" })
			local ack = ctx.live_timer(7)
			task:emit("STOP")
			task:complete(0)
			helpers.assert_eq(stopped, {})
			helpers.assert_eq(ack.cancelled, false, "original STOP deadline remains authoritative")
			helpers.assert_eq(#ctx.tasks, 2, "real completion starts redundant fallback")
			helpers.assert_eq(ctx.tasks[2].args[1], "--karabiner-lease-revoke")
			helpers.assert_eq(ctx.tasks[2].running, true)
			task:final("PED\n")
			helpers.assert_eq(stopped, { true })
			helpers.assert_eq(controller.status(), "idle")
			helpers.assert_eq(ack.cancelled, true)
			helpers.assert_eq(task.eof_calls, 0, "completion is not fabricated explicit native EOF")
		end)
	end)

	for _, failure in ipairs({ "false", "nil", "throw", "foreign" }) do
		helpers.it(failure .. " startup READY never commits real controller activation", function()
			support.with_fixture(function(controller, ctx, runner)
				local starts = {}
				helpers.assert_eq(controller.start(function(ok) starts[#starts + 1] = ok end), false)
				local task = ctx.tasks[1]
				helpers.assert_eq(task.start_calls, 1)
				helpers.assert_eq(starts, { false })
				helpers.assert_eq(task.terminate_calls, 1)
				helpers.assert_eq(task.eof_calls, 0)
				helpers.assert_true(runner._active_tasks[task] ~= nil, "potential native mutation stays pinned until exit")
				task:complete(73)
				task:final("READY\n")
				helpers.assert_eq(starts, { false }, "no uncommitted final activation replay")
				helpers.assert_nil(runner._active_tasks[task])
			end, { start_failure = failure })
		end)
	end

	helpers.it("old final callback cannot mutate live replacement identity", function()
		support.with_fixture(function(controller, ctx)
			local old = activate(controller, ctx)
			local stopped = {}
			controller.stop("replace", function(ok) stopped[#stopped + 1] = ok end)
			old:complete(0)
			old:final("STOPPED\n")
			helpers.assert_eq(stopped, { true })
			local replacement = activate(controller, ctx)
			local token = controller.token()
			local input_count = #replacement.inputs
			old:final("STOPPED\nREADY\n")
			local phase, status = controller.status()
			helpers.assert_eq(phase, "active")
			helpers.assert_eq(status.token, token)
			helpers.assert_eq(#replacement.inputs, input_count)
			helpers.assert_eq(replacement.terminate_calls, 0)
		end)
	end)

	helpers.it("completion and partial STOP do not forgive pending fallback debt", function()
		support.with_fixture(function(controller, ctx)
			local task = activate(controller, ctx)
			local stopped = {}
			controller.stop("missing exact STOP proof", function(ok) stopped[#stopped + 1] = ok end)
			local ack = ctx.live_timer(7)
			task:complete(0)
			task:final("STOP")
			helpers.assert_eq(stopped, {})
			helpers.assert_eq(controller.status(), "stopping")
			ctx.fire(ack)
			helpers.assert_nil(controller.token(), "failed fence blocks replacement")
			task:final("PED\n")
			helpers.assert_eq(stopped, {}, "expired failed generation refuses late STOP proof")
			helpers.assert_eq(ctx.tasks[2].args[1], "--karabiner-lease-revoke")
			ctx.tasks[2]:complete(0)
			helpers.assert_eq(stopped, { true }, "only actual fallback completion may settle remaining debt")
		end)
	end)

	helpers.it("unexpected worker exit does not activate from final READY", function()
		support.with_fixture(function(controller, ctx)
			local starts = {}
			helpers.assert_true(controller.start(function(ok) starts[#starts + 1] = ok end))
			local task = ctx.tasks[1]
			task:complete(73)
			task:final("READY\n")
			helpers.assert_eq(starts, {})
			helpers.assert_nil(controller.token())
			helpers.assert_eq(ctx.tasks[2].args[1], "--karabiner-lease-revoke")
			ctx.tasks[2]:complete(0)
			helpers.assert_eq(starts, { false })
		end)
	end)
end)
