--- modules/gestures/actions.lua

--- ==============================================================================
--- MODULE: Gestures Actions Registry
--- DESCRIPTION:
--- Maps internal logic representations to human-readable labels and executable
--- functions. Handles macOS window, space, and volume navigations.
---
--- FEATURES & RATIONALE:
--- 1. Decoupled Logic: Isolates action definitions from gesture detection.
--- 2. Scalable Actions: Supports both single-fire and continuous adjustments.
--- ==============================================================================

local M = {}

local hs     = hs
local Logger = require("lib.logger")
local LOG    = "gestures.actions"

local rightClickHeld    = false
local mouseEventTap     = nil
local keyboardWatcher   = nil
local gestureInProgress = false

-- Delay after activation before reacting to rightMouseUp events.
-- The gesture fires on finger-lift, which can generate a spurious rightMouseUp
-- that would immediately cancel right-click hold mode.
local RIGHT_CLICK_COOLDOWN_SEC = 0.15





-- =========================================
-- =========================================
-- ======= 1/ Interaction Primitives =======
-- =========================================
-- =========================================

--- Stops the keyboard watcher that auto-releases right-click on key press.
local function stopKeyboardWatcher()
	if keyboardWatcher and type(keyboardWatcher.stop) == "function" then
		pcall(function() keyboardWatcher:stop() end)
		keyboardWatcher = nil
	end
end

--- Starts a keyboard watcher that releases the held right-click on any key
--- press or modifier change.
local function startKeyboardWatcher()
	stopKeyboardWatcher()
	local evTypes = hs.eventtap.event.types
	keyboardWatcher = hs.eventtap.new(
		{ evTypes.keyDown, evTypes.flagsChanged },
		function()
			-- Any keystroke or modifier change releases the held right-click
			hs.timer.doAfter(0, M.force_cleanup)
			return false
		end
	)
	if keyboardWatcher then
		pcall(function() keyboardWatcher:start() end)
	end
end

--- Safely terminates the right-click hold mode.
function M.force_cleanup()
	Logger.debug(LOG, "Forcefully releasing right-click hold mode…")
	stopKeyboardWatcher()
	if mouseEventTap and type(mouseEventTap.stop) == "function" then
		pcall(function() mouseEventTap:stop() end)
		mouseEventTap = nil
	end

	if rightClickHeld then
		pcall(function()
			hs.eventtap.event.newMouseEvent(
				hs.eventtap.event.types.rightMouseUp,
				hs.mouse.absolutePosition()
			):post()
		end)
	end
	rightClickHeld = false
	Logger.info(LOG, "Right-click hold mode forcefully released.")
end

--- Toggles a right-button-held mode mimicking a physical trackpad
--- right-click that stays pressed. Any subsequent keystroke (or physical
--- right-click) releases the button — typically firing the system's
--- right-click action wherever the cursor is at that moment. Useful as a
--- generic "press right button until I do something else" toggle which
--- covers context menus, drag-with-right-button workflows (browser
--- gestures, 3D viewport rotation, …) and whatever else right-click means
--- in the focused app, hence the broader naming over the previous
--- "selection" wording.
function M.toggle_right_click()
	if rightClickHeld then M.force_cleanup(); return end

	Logger.debug(LOG, "Enabling right-click hold mode…")
	pcall(function()
		local event = hs.eventtap.event.newMouseEvent(
			hs.eventtap.event.types.rightMouseDown,
			hs.mouse.absolutePosition()
		)
		-- Mark the event as HID-sourced (kCGEventSourceStateHIDSystemState = 1).
		-- This makes it reach areas that reject session-level synthetic events
		-- (e.g. the WindowServer for title-bar drags).
		pcall(function()
			event:setProperty(hs.eventtap.event.properties.eventSourceStateID, 1)
		end)
		event:post()
	end)
	rightClickHeld = true
	startKeyboardWatcher()

	local activationTime = hs.timer.secondsSinceEpoch()
	local evTypes = hs.eventtap.event.types
	mouseEventTap = hs.eventtap.new(
		{ evTypes.mouseMoved, evTypes.rightMouseUp },
		function(e)
			local t = e:getType()

			if t == evTypes.rightMouseUp then
				-- Ignore spurious mouseUp events generated by the gesture's own
				-- finger-lift within the cooldown window; they would prematurely
				-- release the right-click hold before the user has a chance to drag.
				if hs.timer.secondsSinceEpoch() - activationTime < RIGHT_CLICK_COOLDOWN_SEC then
					return true
				end
				-- Ignore rightMouseUp events generated by new trackpad contact when a
				-- new gesture is starting; the engine will re-trigger right_click_toggle
				-- on commit if needed, so discarding here prevents a phantom cleanup.
				if gestureInProgress then
					return true
				end
				hs.timer.doAfter(0, M.force_cleanup)
				return true
			end

			-- In areas where the synthetic rightMouseDown was not accepted, the OS
			-- emits mouseMoved instead of rightMouseDragged.  Converting here gives
			-- a best-effort drag signal to apps that do honour rightMouseDragged
			-- even without a prior anchor click.
			if t == evTypes.mouseMoved then
				pcall(function()
					hs.eventtap.event.newMouseEvent(
						evTypes.rightMouseDragged, e:location()
					):post()
				end)
				return false
			end

			return false
		end)

	if mouseEventTap then
		pcall(function() mouseEventTap:start() end)
		Logger.info(LOG, "Right-click hold mode enabled.")
	end
end

--- Triggers macOS Dictionary Lookup (Cmd+Ctrl+D).
function M.trigger_lookup()
	Logger.debug(LOG, "Triggering dictionary lookup…")
	pcall(function() hs.eventtap.keyStroke({"ctrl", "cmd"}, "d", 0) end)
	Logger.info(LOG, "Dictionary lookup triggered.")
end

--- Posts system media keys safely.
--- @param name string The system key name.
local function sysKey(name)
	pcall(function()
		hs.eventtap.event.newSystemKeyEvent(name, true):post()
		hs.eventtap.event.newSystemKeyEvent(name, false):post()
	end)
end

--- Cycles through standard windows of the frontmost application.
--- @param goNext boolean True to navigate forward, false to navigate backward.
local function winNav(goNext)
	local ok, app = pcall(hs.application.frontmostApplication)
	if not ok or not app then return end
	
	local ok_wins, wins = pcall(function() return app:allWindows() end)
	if not ok_wins or type(wins) ~= "table" then return end
	
	local visible = {}
	for _, w in ipairs(wins) do
		if w:isStandard() and not w:isMinimized() then table.insert(visible, w) end
	end
	
	if #visible <= 1 then return end
	table.sort(visible, function(a, b) return a:id() < b:id() end)
	
	local ok_cur, cur = pcall(hs.window.focusedWindow)
	local idx = 1
	for i, w in ipairs(visible) do
		if ok_cur and cur and w:id() == cur:id() then idx = i; break end
	end
	
	local target_idx = goNext and (idx % #visible + 1) or ((idx - 2) % #visible + 1)
	pcall(function() visible[target_idx]:focus() end)
end

--- Cycles through macOS Spaces.
--- @param goNext boolean True to navigate forward, false to navigate backward.
local function spaceNav(goNext)
	local ok, spaces = pcall(function() return require("hs.spaces") end)
	if ok and type(spaces) == "table" then
		local screen = hs.screen.mainScreen()
		local uuid = screen and screen:getUUID()
		
		if uuid then
			local ok_all, all = pcall(function() return spaces.allSpaces() end)
			if ok_all and type(all) == "table" and all[uuid] and #all[uuid] > 0 then
				local sps = all[uuid]
				local active = nil
				
				if type(spaces.activeSpace) == "function" then
					pcall(function() active = spaces.activeSpace() end)
				else
					local fw = hs.window.frontmostWindow()
					if fw and type(spaces.windowSpaces) == "function" then
						local okw, ws = pcall(function() return spaces.windowSpaces(fw) end)
						if okw and type(ws) == "table" and #ws > 0 then active = ws[1] end
					end
				end
				
				if active then
					local idx = nil
					for i, id in ipairs(sps) do 
						if tostring(id) == tostring(active) then idx = i; break end 
					end
					
					if idx then
						local total = #sps
						local delta = goNext and 1 or -1
						local newIdx = ((idx - 1 + delta) % total) + 1
						pcall(function() hs.eventtap.keyStroke({"ctrl"}, tostring(newIdx), 0) end)
						return
					end
				end
			end
		end
	end
	
	-- Absolute fallback via AppleScript using raw keycodes (123=Left, 124=Right)
	pcall(hs.osascript.applescript, string.format(
		"tell application \"System Events\" to key code %d using {control down}",
		goNext and 124 or 123
	))
end





-- ==================================
-- ==================================
-- ======= 2/ Action Registry =======
-- ==================================
-- ==================================

local AX, SG = {}, {}
local function ax(n, lbl, p, nx, scalable) AX[n] = {label = lbl, prev = p, next = nx, scalable = scalable} end
local function sg(n, lbl, fn)              SG[n] = {label = lbl, fn = fn} end

-- Axis actions (prev / next) — scalable=true for continuous actions
ax("tabs",       "Onglets",
	function() pcall(hs.eventtap.keyStroke, {"ctrl", "shift"}, "tab") end,
	function() pcall(hs.eventtap.keyStroke, {"ctrl"}, "tab") end)

ax("windows",    "Fenêtres",
	function() winNav(false) end, 
	function() winNav(true) end)

ax("spaces",     "Spaces",
	function() spaceNav(false) end, 
	function() spaceNav(true) end)

ax("volume",     "Volume",
	function() sysKey("SOUND_DOWN") end, 
	function() sysKey("SOUND_UP") end, true)

ax("brightness", "Luminosité",
	function() sysKey("BRIGHTNESS_DOWN") end, 
	function() sysKey("BRIGHTNESS_UP") end, true)

ax("tracks",     "Pistes",
	function() sysKey("PREVIOUS") end, 
	function() sysKey("NEXT") end)

ax("words",      "Mots",
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "left") end,
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "right") end, true)

ax("lines",      "Lignes",
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "up") end,
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "down") end, true)

ax("line_bounds","Ligne (début/fin)",
	function() pcall(hs.eventtap.keyStroke, {"cmd"}, "left") end,
	function() pcall(hs.eventtap.keyStroke, {"cmd"}, "right") end)

ax("paragraphs", "Paragraphes",
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "up") end,
	function() pcall(hs.eventtap.keyStroke, {"alt"}, "down") end, true)

ax("document",   "Document (début/fin)",
	function() pcall(hs.eventtap.keyStroke, {"cmd"}, "up") end,
	function() pcall(hs.eventtap.keyStroke, {"cmd"}, "down") end)

-- Single actions
sg("none",             "Désactivé",            function() end)

-- Selection & navigation cursor
sg("right_click_toggle", "Toggle clic droit maintenu", M.toggle_right_click)
sg("lookup",           "Définition du mot",    M.trigger_lookup)
sg("app_switcher",     "Alt-Tab",              function() pcall(hs.eventtap.keyStroke, {"cmd"}, "tab") end)

-- Editing
sg("copy",             "Copier",               function() pcall(hs.eventtap.keyStroke, {"cmd"}, "c") end)
sg("paste",            "Coller",               function() pcall(hs.eventtap.keyStroke, {"cmd"}, "v") end)
sg("cut",              "Couper",               function() pcall(hs.eventtap.keyStroke, {"cmd"}, "x") end)
sg("undo",             "Annuler",              function() pcall(hs.eventtap.keyStroke, {"cmd"}, "z") end)
sg("redo",             "Rétablir",             function() pcall(hs.eventtap.keyStroke, {"cmd", "shift"}, "z") end)
sg("select_all",       "Tout sélectionner",    function() pcall(hs.eventtap.keyStroke, {"cmd"}, "a") end)
sg("find",             "Rechercher",           function() pcall(hs.eventtap.keyStroke, {"cmd"}, "f") end)

-- Keys
sg("enter",            "Entrée",               function() pcall(hs.eventtap.keyStroke, {}, "return") end)
sg("tab",              "Tab",                  function() pcall(hs.eventtap.keyStroke, {}, "tab") end)
sg("escape",           "Échap",                function() pcall(hs.eventtap.keyStroke, {}, "escape") end)
sg("backspace",        "Suppr. arrière",       function() pcall(hs.eventtap.keyStroke, {}, "delete") end)
sg("delete",           "Supprimer",            function() pcall(hs.eventtap.keyStroke, {}, "forwarddelete") end)

-- Tabs
sg("tab_new",          "Nouvel onglet",        function() pcall(hs.eventtap.keyStroke, {"cmd"}, "t") end)
sg("tab_close",        "Fermer onglet",        function() pcall(hs.eventtap.keyStroke, {"cmd"}, "w") end)
sg("tab_prev",         "Onglet précédent",     function() pcall(hs.eventtap.keyStroke, {"ctrl", "shift"}, "tab") end)
sg("tab_next",         "Onglet suivant",       function() pcall(hs.eventtap.keyStroke, {"ctrl"}, "tab") end)

-- Windows & Spaces
sg("win_prev",         "Fenêtre précédente",   function() winNav(false) end)
sg("win_next",         "Fenêtre suivante",     function() winNav(true) end)
sg("close_window",     "Fermer la fenêtre",    function() pcall(hs.eventtap.keyStroke, {"cmd"}, "w") end)
sg("fullscreen",       "Plein écran",          function() pcall(hs.eventtap.keyStroke, {"cmd", "ctrl"}, "f") end)
sg("snap_left",        "Ancrer à gauche",      function()
	local win = hs.window.focusedWindow()
	if win then pcall(function() win:moveToUnit(hs.layout.left50) end) end
end)
sg("snap_right",       "Ancrer à droite",      function()
	local win = hs.window.focusedWindow()
	if win then pcall(function() win:moveToUnit(hs.layout.right50) end) end
end)
sg("maximize",         "Maximiser",            function()
	local win = hs.window.focusedWindow()
	if win then pcall(function() win:maximize() end) end
end)
sg("space_prev",       "Space précédent",      function() spaceNav(false) end)
sg("space_next",       "Space suivant",        function() spaceNav(true) end)
sg("mission_control",  "Mission Control",      function() pcall(hs.osascript.applescript, "tell application \"System Events\" to key code 160") end)
sg("app_expose",       "App Exposé",           function() pcall(hs.osascript.applescript, "tell application \"System Events\" to key code 125 using {control down}") end)

-- Cursor movement
sg("word_prev",        "Mot précédent",        function() pcall(hs.eventtap.keyStroke, {"alt"}, "left") end)
sg("word_next",        "Mot suivant",          function() pcall(hs.eventtap.keyStroke, {"alt"}, "right") end)
sg("line_start",       "Début de ligne",       function() pcall(hs.eventtap.keyStroke, {"cmd"}, "left") end)
sg("line_end",         "Fin de ligne",         function() pcall(hs.eventtap.keyStroke, {"cmd"}, "right") end)
sg("para_prev",        "Paragraphe précédent", function() pcall(hs.eventtap.keyStroke, {"alt"}, "up") end)
sg("para_next",        "Paragraphe suivant",   function() pcall(hs.eventtap.keyStroke, {"alt"}, "down") end)
sg("doc_start",        "Début du document",    function() pcall(hs.eventtap.keyStroke, {"cmd"}, "up") end)
sg("doc_end",          "Fin du document",      function() pcall(hs.eventtap.keyStroke, {"cmd"}, "down") end)

-- Media
sg("vol_up",           "Volume +",             function() sysKey("SOUND_UP") end)
sg("vol_down",         "Volume -",             function() sysKey("SOUND_DOWN") end)
sg("mute",             "Muet/Unmute",          function() sysKey("MUTE") end)
sg("brightness_up",    "Luminosité +",         function() sysKey("BRIGHTNESS_UP") end)
sg("brightness_down",  "Luminosité -",         function() sysKey("BRIGHTNESS_DOWN") end)
sg("track_play",       "Lecture/Pause",        function() sysKey("PLAY") end)
sg("track_next",       "Piste suivante",       function() sysKey("NEXT") end)
sg("track_prev",       "Piste précédente",     function() sysKey("PREVIOUS") end)

-- System
-- Each capture target ships in two flavours: the *_clipboard variant copies
-- the image to the macOS clipboard for immediate paste into the focused
-- app, and the *_save variant writes a timestamped PNG to
-- ~/Pictures/screenshots/. Defaults across the project favour the
-- clipboard variants because they keep the user inside their current
-- workflow without producing files they then have to clean up. The
-- screencapture(1) CLI is preferred over keystroke synthesis because it
-- bypasses the macOS preview overlay and works reliably regardless of
-- whether Cmd-Shift-N is currently bound by another app.
local function screenshots_dir()
	local home = os.getenv("HOME") or ""
	local dir  = home .. "/Pictures/screenshots"
	pcall(function() hs.fs.mkdir(dir) end)
	return dir
end

local function screenshot_path()
	return screenshots_dir() .. "/screenshot_" .. os.date("%Y_%m_%d_%Hh_%Mmin_%Ss") .. ".png"
end

local function run_screencapture(args)
	pcall(function() hs.execute("/usr/sbin/screencapture " .. args, true) end)
end

sg("screenshot_window_clipboard",     "Capture d'écran de la fenêtre active (presse-papiers)",
	function() run_screencapture("-w -c") end)
sg("screenshot_window_save",          "Capture d'écran de la fenêtre active (sauver sur disque)",
	function() run_screencapture("-w '" .. screenshot_path() .. "'") end)
sg("screenshot_region_clipboard",     "Capture d'écran d'une zone à sélectionner (presse-papiers)",
	function() run_screencapture("-i -c") end)
sg("screenshot_region_save",          "Capture d'écran d'une zone à sélectionner (sauver sur disque)",
	function() run_screencapture("-i '" .. screenshot_path() .. "'") end)
sg("screenshot_fullscreen_clipboard", "Capture d'écran entier (presse-papiers)",
	function() run_screencapture("-c") end)
sg("screenshot_fullscreen_save",      "Capture d'écran entier (sauver sur disque)",
	function() run_screencapture("'" .. screenshot_path() .. "'") end)

sg("lock_screen",      "Verrouiller",          function() pcall(hs.eventtap.keyStroke, {"cmd", "ctrl"}, "q") end)
sg("notification_center", "Notifications",    function() pcall(hs.eventtap.keyStroke, {}, "F12") end)

-- Script management
sg("hs_reload",        "Recharger Hammerspoon", function() pcall(hs.reload) end)
sg("hs_console",       "Console Hammerspoon",   function() pcall(hs.openConsole) end)
sg("hs_quit",          "Quitter Hammerspoon",   function()
	pcall(function() hs.closeConsole() end)
	pcall(function()
		hs.timer.doAfter(0.1, function() os.exit(0) end)
	end)
end)
sg("hs_open_config",   "Ouvrir config.toml",    function()
	-- Resolve via MenuPaths so the gesture honours the user's
	-- configurable ConfigDirPath instead of the hardcoded ~/.hammerspoon.
	local ok_mp, MenuPaths = pcall(require, "ui.menu.menu_paths")
	if ok_mp and MenuPaths and type(MenuPaths.get) == "function" then
		local p = MenuPaths.get("ConfigTomlPath")
		if type(p) == "string" and p ~= "" then
			pcall(hs.execute, string.format("open %q", p))
		end
	end
end)





-- =============================
-- =============================
-- ======= 3/ Public API =======
-- =============================
-- =============================

M.AX_NAMES = {
	"none", "tabs", "windows", "spaces",
	"volume", "brightness", "tracks",
	"words", "lines", "line_bounds", "paragraphs", "document",
}

M.SG_NAMES = {
	"none",
	-- Selection & navigation
	"right_click_toggle", "lookup", "app_switcher",
	-- Editing
	"copy", "paste", "cut", "undo", "redo", "select_all", "find",
	-- Keys
	"enter", "tab", "escape", "backspace", "delete",
	-- Tabs
	"tab_new", "tab_close", "tab_prev", "tab_next",
	-- Windows & Spaces
	"win_prev", "win_next", "close_window", "fullscreen",
	"snap_left", "snap_right", "maximize",
	"space_prev", "space_next", "mission_control", "app_expose",
	-- Cursor movement
	"word_prev", "word_next", "line_start", "line_end",
	"para_prev", "para_next", "doc_start", "doc_end",
	-- Media
	"vol_up", "vol_down", "mute",
	"brightness_up", "brightness_down",
	"track_play", "track_next", "track_prev",
	-- System
	"screenshot_window_clipboard", "screenshot_window_save",
	"screenshot_region_clipboard", "screenshot_region_save",
	"screenshot_fullscreen_clipboard", "screenshot_fullscreen_save",
	"lock_screen", "notification_center",
	-- Script management
	"hs_reload", "hs_console", "hs_quit", "hs_open_config",
}

--- Retrieves the localized label for a given action ID.
--- @param name string The action ID.
--- @return string The human-readable label.
function M.get_label(name)
	if not name or name == "none" then return "Désactivé" end
	if AX[name] then return AX[name].label end
	if SG[name] then return SG[name].label end
	return name
end

--- Executes a single-fire action based on its identifier.
--- @param name string The action ID.
function M.execute_single(name)
	local s = SG[name]
	if s and type(s.fn) == "function" then
		Logger.debug(LOG, string.format("Executing single action: %s…", name))
		pcall(s.fn)
		Logger.info(LOG, string.format("Action %s executed successfully.", name))
	end
end

--- Executes an axis-based action (forward or backward).
--- @param name string The action ID.
--- @param goNext boolean The direction to move.
function M.execute_axis(name, goNext)
	local a = AX[name]
	if not a then return end
	local fn = goNext and a.next or a.prev
	if type(fn) == "function" then
		Logger.debug(LOG, string.format("Executing axis action: %s (direction: %s)…", name, tostring(goNext)))
		pcall(fn)
		Logger.info(LOG, string.format("Axis action %s executed successfully.", name))
	end
end

--- Checks if an action scales continuously.
--- @param name string The action ID.
--- @return boolean True if scalable.
function M.is_scalable(name)
	local a = AX[name]
	return a and a.scalable == true
end

--- Returns whether the synthetic right-click hold mode is currently active.
--- @return boolean True if active.
function M.is_right_click_held()
	return rightClickHeld
end

--- Signals that a new raw gesture frame has started or stopped.
--- Used by the engine to prevent rightMouseUp events generated by new trackpad
--- contact from prematurely releasing an active right-click hold.
--- @param active boolean True when a gesture is being processed, false when done.
function M.set_gesture_in_progress(active)
	gestureInProgress = active
end

return M
