--- _shared/lua/core/llm/managed_python_locator.lua
--- Generated by tools/codegen/codegen-managed-python-release.cjs; do not edit.
--- Source: _shared/modules/llm/managed_python_release.json.
--- These pinned namespace hints never authorize an executable or its native architecture.

return {
	arm64 = "cpython-3.11.16-macos-aarch64-none/bin/python3.11",
	x86_64 = "cpython-3.11.16-macos-x86_64-none/bin/python3.11",
}
