// _shared/ui/layer_editor/_generated/layer_data.js

// ==========================================
// AUTO-GENERATED — do not edit manually
// Source: static/ergopti_plus/_shared/data/keycodes/physical_keys.json
// Source: static/ergopti_plus/_shared/keymap/layer_actions.toml
// Source: static/ergopti_plus/_shared/keymap/layers.recommended.toml
// Source: static/ergopti_plus/_shared/tap_hold/defaults.toml
// Run: npm run codegen:layer-editor-data:js
// ==========================================

// Keys, actions, groups, OS availability and the recommended layer, as the
// layer editor page reads them. Loaded by a <script> tag before the page scripts.
const LAYER_EDITOR_DATA = {
	"schema_version": 1,
	"user_file": "layers.toml",
	"layer": "nav",
	"platforms": [
		"windows",
		"macos",
		"linux"
	],
	"modifier_order": [
		"ctrl",
		"alt",
		"shift",
		"meta",
		"fn"
	],
	"primary_modifier": {
		"windows": "ctrl",
		"macos": "meta",
		"linux": "ctrl"
	},
	"modifiers": {
		"ctrl": {"platforms":["windows","macos","linux"],"reason_key":null},
		"alt": {"platforms":["windows","macos","linux"],"reason_key":null},
		"shift": {"platforms":["windows","macos","linux"],"reason_key":null},
		"meta": {"platforms":["windows","macos","linux"],"reason_key":null},
		"fn": {"platforms":["macos"],"reason_key":"platform_reason.layer_fn_modifier_is_macos"}
	},
	"source_kinds": {
		"key": {"platforms":["windows","macos","linux"],"reason_key":null},
		"mouse_button": {"platforms":["windows","macos"],"reason_key":"platform_reason.layer_pointer_source_is_not_linux"},
		"wheel": {"platforms":["windows","macos"],"reason_key":"platform_reason.layer_wheel_source_is_not_linux"}
	},
	"repeat_count": {
		"platforms": ["windows"],
		"reason_key": "platform_reason.layer_repeat_count_is_windows_only",
		"min": 1,
		"max": 99
	},
	"groups": [
		{"id":"key","label_key":"layer_editor.group.key","actions":["none"]},
		{"id":"cursor","label_key":"layer_editor.group.cursor","actions":["arrow_up","arrow_down","arrow_left","arrow_right","word_prev","word_next","line_start","line_end","para_prev","para_next","doc_start","doc_end"]},
		{"id":"selection","label_key":"layer_editor.group.selection","actions":["sel_up","sel_down","sel_left","sel_right","sel_word_prev","sel_word_next","sel_line_start","sel_line_end","sel_para_prev","sel_para_next","sel_doc_start","sel_doc_end"]},
		{"id":"editing","label_key":"layer_editor.group.editing","actions":["move_line_up","move_line_down","duplicate_line_up","duplicate_line_down","new_line_below","backspace","delete","enter","tab","escape","escape_or_option_shift"]},
		{"id":"window","label_key":"layer_editor.group.window","actions":["maximize","snap_left","snap_right","window_to_monitor_left","window_to_monitor_right"]},
		{"id":"media","label_key":"layer_editor.group.media","actions":["brightness_up","brightness_down","vol_up","vol_down","mute"]},
		{"id":"system","label_key":"layer_editor.group.system","actions":["spotlight"]}
	],
	"actions": {
		"arrow_up": {"label_key":"sg_actions.arrow_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"arrow_down": {"label_key":"sg_actions.arrow_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"arrow_left": {"label_key":"sg_actions.arrow_left","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"arrow_right": {"label_key":"sg_actions.arrow_right","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_up": {"label_key":"sg_actions.sel_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_down": {"label_key":"sg_actions.sel_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_left": {"label_key":"sg_actions.sel_left","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_right": {"label_key":"sg_actions.sel_right","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"word_prev": {"label_key":"sg_actions.word_prev","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"word_next": {"label_key":"sg_actions.word_next","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_word_prev": {"label_key":"sg_actions.sel_word_prev","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_word_next": {"label_key":"sg_actions.sel_word_next","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"line_start": {"label_key":"sg_actions.line_start","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"line_end": {"label_key":"sg_actions.line_end","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"sel_line_start": {"label_key":"layer_actions.sel_line_start","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"sel_line_end": {"label_key":"layer_actions.sel_line_end","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"para_prev": {"label_key":"sg_actions.para_prev","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"para_next": {"label_key":"sg_actions.para_next","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_para_prev": {"label_key":"layer_actions.sel_para_prev","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"sel_para_next": {"label_key":"layer_actions.sel_para_next","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"doc_start": {"label_key":"sg_actions.doc_start","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"doc_end": {"label_key":"sg_actions.doc_end","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"sel_doc_start": {"label_key":"layer_actions.sel_doc_start","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"sel_doc_end": {"label_key":"layer_actions.sel_doc_end","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"move_line_up": {"label_key":"layer_actions.move_line_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"move_line_down": {"label_key":"layer_actions.move_line_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"duplicate_line_up": {"label_key":"layer_actions.duplicate_line_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"duplicate_line_down": {"label_key":"layer_actions.duplicate_line_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"new_line_below": {"label_key":"layer_actions.new_line_below","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"backspace": {"label_key":"sg_actions.backspace","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"delete": {"label_key":"sg_actions.delete","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"enter": {"label_key":"sg_actions.enter","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"tab": {"label_key":"sg_actions.tab","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"escape": {"label_key":"sg_actions.escape","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"escape_or_option_shift": {"label_key":"layer_actions.escape_or_option_shift","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"none": {"label_key":"sg_actions.none","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"maximize": {"label_key":"sg_actions.maximize","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"snap_left": {"label_key":"sg_actions.snap_left","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"snap_right": {"label_key":"sg_actions.snap_right","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"window_to_monitor_left": {"label_key":"layer_actions.window_to_monitor_left","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"window_to_monitor_right": {"label_key":"layer_actions.window_to_monitor_right","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"brightness_up": {"label_key":"sg_actions.brightness_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"brightness_down": {"label_key":"sg_actions.brightness_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"vol_up": {"label_key":"sg_actions.vol_up","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"vol_down": {"label_key":"sg_actions.vol_down","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":true},
		"mute": {"label_key":"sg_actions.mute","platforms":["windows","macos","linux"],"reason_key":null,"repeatable":false},
		"spotlight": {"label_key":"sg_actions.spotlight","platforms":["macos"],"reason_key":"platform_reason.layer_spotlight_is_macos","repeatable":false}
	},
	"keys": [
		{"code":"Escape","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":0,"width":1},"iso":{"row":0,"col":0,"width":1}}},
		{"code":"F1","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":2,"width":1},"iso":{"row":0,"col":2,"width":1}}},
		{"code":"F2","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":3,"width":1},"iso":{"row":0,"col":3,"width":1}}},
		{"code":"F3","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":4,"width":1},"iso":{"row":0,"col":4,"width":1}}},
		{"code":"F4","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":5,"width":1},"iso":{"row":0,"col":5,"width":1}}},
		{"code":"F5","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":6.5,"width":1},"iso":{"row":0,"col":6.5,"width":1}}},
		{"code":"F6","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":7.5,"width":1},"iso":{"row":0,"col":7.5,"width":1}}},
		{"code":"F7","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":8.5,"width":1},"iso":{"row":0,"col":8.5,"width":1}}},
		{"code":"F8","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":9.5,"width":1},"iso":{"row":0,"col":9.5,"width":1}}},
		{"code":"F9","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":11,"width":1},"iso":{"row":0,"col":11,"width":1}}},
		{"code":"F10","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":12,"width":1},"iso":{"row":0,"col":12,"width":1}}},
		{"code":"F11","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":13,"width":1},"iso":{"row":0,"col":13,"width":1}}},
		{"code":"F12","kind":"key","group":"function","geometry":{"ansi":{"row":0,"col":14,"width":1},"iso":{"row":0,"col":14,"width":1}}},
		{"code":"Backquote","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":0,"width":1},"iso":{"row":1,"col":0,"width":1}}},
		{"code":"Digit1","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":1,"width":1},"iso":{"row":1,"col":1,"width":1}}},
		{"code":"Digit2","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":2,"width":1},"iso":{"row":1,"col":2,"width":1}}},
		{"code":"Digit3","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":3,"width":1},"iso":{"row":1,"col":3,"width":1}}},
		{"code":"Digit4","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":4,"width":1},"iso":{"row":1,"col":4,"width":1}}},
		{"code":"Digit5","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":5,"width":1},"iso":{"row":1,"col":5,"width":1}}},
		{"code":"Digit6","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":6,"width":1},"iso":{"row":1,"col":6,"width":1}}},
		{"code":"Digit7","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":7,"width":1},"iso":{"row":1,"col":7,"width":1}}},
		{"code":"Digit8","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":8,"width":1},"iso":{"row":1,"col":8,"width":1}}},
		{"code":"Digit9","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":9,"width":1},"iso":{"row":1,"col":9,"width":1}}},
		{"code":"Digit0","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":10,"width":1},"iso":{"row":1,"col":10,"width":1}}},
		{"code":"Minus","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":11,"width":1},"iso":{"row":1,"col":11,"width":1}}},
		{"code":"Equal","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":1,"col":12,"width":1},"iso":{"row":1,"col":12,"width":1}}},
		{"code":"Backspace","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":1,"col":13,"width":2},"iso":{"row":1,"col":13,"width":2}}},
		{"code":"Tab","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":2,"col":0,"width":1.5},"iso":{"row":2,"col":0,"width":1.5}}},
		{"code":"KeyQ","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":1.5,"width":1},"iso":{"row":2,"col":1.5,"width":1}}},
		{"code":"KeyW","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":2.5,"width":1},"iso":{"row":2,"col":2.5,"width":1}}},
		{"code":"KeyE","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":3.5,"width":1},"iso":{"row":2,"col":3.5,"width":1}}},
		{"code":"KeyR","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":4.5,"width":1},"iso":{"row":2,"col":4.5,"width":1}}},
		{"code":"KeyT","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":5.5,"width":1},"iso":{"row":2,"col":5.5,"width":1}}},
		{"code":"KeyY","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":6.5,"width":1},"iso":{"row":2,"col":6.5,"width":1}}},
		{"code":"KeyU","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":7.5,"width":1},"iso":{"row":2,"col":7.5,"width":1}}},
		{"code":"KeyI","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":8.5,"width":1},"iso":{"row":2,"col":8.5,"width":1}}},
		{"code":"KeyO","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":9.5,"width":1},"iso":{"row":2,"col":9.5,"width":1}}},
		{"code":"KeyP","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":10.5,"width":1},"iso":{"row":2,"col":10.5,"width":1}}},
		{"code":"BracketLeft","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":11.5,"width":1},"iso":{"row":2,"col":11.5,"width":1}}},
		{"code":"BracketRight","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":12.5,"width":1},"iso":{"row":2,"col":12.5,"width":1}}},
		{"code":"Backslash","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":2,"col":13.5,"width":1.5},"iso":{"row":3,"col":12.75,"width":1}}},
		{"code":"CapsLock","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":3,"col":0,"width":1.75},"iso":{"row":3,"col":0,"width":1.75}}},
		{"code":"KeyA","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":1.75,"width":1},"iso":{"row":3,"col":1.75,"width":1}}},
		{"code":"KeyS","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":2.75,"width":1},"iso":{"row":3,"col":2.75,"width":1}}},
		{"code":"KeyD","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":3.75,"width":1},"iso":{"row":3,"col":3.75,"width":1}}},
		{"code":"KeyF","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":4.75,"width":1},"iso":{"row":3,"col":4.75,"width":1}}},
		{"code":"KeyG","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":5.75,"width":1},"iso":{"row":3,"col":5.75,"width":1}}},
		{"code":"KeyH","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":6.75,"width":1},"iso":{"row":3,"col":6.75,"width":1}}},
		{"code":"KeyJ","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":7.75,"width":1},"iso":{"row":3,"col":7.75,"width":1}}},
		{"code":"KeyK","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":8.75,"width":1},"iso":{"row":3,"col":8.75,"width":1}}},
		{"code":"KeyL","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":9.75,"width":1},"iso":{"row":3,"col":9.75,"width":1}}},
		{"code":"Semicolon","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":10.75,"width":1},"iso":{"row":3,"col":10.75,"width":1}}},
		{"code":"Quote","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":3,"col":11.75,"width":1},"iso":{"row":3,"col":11.75,"width":1}}},
		{"code":"Enter","kind":"key","group":"alphanumeric","geometry":{"iso":{"row":2,"col":13.5,"width":1.5,"height":2,"bottom_col":13.75,"bottom_width":1.25},"ansi":{"row":3,"col":12.75,"width":2.25}}},
		{"code":"ShiftLeft","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":4,"col":0,"width":2.25},"iso":{"row":4,"col":0,"width":1.25}}},
		{"code":"IntlBackslash","kind":"key","group":"alphanumeric","character":true,"geometry":{"iso":{"row":4,"col":1.25,"width":1}}},
		{"code":"KeyZ","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":2.25,"width":1},"iso":{"row":4,"col":2.25,"width":1}}},
		{"code":"KeyX","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":3.25,"width":1},"iso":{"row":4,"col":3.25,"width":1}}},
		{"code":"KeyC","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":4.25,"width":1},"iso":{"row":4,"col":4.25,"width":1}}},
		{"code":"KeyV","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":5.25,"width":1},"iso":{"row":4,"col":5.25,"width":1}}},
		{"code":"KeyB","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":6.25,"width":1},"iso":{"row":4,"col":6.25,"width":1}}},
		{"code":"KeyN","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":7.25,"width":1},"iso":{"row":4,"col":7.25,"width":1}}},
		{"code":"KeyM","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":8.25,"width":1},"iso":{"row":4,"col":8.25,"width":1}}},
		{"code":"Comma","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":9.25,"width":1},"iso":{"row":4,"col":9.25,"width":1}}},
		{"code":"Period","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":10.25,"width":1},"iso":{"row":4,"col":10.25,"width":1}}},
		{"code":"Slash","kind":"key","group":"alphanumeric","character":true,"geometry":{"ansi":{"row":4,"col":11.25,"width":1},"iso":{"row":4,"col":11.25,"width":1}}},
		{"code":"ShiftRight","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":4,"col":12.25,"width":2.75},"iso":{"row":4,"col":12.25,"width":2.75}}},
		{"code":"ControlLeft","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":0,"width":1.25},"iso":{"row":5,"col":0,"width":1.25}}},
		{"code":"MetaLeft","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":1.25,"width":1.25},"iso":{"row":5,"col":1.25,"width":1.25}}},
		{"code":"AltLeft","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":2.5,"width":1.25},"iso":{"row":5,"col":2.5,"width":1.25}}},
		{"code":"Space","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":3.75,"width":6.25},"iso":{"row":5,"col":3.75,"width":6.25}}},
		{"code":"AltRight","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":10,"width":1.25},"iso":{"row":5,"col":10,"width":1.25}}},
		{"code":"MetaRight","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":11.25,"width":1.25},"iso":{"row":5,"col":11.25,"width":1.25}}},
		{"code":"ContextMenu","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":12.5,"width":1.25},"iso":{"row":5,"col":12.5,"width":1.25}}},
		{"code":"ControlRight","kind":"key","group":"alphanumeric","geometry":{"ansi":{"row":5,"col":13.75,"width":1.25},"iso":{"row":5,"col":13.75,"width":1.25}}},
		{"code":"Insert","kind":"key","group":"navigation","geometry":{"ansi":{"row":1,"col":15.25,"width":1},"iso":{"row":1,"col":15.25,"width":1}}},
		{"code":"Delete","kind":"key","group":"navigation","geometry":{"ansi":{"row":2,"col":15.25,"width":1},"iso":{"row":2,"col":15.25,"width":1}}},
		{"code":"Home","kind":"key","group":"navigation","geometry":{"ansi":{"row":1,"col":16.25,"width":1},"iso":{"row":1,"col":16.25,"width":1}}},
		{"code":"End","kind":"key","group":"navigation","geometry":{"ansi":{"row":2,"col":16.25,"width":1},"iso":{"row":2,"col":16.25,"width":1}}},
		{"code":"PageUp","kind":"key","group":"navigation","geometry":{"ansi":{"row":1,"col":17.25,"width":1},"iso":{"row":1,"col":17.25,"width":1}}},
		{"code":"PageDown","kind":"key","group":"navigation","geometry":{"ansi":{"row":2,"col":17.25,"width":1},"iso":{"row":2,"col":17.25,"width":1}}},
		{"code":"ArrowUp","kind":"key","group":"navigation","geometry":{"ansi":{"row":4,"col":16.25,"width":1},"iso":{"row":4,"col":16.25,"width":1}}},
		{"code":"ArrowLeft","kind":"key","group":"navigation","geometry":{"ansi":{"row":5,"col":15.25,"width":1},"iso":{"row":5,"col":15.25,"width":1}}},
		{"code":"ArrowDown","kind":"key","group":"navigation","geometry":{"ansi":{"row":5,"col":16.25,"width":1},"iso":{"row":5,"col":16.25,"width":1}}},
		{"code":"ArrowRight","kind":"key","group":"navigation","geometry":{"ansi":{"row":5,"col":17.25,"width":1},"iso":{"row":5,"col":17.25,"width":1}}},
		{"code":"NumLock","kind":"key","group":"numpad","geometry":{"ansi":{"row":1,"col":18.5,"width":1},"iso":{"row":1,"col":18.5,"width":1}}},
		{"code":"NumpadDivide","kind":"key","group":"numpad","geometry":{"ansi":{"row":1,"col":19.5,"width":1},"iso":{"row":1,"col":19.5,"width":1}}},
		{"code":"NumpadMultiply","kind":"key","group":"numpad","geometry":{"ansi":{"row":1,"col":20.5,"width":1},"iso":{"row":1,"col":20.5,"width":1}}},
		{"code":"NumpadSubtract","kind":"key","group":"numpad","geometry":{"ansi":{"row":1,"col":21.5,"width":1},"iso":{"row":1,"col":21.5,"width":1}}},
		{"code":"Numpad7","kind":"key","group":"numpad","geometry":{"ansi":{"row":2,"col":18.5,"width":1},"iso":{"row":2,"col":18.5,"width":1}}},
		{"code":"Numpad8","kind":"key","group":"numpad","geometry":{"ansi":{"row":2,"col":19.5,"width":1},"iso":{"row":2,"col":19.5,"width":1}}},
		{"code":"Numpad9","kind":"key","group":"numpad","geometry":{"ansi":{"row":2,"col":20.5,"width":1},"iso":{"row":2,"col":20.5,"width":1}}},
		{"code":"NumpadAdd","kind":"key","group":"numpad","geometry":{"ansi":{"row":2,"col":21.5,"width":1,"height":2},"iso":{"row":2,"col":21.5,"width":1,"height":2}}},
		{"code":"Numpad4","kind":"key","group":"numpad","geometry":{"ansi":{"row":3,"col":18.5,"width":1},"iso":{"row":3,"col":18.5,"width":1}}},
		{"code":"Numpad5","kind":"key","group":"numpad","geometry":{"ansi":{"row":3,"col":19.5,"width":1},"iso":{"row":3,"col":19.5,"width":1}}},
		{"code":"Numpad6","kind":"key","group":"numpad","geometry":{"ansi":{"row":3,"col":20.5,"width":1},"iso":{"row":3,"col":20.5,"width":1}}},
		{"code":"Numpad1","kind":"key","group":"numpad","geometry":{"ansi":{"row":4,"col":18.5,"width":1},"iso":{"row":4,"col":18.5,"width":1}}},
		{"code":"Numpad2","kind":"key","group":"numpad","geometry":{"ansi":{"row":4,"col":19.5,"width":1},"iso":{"row":4,"col":19.5,"width":1}}},
		{"code":"Numpad3","kind":"key","group":"numpad","geometry":{"ansi":{"row":4,"col":20.5,"width":1},"iso":{"row":4,"col":20.5,"width":1}}},
		{"code":"NumpadEnter","kind":"key","group":"numpad","geometry":{"ansi":{"row":4,"col":21.5,"width":1,"height":2},"iso":{"row":4,"col":21.5,"width":1,"height":2}}},
		{"code":"Numpad0","kind":"key","group":"numpad","geometry":{"ansi":{"row":5,"col":18.5,"width":2},"iso":{"row":5,"col":18.5,"width":2}}},
		{"code":"NumpadDecimal","kind":"key","group":"numpad","geometry":{"ansi":{"row":5,"col":20.5,"width":1},"iso":{"row":5,"col":20.5,"width":1}}},
		{"code":"AudioVolumeMute","kind":"key","group":"media"},
		{"code":"AudioVolumeDown","kind":"key","group":"media"},
		{"code":"AudioVolumeUp","kind":"key","group":"media"},
		{"code":"MouseLeft","kind":"mouse_button","group":"mouse"},
		{"code":"MouseRight","kind":"mouse_button","group":"mouse"},
		{"code":"MouseMiddle","kind":"mouse_button","group":"mouse"},
		{"code":"MouseBack","kind":"mouse_button","group":"mouse"},
		{"code":"MouseForward","kind":"mouse_button","group":"mouse"},
		{"code":"WheelUp","kind":"wheel","group":"wheel"},
		{"code":"WheelDown","kind":"wheel","group":"wheel"},
		{"code":"WheelLeft","kind":"wheel","group":"wheel"},
		{"code":"WheelRight","kind":"wheel","group":"wheel"}
	],
	"recommended": {
		"all": {"KeyQ":"sel_doc_start","KeyW":"doc_start","KeyE":"doc_end","KeyR":"sel_doc_end","KeyT":"keystroke:F2","CapsLock":"backspace","KeyA":"sel_para_prev","KeyS":"arrow_up","KeyD":"arrow_down","KeyF":"sel_para_next","KeyG":"keystroke:F12","IntlBackslash":"duplicate_line_up","KeyZ":"move_line_up","KeyX":"move_line_down","KeyC":"duplicate_line_down","KeyV":"new_line_below","KeyY":"sel_line_start","KeyU":"sel_word_prev","KeyI":"sel_left","KeyO":"sel_right","KeyP":"sel_word_next","BracketLeft":"sel_line_end","KeyH":"window_to_monitor_left","KeyJ":"word_prev","KeyK":"arrow_left","KeyL":"arrow_right","Semicolon":"word_next","Quote":"window_to_monitor_right","KeyN":"maximize","KeyM":"line_start","Comma":"snap_left","Period":"snap_right","Slash":"line_end","AltRight":"escape"},
		"windows": {"WheelUp":"vol_up","WheelDown":"vol_down","Digit1":"repeat_count:1","Digit2":"repeat_count:2","Digit3":"repeat_count:3","Digit4":"repeat_count:4","Digit5":"repeat_count:5","Digit6":"repeat_count:6","Digit7":"repeat_count:7","Digit8":"repeat_count:8","Digit9":"repeat_count:9","Digit0":"repeat_count:10"},
		"macos": {"WheelUp":"vol_up","WheelDown":"vol_down","Digit1":"keystroke:F1","Digit2":"keystroke:F2","Digit3":"keystroke:F3","Digit4":"keystroke:F4","Digit5":"keystroke:F5","Digit6":"keystroke:F6","Digit7":"keystroke:F7","Digit8":"keystroke:F8","Digit9":"keystroke:F9","Digit0":"keystroke:F10","Minus":"keystroke:F11","Equal":"keystroke:F12","Space":"spotlight","Tab":"keystroke:meta+Backquote","MetaRight":"escape_or_option_shift"}
	}
};
