; ui/menu/menu_actions.ahk

; ==============================================================================
; MODULE: Tray Menu / Misc Actions
; DESCRIPTION:
; Standalone tray actions: metrics-frequency setter, open-personal-shortcuts, and the log-folder / today-log / error-log openers, with the personal-shortcuts file template.
;
; Split out of ui/tray_menu.ahk (P5 refactor). tray_menu.ahk remains the module
; index: it declares the shared menu globals and #Include-s this file. Every
; function here is hoisted into the global namespace, so load order across the
; menu/*.ahk files is irrelevant.
; ==============================================================================




; Returns a menu callback bound to a specific check interval (in seconds).
; Defined here rather than inline inside the menu builder so AHK captures the
; value at call time — fat-arrow closures defined inside the loop would all
; share the same loop-variable reference and persist only the last preset.
_MakeFreqSetter(Seconds) {
	return (*) => Updater_SetCheckInterval(Seconds)
}


; Opens personal_shortcuts.ahk in Notepad. Same function the gesture binding
; uses (modules/gestures.ahk:GestureEditPersonalShortcuts), but kept callable
; from the tray menu so the user has both entry points.
OpenPersonalShortcuts(*) {
	Path := ScriptInformation["PersonalAhkPath"]
	EnsurePersonalShortcutsFile(Path)
	Run('notepad.exe "' . Path . '"')
}

; Opens the per-user log directory (under <ConfigDir>/autohotkey/logs/) in Explorer.
; Creates it on first use so the user never sees an "introuvable" dialog
OpenLogsFolder(*) {
	global _AhkSubDir
	LogDir := (IsSet(_ConfigDir) and _ConfigDir != "")
		? _ConfigDir . _AhkSubDir . "logs\"
		: A_ScriptDir . "\logs\"
	if !DirExist(LogDir) {
		try DirCreate(LogDir)
	}
	Run('explorer.exe "' . LogDir . '"')
}

; Opens today's rolling log file in Notepad. LOGGER_LOG_PATH is refreshed by
; LoggerInit() at every menu rebuild, so the path follows day rollover.
OpenTodayLog(*) {
	global LOGGER_LOG_PATH
	Path := (IsSet(LOGGER_LOG_PATH) and LOGGER_LOG_PATH != "")
		? LOGGER_LOG_PATH
		: ""
	if Path = "" or !FileExist(Path) {
		; Fall back to the day-stamped path under <ConfigDir>/autohotkey/logs/ when the
		; logger hasn't initialised yet (very early boot, edge case)
		LogDir := (IsSet(_ConfigDir) and _ConfigDir != "")
			? _ConfigDir . _AhkSubDir . "logs\"
			: A_ScriptDir . "\logs\"
		Path := LogDir . "ErgoptiPlus_" . FormatTime(, "yyyy-MM-dd") . ".log"
	}
	Run('notepad.exe "' . Path . '"')
}

; Opens today's errors-only log (WARNING + ERROR lines) in Notepad.
; LOGGER_ERRORS_LOG_PATH is maintained by the logger (daily, driver-scoped).
; Falls back to computing the path under the logs dir if the global is not set yet.
OpenErrorLog(*) {
	global LOGGER_ERRORS_LOG_PATH, _AhkSubDir
	Path := (IsSet(LOGGER_ERRORS_LOG_PATH) and LOGGER_ERRORS_LOG_PATH != "")
		? LOGGER_ERRORS_LOG_PATH
		: ""
	if Path = "" or !FileExist(Path) {
		LogDir := (IsSet(_ConfigDir) and _ConfigDir != "")
			? _ConfigDir . _AhkSubDir . "logs\"
			: A_ScriptDir . "\logs\"
		Path := LogDir . "ErgoptiPlus_errors_" . FormatTime(, "yyyy-MM-dd") . ".log"
	}
	Run('notepad.exe "' . Path . '"')
}

; Minimal template for personal_shortcuts.ahk — created on first launch so the
; user has a starter file with the canonical header. The header below is the
; same one the user is expected to keep at the top of their personal file, so
; both views stay perfectly aligned across ErgoptiPlus updates.
global PERSONAL_SHORTCUTS_TEMPLATE := "; personal_shortcuts.ahk`r`n"
	. ";`r`n"
	. "; ==============================================================================`r`n"
	. "; MODULE: Personal Shortcuts`r`n"
	. "; DESCRIPTION:`r`n"
	. "; User-defined hotkeys layered on top of the ErgoptiPlus driver. Loaded into`r`n"
	. "; the driver via a forwarding stub generated by EnsurePersonalShortcutsFile, so`r`n"
	. "; this file lives at <ConfigDirPath>/personal_shortcuts.ahk and survives`r`n"
	. "; ErgoptiPlus updates without any manual copying.`r`n"
	. ";`r`n"
	. "; FEATURES & RATIONALE:`r`n"
	. "; 1. Toggle-gated bindings — every binding is wrapped in`r`n"
	. ';    #HotIf PersonalFeatureEnabled(' . '"' . '<Name>' . '"' . ') so the matching' . "`r`n"
	. ";    tray-menu checkbox in « 🎯 Raccourcis » → « Raccourcis personnels » fully controls`r`n"
	. ";    whether the binding fires, with persistence in the configuration INI.`r`n"
	. "; 2. Two-section layout — every feature is registered in section 1 and bound`r`n"
	. ";    (along with any helper functions it needs) in section 2 with matching`r`n"
	. ";    subsection numbering. The at-a-glance roster of available toggles and the`r`n"
	. ";    wiring of each one are each easy to scan in isolation.`r`n"
	. "; 3. AHK input level 2 is already set by the parent driver before this file is`r`n"
	. ";    included, so personal hotkeys override the layout's remappings without`r`n"
	. ";    this file needing its own #InputLevel directives.`r`n"
	. ";`r`n"
	. "; ADDING A FEATURE — drop a RegisterPersonalFeature call into section 1 and`r`n"
	. "; the matching #HotIf-gated binding into section 2. The toggle then appears`r`n"
	. "; in the tray under « 🎯 Raccourcis » → « Raccourcis personnels ». Example:`r`n"
	. ";`r`n"
	. ';     RegisterPersonalFeature(' . '"' . 'lock_screen' . '"' . ', true,' . "`r`n"
	. ';         ' . '"' . 'Lock the workstation with Ctrl + Alt + L' . '"' . ')' . "`r`n"
	. ";`r`n"
	. ';     #HotIf PersonalFeatureEnabled(' . '"' . 'lock_screen' . '"' . ')' . "`r`n"
	. ';     ^!l:: DllCall(' . '"' . 'user32\LockWorkStation' . '"' . ')' . "`r`n"
	. ";     #HotIf`r`n"
	. "; ==============================================================================`r`n"
	. "`r`n"
	. "#Requires AutoHotkey v2.0`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "; =======================================`r`n"
	. "; =======================================`r`n"
	. "; ======= 1/ Feature Registration =======`r`n"
	. "; =======================================`r`n"
	. "; =======================================`r`n"
	. "`r`n"
	. "; (Add RegisterPersonalFeature calls here — see the example in the header.)`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "`r`n"
	. "; ==================================`r`n"
	. "; ==================================`r`n"
	. "; ======= 2/ Hotkey Bindings =======`r`n"
	. "; ==================================`r`n"
	. "; ==================================`r`n"
	. "`r`n"
	. "; (Add #HotIf-gated hotkey blocks here — see the example in the header.)`r`n"
	. "`r`n"

